/**
 * [INPUT]: 无运行时依赖；承载 renderer 稳定的四语本地化 copy。
 * [OUTPUT]: 对外提供四语 UI_TEXT 与状态标题路由，覆盖显式语言选择、单一 Restore English、旧/新/未知 Cavalry 版本只读提示、真正验证失败的分级恢复路径、真实任务 Event、macOS 权限 handoff 前置与重开、Windows UAC 分流、外围 Toast 及完整无障碍名称；内部兼容清理不形成用户文案。
 * [POS]: renderer 的视觉文案与状态语义数据层；将持久事实、即时决策和短时局部失败分别供 Activity、AlertDialog 与 Toast 消费。
 * [PROTOCOL]: 变更时更新此头部，然后检查 CLAUDE.md
 */
const UI_TEXT = {
  en: {
    appTitle: 'Cavalry Language Switcher',
    appFound: 'Cavalry {version}',
    appFoundNoVersion: 'Cavalry found',
    appNotFound: 'Cavalry not found',
    appPathFallback: 'Tried:\n{candidates}',
    skipToControls: 'Skip to controls',
    aboutButtonAria: 'About Cavalry Language Switcher',
    aboutTooltip: 'About',
    aboutVersion: 'Version {version}',
    aboutProjectLinks: 'Project links',
    aboutLicense: 'MIT License',
    openProjectLinkFailed: 'Check your default browser, then try again.',
    aboutOpenFailed: 'Could not open About. Try again.',
    updateButtonAria: 'View available update',
    updateTooltip: 'New version available',
    updatePreviewAvailable: 'Update preview is active. No download or installation will run.',
    updateAvailableAnnouncement: 'Version {version} is available.',
    updateConfirmTitle: 'Update the Switcher?',
    updateConfirmBody: 'Version {version} is ready. The Switcher will download, verify, replace itself, and restart.',
    updateMacAdhocNote: 'This update installs a new macOS app bundle. If the release is not Developer ID notarized, complete the documented local ad-hoc and Gatekeeper step again for the new bundle.',
    installUpdate: 'Update & Restart',
    updateDownloadRunningTitle: 'Downloading update',
    updateDownloadProgress: '{percent}%',
    updateDownloadCompletedTitle: 'Update downloaded',
    updateInstallRunningTitle: 'Verifying and installing the update',
    updateInstallCompletedTitle: 'Update installed',
    updateRestartRunningTitle: 'Restarting the Switcher',
    updaterNotConfigured: 'Automatic updates are not configured for this build.',
    updaterUnsupportedPlatform: 'Automatic updates are not supported on this platform.',
    updateCheckFailed: 'Could not check for updates.',
    updateInstallFailed: 'The update could not be installed. The current version remains available.',
    updateNotChecked: 'Check for an update again before installing.',
    updateBusy: 'Another Switcher operation is already running.',
    updateStateUnavailable: 'The checked update state is unavailable. Restart the Switcher and check again.',
    chooseAppAria: 'Choose Cavalry installation',
    language: 'Language',
    current: 'Current',
    switchTo: 'Switch to',
    chooseLanguage: 'Choose a language',
    apply: 'Switch',
    restore: 'Restore English',
    officialMode: 'Installation: verified official runtime',
    modifiedMode: 'Installation: locally modified runtime',
    recoveryMode: 'Installation: recovery required before further changes',
    officialBadge: 'Official',
    retry: 'Retry',
    openSettings: 'Open Settings',
    openPrivacySecurity: 'Open permission settings',
    requestElevation: 'Retry as administrator',
    close: 'Close',
    notifications: 'Notifications',
    minimizeWindow: 'Minimize',
    maximizeWindow: 'Maximize',
    restoreWindow: 'Restore',
    closeWindow: 'Close',
    statusLabel: 'Status',
    taskProgressLabel: 'Task progress',
    idlePrompt: 'What would you like to do?',
    applyIntro: 'Preparing to switch to {language}…',
    restoreIntro: 'Preparing to restore Cavalry…',
    updateIntro: 'Preparing the update…',
    applyOutcome: 'Switched to {language}. Cavalry is now open.',
    restoreOutcome: 'Restored English. Cavalry is now open.',
    phaseVerifyInstallationRunningTitle: 'Checking the Cavalry installation',
    phaseVerifyInstallationCompletedTitle: 'Cavalry installation verified',
    phaseVerifyInstallationErrorTitle: 'Couldn’t verify the Cavalry installation',
    verifyInstallationRecovery: 'Reopen the Switcher and try again. If it still can’t verify the Cavalry installation integrity, reinstall Cavalry {supportedVersion} from the official installer.',
    phaseEnsureRecoveryRunningTitle: 'Preparing recovery files',
    phaseEnsureRecoveryCompletedTitle: 'Recovery files ready',
    phaseEnsureRecoveryErrorTitle: 'Couldn’t prepare recovery files',
    loadingTitle: 'Loading Cavalry',
    desktopServiceUnavailableTitle: 'Desktop service unavailable',
    restartSwitcherTitle: 'Restart the Switcher',
    updateAvailableTitle: 'Update available',
    updatesUnavailableTitle: 'Automatic updates unavailable',
    updateCheckFailedTitle: 'Couldn’t check for updates',
    updateInstallFailedTitle: 'Couldn’t install the update',
    checkUpdateAgainTitle: 'Check for updates again',
    operationInProgressTitle: 'Another operation is running',
    permissionRequiredTitle: 'System permission required',
    permissionRestartRequiredTitle: 'Reopen the Switcher',
    recoveryFailedTitle: 'Couldn’t recover the interrupted operation',
    chooseAppTitle: 'Choose Cavalry',
    reinstallCavalryTitle: 'Reinstall Cavalry',
    olderVersionUnsupportedTitle: 'Cavalry {version} isn’t supported',
    newerVersionUnsupportedTitle: 'Cavalry {version} isn’t supported yet',
    unknownVersionUnsupportedTitle: 'This Cavalry version isn’t supported',
    finishRuntimeCleanupTitle: 'Restore Cavalry to finish cleanup',
    readyToApplyTitle: 'Ready to apply',
    folderNotWritableTitle: 'Cavalry folder isn’t writable',
    preparingApplyTitle: 'Preparing {language}',
    restoringTitle: 'Restoring Cavalry',
    noLanguageTitle: 'Choose a language',
    applyingTitle: 'Applying {language}',
    closeCavalryTitle: 'Cavalry is running',
    applyFailedTitle: 'Couldn’t apply the language pack',
    restoredTitle: 'Cavalry restored',
    appliedTitle: '{language} applied',
    phaseApplyRunningTitle: 'Switching Cavalry to {language}',
    phaseApplyCompletedTitle: 'Switched to {language}',
    phaseApplyErrorTitle: 'Couldn’t switch to {language}',
    phaseRestoreRunningTitle: 'Restoring Cavalry',
    phaseRestoreCompletedTitle: 'Cavalry restored',
    phaseRestoreErrorTitle: 'Couldn’t restore Cavalry',
    phaseRestartRunningTitle: 'Opening Cavalry',
    phaseRestartCompletedTitle: 'Cavalry opened',
    phaseRestartWarningTitle: 'Cavalry did not open',
    phaseRestartErrorTitle: 'Cavalry did not open',
    recoveryCleanupPendingTitle: 'Recovery cleanup is pending',
    keepRecoveryFilesTitle: 'Keep the recovery files',
    temporaryCleanupPendingTitle: 'Temporary cleanup is pending',
    finderReplacementTitle: 'Finder replacement was used',
    cleanupAttentionTitle: 'Cleanup needs attention',
    settingsFailedTitle: 'Couldn’t open permission settings',
    projectLinkFailedTitle: 'Couldn’t open the project link',
    aboutOpenFailedTitle: 'Couldn’t open About',
    startupFailedTitle: 'Couldn’t start the Switcher',
    customRootNotWritable:
      'Cavalry’s folder isn’t writable. Administrator retry only supports Program Files. Choose a writable copy or change the folder permissions.',
    readyToApply: 'Choose a language, then switch.',
    chooseAppToContinue: 'Choose a Cavalry installation to continue.',
    reinstallRequired: 'The Switcher can’t verify the integrity of the Cavalry installation. Reinstall Cavalry from the official installer, then reopen the Switcher.',
    olderVersionUnsupported: 'This Switcher currently supports Cavalry {supportedVersion}. Update Cavalry to {supportedVersion}, then reopen the Switcher. Your installation has not been changed.',
    newerVersionUnsupported: 'This Switcher currently supports Cavalry {supportedVersion} and won’t modify this installation. Keep using Cavalry, then try again after a compatible Switcher update is available.',
    unknownVersionUnsupported: 'This Switcher supports Cavalry {supportedVersion} and has not changed your installation.',
    warningStateDurabilityPending: 'Restart the Switcher before applying a language or restoring Cavalry.',
    warningRecoveryCleanupPending:
      'Recovery cleanup is still pending. Keep the recovery files until the Switcher completes cleanup.',
    warningProtectedRecoveryEvidenceRetained:
      'Recovery files are still needed. Do not delete them manually.',
    warningTemporaryCleanupPending:
      'Temporary cleanup is still pending. Close the Switcher before removing temporary files.',
    warningFinderFallbackUsed:
      'macOS used Finder-style replacement because direct copy was blocked.',
    warningNonFatalCleanup: 'A non-fatal cleanup step still needs attention.',
    chooseAppFirst: 'Choose a Cavalry installation first.',
    noLanguage: 'Choose a language before switching.',
    preparingApply: 'Saving the original files needed for recovery before Cavalry is modified.',
    restoring: 'Cavalry will open after its official English files and runtime are restored.',
    runtimeResidueWarning: 'Files from a previous Windows language setup are still active. Choose Restore English to finish cleanup.',
    applying: 'Cavalry will open when the language files are ready.',
    waitingPermission: 'Allow the Switcher to modify Cavalry, then retry.',
    permissionRestartRequiredBody:
      'The new permission takes effect after the Switcher quits. Quit and reopen it, then choose a language again.',
    patchFailed: 'Cavalry was not changed. Try again.',
    restoreFailed: 'Cavalry was not restored. Try again.',
    cavalryStillRunning: 'Save your work and quit Cavalry, then try again. The installation has not been changed.',
    restartWarning: 'Cavalry could not be opened.',
    restartRecovery: 'Open Cavalry manually.',
    applied: 'The language was switched.{warning}',
    appliedWithWarnings: '{warnings}',
    openPrivacyFailed: 'Open Privacy & Security in System Settings, then allow the Switcher to modify Cavalry.',
    bootstrapFailed: '{detail}',
    operationFailed: 'Could not contact the desktop service. Try again.',
    startupRecoveryFailed:
      'Close Cavalry, then restart the Switcher. To preserve the recovery data, don’t modify the Cavalry installation folder manually.',
    detail: ' Details: {detail}',
    restoreConfirmTitle: 'Restore English?',
    restoreConfirmBody: 'Cavalry will return to English and reopen.',
    restoreSuccess: 'Cavalry opened.',
    restoreWithWarnings: '{warnings}',
    cancel: 'Cancel',
    permissionMacTitle: 'Allow changes to Cavalry',
    permissionMacBody: 'In System Settings, allow Cavalry Language Switcher to modify Cavalry, then retry.',
    permissionHandoffBody: 'First allow Cavalry Language Switcher to modify Cavalry in System Settings, then switch the language.',
    permissionWindowsTitle: 'Administrator permission required',
    permissionWindowsBody: 'Retry as administrator, then allow the change when Windows asks.',
  },
  'zh-Hans': {
    appTitle: 'Cavalry 语言切换器',
    appFound: 'Cavalry {version}',
    appFoundNoVersion: '已找到 Cavalry',
    appNotFound: '未找到 Cavalry',
    appPathFallback: '已尝试：\n{candidates}',
    skipToControls: '跳到操作区域',
    aboutButtonAria: '关于 Cavalry 语言切换器',
    aboutTooltip: '关于',
    aboutVersion: '版本 {version}',
    aboutProjectLinks: '项目链接',
    aboutLicense: 'MIT 许可证',
    openProjectLinkFailed: '检查默认浏览器后重试。',
    aboutOpenFailed: '无法打开“关于”窗口，请重试。',
    updateButtonAria: '查看可用更新',
    updateTooltip: '发现新版本',
    updatePreviewAvailable: '更新预览已启用，不会执行下载或安装。',
    updateAvailableAnnouncement: '发现版本 {version}。',
    updateConfirmTitle: '更新语言切换器？',
    updateConfirmBody: '版本 {version} 已准备好。语言切换器将下载并验证更新，替换自身后重新启动。',
    updateMacAdhocNote: '此次更新会安装一个新的 macOS 应用包。若发布版本没有 Developer ID 公证，新包仍需重新执行发布说明中的本地 ad-hoc 与 Gatekeeper 步骤。',
    installUpdate: '更新并重启',
    updateDownloadRunningTitle: '正在下载更新',
    updateDownloadProgress: '{percent}%',
    updateDownloadCompletedTitle: '更新已下载',
    updateInstallRunningTitle: '正在验证并安装更新',
    updateInstallCompletedTitle: '更新已安装',
    updateRestartRunningTitle: '正在重启语言切换器',
    updaterNotConfigured: '此构建尚未配置自动更新。',
    updaterUnsupportedPlatform: '此平台不支持自动更新。',
    updateCheckFailed: '无法检查更新。',
    updateInstallFailed: '无法安装更新，当前版本仍可继续使用。',
    updateNotChecked: '请重新检查更新后再安装。',
    updateBusy: '语言切换器正在执行其他操作。',
    updateStateUnavailable: '已检查的更新状态不可用，请重启语言切换器后重新检查。',
    chooseAppAria: '选择 Cavalry 安装位置',
    language: '语言',
    current: '当前',
    switchTo: '切换为',
    chooseLanguage: '选择语言',
    apply: '切换',
    restore: '恢复英文',
    officialMode: '安装状态：已验证的官方运行时',
    modifiedMode: '安装状态：已在本机修改',
    recoveryMode: '安装状态：必须先完成中断事务恢复',
    officialBadge: '官方',
    retry: '重试',
    openSettings: '打开设置',
    openPrivacySecurity: '打开权限设置',
    requestElevation: '以管理员身份重试',
    close: '关闭',
    notifications: '通知',
    minimizeWindow: '最小化',
    maximizeWindow: '最大化',
    restoreWindow: '还原',
    closeWindow: '关闭',
    statusLabel: '状态',
    taskProgressLabel: '任务进度',
    idlePrompt: '这次你想做什么？',
    applyIntro: '正在准备切换为{language}……',
    restoreIntro: '正在准备恢复 Cavalry……',
    updateIntro: '正在准备更新……',
    applyOutcome: '已切换为{language}，Cavalry 已打开。',
    restoreOutcome: '已恢复英文，Cavalry 已打开。',
    phaseVerifyInstallationRunningTitle: '正在检查 Cavalry 安装',
    phaseVerifyInstallationCompletedTitle: '已验证 Cavalry 安装',
    phaseVerifyInstallationErrorTitle: '无法验证 Cavalry 安装',
    verifyInstallationRecovery: '重新打开语言切换器后重试。如果仍无法验证 Cavalry 安装的完整性，请使用官方安装包重新安装 Cavalry {supportedVersion}。',
    phaseEnsureRecoveryRunningTitle: '正在准备恢复文件',
    phaseEnsureRecoveryCompletedTitle: '恢复文件已就绪',
    phaseEnsureRecoveryErrorTitle: '无法准备恢复文件',
    loadingTitle: '正在载入 Cavalry',
    desktopServiceUnavailableTitle: '桌面服务不可用',
    restartSwitcherTitle: '重启语言切换器',
    updateAvailableTitle: '有可用更新',
    updatesUnavailableTitle: '自动更新不可用',
    updateCheckFailedTitle: '无法检查更新',
    updateInstallFailedTitle: '无法安装更新',
    checkUpdateAgainTitle: '重新检查更新',
    operationInProgressTitle: '正在执行其他操作',
    permissionRequiredTitle: '需要系统权限',
    permissionRestartRequiredTitle: '重新打开语言切换器',
    recoveryFailedTitle: '无法恢复中断的操作',
    chooseAppTitle: '选择 Cavalry 安装位置',
    reinstallCavalryTitle: '重新安装 Cavalry',
    olderVersionUnsupportedTitle: '暂不支持 Cavalry {version}',
    newerVersionUnsupportedTitle: '尚未支持 Cavalry {version}',
    unknownVersionUnsupportedTitle: '暂不支持此 Cavalry 版本',
    finishRuntimeCleanupTitle: '恢复 Cavalry 以完成清理',
    readyToApplyTitle: '可以应用语言包',
    folderNotWritableTitle: 'Cavalry 文件夹不可写',
    preparingApplyTitle: '正在准备{language}',
    restoringTitle: '正在恢复 Cavalry',
    noLanguageTitle: '选择语言',
    applyingTitle: '正在应用{language}',
    closeCavalryTitle: 'Cavalry 正在运行',
    applyFailedTitle: '无法应用语言包',
    restoredTitle: '已恢复 Cavalry',
    appliedTitle: '已应用{language}',
    phaseApplyRunningTitle: '正在将 Cavalry 切换为{language}',
    phaseApplyCompletedTitle: '已切换为{language}',
    phaseApplyErrorTitle: '无法切换为{language}',
    phaseRestoreRunningTitle: '正在恢复 Cavalry',
    phaseRestoreCompletedTitle: '已恢复 Cavalry',
    phaseRestoreErrorTitle: '无法恢复 Cavalry',
    phaseRestartRunningTitle: '正在打开 Cavalry',
    phaseRestartCompletedTitle: 'Cavalry 已打开',
    phaseRestartWarningTitle: 'Cavalry 未打开',
    phaseRestartErrorTitle: 'Cavalry 未打开',
    recoveryCleanupPendingTitle: '恢复清理尚未完成',
    keepRecoveryFilesTitle: '请保留恢复文件',
    temporaryCleanupPendingTitle: '临时清理尚未完成',
    finderReplacementTitle: '已使用 Finder 替换文件',
    cleanupAttentionTitle: '清理仍需处理',
    settingsFailedTitle: '无法打开权限设置',
    projectLinkFailedTitle: '无法打开项目链接',
    aboutOpenFailedTitle: '无法打开关于窗口',
    startupFailedTitle: '无法启动语言切换器',
    customRootNotWritable:
      'Cavalry 文件夹不可写。仅“Program Files”中的安装可以管理员身份重试。请选择可写副本或修改文件夹权限。',
    readyToApply: '选择语言，然后切换。',
    chooseAppToContinue: '请选择 Cavalry 安装位置后继续。',
    reinstallRequired: '语言切换器无法验证 Cavalry 安装的完整性。请使用官方安装包重新安装 Cavalry，再重新打开语言切换器。',
    olderVersionUnsupported: '语言切换器目前支持 Cavalry {supportedVersion}。请先将 Cavalry 更新至 {supportedVersion}，再重新打开语言切换器。当前安装未被修改。',
    newerVersionUnsupported: '语言切换器目前支持 Cavalry {supportedVersion}，不会修改此安装。你可以继续使用 Cavalry；请在兼容更新发布后再试。',
    unknownVersionUnsupported: '此语言切换器支持 Cavalry {supportedVersion}，当前安装未被修改。',
    warningStateDurabilityPending: '重启语言切换器，然后再应用语言或恢复 Cavalry。',
    warningRecoveryCleanupPending: '恢复清理仍未完成。请保留恢复文件，等待切换器完成清理。',
    warningProtectedRecoveryEvidenceRetained: '恢复文件仍然需要保留，请勿手动删除。',
    warningTemporaryCleanupPending: '临时清理仍未完成。请先关闭切换器，再移除临时文件。',
    warningFinderFallbackUsed: 'macOS 阻止直接复制后，已改用 Finder 方式替换文件。',
    warningNonFatalCleanup: '仍有一项非致命清理需要处理。',
    chooseAppFirst: '请先选择 Cavalry 安装位置。',
    noLanguage: '选择语言后再切换。',
    preparingApply: '修改 Cavalry 前，将保存恢复所需的原始文件。',
    restoring: '恢复官方英文文件和运行环境后，将打开 Cavalry。',
    runtimeResidueWarning: '之前的 Windows 语言设置仍有文件在生效。选择“恢复英文”以完成清理。',
    applying: '语言文件就绪后，Cavalry 将自动打开。',
    waitingPermission: '允许语言切换器修改 Cavalry，然后重试。',
    permissionRestartRequiredBody:
      '新权限会在语言切换器退出后生效。请退出并重新打开，然后再次选择语言。',
    patchFailed: 'Cavalry 未被修改，请重试。',
    restoreFailed: '未恢复 Cavalry，请重试。',
    cavalryStillRunning: '保存工作并退出 Cavalry 后重试。安装内容未被修改。',
    restartWarning: '无法打开 Cavalry。',
    restartRecovery: '请手动打开 Cavalry。',
    applied: '已切换语言。{warning}',
    appliedWithWarnings: '{warnings}',
    openPrivacyFailed: '请在系统设置中打开“隐私与安全性”，允许语言切换器修改 Cavalry。',
    bootstrapFailed: '{detail}',
    operationFailed: '无法连接桌面服务，请重试。',
    startupRecoveryFailed: '请关闭 Cavalry，然后重新启动语言切换器。为避免丢失恢复信息，请勿手动修改 Cavalry 安装目录。',
    detail: '详情：{detail}',
    restoreConfirmTitle: '恢复英文？',
    restoreConfirmBody: 'Cavalry 将恢复为英文并重新打开。',
    restoreSuccess: 'Cavalry 已打开。',
    restoreWithWarnings: '{warnings}',
    cancel: '取消',
    permissionMacTitle: '允许修改 Cavalry',
    permissionMacBody: '请在系统设置中允许语言切换器修改 Cavalry，然后重试。',
    permissionHandoffBody: '请先在系统设置中允许语言切换器修改 Cavalry，然后再切换语言。',
    permissionWindowsTitle: '需要管理员权限',
    permissionWindowsBody: '请以管理员身份重试，并在 Windows 提示时允许此次更改。',
  },
  'zh-Hant': {
    appTitle: 'Cavalry 語言切換器',
    appFound: 'Cavalry {version}',
    appFoundNoVersion: '已找到 Cavalry',
    appNotFound: '未找到 Cavalry',
    appPathFallback: '已嘗試：\n{candidates}',
    skipToControls: '跳到操作區域',
    aboutButtonAria: '關於 Cavalry 語言切換器',
    aboutTooltip: '關於',
    aboutVersion: '版本 {version}',
    aboutProjectLinks: '專案連結',
    aboutLicense: 'MIT 授權條款',
    openProjectLinkFailed: '檢查預設瀏覽器後重試。',
    aboutOpenFailed: '無法開啟「關於」視窗，請重試。',
    updateButtonAria: '查看可用更新',
    updateTooltip: '發現新版本',
    updatePreviewAvailable: '更新預覽已啟用，不會執行下載或安裝。',
    updateAvailableAnnouncement: '發現版本 {version}。',
    updateConfirmTitle: '更新語言切換器？',
    updateConfirmBody: '版本 {version} 已準備好。語言切換器將下載並驗證更新，替換自身後重新啟動。',
    updateMacAdhocNote: '此次更新會安裝一個新的 macOS 應用程式套件。若發布版本沒有 Developer ID 公證，新套件仍需重新執行發布說明中的本機 ad-hoc 與 Gatekeeper 步驟。',
    installUpdate: '更新並重新啟動',
    updateDownloadRunningTitle: '正在下載更新',
    updateDownloadProgress: '{percent}%',
    updateDownloadCompletedTitle: '更新已下載',
    updateInstallRunningTitle: '正在驗證並安裝更新',
    updateInstallCompletedTitle: '更新已安裝',
    updateRestartRunningTitle: '正在重新啟動語言切換器',
    updaterNotConfigured: '此建置尚未設定自動更新。',
    updaterUnsupportedPlatform: '此平台不支援自動更新。',
    updateCheckFailed: '無法檢查更新。',
    updateInstallFailed: '無法安裝更新，目前版本仍可繼續使用。',
    updateNotChecked: '請重新檢查更新後再安裝。',
    updateBusy: '語言切換器正在執行其他操作。',
    updateStateUnavailable: '已檢查的更新狀態無法使用，請重新啟動語言切換器後再檢查。',
    chooseAppAria: '選擇 Cavalry 安裝位置',
    language: '語言',
    current: '目前',
    switchTo: '切換為',
    chooseLanguage: '選擇語言',
    apply: '切換',
    restore: '還原英文',
    officialMode: '安裝狀態：已驗證的官方執行環境',
    modifiedMode: '安裝狀態：已在本機修改',
    recoveryMode: '安裝狀態：必須先完成中斷交易復原',
    officialBadge: '官方',
    retry: '重試',
    openSettings: '打開設定',
    openPrivacySecurity: '打開權限設定',
    requestElevation: '以系統管理員身分重試',
    close: '關閉',
    notifications: '通知',
    minimizeWindow: '最小化',
    maximizeWindow: '最大化',
    restoreWindow: '還原',
    closeWindow: '關閉',
    statusLabel: '狀態',
    taskProgressLabel: '任務進度',
    idlePrompt: '這次你想做什麼？',
    applyIntro: '正在準備切換為{language}……',
    restoreIntro: '正在準備還原 Cavalry……',
    updateIntro: '正在準備更新……',
    applyOutcome: '已切換為{language}，Cavalry 已開啟。',
    restoreOutcome: '已還原英文，Cavalry 已開啟。',
    phaseVerifyInstallationRunningTitle: '正在檢查 Cavalry 安裝',
    phaseVerifyInstallationCompletedTitle: '已驗證 Cavalry 安裝',
    phaseVerifyInstallationErrorTitle: '無法驗證 Cavalry 安裝',
    verifyInstallationRecovery: '重新開啟語言切換器後重試。如果仍無法驗證 Cavalry 安裝的完整性，請使用官方安裝程式重新安裝 Cavalry {supportedVersion}。',
    phaseEnsureRecoveryRunningTitle: '正在準備還原檔案',
    phaseEnsureRecoveryCompletedTitle: '還原檔案已就緒',
    phaseEnsureRecoveryErrorTitle: '無法準備還原檔案',
    loadingTitle: '正在載入 Cavalry',
    desktopServiceUnavailableTitle: '桌面服務無法使用',
    restartSwitcherTitle: '重新啟動語言切換器',
    updateAvailableTitle: '有可用更新',
    updatesUnavailableTitle: '自動更新無法使用',
    updateCheckFailedTitle: '無法檢查更新',
    updateInstallFailedTitle: '無法安裝更新',
    checkUpdateAgainTitle: '重新檢查更新',
    operationInProgressTitle: '正在執行其他操作',
    permissionRequiredTitle: '需要系統權限',
    permissionRestartRequiredTitle: '重新打開語言切換器',
    recoveryFailedTitle: '無法復原中斷的操作',
    chooseAppTitle: '選擇 Cavalry 安裝位置',
    reinstallCavalryTitle: '重新安裝 Cavalry',
    olderVersionUnsupportedTitle: '暫不支援 Cavalry {version}',
    newerVersionUnsupportedTitle: '尚未支援 Cavalry {version}',
    unknownVersionUnsupportedTitle: '暫不支援此 Cavalry 版本',
    finishRuntimeCleanupTitle: '還原 Cavalry 以完成清理',
    readyToApplyTitle: '可以套用語言包',
    folderNotWritableTitle: 'Cavalry 資料夾無法寫入',
    preparingApplyTitle: '正在準備{language}',
    restoringTitle: '正在還原 Cavalry',
    noLanguageTitle: '選擇語言',
    applyingTitle: '正在套用{language}',
    closeCavalryTitle: 'Cavalry 仍在執行',
    applyFailedTitle: '無法套用語言包',
    restoredTitle: '已還原 Cavalry',
    appliedTitle: '已套用{language}',
    phaseApplyRunningTitle: '正在將 Cavalry 切換為{language}',
    phaseApplyCompletedTitle: '已切換為{language}',
    phaseApplyErrorTitle: '無法切換為{language}',
    phaseRestoreRunningTitle: '正在還原 Cavalry',
    phaseRestoreCompletedTitle: '已還原 Cavalry',
    phaseRestoreErrorTitle: '無法還原 Cavalry',
    phaseRestartRunningTitle: '正在開啟 Cavalry',
    phaseRestartCompletedTitle: 'Cavalry 已開啟',
    phaseRestartWarningTitle: 'Cavalry 未開啟',
    phaseRestartErrorTitle: 'Cavalry 未開啟',
    recoveryCleanupPendingTitle: '復原清理尚未完成',
    keepRecoveryFilesTitle: '請保留復原檔案',
    temporaryCleanupPendingTitle: '暫存清理尚未完成',
    finderReplacementTitle: '已使用 Finder 替換檔案',
    cleanupAttentionTitle: '清理仍需處理',
    settingsFailedTitle: '無法打開權限設定',
    projectLinkFailedTitle: '無法打開專案連結',
    aboutOpenFailedTitle: '無法開啟關於視窗',
    startupFailedTitle: '無法啟動語言切換器',
    customRootNotWritable:
      'Cavalry 資料夾無法寫入。只有「Program Files」中的安裝可用系統管理員身分重試。請選擇可寫入的副本或修改資料夾權限。',
    readyToApply: '選擇語言，然後切換。',
    chooseAppToContinue: '請先選擇 Cavalry 安裝位置再繼續。',
    reinstallRequired: '語言切換器無法驗證 Cavalry 安裝的完整性。請使用官方安裝程式重新安裝 Cavalry，再重新開啟語言切換器。',
    olderVersionUnsupported: '語言切換器目前支援 Cavalry {supportedVersion}。請先將 Cavalry 更新至 {supportedVersion}，再重新開啟語言切換器。目前的安裝未被修改。',
    newerVersionUnsupported: '語言切換器目前支援 Cavalry {supportedVersion}，不會修改此安裝。你可以繼續使用 Cavalry；請在相容更新推出後再試。',
    unknownVersionUnsupported: '此語言切換器支援 Cavalry {supportedVersion}，目前安裝未被修改。',
    warningStateDurabilityPending: '重新啟動語言切換器，然後再套用語言或還原 Cavalry。',
    warningRecoveryCleanupPending: '復原清理仍未完成。請保留復原檔案，等待切換器完成清理。',
    warningProtectedRecoveryEvidenceRetained: '復原檔案仍需保留，請勿手動刪除。',
    warningTemporaryCleanupPending: '暫存清理仍未完成。請先關閉切換器，再移除暫存檔案。',
    warningFinderFallbackUsed: 'macOS 阻止直接複製後，已改用 Finder 方式替換檔案。',
    warningNonFatalCleanup: '仍有一項非致命清理需要處理。',
    chooseAppFirst: '請先選擇 Cavalry 安裝位置。',
    noLanguage: '選擇語言後再切換。',
    preparingApply: '修改 Cavalry 前，將儲存還原所需的原始檔案。',
    restoring: '還原官方英文檔案和執行環境後，將開啟 Cavalry。',
    runtimeResidueWarning: '之前的 Windows 語言設定仍有檔案在生效。選擇「還原英文」以完成清理。',
    applying: '語言檔案就緒後，Cavalry 將自動開啟。',
    waitingPermission: '允許語言切換器修改 Cavalry，然後重試。',
    permissionRestartRequiredBody:
      '新權限會在語言切換器結束後生效。請結束並重新打開，然後再次選擇語言。',
    patchFailed: 'Cavalry 未被修改，請重試。',
    restoreFailed: '未還原 Cavalry，請重試。',
    cavalryStillRunning: '請先儲存工作並結束 Cavalry，然後重試。目前的安裝未被修改。',
    restartWarning: '無法開啟 Cavalry。',
    restartRecovery: '請手動開啟 Cavalry。',
    applied: '已切換語言。{warning}',
    appliedWithWarnings: '{warnings}',
    openPrivacyFailed: '請在系統設定中打開「隱私權與安全性」，允許語言切換器修改 Cavalry。',
    bootstrapFailed: '{detail}',
    operationFailed: '無法連線至桌面服務，請重試。',
    startupRecoveryFailed: '請關閉 Cavalry，然後重新啟動語言切換器。為避免遺失復原資料，請勿手動修改 Cavalry 安裝目錄。',
    detail: '詳情：{detail}',
    restoreConfirmTitle: '還原英文？',
    restoreConfirmBody: 'Cavalry 將還原為英文並重新開啟。',
    restoreSuccess: 'Cavalry 已開啟。',
    restoreWithWarnings: '{warnings}',
    cancel: '取消',
    permissionMacTitle: '允許修改 Cavalry',
    permissionMacBody: '請在系統設定中允許語言切換器修改 Cavalry，然後重試。',
    permissionHandoffBody: '請先在系統設定中允許語言切換器修改 Cavalry，然後再切換語言。',
    permissionWindowsTitle: '需要系統管理員權限',
    permissionWindowsBody: '請以系統管理員身分重試，並在 Windows 提示時允許這項變更。',
  },
  ja_JP: {
    appTitle: 'Cavalry 言語スイッチャー',
    appFound: 'Cavalry {version}',
    appFoundNoVersion: 'Cavalry が見つかりました',
    appNotFound: 'Cavalry が見つかりません',
    appPathFallback: '確認した場所:\n{candidates}',
    skipToControls: '操作領域へ移動',
    aboutButtonAria: 'Cavalry 言語スイッチャーについて',
    aboutTooltip: 'このアプリについて',
    aboutVersion: 'バージョン {version}',
    aboutProjectLinks: 'プロジェクトリンク',
    aboutLicense: 'MIT ライセンス',
    openProjectLinkFailed: '既定のブラウザを確認して、再試行してください。',
    aboutOpenFailed: '「このアプリについて」を開けませんでした。もう一度お試しください。',
    updateButtonAria: '利用可能な更新を表示',
    updateTooltip: '新しいバージョンがあります',
    updatePreviewAvailable: '更新プレビューが有効です。ダウンロードやインストールは実行されません。',
    updateAvailableAnnouncement: 'バージョン {version} を利用できます。',
    updateConfirmTitle: '言語スイッチャーを更新しますか？',
    updateConfirmBody: 'バージョン {version} を利用できます。更新をダウンロードして検証し、アプリを置き換えて再起動します。',
    updateMacAdhocNote: 'この更新では新しい macOS アプリバンドルがインストールされます。Developer ID で公証されていないリリースでは、新しいバンドルに対してリリース案内のローカル ad-hoc と Gatekeeper の手順をもう一度実行してください。',
    installUpdate: '更新して再起動',
    updateDownloadRunningTitle: 'アップデートをダウンロード中',
    updateDownloadProgress: '{percent}%',
    updateDownloadCompletedTitle: '更新をダウンロードしました',
    updateInstallRunningTitle: '更新を検証してインストール中',
    updateInstallCompletedTitle: '更新をインストールしました',
    updateRestartRunningTitle: '言語スイッチャーを再起動中',
    updaterNotConfigured: 'このビルドには自動更新が設定されていません。',
    updaterUnsupportedPlatform: 'このプラットフォームでは自動更新を利用できません。',
    updateCheckFailed: '更新を確認できませんでした。',
    updateInstallFailed: '更新をインストールできませんでした。現在のバージョンは引き続き使用できます。',
    updateNotChecked: 'インストールする前に更新をもう一度確認してください。',
    updateBusy: '言語スイッチャーで別の操作を実行中です。',
    updateStateUnavailable: '確認済みの更新状態を利用できません。言語スイッチャーを再起動して、もう一度確認してください。',
    chooseAppAria: 'Cavalry のインストール先を選択',
    language: '言語',
    current: '現在',
    switchTo: '切り替え先',
    chooseLanguage: '言語を選択',
    apply: '切り替える',
    restore: '英語に戻す',
    officialMode: 'インストール状態: 検証済みの公式ランタイム',
    modifiedMode: 'インストール状態: ローカルで変更済み',
    recoveryMode: 'インストール状態: 中断した処理の復旧が必要です',
    officialBadge: '公式',
    retry: '再試行',
    openSettings: '設定を開く',
    openPrivacySecurity: '権限設定を開く',
    requestElevation: '管理者として再試行',
    close: '閉じる',
    notifications: '通知',
    minimizeWindow: '最小化',
    maximizeWindow: '最大化',
    restoreWindow: '元に戻す',
    closeWindow: '閉じる',
    statusLabel: '状態',
    taskProgressLabel: 'タスクの進行状況',
    idlePrompt: '今回は何をしますか？',
    applyIntro: '{language}への切り替えを準備しています…',
    restoreIntro: 'Cavalry の復元を準備しています…',
    updateIntro: '更新を準備しています…',
    applyOutcome: '{language}に切り替えました。Cavalry は起動済みです。',
    restoreOutcome: '英語に戻しました。Cavalry は起動済みです。',
    phaseVerifyInstallationRunningTitle: 'Cavalry のインストールを確認中',
    phaseVerifyInstallationCompletedTitle: 'Cavalry のインストールを確認しました',
    phaseVerifyInstallationErrorTitle: 'Cavalry のインストールを確認できません',
    verifyInstallationRecovery: '言語スイッチャーを開き直して再試行してください。それでも Cavalry のインストールの完全性を確認できない場合は、公式インストーラーから Cavalry {supportedVersion} を再インストールしてください。',
    phaseEnsureRecoveryRunningTitle: '復元ファイルを準備中',
    phaseEnsureRecoveryCompletedTitle: '復元ファイルの準備ができました',
    phaseEnsureRecoveryErrorTitle: '復元ファイルを準備できません',
    loadingTitle: 'Cavalry を読み込み中',
    desktopServiceUnavailableTitle: 'デスクトップサービスを利用できません',
    restartSwitcherTitle: '言語スイッチャーを再起動',
    updateAvailableTitle: '更新があります',
    updatesUnavailableTitle: '自動更新を利用できません',
    updateCheckFailedTitle: '更新を確認できません',
    updateInstallFailedTitle: '更新をインストールできません',
    checkUpdateAgainTitle: '更新をもう一度確認',
    operationInProgressTitle: '別の操作を実行中です',
    permissionRequiredTitle: 'システム権限が必要です',
    permissionRestartRequiredTitle: '言語スイッチャーを開き直す',
    recoveryFailedTitle: '中断した操作を復旧できません',
    chooseAppTitle: 'Cavalry のインストール先を選択',
    reinstallCavalryTitle: 'Cavalry を再インストール',
    olderVersionUnsupportedTitle: 'Cavalry {version} はサポートされていません',
    newerVersionUnsupportedTitle: 'Cavalry {version} はまだサポートされていません',
    unknownVersionUnsupportedTitle: 'この Cavalry バージョンはサポートされていません',
    finishRuntimeCleanupTitle: 'Cavalry を復元してクリーンアップを完了',
    readyToApplyTitle: '言語パックを適用できます',
    folderNotWritableTitle: 'Cavalry フォルダーに書き込めません',
    preparingApplyTitle: '{language}を準備中',
    restoringTitle: 'Cavalry を復元中',
    noLanguageTitle: '言語を選択',
    applyingTitle: '{language}を適用中',
    closeCavalryTitle: 'Cavalry が実行中です',
    applyFailedTitle: '言語パックを適用できません',
    restoredTitle: 'Cavalry を復元しました',
    appliedTitle: '{language}を適用しました',
    phaseApplyRunningTitle: 'Cavalry を{language}に切り替え中',
    phaseApplyCompletedTitle: '{language}に切り替えました',
    phaseApplyErrorTitle: '{language}に切り替えられません',
    phaseRestoreRunningTitle: 'Cavalry を復元中',
    phaseRestoreCompletedTitle: 'Cavalry を復元しました',
    phaseRestoreErrorTitle: 'Cavalry を復元できません',
    phaseRestartRunningTitle: 'Cavalry を起動中',
    phaseRestartCompletedTitle: 'Cavalry を起動しました',
    phaseRestartWarningTitle: 'Cavalry を起動できませんでした',
    phaseRestartErrorTitle: 'Cavalry を起動できませんでした',
    recoveryCleanupPendingTitle: '復旧処理が完了していません',
    keepRecoveryFilesTitle: '復旧ファイルを残してください',
    temporaryCleanupPendingTitle: '一時ファイルの処理が完了していません',
    finderReplacementTitle: 'Finder 方式で置き換えました',
    cleanupAttentionTitle: 'クリーンアップを確認してください',
    settingsFailedTitle: '権限設定を開けません',
    projectLinkFailedTitle: 'プロジェクトリンクを開けませんでした',
    aboutOpenFailedTitle: '「このアプリについて」を開けませんでした',
    startupFailedTitle: '言語スイッチャーを起動できません',
    customRootNotWritable:
      'Cavalry フォルダーに書き込めません。管理者として再試行できるのは Program Files 内だけです。書き込み可能なコピーを選ぶか、アクセス権を変更してください。',
    readyToApply: '言語を選んで切り替えます。',
    chooseAppToContinue: '続行するには Cavalry のインストール先を選択してください。',
    reinstallRequired: '言語スイッチャーは Cavalry のインストールの完全性を確認できません。公式インストーラーから Cavalry を再インストールして、言語スイッチャーを開き直してください。',
    olderVersionUnsupported: 'この言語スイッチャーは現在 Cavalry {supportedVersion} に対応しています。Cavalry を {supportedVersion} に更新してから、言語スイッチャーを開き直してください。現在のインストールは変更されていません。',
    newerVersionUnsupported: 'この言語スイッチャーは現在 Cavalry {supportedVersion} に対応しており、このインストールは変更しません。Cavalry はそのまま使用し、対応版の更新後にもう一度お試しください。',
    unknownVersionUnsupported: 'この言語スイッチャーは Cavalry {supportedVersion} に対応しています。現在のインストールは変更されていません。',
    warningStateDurabilityPending: '言語の適用または Cavalry の復元前に、言語スイッチャーを再起動してください。',
    warningRecoveryCleanupPending:
      '復旧用ファイルのクリーンアップがまだ完了していません。Switcher が完了するまで復旧用ファイルを残してください。',
    warningProtectedRecoveryEvidenceRetained:
      '復旧ファイルはまだ必要です。手動で削除しないでください。',
    warningTemporaryCleanupPending:
      '一時ファイルのクリーンアップがまだ完了していません。Switcher を終了してから一時ファイルを削除してください。',
    warningFinderFallbackUsed:
      'macOS が直接コピーを拒否したため、Finder 方式でファイルを置き換えました。',
    warningNonFatalCleanup: '致命的ではないクリーンアップ処理が残っています。',
    chooseAppFirst: '先に Cavalry のインストール先を選択してください。',
    noLanguage: '言語を選択してから切り替えてください。',
    preparingApply: 'Cavalry を変更する前に、復元に必要な元のファイルを保存しています。',
    restoring: '公式の英語ファイルとランタイムを復元した後、Cavalry を起動します。',
    runtimeResidueWarning: '以前の Windows 言語設定のファイルがまだ有効です。「英語に戻す」を選んでクリーンアップを完了してください。',
    applying: '言語ファイルの準備ができると Cavalry が起動します。',
    waitingPermission: '言語スイッチャーによる Cavalry の変更を許可してから、再試行してください。',
    permissionRestartRequiredBody:
      '新しい権限は、言語スイッチャーを終了した後に有効になります。言語スイッチャーを終了して開き直し、もう一度言語を選択してください。',
    patchFailed: 'Cavalry は変更されていません。もう一度お試しください。',
    restoreFailed: 'Cavalry は復元されていません。もう一度お試しください。',
    cavalryStillRunning: '作業を保存して Cavalry を終了してから、もう一度お試しください。インストール内容は変更されていません。',
    restartWarning: 'Cavalry を起動できませんでした。',
    restartRecovery: 'Cavalry を手動で起動してください。',
    applied: '言語を切り替えました。{warning}',
    appliedWithWarnings: '{warnings}',
    openPrivacyFailed: 'システム設定で「プライバシーとセキュリティ」を開き、Switcher に Cavalry の変更を許可してください。',
    bootstrapFailed: '{detail}',
    operationFailed: 'デスクトップサービスに接続できませんでした。もう一度お試しください。',
    startupRecoveryFailed:
      'Cavalry を終了してから、言語スイッチャーを再起動してください。復元データを保持するため、Cavalry のインストール先を手動で変更しないでください。',
    detail: ' 詳細: {detail}',
    restoreConfirmTitle: '英語に戻しますか？',
    restoreConfirmBody: 'Cavalry を英語に戻して、もう一度開きます。',
    restoreSuccess: 'Cavalry を起動しました。',
    restoreWithWarnings: '{warnings}',
    cancel: 'キャンセル',
    permissionMacTitle: 'Cavalry の変更を許可',
    permissionMacBody: 'システム設定で、言語スイッチャーによる Cavalry の変更を許可してから再試行してください。',
    permissionHandoffBody: 'まずシステム設定で言語スイッチャーによる Cavalry の変更を許可してから、言語を切り替えてください。',
    permissionWindowsTitle: '管理者権限が必要です',
    permissionWindowsBody: '管理者として再試行し、Windows の確認画面で変更を許可してください。',
  },
};

const STATUS_TITLE_KEYS = Object.freeze({
  operationFailed: 'desktopServiceUnavailableTitle',
  warningStateDurabilityPending: 'restartSwitcherTitle',
  warningRecoveryCleanupPending: 'recoveryCleanupPendingTitle',
  warningProtectedRecoveryEvidenceRetained: 'keepRecoveryFilesTitle',
  warningTemporaryCleanupPending: 'temporaryCleanupPendingTitle',
  warningFinderFallbackUsed: 'finderReplacementTitle',
  warningNonFatalCleanup: 'cleanupAttentionTitle',
  updatePreviewAvailable: 'updateAvailableTitle',
  updaterNotConfigured: 'updatesUnavailableTitle',
  updaterUnsupportedPlatform: 'updatesUnavailableTitle',
  updateCheckFailed: 'updateCheckFailedTitle',
  updateInstallFailed: 'updateInstallFailedTitle',
  updateNotChecked: 'checkUpdateAgainTitle',
  updateBusy: 'operationInProgressTitle',
  updateStateUnavailable: 'checkUpdateAgainTitle',
  waitingPermission: 'permissionRequiredTitle',
  startupRecoveryFailed: 'recoveryFailedTitle',
  chooseAppToContinue: 'chooseAppTitle',
  chooseAppFirst: 'chooseAppTitle',
  reinstallRequired: 'reinstallCavalryTitle',
  olderVersionUnsupported: 'olderVersionUnsupportedTitle',
  newerVersionUnsupported: 'newerVersionUnsupportedTitle',
  unknownVersionUnsupported: 'unknownVersionUnsupportedTitle',
  runtimeResidueWarning: 'finishRuntimeCleanupTitle',
  readyToApply: 'readyToApplyTitle',
  customRootNotWritable: 'folderNotWritableTitle',
  preparingApply: 'preparingApplyTitle',
  restoring: 'restoringTitle',
  noLanguage: 'noLanguageTitle',
  applying: 'applyingTitle',
  cavalryStillRunning: 'closeCavalryTitle',
  patchFailed: 'applyFailedTitle',
  restoreSuccess: 'restoredTitle',
  restoreWithWarnings: 'restoredTitle',
  applied: 'appliedTitle',
  appliedWithWarnings: 'appliedTitle',
  openPrivacyFailed: 'settingsFailedTitle',
  openProjectLinkFailed: 'projectLinkFailedTitle',
  aboutOpenFailed: 'aboutOpenFailedTitle',
  bootstrapFailed: 'startupFailedTitle',
});
