/**
 * [INPUT]: 无运行时依赖；承载 renderer 稳定的四语本地化 copy。
 * [OUTPUT]: 对外提供非模块脚本全局 UI_TEXT 文案目录，供 renderer/app.js 读取；包含跳转导航、单一更新图标 tooltip/安装确认/错误状态、macOS 新包 ad-hoc 提醒、紧凑维护动作及其完整无障碍名称。
 * [POS]: renderer 的视觉文案数据层；由 index.html 在 app.js 前加载，保持交互逻辑与稳定 copy 分离。
 * [PROTOCOL]: 变更时更新此头部，然后检查 CLAUDE.md
 */
const UI_TEXT = {
  en: {
    appTitle: 'Cavalry Language Switcher',
    appFound: 'Cavalry {version}',
    appFoundNoVersion: 'Cavalry found',
    appNotFound: 'Cavalry not found',
    appPathFallback: 'Tried:\n{candidates}',
    skipToControls: 'Skip to controls',
    updateButtonAria: 'View available update',
    updateTooltip: 'New version available',
    updatePreviewAvailable: 'Update preview is active. No download or installation will run.',
    updateAvailableAnnouncement: 'Version {version} is available.',
    updateConfirmTitle: 'Update the Switcher?',
    updateConfirmBody: 'Version {version} is ready. The Switcher will download, verify, replace itself, and restart.',
    updateMacAdhocNote: 'This update installs a new macOS app bundle. If the release is not Developer ID notarized, complete the documented local ad-hoc and Gatekeeper step again for the new bundle.',
    installUpdate: 'Update & Restart',
    installingUpdate: 'Downloading, verifying, and installing version {version}…',
    updaterNotConfigured: 'Automatic updates are not configured for this build.',
    updaterUnsupportedPlatform: 'Automatic updates are not supported on this platform.',
    updateCheckFailed: 'Could not check for updates.',
    updateInstallFailed: 'The update could not be installed. The current version remains available.',
    updateNotChecked: 'Check for an update again before installing.',
    updateBusy: 'Another Switcher operation is already running.',
    updateStateUnavailable: 'The checked update state is unavailable. Restart the Switcher and check again.',
    chooseAppAria: 'Choose Cavalry installation',
    language: 'Language',
    current: 'Current',
    switchTo: 'Switch to',
    englishUi: 'English UI',
    apply: 'Apply & Restart',
    restoreOfficial: 'Restore official Cavalry',
    officialMode: 'Installation: verified official runtime',
    modifiedMode: 'Installation: Switcher-managed or unverified runtime',
    recoveryMode: 'Installation: recovery required before further changes',
    retryApply: 'Retry Apply',
    refreshEnglish: 'Refresh English',
    refreshEnglishAria: 'Refresh English Snapshot',
    restoreEnglish: 'Restore English',
    openPrivacySecurity: 'Open permission settings',
    requestElevation: 'Retry as administrator',
    close: 'Close',
    statusLabel: 'Status',
    readyPermission: 'System permission may be required to modify the Cavalry installation.',
    customRootNotWritable:
      'The selected Cavalry folder is not writable. Windows administrator retry is only available for installations under Program Files; choose a writable copy or update this folder’s permissions.',
    readyToApply: 'Ready to apply a language pack.',
    chooseAppToContinue: 'Choose a Cavalry installation to continue.',
    needsExtract: 'English source files need to be refreshed before the next patch.',
    reinstallRequired: 'This Cavalry installation cannot be safely restored because its original English provenance is incomplete. Reinstall Cavalry from the official installer, then choose the new installation.',
    warningStateDurabilityPending:
      'State storage durability could not be confirmed. Refresh the English snapshot again before applying or restoring.',
    warningRecoveryCleanupPending:
      'Recovery cleanup is still pending. Keep the recovery files until the Switcher completes cleanup.',
    warningProtectedRecoveryEvidenceRetained:
      'Protected transaction recovery evidence remains. Do not delete it manually.',
    warningTemporaryCleanupPending:
      'Temporary cleanup is still pending. Close the Switcher before removing temporary files.',
    warningFinderFallbackUsed:
      'macOS used Finder-style replacement because direct copy was blocked.',
    warningNonFatalCleanup: 'A non-fatal cleanup step still needs attention.',
    extractSuccessWarning: 'English snapshot refreshed ({count} files). {warnings}',
    chooseAppFirst: 'Choose a Cavalry installation first.',
    noLanguage: 'No language pack is available.',
    refreshingEnglish: 'Refreshing the English snapshot...',
    extractFailed: 'Could not refresh the English snapshot.',
    extractSuccess: 'English snapshot refreshed ({count} files).',
    runtimeResidueWarning:
      'Windows runtime residue was detected. Refresh English made no runtime changes; click Restore English when needed.',
    runtimeResidueAfterRefresh:
      'English snapshot refreshed ({count} files). Windows runtime residue was detected. Refresh English made no runtime changes; click Restore English when needed.',
    applying: 'Applying {language}...',
    waitingPermission: 'Waiting for system permission.',
    patchFailed: 'Patch failed.',
    cavalryStillRunning:
      'Cavalry is still running. Save your work, close Cavalry, and try again. The Cavalry installation was not changed.',
    restartWarning: 'Cavalry could not be restarted.',
    applied: 'Applied {language} and restarted Cavalry.{warning}',
    appliedWithWarnings: 'Applied {language}. {warnings}',
    openPrivacyFailed: 'Could not open permission settings.',
    bootstrapFailed: 'Bootstrap failed: {detail}',
    operationFailed: 'Could not contact the desktop service. Try again.',
    startupRecoveryFailed:
      'An interrupted Cavalry update could not be recovered safely. Close Cavalry, relaunch the Switcher, and do not modify the installation manually.',
    detail: ' Details: {detail}',
    confirmTitle: 'Install language pack?',
    confirmBody:
      'The selected language pack will modify the chosen Cavalry installation. Cavalry will restart after the files are applied.',
    restoreConfirmTitle: 'Restore the official Cavalry installation?',
    restoreConfirmBody:
      'This removes Switcher runtime files and restores the captured vendor files and signature. If any complete verified preimage is unavailable, the operation will stop and you must reinstall Cavalry.',
    officialRestoreSuccess: 'The captured official Cavalry installation was restored and restarted.',
    officialRestoreWithWarnings: 'The captured official Cavalry installation was restored. {warnings}',
    continue: 'Continue',
    cancel: 'Cancel',
    permissionTitle: 'System permission required',
    permissionBody:
      'Approve the operating system permission request for Cavalry Language Switcher, then retry.',
  },
  'zh-Hans': {
    appTitle: 'Cavalry 语言切换器',
    appFound: 'Cavalry {version}',
    appFoundNoVersion: '已找到 Cavalry',
    appNotFound: '未找到 Cavalry',
    appPathFallback: '已尝试：\n{candidates}',
    skipToControls: '跳到操作区域',
    updateButtonAria: '查看可用更新',
    updateTooltip: '发现新版本',
    updatePreviewAvailable: '更新预览已启用，不会执行下载或安装。',
    updateAvailableAnnouncement: '发现版本 {version}。',
    updateConfirmTitle: '更新语言切换器？',
    updateConfirmBody: '版本 {version} 已准备好。语言切换器将下载并验证更新，替换自身后重新启动。',
    updateMacAdhocNote: '此次更新会安装一个新的 macOS 应用包。若发布版本没有 Developer ID 公证，新包仍需重新执行发布说明中的本地 ad-hoc 与 Gatekeeper 步骤。',
    installUpdate: '更新并重启',
    installingUpdate: '正在下载、验证并安装版本 {version}…',
    updaterNotConfigured: '此构建尚未配置自动更新。',
    updaterUnsupportedPlatform: '此平台不支持自动更新。',
    updateCheckFailed: '无法检查更新。',
    updateInstallFailed: '无法安装更新，当前版本仍可继续使用。',
    updateNotChecked: '请重新检查更新后再安装。',
    updateBusy: '语言切换器正在执行其他操作。',
    updateStateUnavailable: '已检查的更新状态不可用，请重启语言切换器后重新检查。',
    chooseAppAria: '选择 Cavalry 安装位置',
    language: '语言',
    current: '当前',
    switchTo: '切换为',
    englishUi: '英文界面',
    apply: '应用并重启',
    restoreOfficial: '恢复官方 Cavalry 安装',
    officialMode: '安装状态：已验证的官方运行时',
    modifiedMode: '安装状态：由切换器管理或尚未验证',
    recoveryMode: '安装状态：必须先完成中断事务恢复',
    retryApply: '重试应用',
    refreshEnglish: '刷新英文',
    refreshEnglishAria: '刷新英文快照',
    restoreEnglish: '恢复英文',
    openPrivacySecurity: '打开权限设置',
    requestElevation: '以管理员身份重试',
    close: '关闭',
    statusLabel: '操作状态',
    readyPermission: '修改 Cavalry 安装目录可能需要系统授权。',
    customRootNotWritable:
      '所选 Cavalry 文件夹不可写。Windows 仅能为“Program Files”下的安装请求管理员重试；请选择可写副本或调整此文件夹的权限。',
    readyToApply: '可以开始应用语言包。',
    chooseAppToContinue: '请选择 Cavalry 安装位置后继续。',
    needsExtract: '下次补丁前需要先刷新英文源文件。',
    reinstallRequired: '此 Cavalry 安装的原始英文来源记录不完整，无法安全还原。请使用官方安装包重新安装 Cavalry，然后选择新的安装位置。',
    warningStateDurabilityPending: '无法确认状态存储已经持久化。请再次刷新英文快照，再应用语言或恢复官方安装。',
    warningRecoveryCleanupPending: '恢复清理仍未完成。请保留恢复文件，等待切换器完成清理。',
    warningProtectedRecoveryEvidenceRetained: '受保护事务的恢复证据仍然存在，请勿手动删除。',
    warningTemporaryCleanupPending: '临时清理仍未完成。请先关闭切换器，再移除临时文件。',
    warningFinderFallbackUsed: 'macOS 阻止直接复制后，已改用 Finder 方式替换文件。',
    warningNonFatalCleanup: '仍有一项非致命清理需要处理。',
    extractSuccessWarning: '英文快照已刷新（{count} 个文件）。{warnings}',
    chooseAppFirst: '请先选择 Cavalry 安装位置。',
    noLanguage: '没有可用的语言包。',
    refreshingEnglish: '正在刷新英文快照...',
    extractFailed: '无法刷新英文快照。',
    extractSuccess: '英文快照已刷新（{count} 个文件）。',
    runtimeResidueWarning:
      '检测到 Windows 运行时残留。刷新英文未修改运行时文件；需要时请点击“恢复英文”。',
    runtimeResidueAfterRefresh:
      '英文快照已刷新（{count} 个文件）。检测到 Windows 运行时残留。刷新英文未修改运行时文件；需要时请点击“恢复英文”。',
    applying: '正在应用{language}...',
    waitingPermission: '正在等待系统授权。',
    patchFailed: '应用语言包失败。',
    cavalryStillRunning: 'Cavalry 仍在运行。请先保存工作并关闭 Cavalry，然后重试；Cavalry 安装内容未被修改。',
    restartWarning: '无法重启 Cavalry。',
    applied: '已应用{language}并重启 Cavalry。{warning}',
    appliedWithWarnings: '已应用{language}。{warnings}',
    openPrivacyFailed: '无法打开权限设置。',
    bootstrapFailed: '启动失败：{detail}',
    operationFailed: '无法连接桌面服务，请重试。',
    startupRecoveryFailed: '中断的 Cavalry 更新无法安全恢复。请关闭 Cavalry 后重新启动切换器，且不要手动修改安装目录。',
    detail: '详情：{detail}',
    confirmTitle: '安装语言包？',
    confirmBody:
      '所选语言包会修改当前 Cavalry 安装目录；文件应用完成后将重启 Cavalry。',
    restoreConfirmTitle: '恢复官方 Cavalry 安装？',
    restoreConfirmBody:
      '此操作会移除切换器运行文件，并恢复已采集的原厂文件与签名。若任一完整且已验证的原始副本缺失，操作会停止，你需要重新安装 Cavalry。',
    officialRestoreSuccess: '已恢复并重启采集时的官方 Cavalry 安装。',
    officialRestoreWithWarnings: '已恢复采集时的官方 Cavalry 安装。{warnings}',
    continue: '继续',
    cancel: '取消',
    permissionTitle: '需要系统授权',
    permissionBody: '请批准操作系统为 Cavalry 语言切换器显示的权限请求，然后重试。',
  },
  'zh-Hant': {
    appTitle: 'Cavalry 語言切換器',
    appFound: 'Cavalry {version}',
    appFoundNoVersion: '已找到 Cavalry',
    appNotFound: '未找到 Cavalry',
    appPathFallback: '已嘗試：\n{candidates}',
    skipToControls: '跳到操作區域',
    updateButtonAria: '查看可用更新',
    updateTooltip: '發現新版本',
    updatePreviewAvailable: '更新預覽已啟用，不會執行下載或安裝。',
    updateAvailableAnnouncement: '發現版本 {version}。',
    updateConfirmTitle: '更新語言切換器？',
    updateConfirmBody: '版本 {version} 已準備好。語言切換器將下載並驗證更新，替換自身後重新啟動。',
    updateMacAdhocNote: '此次更新會安裝一個新的 macOS 應用程式套件。若發布版本沒有 Developer ID 公證，新套件仍需重新執行發布說明中的本機 ad-hoc 與 Gatekeeper 步驟。',
    installUpdate: '更新並重新啟動',
    installingUpdate: '正在下載、驗證並安裝版本 {version}…',
    updaterNotConfigured: '此建置尚未設定自動更新。',
    updaterUnsupportedPlatform: '此平台不支援自動更新。',
    updateCheckFailed: '無法檢查更新。',
    updateInstallFailed: '無法安裝更新，目前版本仍可繼續使用。',
    updateNotChecked: '請重新檢查更新後再安裝。',
    updateBusy: '語言切換器正在執行其他操作。',
    updateStateUnavailable: '已檢查的更新狀態無法使用，請重新啟動語言切換器後再檢查。',
    chooseAppAria: '選擇 Cavalry 安裝位置',
    language: '語言',
    current: '目前',
    switchTo: '切換為',
    englishUi: '英文介面',
    apply: '套用並重新啟動',
    restoreOfficial: '還原官方 Cavalry 安裝',
    officialMode: '安裝狀態：已驗證的官方執行環境',
    modifiedMode: '安裝狀態：由切換器管理或尚未驗證',
    recoveryMode: '安裝狀態：必須先完成中斷交易復原',
    retryApply: '重試套用',
    refreshEnglish: '重新整理英文',
    refreshEnglishAria: '重新整理英文快照',
    restoreEnglish: '還原英文',
    openPrivacySecurity: '打開權限設定',
    requestElevation: '以系統管理員身分重試',
    close: '關閉',
    statusLabel: '操作狀態',
    readyPermission: '修改 Cavalry 安裝目錄可能需要系統授權。',
    customRootNotWritable:
      '所選 Cavalry 資料夾不可寫入。Windows 僅能為「Program Files」下的安裝要求以系統管理員身分重試；請選擇可寫入的副本或調整此資料夾的權限。',
    readyToApply: '可以開始套用語言包。',
    chooseAppToContinue: '請先選擇 Cavalry 安裝位置再繼續。',
    needsExtract: '下次補丁前需要先重新整理英文來源檔案。',
    reinstallRequired: '此 Cavalry 安裝的原始英文來源記錄不完整，無法安全還原。請使用官方安裝程式重新安裝 Cavalry，然後選擇新的安裝位置。',
    warningStateDurabilityPending: '無法確認狀態儲存已持久化。請再次重新整理英文快照，再套用語言或還原官方安裝。',
    warningRecoveryCleanupPending: '復原清理仍未完成。請保留復原檔案，等待切換器完成清理。',
    warningProtectedRecoveryEvidenceRetained: '受保護交易的復原證據仍然存在，請勿手動刪除。',
    warningTemporaryCleanupPending: '暫存清理仍未完成。請先關閉切換器，再移除暫存檔案。',
    warningFinderFallbackUsed: 'macOS 阻止直接複製後，已改用 Finder 方式替換檔案。',
    warningNonFatalCleanup: '仍有一項非致命清理需要處理。',
    extractSuccessWarning: '英文快照已重新整理（{count} 個檔案）。{warnings}',
    chooseAppFirst: '請先選擇 Cavalry 安裝位置。',
    noLanguage: '沒有可用的語言包。',
    refreshingEnglish: '正在重新整理英文快照...',
    extractFailed: '無法重新整理英文快照。',
    extractSuccess: '英文快照已重新整理（{count} 個檔案）。',
    runtimeResidueWarning:
      '偵測到 Windows 執行環境殘留。重新整理英文未修改執行環境檔案；需要時請點擊「還原英文」。',
    runtimeResidueAfterRefresh:
      '英文快照已重新整理（{count} 個檔案）。偵測到 Windows 執行環境殘留。重新整理英文未修改執行環境檔案；需要時請點擊「還原英文」。',
    applying: '正在套用{language}...',
    waitingPermission: '正在等待系統授權。',
    patchFailed: '套用語言包失敗。',
    cavalryStillRunning: 'Cavalry 仍在執行。請先儲存工作並關閉 Cavalry，然後重試；Cavalry 安裝內容未被修改。',
    restartWarning: '無法重新啟動 Cavalry。',
    applied: '已套用{language}並重新啟動 Cavalry。{warning}',
    appliedWithWarnings: '已套用{language}。{warnings}',
    openPrivacyFailed: '無法打開權限設定。',
    bootstrapFailed: '啟動失敗：{detail}',
    operationFailed: '無法連線至桌面服務，請重試。',
    startupRecoveryFailed: '中斷的 Cavalry 更新無法安全復原。請關閉 Cavalry 後重新啟動切換器，且不要手動修改安裝目錄。',
    detail: '詳情：{detail}',
    confirmTitle: '安裝語言包？',
    confirmBody:
      '所選語言包會修改目前 Cavalry 安裝目錄；檔案套用完成後將重新啟動 Cavalry。',
    restoreConfirmTitle: '還原官方 Cavalry 安裝？',
    restoreConfirmBody:
      '此操作會移除切換器執行檔案，並還原已擷取的原廠檔案與簽章。若任何完整且已驗證的原始副本缺失，操作會停止，你需要重新安裝 Cavalry。',
    officialRestoreSuccess: '已還原並重新啟動擷取時的官方 Cavalry 安裝。',
    officialRestoreWithWarnings: '已還原擷取時的官方 Cavalry 安裝。{warnings}',
    continue: '繼續',
    cancel: '取消',
    permissionTitle: '需要系統授權',
    permissionBody: '請允許作業系統為 Cavalry 語言切換器顯示的權限請求，然後重試。',
  },
  ja_JP: {
    appTitle: 'Cavalry 言語スイッチャー',
    appFound: 'Cavalry {version}',
    appFoundNoVersion: 'Cavalry が見つかりました',
    appNotFound: 'Cavalry が見つかりません',
    appPathFallback: '確認した場所:\n{candidates}',
    skipToControls: '操作領域へ移動',
    updateButtonAria: '利用可能な更新を表示',
    updateTooltip: '新しいバージョンがあります',
    updatePreviewAvailable: '更新プレビューが有効です。ダウンロードやインストールは実行されません。',
    updateAvailableAnnouncement: 'バージョン {version} を利用できます。',
    updateConfirmTitle: '言語スイッチャーを更新しますか？',
    updateConfirmBody: 'バージョン {version} を利用できます。更新をダウンロードして検証し、アプリを置き換えて再起動します。',
    updateMacAdhocNote: 'この更新では新しい macOS アプリバンドルがインストールされます。Developer ID で公証されていないリリースでは、新しいバンドルに対してリリース案内のローカル ad-hoc と Gatekeeper の手順をもう一度実行してください。',
    installUpdate: '更新して再起動',
    installingUpdate: 'バージョン {version} をダウンロード、検証、インストールしています…',
    updaterNotConfigured: 'このビルドには自動更新が設定されていません。',
    updaterUnsupportedPlatform: 'このプラットフォームでは自動更新を利用できません。',
    updateCheckFailed: '更新を確認できませんでした。',
    updateInstallFailed: '更新をインストールできませんでした。現在のバージョンは引き続き使用できます。',
    updateNotChecked: 'インストールする前に更新をもう一度確認してください。',
    updateBusy: '言語スイッチャーで別の操作を実行中です。',
    updateStateUnavailable: '確認済みの更新状態を利用できません。言語スイッチャーを再起動して、もう一度確認してください。',
    chooseAppAria: 'Cavalry のインストール先を選択',
    language: '言語',
    current: '現在',
    switchTo: '切り替え先',
    englishUi: '英語 UI',
    apply: '適用して再起動',
    restoreOfficial: '公式 Cavalry を復元',
    officialMode: 'インストール状態: 検証済みの公式ランタイム',
    modifiedMode: 'インストール状態: Switcher 管理または未検証',
    recoveryMode: 'インストール状態: 中断した処理の復旧が必要です',
    retryApply: '適用を再試行',
    refreshEnglish: '英語を更新',
    refreshEnglishAria: '英語スナップショットを更新',
    restoreEnglish: '英語に戻す',
    openPrivacySecurity: '権限設定を開く',
    requestElevation: '管理者として再試行',
    close: '閉じる',
    statusLabel: '操作状況',
    readyPermission: 'Cavalry のインストール先を変更するにはシステム権限が必要な場合があります。',
    customRootNotWritable:
      '選択した Cavalry フォルダーには書き込めません。Windows で管理者として再試行できるのは Program Files 配下のインストールのみです。書き込み可能なコピーを選ぶか、このフォルダーのアクセス許可を変更してください。',
    readyToApply: '言語パックを適用できます。',
    chooseAppToContinue: '続行するには Cavalry のインストール先を選択してください。',
    needsExtract: '次のパッチの前に英語ソースファイルを更新する必要があります。',
    reinstallRequired: 'この Cavalry インストールは元の英語データの来歴が不完全なため、安全に復元できません。公式インストーラーで Cavalry を再インストールしてから、新しいインストール先を選択してください。',
    warningStateDurabilityPending:
      '状態ストレージの永続化を確認できませんでした。言語の適用や公式版の復元を行う前に、英語スナップショットをもう一度更新してください。',
    warningRecoveryCleanupPending:
      '復旧用ファイルのクリーンアップがまだ完了していません。Switcher が完了するまで復旧用ファイルを残してください。',
    warningProtectedRecoveryEvidenceRetained:
      '保護されたトランザクションの復旧証跡が残っています。手動で削除しないでください。',
    warningTemporaryCleanupPending:
      '一時ファイルのクリーンアップがまだ完了していません。Switcher を終了してから一時ファイルを削除してください。',
    warningFinderFallbackUsed:
      'macOS が直接コピーを拒否したため、Finder 方式でファイルを置き換えました。',
    warningNonFatalCleanup: '致命的ではないクリーンアップ処理が残っています。',
    extractSuccessWarning: '英語スナップショットを更新しました（{count} ファイル）。{warnings}',
    chooseAppFirst: '先に Cavalry のインストール先を選択してください。',
    noLanguage: '利用できる言語パックがありません。',
    refreshingEnglish: '英語スナップショットを更新しています...',
    extractFailed: '英語スナップショットを更新できませんでした。',
    extractSuccess: '英語スナップショットを更新しました（{count} ファイル）。',
    runtimeResidueWarning:
      'Windows ランタイムの残留を検出しました。英語の更新ではランタイムを変更していません。必要に応じて「英語に戻す」をクリックしてください。',
    runtimeResidueAfterRefresh:
      '英語スナップショットを更新しました（{count} ファイル）。Windows ランタイムの残留を検出しました。英語の更新ではランタイムを変更していません。必要に応じて「英語に戻す」をクリックしてください。',
    applying: '{language}を適用しています...',
    waitingPermission: 'システム権限を待っています。',
    patchFailed: '言語パックの適用に失敗しました。',
    cavalryStillRunning:
      'Cavalry がまだ起動しています。作業を保存して Cavalry を終了してから再試行してください。Cavalry のインストール内容は変更されていません。',
    restartWarning: 'Cavalry を再起動できませんでした。',
    applied: '{language}を適用して Cavalry を再起動しました。{warning}',
    appliedWithWarnings: '{language}を適用しました。{warnings}',
    openPrivacyFailed: '権限設定を開けませんでした。',
    bootstrapFailed: '起動に失敗しました: {detail}',
    operationFailed: 'デスクトップサービスに接続できませんでした。もう一度お試しください。',
    startupRecoveryFailed:
      '中断した Cavalry 更新を安全に復旧できませんでした。Cavalry を終了して Switcher を再起動し、インストール先を手動で変更しないでください。',
    detail: ' 詳細: {detail}',
    confirmTitle: '言語パックをインストールしますか？',
    confirmBody:
      '選択した言語パックは Cavalry のインストール先を変更します。ファイルの適用後に Cavalry を再起動します。',
    restoreConfirmTitle: '公式 Cavalry インストールを復元しますか？',
    restoreConfirmBody:
      'Switcher のランタイムファイルを削除し、取得済みのベンダーファイルと署名を復元します。完全で検証済みの原本が一つでもない場合は停止し、Cavalry の再インストールが必要です。',
    officialRestoreSuccess: '取得時の公式 Cavalry インストールを復元して再起動しました。',
    officialRestoreWithWarnings: '取得時の公式 Cavalry インストールを復元しました。{warnings}',
    continue: '続行',
    cancel: 'キャンセル',
    permissionTitle: 'システム権限が必要です',
    permissionBody:
      'Cavalry 言語スイッチャーに対するオペレーティングシステムの権限要求を許可してから再試行してください。',
  },
};
