/**
 * [INPUT]: 无运行时依赖；承载 renderer 稳定的四语本地化 copy。
 * [OUTPUT]: 对外提供非模块脚本全局 UI_TEXT 四语文案目录与 STATUS_TITLE_KEYS 状态标题路由；包含标题区、Windows caption controls、语言/安装状态双徽章、Apply/Restore/Update 任务上下文、真实阶段事件、AlertDialog、macOS 新包 ad-hoc 提醒及完整无障碍名称。
 * [POS]: renderer 的视觉文案与状态语义数据层；由 index.html 在业务脚本前加载，把后端稳定边界压缩为用户可理解的任务事件，把持久阻塞留在视窗、把必须立即选择的风险送入 AlertDialog，隔离交互逻辑与产品 copy。
 * [PROTOCOL]: 变更时更新此头部，然后检查 CLAUDE.md
 */
const UI_TEXT = {
  en: {
    appTitle: 'Cavalry Language Switcher',
    appFound: 'Cavalry {version}',
    appFoundNoVersion: 'Cavalry found',
    appNotFound: 'Cavalry not found',
    appPathFallback: 'Tried:\n{candidates}',
    skipToControls: 'Skip to controls',
    aboutButtonAria: 'About Cavalry Language Switcher',
    aboutTooltip: 'About',
    aboutVersion: 'Version {version}',
    aboutProjectLinks: 'Project links',
    aboutLicense: 'MIT License',
    openProjectLinkFailed: 'Check your default browser, then try again.',
    aboutOpenFailed: 'Could not open About. Try again.',
    updateButtonAria: 'View available update',
    updateTooltip: 'New version available',
    updatePreviewAvailable: 'Update preview is active. No download or installation will run.',
    updateAvailableAnnouncement: 'Version {version} is available.',
    updateConfirmTitle: 'Update the Switcher?',
    updateConfirmBody: 'Version {version} is ready. The Switcher will download, verify, replace itself, and restart.',
    updateMacAdhocNote: 'This update installs a new macOS app bundle. If the release is not Developer ID notarized, complete the documented local ad-hoc and Gatekeeper step again for the new bundle.',
    installUpdate: 'Update & Restart',
    updateDownloadRunningTitle: 'Downloading version {version}',
    updateDownloadProgress: '{percent}% downloaded',
    updateDownloadCompletedTitle: 'Update downloaded',
    updateInstallRunningTitle: 'Verifying and installing the update',
    updateInstallCompletedTitle: 'Update installed',
    updateRestartRunningTitle: 'Restarting the Switcher',
    updaterNotConfigured: 'Automatic updates are not configured for this build.',
    updaterUnsupportedPlatform: 'Automatic updates are not supported on this platform.',
    updateCheckFailed: 'Could not check for updates.',
    updateInstallFailed: 'The update could not be installed. The current version remains available.',
    updateNotChecked: 'Check for an update again before installing.',
    updateBusy: 'Another Switcher operation is already running.',
    updateStateUnavailable: 'The checked update state is unavailable. Restart the Switcher and check again.',
    chooseAppAria: 'Choose Cavalry installation',
    language: 'Language',
    current: 'Current',
    switchTo: 'Switch to',
    englishUi: 'English UI',
    apply: 'Apply & Restart',
    restore: 'Restore',
    officialMode: 'Installation: verified official runtime',
    modifiedMode: 'Installation: locally modified runtime',
    recoveryMode: 'Installation: recovery required before further changes',
    officialBadge: 'Official',
    translatedBadge: 'Translated',
    modifiedBadge: 'Modified',
    retry: 'Retry',
    openSettings: 'Open Settings',
    openPrivacySecurity: 'Open permission settings',
    requestElevation: 'Retry as administrator',
    close: 'Close',
    minimizeWindow: 'Minimize',
    maximizeWindow: 'Maximize',
    restoreWindow: 'Restore',
    closeWindow: 'Close',
    statusLabel: 'Status',
    taskProgressLabel: 'Task progress',
    applyTaskTitle: 'Apply {language}',
    restoreTaskTitle: 'Restore Cavalry',
    updateTaskTitle: 'Update to {version}',
    phaseVerifyInstallationRunningTitle: 'Checking the Cavalry installation',
    phaseVerifyInstallationCompletedTitle: 'Cavalry installation verified',
    phaseVerifyInstallationErrorTitle: 'Couldn’t verify the Cavalry installation',
    phaseEnsureRecoveryRunningTitle: 'Preparing recovery files',
    phaseEnsureRecoveryCompletedTitle: 'Recovery files ready',
    phaseEnsureRecoveryErrorTitle: 'Couldn’t prepare recovery files',
    loadingTitle: 'Loading Cavalry',
    desktopServiceUnavailableTitle: 'Desktop service unavailable',
    restartSwitcherTitle: 'Restart the Switcher',
    updateAvailableTitle: 'Update available',
    updatesUnavailableTitle: 'Automatic updates unavailable',
    updateCheckFailedTitle: 'Couldn’t check for updates',
    updateInstallFailedTitle: 'Couldn’t install the update',
    checkUpdateAgainTitle: 'Check for updates again',
    operationInProgressTitle: 'Another operation is running',
    permissionRequiredTitle: 'System permission required',
    permissionMayBeRequiredTitle: 'System permission may be required',
    recoveryFailedTitle: 'Couldn’t recover the interrupted operation',
    chooseAppTitle: 'Choose Cavalry',
    reinstallCavalryTitle: 'Reinstall Cavalry',
    finishRuntimeCleanupTitle: 'Restore Cavalry to finish cleanup',
    readyToApplyTitle: 'Ready to apply',
    folderNotWritableTitle: 'Cavalry folder isn’t writable',
    preparingApplyTitle: 'Preparing {language}',
    restoringTitle: 'Restoring Cavalry',
    noLanguageTitle: 'No language pack available',
    applyingTitle: 'Applying {language}',
    closeCavalryTitle: 'Close Cavalry before retrying',
    applyFailedTitle: 'Couldn’t apply the language pack',
    restoredTitle: 'Cavalry restored',
    appliedTitle: '{language} applied',
    phaseApplyRunningTitle: 'Applying {language}',
    phaseApplyCompletedTitle: '{language} applied',
    phaseApplyErrorTitle: 'Couldn’t apply {language}',
    phaseRestoreRunningTitle: 'Restoring Cavalry',
    phaseRestoreCompletedTitle: 'Cavalry restored',
    phaseRestoreErrorTitle: 'Couldn’t restore Cavalry',
    phaseRestartRunningTitle: 'Restarting Cavalry',
    phaseRestartCompletedTitle: 'Cavalry restarted',
    phaseRestartWarningTitle: 'Cavalry did not restart',
    phaseRestartErrorTitle: 'Cavalry did not restart',
    recoveryCleanupPendingTitle: 'Recovery cleanup is pending',
    keepRecoveryFilesTitle: 'Keep the recovery files',
    temporaryCleanupPendingTitle: 'Temporary cleanup is pending',
    finderReplacementTitle: 'Finder replacement was used',
    cleanupAttentionTitle: 'Cleanup needs attention',
    settingsFailedTitle: 'Couldn’t open permission settings',
    projectLinkFailedTitle: 'Couldn’t open the project link',
    aboutOpenFailedTitle: 'Couldn’t open About',
    startupFailedTitle: 'Couldn’t start the Switcher',
    readyPermission: 'System permission may be required to modify the Cavalry installation.',
    customRootNotWritable:
      'Cavalry’s folder isn’t writable. Administrator retry only supports Program Files. Choose a writable copy or change the folder permissions.',
    readyToApply: 'Choose a language, then apply and restart Cavalry.',
    chooseAppToContinue: 'Choose a Cavalry installation to continue.',
    reinstallRequired: 'The original English files cannot be verified. Reinstall Cavalry from the official installer, then choose the new installation.',
    warningStateDurabilityPending: 'Restart the Switcher before applying a language or restoring Cavalry.',
    warningRecoveryCleanupPending:
      'Recovery cleanup is still pending. Keep the recovery files until the Switcher completes cleanup.',
    warningProtectedRecoveryEvidenceRetained:
      'Recovery files are still needed. Do not delete them manually.',
    warningTemporaryCleanupPending:
      'Temporary cleanup is still pending. Close the Switcher before removing temporary files.',
    warningFinderFallbackUsed:
      'macOS used Finder-style replacement because direct copy was blocked.',
    warningNonFatalCleanup: 'A non-fatal cleanup step still needs attention.',
    chooseAppFirst: 'Choose a Cavalry installation first.',
    noLanguage: 'No language pack is available.',
    preparingApply: 'Saving the original files needed for recovery before Cavalry is modified.',
    restoring: 'Cavalry will restart after its official English files and runtime are restored.',
    runtimeResidueWarning: 'Files from a previous Windows language setup are still active. Choose Restore to finish cleanup.',
    applying: 'Cavalry will restart when the language files are ready.',
    waitingPermission: 'Approve the system request, then retry.',
    patchFailed: 'Cavalry was not changed. Try again.',
    restoreFailed: 'Cavalry was not restored. Try again.',
    cavalryStillRunning:
      'Cavalry is still running. Save your work, close Cavalry, and try again. The Cavalry installation was not changed.',
    restartWarning: 'Cavalry could not be restarted.',
    restartRecovery: 'Open Cavalry manually.',
    applied: 'Cavalry restarted.{warning}',
    appliedWithWarnings: '{warnings}',
    openPrivacyFailed: 'Open Privacy & Security in System Settings, then allow the Switcher to modify Cavalry.',
    bootstrapFailed: '{detail}',
    operationFailed: 'Could not contact the desktop service. Try again.',
    startupRecoveryFailed:
      'Couldn’t recover an interrupted update. Close Cavalry and restart the Switcher. Don’t modify the installation manually.',
    detail: ' Details: {detail}',
    confirmTitle: 'Install language pack?',
    confirmBody:
      'The selected language pack will modify the chosen Cavalry installation. Cavalry will restart after the files are applied.',
    restoreConfirmTitle: 'Restore Cavalry?',
    restoreConfirmBody: 'Cavalry will return to its official English state. Switcher translation files will be removed, and Cavalry will restart.',
    restoreSuccess: 'Cavalry restarted.',
    restoreWithWarnings: '{warnings}',
    continue: 'Continue',
    cancel: 'Cancel',
    permissionTitle: 'System permission required',
    permissionBody:
      'Approve the operating system permission request for Cavalry Language Switcher, then retry.',
  },
  'zh-Hans': {
    appTitle: 'Cavalry 语言切换器',
    appFound: 'Cavalry {version}',
    appFoundNoVersion: '已找到 Cavalry',
    appNotFound: '未找到 Cavalry',
    appPathFallback: '已尝试：\n{candidates}',
    skipToControls: '跳到操作区域',
    aboutButtonAria: '关于 Cavalry 语言切换器',
    aboutTooltip: '关于',
    aboutVersion: '版本 {version}',
    aboutProjectLinks: '项目链接',
    aboutLicense: 'MIT 许可证',
    openProjectLinkFailed: '检查默认浏览器后重试。',
    aboutOpenFailed: '无法打开“关于”窗口，请重试。',
    updateButtonAria: '查看可用更新',
    updateTooltip: '发现新版本',
    updatePreviewAvailable: '更新预览已启用，不会执行下载或安装。',
    updateAvailableAnnouncement: '发现版本 {version}。',
    updateConfirmTitle: '更新语言切换器？',
    updateConfirmBody: '版本 {version} 已准备好。语言切换器将下载并验证更新，替换自身后重新启动。',
    updateMacAdhocNote: '此次更新会安装一个新的 macOS 应用包。若发布版本没有 Developer ID 公证，新包仍需重新执行发布说明中的本地 ad-hoc 与 Gatekeeper 步骤。',
    installUpdate: '更新并重启',
    updateDownloadRunningTitle: '正在下载版本 {version}',
    updateDownloadProgress: '已下载 {percent}%',
    updateDownloadCompletedTitle: '更新已下载',
    updateInstallRunningTitle: '正在验证并安装更新',
    updateInstallCompletedTitle: '更新已安装',
    updateRestartRunningTitle: '正在重启语言切换器',
    updaterNotConfigured: '此构建尚未配置自动更新。',
    updaterUnsupportedPlatform: '此平台不支持自动更新。',
    updateCheckFailed: '无法检查更新。',
    updateInstallFailed: '无法安装更新，当前版本仍可继续使用。',
    updateNotChecked: '请重新检查更新后再安装。',
    updateBusy: '语言切换器正在执行其他操作。',
    updateStateUnavailable: '已检查的更新状态不可用，请重启语言切换器后重新检查。',
    chooseAppAria: '选择 Cavalry 安装位置',
    language: '语言',
    current: '当前',
    switchTo: '切换为',
    englishUi: '英文界面',
    apply: '应用并重启',
    restore: '恢复',
    officialMode: '安装状态：已验证的官方运行时',
    modifiedMode: '安装状态：已在本机修改',
    recoveryMode: '安装状态：必须先完成中断事务恢复',
    officialBadge: '官方',
    translatedBadge: '已翻译',
    modifiedBadge: '已修改',
    retry: '重试',
    openSettings: '打开设置',
    openPrivacySecurity: '打开权限设置',
    requestElevation: '以管理员身份重试',
    close: '关闭',
    minimizeWindow: '最小化',
    maximizeWindow: '最大化',
    restoreWindow: '还原',
    closeWindow: '关闭',
    statusLabel: '状态',
    taskProgressLabel: '任务进度',
    applyTaskTitle: '应用{language}',
    restoreTaskTitle: '恢复 Cavalry',
    updateTaskTitle: '更新到版本 {version}',
    phaseVerifyInstallationRunningTitle: '正在检查 Cavalry 安装',
    phaseVerifyInstallationCompletedTitle: '已验证 Cavalry 安装',
    phaseVerifyInstallationErrorTitle: '无法验证 Cavalry 安装',
    phaseEnsureRecoveryRunningTitle: '正在准备恢复文件',
    phaseEnsureRecoveryCompletedTitle: '恢复文件已就绪',
    phaseEnsureRecoveryErrorTitle: '无法准备恢复文件',
    loadingTitle: '正在载入 Cavalry',
    desktopServiceUnavailableTitle: '桌面服务不可用',
    restartSwitcherTitle: '重启语言切换器',
    updateAvailableTitle: '有可用更新',
    updatesUnavailableTitle: '自动更新不可用',
    updateCheckFailedTitle: '无法检查更新',
    updateInstallFailedTitle: '无法安装更新',
    checkUpdateAgainTitle: '重新检查更新',
    operationInProgressTitle: '正在执行其他操作',
    permissionRequiredTitle: '需要系统权限',
    permissionMayBeRequiredTitle: '可能需要系统权限',
    recoveryFailedTitle: '无法恢复中断的操作',
    chooseAppTitle: '选择 Cavalry 安装位置',
    reinstallCavalryTitle: '重新安装 Cavalry',
    finishRuntimeCleanupTitle: '恢复 Cavalry 以完成清理',
    readyToApplyTitle: '可以应用语言包',
    folderNotWritableTitle: 'Cavalry 文件夹不可写',
    preparingApplyTitle: '正在准备{language}',
    restoringTitle: '正在恢复 Cavalry',
    noLanguageTitle: '没有可用的语言包',
    applyingTitle: '正在应用{language}',
    closeCavalryTitle: '关闭 Cavalry 后重试',
    applyFailedTitle: '无法应用语言包',
    restoredTitle: '已恢复 Cavalry',
    appliedTitle: '已应用{language}',
    phaseApplyRunningTitle: '正在应用{language}',
    phaseApplyCompletedTitle: '已应用{language}',
    phaseApplyErrorTitle: '无法应用{language}',
    phaseRestoreRunningTitle: '正在恢复 Cavalry',
    phaseRestoreCompletedTitle: '已恢复 Cavalry',
    phaseRestoreErrorTitle: '无法恢复 Cavalry',
    phaseRestartRunningTitle: '正在重启 Cavalry',
    phaseRestartCompletedTitle: 'Cavalry 已重启',
    phaseRestartWarningTitle: 'Cavalry 未重启',
    phaseRestartErrorTitle: 'Cavalry 未重启',
    recoveryCleanupPendingTitle: '恢复清理尚未完成',
    keepRecoveryFilesTitle: '请保留恢复文件',
    temporaryCleanupPendingTitle: '临时清理尚未完成',
    finderReplacementTitle: '已使用 Finder 替换文件',
    cleanupAttentionTitle: '清理仍需处理',
    settingsFailedTitle: '无法打开权限设置',
    projectLinkFailedTitle: '无法打开项目链接',
    aboutOpenFailedTitle: '无法打开关于窗口',
    startupFailedTitle: '无法启动语言切换器',
    readyPermission: '修改 Cavalry 安装目录可能需要系统授权。',
    customRootNotWritable:
      'Cavalry 文件夹不可写。仅“Program Files”中的安装可以管理员身份重试。请选择可写副本或修改文件夹权限。',
    readyToApply: '选择语言，然后应用并重启 Cavalry。',
    chooseAppToContinue: '请选择 Cavalry 安装位置后继续。',
    reinstallRequired: '无法验证原始英文文件。使用官方安装包重新安装 Cavalry，然后选择新的安装位置。',
    warningStateDurabilityPending: '重启语言切换器，然后再应用语言或恢复 Cavalry。',
    warningRecoveryCleanupPending: '恢复清理仍未完成。请保留恢复文件，等待切换器完成清理。',
    warningProtectedRecoveryEvidenceRetained: '恢复文件仍然需要保留，请勿手动删除。',
    warningTemporaryCleanupPending: '临时清理仍未完成。请先关闭切换器，再移除临时文件。',
    warningFinderFallbackUsed: 'macOS 阻止直接复制后，已改用 Finder 方式替换文件。',
    warningNonFatalCleanup: '仍有一项非致命清理需要处理。',
    chooseAppFirst: '请先选择 Cavalry 安装位置。',
    noLanguage: '没有可用的语言包。',
    preparingApply: '修改 Cavalry 前，将保存恢复所需的原始文件。',
    restoring: '恢复官方英文文件和运行环境后，Cavalry 将重启。',
    runtimeResidueWarning: '之前的 Windows 语言设置仍有文件在生效。选择“恢复”以完成清理。',
    applying: '语言文件就绪后，Cavalry 将自动重启。',
    waitingPermission: '批准系统权限请求，然后重试。',
    patchFailed: 'Cavalry 未被修改，请重试。',
    restoreFailed: '未恢复 Cavalry，请重试。',
    cavalryStillRunning: 'Cavalry 仍在运行。请先保存工作并关闭 Cavalry，然后重试；Cavalry 安装内容未被修改。',
    restartWarning: '无法重启 Cavalry。',
    restartRecovery: '请手动打开 Cavalry。',
    applied: 'Cavalry 已重启。{warning}',
    appliedWithWarnings: '{warnings}',
    openPrivacyFailed: '请在系统设置中打开“隐私与安全性”，允许语言切换器修改 Cavalry。',
    bootstrapFailed: '{detail}',
    operationFailed: '无法连接桌面服务，请重试。',
    startupRecoveryFailed: '无法恢复中断的更新。请关闭 Cavalry 并重启语言切换器，不要手动修改安装目录。',
    detail: '详情：{detail}',
    confirmTitle: '安装语言包？',
    confirmBody:
      '所选语言包会修改当前 Cavalry 安装目录；文件应用完成后将重启 Cavalry。',
    restoreConfirmTitle: '恢复 Cavalry？',
    restoreConfirmBody: 'Cavalry 将恢复为官方英文状态。语言切换器添加的翻译文件会被移除，随后 Cavalry 将重启。',
    restoreSuccess: 'Cavalry 已重启。',
    restoreWithWarnings: '{warnings}',
    continue: '继续',
    cancel: '取消',
    permissionTitle: '需要系统授权',
    permissionBody: '请批准操作系统为 Cavalry 语言切换器显示的权限请求，然后重试。',
  },
  'zh-Hant': {
    appTitle: 'Cavalry 語言切換器',
    appFound: 'Cavalry {version}',
    appFoundNoVersion: '已找到 Cavalry',
    appNotFound: '未找到 Cavalry',
    appPathFallback: '已嘗試：\n{candidates}',
    skipToControls: '跳到操作區域',
    aboutButtonAria: '關於 Cavalry 語言切換器',
    aboutTooltip: '關於',
    aboutVersion: '版本 {version}',
    aboutProjectLinks: '專案連結',
    aboutLicense: 'MIT 授權條款',
    openProjectLinkFailed: '檢查預設瀏覽器後重試。',
    aboutOpenFailed: '無法開啟「關於」視窗，請重試。',
    updateButtonAria: '查看可用更新',
    updateTooltip: '發現新版本',
    updatePreviewAvailable: '更新預覽已啟用，不會執行下載或安裝。',
    updateAvailableAnnouncement: '發現版本 {version}。',
    updateConfirmTitle: '更新語言切換器？',
    updateConfirmBody: '版本 {version} 已準備好。語言切換器將下載並驗證更新，替換自身後重新啟動。',
    updateMacAdhocNote: '此次更新會安裝一個新的 macOS 應用程式套件。若發布版本沒有 Developer ID 公證，新套件仍需重新執行發布說明中的本機 ad-hoc 與 Gatekeeper 步驟。',
    installUpdate: '更新並重新啟動',
    updateDownloadRunningTitle: '正在下載版本 {version}',
    updateDownloadProgress: '已下載 {percent}%',
    updateDownloadCompletedTitle: '更新已下載',
    updateInstallRunningTitle: '正在驗證並安裝更新',
    updateInstallCompletedTitle: '更新已安裝',
    updateRestartRunningTitle: '正在重新啟動語言切換器',
    updaterNotConfigured: '此建置尚未設定自動更新。',
    updaterUnsupportedPlatform: '此平台不支援自動更新。',
    updateCheckFailed: '無法檢查更新。',
    updateInstallFailed: '無法安裝更新，目前版本仍可繼續使用。',
    updateNotChecked: '請重新檢查更新後再安裝。',
    updateBusy: '語言切換器正在執行其他操作。',
    updateStateUnavailable: '已檢查的更新狀態無法使用，請重新啟動語言切換器後再檢查。',
    chooseAppAria: '選擇 Cavalry 安裝位置',
    language: '語言',
    current: '目前',
    switchTo: '切換為',
    englishUi: '英文介面',
    apply: '套用並重新啟動',
    restore: '還原',
    officialMode: '安裝狀態：已驗證的官方執行環境',
    modifiedMode: '安裝狀態：已在本機修改',
    recoveryMode: '安裝狀態：必須先完成中斷交易復原',
    officialBadge: '官方',
    translatedBadge: '已翻譯',
    modifiedBadge: '已修改',
    retry: '重試',
    openSettings: '打開設定',
    openPrivacySecurity: '打開權限設定',
    requestElevation: '以系統管理員身分重試',
    close: '關閉',
    minimizeWindow: '最小化',
    maximizeWindow: '最大化',
    restoreWindow: '還原',
    closeWindow: '關閉',
    statusLabel: '狀態',
    taskProgressLabel: '任務進度',
    applyTaskTitle: '套用{language}',
    restoreTaskTitle: '還原 Cavalry',
    updateTaskTitle: '更新至版本 {version}',
    phaseVerifyInstallationRunningTitle: '正在檢查 Cavalry 安裝',
    phaseVerifyInstallationCompletedTitle: '已驗證 Cavalry 安裝',
    phaseVerifyInstallationErrorTitle: '無法驗證 Cavalry 安裝',
    phaseEnsureRecoveryRunningTitle: '正在準備還原檔案',
    phaseEnsureRecoveryCompletedTitle: '還原檔案已就緒',
    phaseEnsureRecoveryErrorTitle: '無法準備還原檔案',
    loadingTitle: '正在載入 Cavalry',
    desktopServiceUnavailableTitle: '桌面服務無法使用',
    restartSwitcherTitle: '重新啟動語言切換器',
    updateAvailableTitle: '有可用更新',
    updatesUnavailableTitle: '自動更新無法使用',
    updateCheckFailedTitle: '無法檢查更新',
    updateInstallFailedTitle: '無法安裝更新',
    checkUpdateAgainTitle: '重新檢查更新',
    operationInProgressTitle: '正在執行其他操作',
    permissionRequiredTitle: '需要系統權限',
    permissionMayBeRequiredTitle: '可能需要系統權限',
    recoveryFailedTitle: '無法復原中斷的操作',
    chooseAppTitle: '選擇 Cavalry 安裝位置',
    reinstallCavalryTitle: '重新安裝 Cavalry',
    finishRuntimeCleanupTitle: '還原 Cavalry 以完成清理',
    readyToApplyTitle: '可以套用語言包',
    folderNotWritableTitle: 'Cavalry 資料夾無法寫入',
    preparingApplyTitle: '正在準備{language}',
    restoringTitle: '正在還原 Cavalry',
    noLanguageTitle: '沒有可用的語言包',
    applyingTitle: '正在套用{language}',
    closeCavalryTitle: '關閉 Cavalry 後重試',
    applyFailedTitle: '無法套用語言包',
    restoredTitle: '已還原 Cavalry',
    appliedTitle: '已套用{language}',
    phaseApplyRunningTitle: '正在套用{language}',
    phaseApplyCompletedTitle: '已套用{language}',
    phaseApplyErrorTitle: '無法套用{language}',
    phaseRestoreRunningTitle: '正在還原 Cavalry',
    phaseRestoreCompletedTitle: '已還原 Cavalry',
    phaseRestoreErrorTitle: '無法還原 Cavalry',
    phaseRestartRunningTitle: '正在重新啟動 Cavalry',
    phaseRestartCompletedTitle: 'Cavalry 已重新啟動',
    phaseRestartWarningTitle: 'Cavalry 未重新啟動',
    phaseRestartErrorTitle: 'Cavalry 未重新啟動',
    recoveryCleanupPendingTitle: '復原清理尚未完成',
    keepRecoveryFilesTitle: '請保留復原檔案',
    temporaryCleanupPendingTitle: '暫存清理尚未完成',
    finderReplacementTitle: '已使用 Finder 替換檔案',
    cleanupAttentionTitle: '清理仍需處理',
    settingsFailedTitle: '無法打開權限設定',
    projectLinkFailedTitle: '無法打開專案連結',
    aboutOpenFailedTitle: '無法開啟關於視窗',
    startupFailedTitle: '無法啟動語言切換器',
    readyPermission: '修改 Cavalry 安裝目錄可能需要系統授權。',
    customRootNotWritable:
      'Cavalry 資料夾無法寫入。只有「Program Files」中的安裝可用系統管理員身分重試。請選擇可寫入的副本或修改資料夾權限。',
    readyToApply: '選擇語言，然後套用並重新啟動 Cavalry。',
    chooseAppToContinue: '請先選擇 Cavalry 安裝位置再繼續。',
    reinstallRequired: '無法驗證原始英文檔案。使用官方安裝程式重新安裝 Cavalry，然後選擇新的安裝位置。',
    warningStateDurabilityPending: '重新啟動語言切換器，然後再套用語言或還原 Cavalry。',
    warningRecoveryCleanupPending: '復原清理仍未完成。請保留復原檔案，等待切換器完成清理。',
    warningProtectedRecoveryEvidenceRetained: '復原檔案仍需保留，請勿手動刪除。',
    warningTemporaryCleanupPending: '暫存清理仍未完成。請先關閉切換器，再移除暫存檔案。',
    warningFinderFallbackUsed: 'macOS 阻止直接複製後，已改用 Finder 方式替換檔案。',
    warningNonFatalCleanup: '仍有一項非致命清理需要處理。',
    chooseAppFirst: '請先選擇 Cavalry 安裝位置。',
    noLanguage: '沒有可用的語言包。',
    preparingApply: '修改 Cavalry 前，將儲存還原所需的原始檔案。',
    restoring: '還原官方英文檔案和執行環境後，Cavalry 將重新啟動。',
    runtimeResidueWarning: '之前的 Windows 語言設定仍有檔案在生效。選擇「還原」以完成清理。',
    applying: '語言檔案就緒後，Cavalry 將自動重新啟動。',
    waitingPermission: '允許系統權限要求，然後重試。',
    patchFailed: 'Cavalry 未被修改，請重試。',
    restoreFailed: '未還原 Cavalry，請重試。',
    cavalryStillRunning: 'Cavalry 仍在執行。請先儲存工作並關閉 Cavalry，然後重試；Cavalry 安裝內容未被修改。',
    restartWarning: '無法重新啟動 Cavalry。',
    restartRecovery: '請手動開啟 Cavalry。',
    applied: 'Cavalry 已重新啟動。{warning}',
    appliedWithWarnings: '{warnings}',
    openPrivacyFailed: '請在系統設定中打開「隱私權與安全性」，允許語言切換器修改 Cavalry。',
    bootstrapFailed: '{detail}',
    operationFailed: '無法連線至桌面服務，請重試。',
    startupRecoveryFailed: '無法復原中斷的更新。請關閉 Cavalry 並重新啟動語言切換器，不要手動修改安裝目錄。',
    detail: '詳情：{detail}',
    confirmTitle: '安裝語言包？',
    confirmBody:
      '所選語言包會修改目前 Cavalry 安裝目錄；檔案套用完成後將重新啟動 Cavalry。',
    restoreConfirmTitle: '還原 Cavalry？',
    restoreConfirmBody: 'Cavalry 將還原為官方英文狀態。語言切換器加入的翻譯檔案會被移除，隨後 Cavalry 將重新啟動。',
    restoreSuccess: 'Cavalry 已重新啟動。',
    restoreWithWarnings: '{warnings}',
    continue: '繼續',
    cancel: '取消',
    permissionTitle: '需要系統授權',
    permissionBody: '請允許作業系統為 Cavalry 語言切換器顯示的權限請求，然後重試。',
  },
  ja_JP: {
    appTitle: 'Cavalry 言語スイッチャー',
    appFound: 'Cavalry {version}',
    appFoundNoVersion: 'Cavalry が見つかりました',
    appNotFound: 'Cavalry が見つかりません',
    appPathFallback: '確認した場所:\n{candidates}',
    skipToControls: '操作領域へ移動',
    aboutButtonAria: 'Cavalry 言語スイッチャーについて',
    aboutTooltip: 'このアプリについて',
    aboutVersion: 'バージョン {version}',
    aboutProjectLinks: 'プロジェクトリンク',
    aboutLicense: 'MIT ライセンス',
    openProjectLinkFailed: '既定のブラウザを確認して、再試行してください。',
    aboutOpenFailed: '「このアプリについて」を開けませんでした。もう一度お試しください。',
    updateButtonAria: '利用可能な更新を表示',
    updateTooltip: '新しいバージョンがあります',
    updatePreviewAvailable: '更新プレビューが有効です。ダウンロードやインストールは実行されません。',
    updateAvailableAnnouncement: 'バージョン {version} を利用できます。',
    updateConfirmTitle: '言語スイッチャーを更新しますか？',
    updateConfirmBody: 'バージョン {version} を利用できます。更新をダウンロードして検証し、アプリを置き換えて再起動します。',
    updateMacAdhocNote: 'この更新では新しい macOS アプリバンドルがインストールされます。Developer ID で公証されていないリリースでは、新しいバンドルに対してリリース案内のローカル ad-hoc と Gatekeeper の手順をもう一度実行してください。',
    installUpdate: '更新して再起動',
    updateDownloadRunningTitle: 'バージョン {version} をダウンロード中',
    updateDownloadProgress: '{percent}% ダウンロード済み',
    updateDownloadCompletedTitle: '更新をダウンロードしました',
    updateInstallRunningTitle: '更新を検証してインストール中',
    updateInstallCompletedTitle: '更新をインストールしました',
    updateRestartRunningTitle: '言語スイッチャーを再起動中',
    updaterNotConfigured: 'このビルドには自動更新が設定されていません。',
    updaterUnsupportedPlatform: 'このプラットフォームでは自動更新を利用できません。',
    updateCheckFailed: '更新を確認できませんでした。',
    updateInstallFailed: '更新をインストールできませんでした。現在のバージョンは引き続き使用できます。',
    updateNotChecked: 'インストールする前に更新をもう一度確認してください。',
    updateBusy: '言語スイッチャーで別の操作を実行中です。',
    updateStateUnavailable: '確認済みの更新状態を利用できません。言語スイッチャーを再起動して、もう一度確認してください。',
    chooseAppAria: 'Cavalry のインストール先を選択',
    language: '言語',
    current: '現在',
    switchTo: '切り替え先',
    englishUi: '英語 UI',
    apply: '適用して再起動',
    restore: '復元',
    officialMode: 'インストール状態: 検証済みの公式ランタイム',
    modifiedMode: 'インストール状態: ローカルで変更済み',
    recoveryMode: 'インストール状態: 中断した処理の復旧が必要です',
    officialBadge: '公式',
    translatedBadge: '翻訳済み',
    modifiedBadge: '変更済み',
    retry: '再試行',
    openSettings: '設定を開く',
    openPrivacySecurity: '権限設定を開く',
    requestElevation: '管理者として再試行',
    close: '閉じる',
    minimizeWindow: '最小化',
    maximizeWindow: '最大化',
    restoreWindow: '元に戻す',
    closeWindow: '閉じる',
    statusLabel: '状態',
    taskProgressLabel: 'タスクの進行状況',
    applyTaskTitle: '{language}を適用',
    restoreTaskTitle: 'Cavalry を復元',
    updateTaskTitle: 'バージョン {version} に更新',
    phaseVerifyInstallationRunningTitle: 'Cavalry のインストールを確認中',
    phaseVerifyInstallationCompletedTitle: 'Cavalry のインストールを確認しました',
    phaseVerifyInstallationErrorTitle: 'Cavalry のインストールを確認できません',
    phaseEnsureRecoveryRunningTitle: '復元ファイルを準備中',
    phaseEnsureRecoveryCompletedTitle: '復元ファイルの準備ができました',
    phaseEnsureRecoveryErrorTitle: '復元ファイルを準備できません',
    loadingTitle: 'Cavalry を読み込み中',
    desktopServiceUnavailableTitle: 'デスクトップサービスを利用できません',
    restartSwitcherTitle: '言語スイッチャーを再起動',
    updateAvailableTitle: '更新があります',
    updatesUnavailableTitle: '自動更新を利用できません',
    updateCheckFailedTitle: '更新を確認できません',
    updateInstallFailedTitle: '更新をインストールできません',
    checkUpdateAgainTitle: '更新をもう一度確認',
    operationInProgressTitle: '別の操作を実行中です',
    permissionRequiredTitle: 'システム権限が必要です',
    permissionMayBeRequiredTitle: 'システム権限が必要な場合があります',
    recoveryFailedTitle: '中断した操作を復旧できません',
    chooseAppTitle: 'Cavalry のインストール先を選択',
    reinstallCavalryTitle: 'Cavalry を再インストール',
    finishRuntimeCleanupTitle: 'Cavalry を復元してクリーンアップを完了',
    readyToApplyTitle: '言語パックを適用できます',
    folderNotWritableTitle: 'Cavalry フォルダーに書き込めません',
    preparingApplyTitle: '{language}を準備中',
    restoringTitle: 'Cavalry を復元中',
    noLanguageTitle: '利用できる言語パックがありません',
    applyingTitle: '{language}を適用中',
    closeCavalryTitle: 'Cavalry を終了して再試行',
    applyFailedTitle: '言語パックを適用できません',
    restoredTitle: 'Cavalry を復元しました',
    appliedTitle: '{language}を適用しました',
    phaseApplyRunningTitle: '{language}を適用中',
    phaseApplyCompletedTitle: '{language}を適用しました',
    phaseApplyErrorTitle: '{language}を適用できません',
    phaseRestoreRunningTitle: 'Cavalry を復元中',
    phaseRestoreCompletedTitle: 'Cavalry を復元しました',
    phaseRestoreErrorTitle: 'Cavalry を復元できません',
    phaseRestartRunningTitle: 'Cavalry を再起動中',
    phaseRestartCompletedTitle: 'Cavalry を再起動しました',
    phaseRestartWarningTitle: 'Cavalry を再起動できませんでした',
    phaseRestartErrorTitle: 'Cavalry を再起動できませんでした',
    recoveryCleanupPendingTitle: '復旧処理が完了していません',
    keepRecoveryFilesTitle: '復旧ファイルを残してください',
    temporaryCleanupPendingTitle: '一時ファイルの処理が完了していません',
    finderReplacementTitle: 'Finder 方式で置き換えました',
    cleanupAttentionTitle: 'クリーンアップを確認してください',
    settingsFailedTitle: '権限設定を開けません',
    projectLinkFailedTitle: 'プロジェクトリンクを開けませんでした',
    aboutOpenFailedTitle: '「このアプリについて」を開けませんでした',
    startupFailedTitle: '言語スイッチャーを起動できません',
    readyPermission: 'Cavalry のインストール先を変更するにはシステム権限が必要な場合があります。',
    customRootNotWritable:
      'Cavalry フォルダーに書き込めません。管理者として再試行できるのは Program Files 内だけです。書き込み可能なコピーを選ぶか、アクセス権を変更してください。',
    readyToApply: '言語を選び、適用して Cavalry を再起動します。',
    chooseAppToContinue: '続行するには Cavalry のインストール先を選択してください。',
    reinstallRequired: '元の英語ファイルを確認できません。公式インストーラーで Cavalry を再インストールしてから、新しいインストール先を選択してください。',
    warningStateDurabilityPending: '言語の適用または Cavalry の復元前に、言語スイッチャーを再起動してください。',
    warningRecoveryCleanupPending:
      '復旧用ファイルのクリーンアップがまだ完了していません。Switcher が完了するまで復旧用ファイルを残してください。',
    warningProtectedRecoveryEvidenceRetained:
      '復旧ファイルはまだ必要です。手動で削除しないでください。',
    warningTemporaryCleanupPending:
      '一時ファイルのクリーンアップがまだ完了していません。Switcher を終了してから一時ファイルを削除してください。',
    warningFinderFallbackUsed:
      'macOS が直接コピーを拒否したため、Finder 方式でファイルを置き換えました。',
    warningNonFatalCleanup: '致命的ではないクリーンアップ処理が残っています。',
    chooseAppFirst: '先に Cavalry のインストール先を選択してください。',
    noLanguage: '利用できる言語パックがありません。',
    preparingApply: 'Cavalry を変更する前に、復元に必要な元のファイルを保存しています。',
    restoring: '公式の英語ファイルとランタイムを復元した後、Cavalry を再起動します。',
    runtimeResidueWarning: '以前の Windows 言語設定のファイルがまだ有効です。「復元」を選んでクリーンアップを完了してください。',
    applying: '言語ファイルの準備ができると Cavalry が再起動します。',
    waitingPermission: 'システムの権限要求を許可してから再試行してください。',
    patchFailed: 'Cavalry は変更されていません。もう一度お試しください。',
    restoreFailed: 'Cavalry は復元されていません。もう一度お試しください。',
    cavalryStillRunning:
      'Cavalry がまだ起動しています。作業を保存して Cavalry を終了してから再試行してください。Cavalry のインストール内容は変更されていません。',
    restartWarning: 'Cavalry を再起動できませんでした。',
    restartRecovery: 'Cavalry を手動で起動してください。',
    applied: 'Cavalry を再起動しました。{warning}',
    appliedWithWarnings: '{warnings}',
    openPrivacyFailed: 'システム設定で「プライバシーとセキュリティ」を開き、Switcher に Cavalry の変更を許可してください。',
    bootstrapFailed: '{detail}',
    operationFailed: 'デスクトップサービスに接続できませんでした。もう一度お試しください。',
    startupRecoveryFailed:
      '中断した更新を復旧できません。Cavalry を終了して言語スイッチャーを再起動し、インストール先を手動で変更しないでください。',
    detail: ' 詳細: {detail}',
    confirmTitle: '言語パックをインストールしますか？',
    confirmBody:
      '選択した言語パックは Cavalry のインストール先を変更します。ファイルの適用後に Cavalry を再起動します。',
    restoreConfirmTitle: 'Cavalry を復元しますか？',
    restoreConfirmBody: 'Cavalry を公式の英語状態に戻します。言語スイッチャーが追加した翻訳ファイルを削除し、Cavalry を再起動します。',
    restoreSuccess: 'Cavalry を再起動しました。',
    restoreWithWarnings: '{warnings}',
    continue: '続行',
    cancel: 'キャンセル',
    permissionTitle: 'システム権限が必要です',
    permissionBody:
      'Cavalry 言語スイッチャーに対するオペレーティングシステムの権限要求を許可してから再試行してください。',
  },
};

const STATUS_TITLE_KEYS = Object.freeze({
  operationFailed: 'desktopServiceUnavailableTitle',
  warningStateDurabilityPending: 'restartSwitcherTitle',
  warningRecoveryCleanupPending: 'recoveryCleanupPendingTitle',
  warningProtectedRecoveryEvidenceRetained: 'keepRecoveryFilesTitle',
  warningTemporaryCleanupPending: 'temporaryCleanupPendingTitle',
  warningFinderFallbackUsed: 'finderReplacementTitle',
  warningNonFatalCleanup: 'cleanupAttentionTitle',
  updatePreviewAvailable: 'updateAvailableTitle',
  updaterNotConfigured: 'updatesUnavailableTitle',
  updaterUnsupportedPlatform: 'updatesUnavailableTitle',
  updateCheckFailed: 'updateCheckFailedTitle',
  updateInstallFailed: 'updateInstallFailedTitle',
  updateNotChecked: 'checkUpdateAgainTitle',
  updateBusy: 'operationInProgressTitle',
  updateStateUnavailable: 'checkUpdateAgainTitle',
  waitingPermission: 'permissionRequiredTitle',
  startupRecoveryFailed: 'recoveryFailedTitle',
  chooseAppToContinue: 'chooseAppTitle',
  chooseAppFirst: 'chooseAppTitle',
  reinstallRequired: 'reinstallCavalryTitle',
  runtimeResidueWarning: 'finishRuntimeCleanupTitle',
  readyToApply: 'readyToApplyTitle',
  customRootNotWritable: 'folderNotWritableTitle',
  readyPermission: 'permissionMayBeRequiredTitle',
  preparingApply: 'preparingApplyTitle',
  restoring: 'restoringTitle',
  noLanguage: 'noLanguageTitle',
  applying: 'applyingTitle',
  cavalryStillRunning: 'closeCavalryTitle',
  patchFailed: 'applyFailedTitle',
  restoreSuccess: 'restoredTitle',
  restoreWithWarnings: 'restoredTitle',
  applied: 'appliedTitle',
  appliedWithWarnings: 'appliedTitle',
  openPrivacyFailed: 'settingsFailedTitle',
  openProjectLinkFailed: 'projectLinkFailedTitle',
  aboutOpenFailed: 'aboutOpenFailedTitle',
  bootstrapFailed: 'startupFailedTitle',
});
