#!/usr/bin/env node
/**
 * [INPUT]: 依赖 package.json、CHANGELOG.md、tools/sync_project_version.js、src-tauri/tauri.conf.json、capabilities/default.json 与本地打包 SOP 文档
 * [OUTPUT]: 对外提供 Tauri-only 打包 SOP、版本同步与配置 contract 测试，阻止发布路径恢复旧壳层链路
 * [POS]: tools 的 Phase 6 打包守门，连接文档相、版本真相源、npm script 与 Tauri bundle 配置
 * [PROTOCOL]: 变更时更新此头部，然后检查 CLAUDE.md
 */
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { spawnSync } = require('node:child_process');

const repoRoot = path.resolve(__dirname, '..');

function readJson(relativePath) {
  const filePath = path.isAbsolute(relativePath) ? relativePath : path.join(repoRoot, relativePath);
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function readText(relativePath) {
  return fs.readFileSync(path.join(repoRoot, relativePath), 'utf8');
}

function writeJson(filePath, value) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`);
}

function makeVersionFixture() {
  const tempRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'cavalry-version-sync-'));
  fs.mkdirSync(path.join(tempRoot, 'tools'), { recursive: true });
  fs.mkdirSync(path.join(tempRoot, 'src-tauri'), { recursive: true });

  fs.copyFileSync(
    path.join(repoRoot, 'tools', 'sync_project_version.js'),
    path.join(tempRoot, 'tools', 'sync_project_version.js')
  );
  fs.writeFileSync(
    path.join(tempRoot, 'CHANGELOG.md'),
    [
      '# Changelog',
      '',
      '## [Unreleased]',
      '',
      '## [9.8.7] - 2026-05-14',
      '- Release fixture.',
      '',
    ].join('\n')
  );
  writeJson(path.join(tempRoot, 'package.json'), { name: 'cavalry-i18n', version: '0.1.0' });
  writeJson(path.join(tempRoot, 'package-lock.json'), {
    name: 'cavalry-i18n',
    version: '0.1.0',
    lockfileVersion: 3,
    packages: {
      '': {
        name: 'cavalry-i18n',
        version: '0.1.0',
      },
    },
  });
  fs.writeFileSync(
    path.join(tempRoot, 'src-tauri', 'Cargo.toml'),
    [
      '[package]',
      'name = "cavalry-i18n-tauri"',
      'version = "0.1.0"',
      'edition = "2021"',
      '',
    ].join('\n')
  );
  writeJson(path.join(tempRoot, 'src-tauri', 'tauri.conf.json'), {
    productName: 'Cavalry Language Switcher',
    version: '0.1.0',
  });
  fs.writeFileSync(
    path.join(tempRoot, 'src-tauri', 'Cargo.lock'),
    [
      '# This file is automatically @generated by Cargo.',
      'version = 4',
      '',
      '[[package]]',
      'name = "cavalry-i18n-tauri"',
      'version = "0.1.0"',
      'dependencies = [',
      ' "tauri",',
      ']',
      '',
      '[[package]]',
      'name = "dpi"',
      'version = "0.1.2"',
      '',
    ].join('\n')
  );

  return tempRoot;
}

test('tauri local build SOP is the only release path', () => {
  const localSop = readText('LOCAL_BUILD_SOP.md');

  assert.match(localSop, /Tauri/i);
  assert.match(localSop, /npm run tauri:build/);
  assert.match(localSop, /npm run prepare:qt-sdk/);
  assert.match(localSop, /APPLE_SIGNING_IDENTITY="-"/);
  assert.match(localSop, /tools\/cavalry_qt_target\.json/);
  assert.match(localSop, /6\.6\.3/);
  assert.doesNotMatch(localSop, /Electron|electron-builder|test:desktop|check:desktop|desktop-patcher/);
});

test('tauri build scripts and config describe one injector and resource pipeline', () => {
  const pkg = readJson('package.json');
  const config = readJson('src-tauri/tauri.conf.json');
  const resources = config.bundle.resources;
  const qtTarget = readJson('tools/cavalry_qt_target.json');

  assert.equal(pkg.scripts['tauri:build'], 'tauri build');
  assert.equal(pkg.scripts.build, 'npm run tauri:build');
  assert.equal(pkg.scripts.desktop, undefined);
  assert.equal(pkg.scripts['build:electron'], undefined);
  assert.equal(pkg.scripts['build:electron:dir'], undefined);
  assert.equal(pkg.scripts['build:dir'], undefined);
  assert.equal(pkg.build, undefined);
  assert.equal(pkg.devDependencies.electron, undefined);
  assert.equal(pkg.devDependencies['electron-builder'], undefined);
  assert.equal(pkg.scripts['prepare:qt-sdk'], 'node tools/resolve_cavalry_qt_sdk.js --ensure');
  assert.match(pkg.scripts['build:injector'], /resolve_cavalry_qt_sdk\.js --print-env --ensure/);
  assert.match(pkg.scripts['build:injector'], /build_translator_injector\.sh injector\/libCavalryTranslatorInjector\.dylib/);
  assert.equal(qtTarget.qtVersion, '6.6.3');
  assert.equal(qtTarget.sdkPath, 'qt_sdk/6.6.3/macos');
  assert.equal(config.build.beforeBuildCommand, 'npm run build:injector');
  assert.equal(config.build.frontendDist, '../renderer');
  assert.equal(config.app.withGlobalTauri, true);
  assert.equal(resources['../languages'], 'languages');
  assert.equal(
    resources['../injector/libCavalryTranslatorInjector.dylib'],
    'injector/libCavalryTranslatorInjector.dylib'
  );
});

test('project version workflow exposes one synchronizer and a pre-commit hook installer', () => {
  const pkg = readJson('package.json');

  assert.equal(pkg.scripts['sync:version'], 'node tools/sync_project_version.js');
  assert.equal(pkg.scripts['check:version'], 'node tools/sync_project_version.js --check');
  assert.equal(
    pkg.scripts['hooks:install'],
    'git rev-parse --is-inside-work-tree >/dev/null 2>&1 && git config core.hooksPath tools/git-hooks || true'
  );
  assert.equal(pkg.scripts.postinstall, 'npm run hooks:install');
});

test('project version synchronizer propagates changelog version across npm, Cargo, and Tauri metadata', () => {
  const tempRoot = makeVersionFixture();
  const result = spawnSync(process.execPath, ['tools/sync_project_version.js'], {
    cwd: tempRoot,
    encoding: 'utf8',
  });

  assert.equal(result.status, 0, result.stderr || result.stdout);
  assert.equal(readJson(path.join(tempRoot, 'package.json')).version, '9.8.7');
  assert.equal(readJson(path.join(tempRoot, 'package-lock.json')).version, '9.8.7');
  assert.equal(readJson(path.join(tempRoot, 'package-lock.json')).packages[''].version, '9.8.7');
  assert.match(fs.readFileSync(path.join(tempRoot, 'src-tauri', 'Cargo.toml'), 'utf8'), /version = "9\.8\.7"/);
  assert.equal(readJson(path.join(tempRoot, 'src-tauri', 'tauri.conf.json')).version, '9.8.7');
  assert.match(
    fs.readFileSync(path.join(tempRoot, 'src-tauri', 'Cargo.lock'), 'utf8'),
    /name = "cavalry-i18n-tauri"\nversion = "9\.8\.7"/
  );
});

test('tauri bundle config preserves the frozen Tauri window contract', () => {
  const config = readJson('src-tauri/tauri.conf.json');
  const window = config.app.windows.find((candidate) => candidate.label === 'main');

  assert.ok(window, 'main window missing');
  assert.equal(window.url, 'index.html');
  assert.equal(window.width, 480);
  assert.equal(window.height, 528);
  assert.equal(window.minWidth, 420);
  assert.equal(window.minHeight, 528);
  assert.deepEqual(config.bundle.targets, ['dmg', 'app']);
});

test('tauri macOS package uses explicit ad-hoc bundle signing for downloaded apps', () => {
  const config = readJson('src-tauri/tauri.conf.json');

  assert.equal(config.bundle.macOS.signingIdentity, '-');
});

test('tauri window icon is an 8-bit PNG compatible with generate_context', () => {
  const icon = fs.readFileSync(path.join(repoRoot, 'src-tauri/icons/icon.png'));
  assert.equal(icon.toString('hex', 0, 8), '89504e470d0a1a0a');
  assert.equal(icon.readUInt32BE(16), 1024);
  assert.equal(icon.readUInt32BE(20), 1024);
  assert.equal(icon.readUInt8(24), 8, 'Tauri rejects the original 16-bit PNG at runtime');
  assert.equal(icon.readUInt8(25), 6, 'icon.png must be RGBA');
});

test('tauri capability and SOP mention the bridge and packaged resource boundaries', () => {
  const localSop = readText('LOCAL_BUILD_SOP.md');
  const capabilities = readJson('src-tauri/capabilities/default.json');

  assert.ok(capabilities.windows.includes('main'));
  assert.ok(capabilities.permissions.includes('core:default'));
  assert.ok(capabilities.permissions.includes('core:window:default'));
  assert.ok(capabilities.permissions.includes('core:webview:default'));

  for (const requiredText of [
    'bundle.resources',
    'languages',
    'libCavalryTranslatorInjector.dylib',
    'src-tauri/target/release/bundle',
    'DMG',
    '.app',
  ]) {
    assert.match(localSop, new RegExp(requiredText.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  }
});
