#!/usr/bin/env node
/**
 * [INPUT]: 依赖 tools/zh-Hans.ts、tools/zh-Hant.ts、tools/ja_JP.ts 的 Qt TS 翻译目录，以及 model_display_translations.json 的显示层模型名词典
 * [OUTPUT]: 对外生成 injector/generated_translations.inc 编译期 C++ 翻译表，附加 display-only 模型 niceName 译名
 * [POS]: tools 的 TS/显示层词典到 C++ 投影器，连接翻译资产与 Objective-C++ injector
 * [PROTOCOL]: 变更时更新此头部，然后检查 CLAUDE.md
 */

const fs = require('node:fs');
const path = require('node:path');

const repoRoot = path.resolve(__dirname, '..');
const outputPath =
  process.argv[2] || path.join(repoRoot, 'injector', 'generated_translations.inc');
const modelDisplayPath = path.join(repoRoot, 'tools', 'model_display_translations.json');

const languages = [
  { code: 'zh-Hans', symbol: 'kZhHansEntries', file: path.join(repoRoot, 'tools', 'zh-Hans.ts') },
  { code: 'zh-Hant', symbol: 'kZhHantEntries', file: path.join(repoRoot, 'tools', 'zh-Hant.ts') },
  { code: 'ja_JP', symbol: 'kJaEntries', file: path.join(repoRoot, 'tools', 'ja_JP.ts') },
];

function decodeXml(value) {
  return value
    .replace(/&apos;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/&gt;/g, '>')
    .replace(/&lt;/g, '<')
    .replace(/&amp;/g, '&');
}

function escapeCpp(value) {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n');
}

function parseTag(block, tagName) {
  const match = block.match(new RegExp(`<${tagName}>([\\s\\S]*?)<\\/${tagName}>`));
  return match ? decodeXml(match[1].trim()) : '';
}

function parseTs(filePath) {
  const xml = fs.readFileSync(filePath, 'utf8');
  const entries = [];
  const contextRegex = /<context>([\s\S]*?)<\/context>/g;

  for (const contextMatch of xml.matchAll(contextRegex)) {
    const contextBlock = contextMatch[1];
    const contextName = parseTag(contextBlock, 'name');
    if (!contextName) {
      continue;
    }

    const messageRegex = /<message>([\s\S]*?)<\/message>/g;
    for (const messageMatch of contextBlock.matchAll(messageRegex)) {
      const messageBlock = messageMatch[1];
      const source = parseTag(messageBlock, 'source');
      const translation = parseTag(messageBlock, 'translation');
      if (!source || !translation) {
        continue;
      }
      entries.push({ context: contextName, source, translation });
    }
  }

  return entries;
}

function parseModelDisplayTranslations(languageCode) {
  const payload = JSON.parse(fs.readFileSync(modelDisplayPath, 'utf8'));
  const entries = (payload.entries || [])
    .map((entry) => ({
      context: 'ModelDisplay',
      source: entry.source || '',
      translation: entry[languageCode] || '',
    }))
    .filter((entry) => entry.source && entry.translation);
  const menuVariants = entries.map((entry) => ({
    context: 'ModelDisplay',
    source: `${entry.source}...`,
    translation: `${entry.translation}...`,
  }));
  return [...entries, ...menuVariants];
}

function renderEntries(symbol, entries) {
  const body = entries
    .map(
      ({ context, source, translation }) =>
        `    {"${escapeCpp(context)}", "${escapeCpp(source)}", "${escapeCpp(translation)}"},`
    )
    .join('\n');

  return `const TranslationEntry ${symbol}[] = {\n${body}\n};\n`;
}

function renderDispatcher() {
  const branches = languages
    .map(
      ({ code, symbol }) => `    if (lang == QStringLiteral("${code}")) {
        *count = static_cast<int>(sizeof(${symbol}) / sizeof(${symbol}[0]));
        return ${symbol};
    }`
    )
    .join('\n');

  return `const TranslationEntry *entriesForLanguage(const QString &lang, int *count)
{
${branches}

    *count = 0;
    return nullptr;
}
`;
}

const header = `// Generated by tools/generate_embedded_translations.js. Do not edit by hand.
`;

const output = [
  header,
  ...languages.map(({ code, symbol, file }) =>
    renderEntries(symbol, [...parseTs(file), ...parseModelDisplayTranslations(code)])
  ),
  renderDispatcher(),
].join('\n');

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, output);
