<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="ja_JP">
  <context>
    <name>QMenuBar</name>
    <message>
      <source>File</source>
      <translation>ファイル</translation>
    </message>
    <message>
      <source>Edit</source>
      <translation>編集</translation>
    </message>
    <message>
      <source>View</source>
      <translation>表示</translation>
    </message>
    <message>
      <source>Window</source>
      <translation>ウィンドウ</translation>
    </message>
    <message>
      <source>Help</source>
      <translation>ヘルプ</translation>
    </message>
  </context>
  <context>
    <name>MenuBarManager</name>
    <message>
      <source>File</source>
      <translation>ファイル</translation>
    </message>
    <message>
      <source>Edit</source>
      <translation>編集</translation>
    </message>
    <message>
      <source>View</source>
      <translation>表示</translation>
    </message>
    <message>
      <source>Window</source>
      <translation>ウィンドウ</translation>
    </message>
    <message>
      <source>&amp;Help</source>
      <translation>&amp;ヘルプ</translation>
    </message>
    <message>
      <source>New Scene</source>
      <translation>新規シーン</translation>
    </message>
    <message>
      <source>Import Assets...</source>
      <translation>アセットを読み込み...</translation>
    </message>
    <message>
      <source>Import Assets</source>
      <translation>アセットを読み込み</translation>
    </message>
    <message>
      <source>Save Scene</source>
      <translation>シーンを保存</translation>
    </message>
    <message>
      <source>Project Settings</source>
      <translation>プロジェクト設定</translation>
    </message>
    <message>
      <source>Open Project Settings</source>
      <translation>プロジェクト設定を開く</translation>
    </message>
    <message>
      <source>Preferences</source>
      <translation>環境設定</translation>
    </message>
    <message>
      <source>Show Preferences Folder</source>
      <translation>Preferences フォルダを表示</translation>
    </message>
    <message>
      <source>Override Preferences</source>
      <translation>環境設定を上書き</translation>
    </message>
    <message>
      <source>About Cavalry</source>
      <translation>Cavalry について</translation>
    </message>
  </context>
  <context>
    <name>QFileDialog</name>
    <message>
      <source>Open</source>
      <translation>開く</translation>
    </message>
    <message>
      <source>Save</source>
      <translation>保存</translation>
    </message>
    <message>
      <source>Save As</source>
      <translation>名前を付けて保存</translation>
    </message>
    <message>
      <source>Close</source>
      <translation>閉じる</translation>
    </message>
    <message>
      <source>File</source>
      <translation>ファイル</translation>
    </message>
    <message>
      <source>Folder</source>
      <translation>フォルダー</translation>
    </message>
    <message>
      <source>Files of type:</source>
      <translation>ファイルの種類:</translation>
    </message>
    <message>
      <source>Look in:</source>
      <translation>検索場所:</translation>
    </message>
    <message>
      <source>File name:</source>
      <translation>ファイル名:</translation>
    </message>
    <message>
      <source>Back</source>
      <translation>戻る</translation>
    </message>
    <message>
      <source>Forward</source>
      <translation>進む</translation>
    </message>
    <message>
      <source>Parent Directory</source>
      <translation>親ディレクトリ</translation>
    </message>
    <message>
      <source>Create New Folder</source>
      <translation>新しいフォルダーの作成</translation>
    </message>
    <message>
      <source>List View</source>
      <translation>リスト表示</translation>
    </message>
    <message>
      <source>Detail View</source>
      <translation>詳細表示</translation>
    </message>
  </context>
  <context>
    <name>QDialog</name>
    <message>
      <source>OK</source>
      <translation>OK</translation>
    </message>
    <message>
      <source>Cancel</source>
      <translation>キャンセル</translation>
    </message>
    <message>
      <source>Apply</source>
      <translation>適用</translation>
    </message>
    <message>
      <source>Yes</source>
      <translation>はい</translation>
    </message>
    <message>
      <source>No</source>
      <translation>いいえ</translation>
    </message>
    <message>
      <source>Close</source>
      <translation>閉じる</translation>
    </message>
    <message>
      <source>Help</source>
      <translation>ヘルプ</translation>
    </message>
    <message>
      <source>Reset</source>
      <translation>リセット</translation>
    </message>
    <message>
      <source>Retry</source>
      <translation>再試行</translation>
    </message>
    <message>
      <source>Ignore</source>
      <translation>無視</translation>
    </message>
    <message>
      <source>Abort</source>
      <translation>中止</translation>
    </message>
  </context>
  <context>
    <name>QMessageBox</name>
    <message>
      <source>OK</source>
      <translation>OK</translation>
    </message>
    <message>
      <source>Cancel</source>
      <translation>キャンセル</translation>
    </message>
    <message>
      <source>Yes</source>
      <translation>はい</translation>
    </message>
    <message>
      <source>No</source>
      <translation>いいえ</translation>
    </message>
    <message>
      <source>Yes to All</source>
      <translation>すべてはい</translation>
    </message>
    <message>
      <source>No to All</source>
      <translation>すべていいえ</translation>
    </message>
    <message>
      <source>Save</source>
      <translation>保存</translation>
    </message>
    <message>
      <source>Discard</source>
      <translation>破棄</translation>
    </message>
    <message>
      <source>Don&apos;t Save</source>
      <translation>保存しない</translation>
    </message>
    <message>
      <source>Close</source>
      <translation>閉じる</translation>
    </message>
    <message>
      <source>Help</source>
      <translation>ヘルプ</translation>
    </message>
  </context>
  <context>
    <name>QUndoStack</name>
    <message>
      <source>Undo</source>
      <translation>元に戻す</translation>
    </message>
    <message>
      <source>Redo</source>
      <translation>やり直し</translation>
    </message>
    <message>
      <source>Undo %1</source>
      <translation>%1を元に戻す</translation>
    </message>
    <message>
      <source>Redo %1</source>
      <translation>%1をやり直し</translation>
    </message>
  </context>
  <context>
    <name>QShortcut</name>
    <message>
      <source>Ctrl</source>
      <translation>Ctrl</translation>
    </message>
    <message>
      <source>Shift</source>
      <translation>Shift</translation>
    </message>
    <message>
      <source>Alt</source>
      <translation>Alt</translation>
    </message>
  </context>
  <context>
    <name>QTabBar</name>
    <message>
      <source>Close</source>
      <translation>閉じる</translation>
    </message>
    <message>
      <source>Close Tab</source>
      <translation>タブを閉じる</translation>
    </message>
    <message>
      <source>Close Other Tabs</source>
      <translation>他のタブを閉じる</translation>
    </message>
  </context>
  <context>
    <name>QLineEdit</name>
    <message>
      <source>Cut</source>
      <translation>切り取り</translation>
    </message>
    <message>
      <source>Copy</source>
      <translation>コピー</translation>
    </message>
    <message>
      <source>Paste</source>
      <translation>ペースト</translation>
    </message>
    <message>
      <source>Select All</source>
      <translation>すべて選択</translation>
    </message>
    <message>
      <source>Undo</source>
      <translation>元に戻す</translation>
    </message>
    <message>
      <source>Redo</source>
      <translation>やり直し</translation>
    </message>
    <message>
      <source>Delete</source>
      <translation>削除</translation>
    </message>
  </context>
  <context>
    <name>QPrintDialog</name>
    <message>
      <source>Print</source>
      <translation>印刷</translation>
    </message>
    <message>
      <source>Printer</source>
      <translation>プリンター</translation>
    </message>
    <message>
      <source>Print to File</source>
      <translation>ファイルに出力</translation>
    </message>
  </context>
</TS>
