T = {
'Octaves': ('八度', '八度', 'オクターブ'),
'Lacunarity': ('间隙度', '間隙度', 'ラクナリティ'),
'Gain': ('增益', '增益', 'ゲイン'),
'Curl Noise': ('卷曲噪声', '卷曲雜訊', 'カールノイズ'),
'Curl Amount': ('卷曲量', '卷曲量', 'カール量'),
'Value Noise': ('值噪声', '值雜訊', 'バリューノイズ'),
'Generate a Value Noise pattern.': ('生成值噪声图案。', '產生值雜訊圖案。', 'バリューノイズパターンを生成します。'),
'Curl': ('卷曲', '卷曲', 'カール'),
'Curl Amplitude': ('卷曲振幅', '卷曲振幅', 'カール振幅'),
'Cubic Noise': ('立方噪声', '立方雜訊', 'キュービックノイズ'),
'Generate a Cubic Noise pattern.': ('生成立方噪声图案。', '產生立方雜訊圖案。', 'キュービックノイズパターンを生成します。'),
'Cellular Noise': ('细胞噪声', '細胞雜訊', 'セルラーノイズ'),
'Generate a Cellular Noise pattern.': ('生成细胞噪声图案。', '產生細胞雜訊圖案。', 'セルラーノイズパターンを生成します。'),
'Distance Function': ('距离函数', '距離函數', '距離関数'),
'Cellular Type': ('细胞类型', '細胞類型', 'セルラータイプ'),
'Jitter': ('抖动', '抖動', 'ジッター'),
'Euclidean': ('欧几里得', '歐幾里得', 'ユークリッド'),
'Manhattan': ('曼哈顿', '曼哈頓', 'マンハッタン'),
'Natural': ('自然', '自然', '自然'),
'Cell Value': ('单元值', '儲存格值', 'セル値'),
'Noise Lookup': ('噪声查找', '雜訊查詢', 'ノイズルックアップ'),
'Distance': ('距离', '距離', '距離'),
'Distance 2': ('距离 2', '距離 2', '距離 2'),
'Distance 2 Add': ('距离 2 加', '距離 2 加', '距離 2 加算'),
'Distance 2 Sub': ('距离 2 减', '距離 2 減', '距離 2 減算'),
'Distance 2 Mul': ('距离 2 乘', '距離 2 乘', '距離 2 乗算'),
'Distance 2 Div': ('距离 2 除', '距離 2 除', '距離 2 除算'),
'A simple (non-volume preserving) Squash and Stretch deformer.': ('简单的（非保体积）挤压和拉伸变形器。', '簡單的（非保體積）擠壓和拉伸變形器。', 'シンプルな（体積非保存）スカッシュ＆ストレッチデフォーマ。'),
'Spread': ('展开', '展開', 'スプレッド'),
'Bulge': ('膨胀', '膨脹', 'バルジ'),
'Bulge Graph': ('膨胀曲线', '膨脹曲線', 'バルジグラフ'),
'Pin': ('钉固', '釘固', 'ピン'),
'Left': ('左', '左', '左'),
'Right': ('右', '右', '右'),
"Add dynamic, secondary motion to a Shape's position keyframes.": ('为形状的位置关键帧添加动态的次级运动。', '為形狀的位置關鍵幀新增動態的次級運動。', 'シェイプの位置キーフレームにダイナミックなセカンダリモーションを追加します。'),
'Damping': ('阻尼', '阻尼', '減衰'),
'Stiffness': ('刚度', '剛度', '剛性'),
'Move or deform Shapes along a path.': ('沿路径移动或变形形状。', '沿路徑移動或變形形狀。', 'パスに沿ってシェイプを移動または変形します。'),
'Travel': ('行进', '行進', 'トラベル'),
'Input Shape': ('输入形状', '輸入形狀', '入力シェイプ'),
'Taper Graph': ('锥化曲线', '錐化曲線', 'テーパーグラフ'),
'Flip': ('翻转', '翻轉', '反転'),
'Path Offset': ('路径偏移', '路徑偏移', 'パスオフセット'),
'Loop': ('循环', '循環', 'ループ'),
'Reverse Input Path': ('反转输入路径', '反轉輸入路徑', '入力パスを反転'),
'Rotation Offset': ('旋转偏移', '旋轉偏移', '回転オフセット'),
'Deformer': ('变形器', '變形器', 'デフォーマ'),
'Generate random numbers and control how biased they are.': ('生成随机数并控制其偏向程度。', '產生隨機數並控制其偏向程度。', '乱数を生成し、その偏りを制御します。'),
'Use Bias Graph': ('使用偏置曲线', '使用偏置曲線', 'バイアスグラフを使用'),
'Bias Graph': ('偏置曲线', '偏置曲線', 'バイアスグラフ'),
'Use Incoming Index': ('使用传入索引', '使用傳入索引', '入力インデックスを使用'),
'Deform and affect Shapes using trigonometric wave patterns.': ('使用三角函数波形来变形和影响形状。', '使用三角函數波形來變形和影響形狀。', '三角関数の波パターンを使用してシェイプを変形および影響します。'),
'Value Offset': ('值偏移', '值偏移', '値オフセット'),
'Wave Style': ('波形样式', '波形樣式', '波形スタイル'),
'Sine': ('正弦', '正弦', 'サイン'),
'Cosine': ('余弦', '餘弦', 'コサイン'),
'Tangent': ('正切', '正切', 'タンジェント'),
'Square': ('方波', '方波', '矩形波'),
'Triangle': ('三角波', '三角波', '三角波'),
'Sawtooth': ('锯齿波', '鋸齒波', 'ノコギリ波'),
'Time Mode': ('时间模式', '時間模式', '時間モード'),
'Minutes (BPM)': ('分钟 (BPM)', '分鐘 (BPM)', '分 (BPM)'),
'Perform simple comparison operations on values.': ('对值执行简单的比较运算。', '對值執行簡單的比較運算。', '値に対してシンプルな比較演算を実行します。'),
'First': ('第一', '第一', '第 1'),
'Second': ('第二', '第二', '第 2'),
'Operation': ('运算', '運算', '演算'),
'Result': ('结果', '結果', '結果'),
'Less Than': ('小于', '小於', '未満'),
'Greater Than': ('大于', '大於', 'より大きい'),
'Equal To': ('等于', '等於', '等しい'),
'Not Equal To': ('不等于', '不等於', '等しくない'),
'Less Than Or Equal To': ('小于或等于', '小於或等於', '以下'),
'Greater Than Or Equal To': ('大于或等于', '大於或等於', '以上'),
'Perform simple logic operations on boolean (on/off) values.': ('对布尔值（开/关）执行简单的逻辑运算。', '對布林值（開/關）執行簡單的邏輯運算。', 'ブール値（オン/オフ）に対してシンプルな論理演算を実行します。'),
'AND (both)': ('AND（两者）', 'AND（兩者）', 'AND（両方）'),
'OR (one or both)': ('OR（一方或两者）', 'OR（一方或兩者）', 'OR（一方または両方）'),
'XOR (one but not both)': ('XOR（一方但非两者）', 'XOR（一方但非兩者）', 'XOR（一方のみ）'),
'Perform simple mathematical operations on values.': ('对值执行简单的数学运算。', '對值執行簡單的數學運算。', '値に対してシンプルな数学演算を実行します。'),
'Add': ('加', '加', '加算'),
'Subtract': ('减', '減', '減算'),
'Divide': ('除', '除', '除算'),
'Modulus': ('取模', '取模', '剰余'),
'FModulus': ('浮点取模', '浮點取模', '浮動小数点剰余'),
'Max': ('最大值', '最大值', '最大値'),
'Min': ('最小值', '最小值', '最小値'),
'Average': ('平均值', '平均值', '平均値'),
'Power': ('幂', '冪', '累乗'),
'Square Root': ('平方根', '平方根', '平方根'),
'Floor': ('向下取整', '向下取整', '切り捨て'),
'Ceiling': ('向上取整', '向上取整', '切り上げ'),
'Round': ('四舍五入', '四捨五入', '四捨五入'),
'Absolute': ('绝对值', '絕對值', '絶対値'),
'Equil To': ('等于', '等於', '等しい'),
'Math2': ('数学 2', '數學 2', '数学 2'),
'Perform simple mathematical operations on two dimensional values (e.g. X,Y).': ('对二维值（例如 X,Y）执行简单的数学运算。', '對二維值（例如 X,Y）執行簡單的數學運算。', '2 次元の値（例: X,Y）に対してシンプルな数学演算を実行します。'),
'Math3': ('数学 3', '數學 3', '数学 3'),
'Perform simple mathematical operations on three dimensional values (e.g. X,Y,Z).': ('对三维值（例如 X,Y,Z）执行简单的数学运算。', '對三維值（例如 X,Y,Z）執行簡單的數學運算。', '3 次元の値（例: X,Y,Z）に対してシンプルな数学演算を実行します。'),
'Value2 Array': ('二维值数组', '二維值陣列', '2D 値配列'),
'Create a list of 2D values (X,Y) which can be assigned to other Layers via their indices.': ('创建一个 2D 值（X,Y）列表，可通过索引分配给其他图层。', '建立一個 2D 值（X,Y）列表，可透過索引指派給其他圖層。', '2D 値（X,Y）のリストを作成し、インデックスを介して他のレイヤーに割り当てることができます。'),
'Array Index': ('数组索引', '陣列索引', '配列インデックス'),
'Value3 Array': ('三维值数组', '三維值陣列', '3D 値配列'),
'Create a list of 3D values (X,Y,Z) which can be assigned to other Layers via their indices.': ('创建一个 3D 值（X,Y,Z）列表，可通过索引分配给其他图层。', '建立一個 3D 值（X,Y,Z）列表，可透過索引指派給其他圖層。', '3D 値（X,Y,Z）のリストを作成し、インデックスを介して他のレイヤーに割り当てることができます。'),
'Create a list of values which can be assigned to other layers via their indices.': ('创建一个值列表，可通过索引分配给其他图层。', '建立一個值列表，可透過索引指派給其他圖層。', '値のリストを作成し、インデックスを介して他のレイヤーに割り当てることができます。'),
'Average (Mean)': ('平均值（均值）', '平均值（均值）', '平均値（算術平均）'),
'Accumulate': ('累加', '累加', '累積'),
'Use JavaScript to perform mathematical operations on values.': ('使用 JavaScript 对值执行数学运算。', '使用 JavaScript 對值執行數學運算。', 'JavaScript を使用して値に対して数学演算を実行します。'),
'Number': ('数值', '數值', '数値'),
'Expression': ('表达式', '表達式', 'エクスプレッション'),
'Switch between two results dependent on a condition being set or not.': ('根据条件是否设置在两个结果之间切换。', '根據條件是否設定在兩個結果之間切換。', '条件の設定有無に応じて 2 つの結果を切り替えます。'),
'Condition': ('条件', '條件', '条件'),
'A boolean which will output True for any value ≥ 0.5 and False for any value < 0.5': ('布尔值，任何值 ≥ 0.5 时输出 True，任何值 < 0.5 时输出 False', '布林值，任何值 ≥ 0.5 時輸出 True，任何值 < 0.5 時輸出 False', '値が 0.5 以上の場合に True、0.5 未満の場合に False を出力するブール値'),
'True': ('True', 'True', 'True'),
'The result if the Condition is True. You can connect anything here.': ('条件为 True 时的结果。您可以在此连接任何内容。', '條件為 True 時的結果。您可以在此連接任何內容。', '条件が True の場合の結果。ここには何でも接続できます。'),
'False': ('False', 'False', 'False'),
'The result if the Condition is False. You can connect anything here.': ('条件为 False 时的结果。您可以在此连接任何内容。', '條件為 False 時的結果。您可以在此連接任何內容。', '条件が False の場合の結果。ここには何でも接続できます。'),
'Attenuate the effect of Behaviours/ Deformers.': ('衰减行为/变形器的效果。', '衰減行為/變形器的效果。', 'ビヘイビア/デフォーマの効果を減衰させます。'),
'Shape Type': ('形状类型', '形狀類型', 'シェイプタイプ'),
'Falloff Graph': ('衰减曲线', '衰減曲線', 'フォールオフグラフ'),
'Probability': ('概率', '機率', '確率'),
'Custom Color': ('自定义颜色', '自訂顏色', 'カスタムカラー'),
'Enabled': ('启用', '啟用', '有効'),
'Path Mode': ('路径模式', '路徑模式', 'パスモード'),
'Angles': ('角度', '角度', '角度'),
'Repetitions': ('重复次数', '重複次數', '繰り返し回数'),
'Circle': ('圆形', '圓形', '円'),
'Rectangle': ('矩形', '矩形', '矩形'),
'Sweep': ('扫描', '掃描', 'スウィープ'),
'Filled Path': ('填充路径', '填充路徑', '塗りつぶしパス'),
'Path Edges': ('路径边缘', '路徑邊緣', 'パスエッジ'),
'Smoothing Steps': ('平滑步数', '平滑步數', 'スムージングステップ'),
'Deform a Shape based on its velocity.': ('根据形状的速度对其进行变形。', '根據形狀的速度對其進行變形。', 'シェイプの速度に基づいて変形します。'),
'Speed Theshold': ('速度阈值', '速度閾值', '速度しきい値'),
'Generate sequential values between a minimum and maximum. Use to create step effects.': ('在最小值和最大值之间生成连续值。用于创建阶梯效果。', '在最小值和最大值之間產生連續值。用於建立階梯效果。', '最小値と最大値の間で連続値を生成します。ステップ効果の作成に使用します。'),
'Graph': ('曲线', '曲線', 'グラフ'),
'Read and remap data from a Spreadsheet Asset.': ('从电子表格资产中读取和重映射数据。', '從試算表資產中讀取和重新映射資料。', 'スプレッドシートアセットからデータを読み取り、リマップします。'),
'Column Title': ('列标题', '欄標題', '列タイトル'),
'Out': ('输出', '輸出', '出力'),
'Remapping': ('重映射', '重新映射', 'リマッピング'),
'Remap Minimum': ('重映射最小值', '重新映射最小值', 'リマップ最小値'),
'Remap Maximum': ('重映射最大值', '重新映射最大值', 'リマップ最大値'),
'Remap Gradient': ('重映射渐变', '重新映射漸層', 'リマップグラデーション'),
'Fixed Row': ('固定行', '固定列', '固定行'),
'Row Index': ('行索引', '列索引', '行インデックス'),
'Row Offset': ('行偏移', '列偏移', '行オフセット'),
'Use Every Nth Row': ('每隔 N 行使用', '每隔 N 列使用', 'N 行ごとに使用'),
'Row Count': ('行数', '列數', '行数'),
'Column Count': ('列数', '欄數', '列数'),
'Interpolate': ('插值', '內插', '補間'),
'Output Mode': ('输出模式', '輸出模式', '出力モード'),
'To Range': ('到范围', '到範圍', '範囲へ'),
'To Color': ('到颜色', '到顏色', 'カラーへ'),
'Data': ('数据', '資料', 'データ'),
'Sort Order (Ascending)': ('排序（升序）', '排序（升冪）', '並び順（昇順）'),
'Sort Order (Descending)': ('排序（降序）', '排序（降冪）', '並び順（降順）'),
'Map a gradient to each of the Shapes within a Duplicator (or other Sub-Mesh generating shape).': ('将渐变映射到复制器（或其他子网格生成形状）中的每个形状。', '將漸層映射到複製器（或其他子網格生成形狀）中的每個形狀。', 'デュプリケーター（またはその他のサブメッシュ生成シェイプ）内の各シェイプにグラデーションをマッピングします。'),
'Gradient': ('渐变', '漸層', 'グラデーション'),
'Add any incoming index (for example from a Duplicator) to the indices that this layer creates.': ('将任何传入的索引（例如来自复制器的索引）添加到此图层创建的索引中。', '將任何傳入的索引（例如來自複製器的索引）新增到此圖層建立的索引中。', '任意の入力インデックス（例: デュプリケーターからのもの）を、このレイヤーが作成するインデックスに追加します。'),
'Gradient Mode': ('渐变模式', '漸層模式', 'グラデーションモード'),
'RGB Interpolation': ('RGB 插值', 'RGB 內插', 'RGB 補間'),
'HSV Interpolation (Short Path)': ('HSV 插值（短路径）', 'HSV 內插（短路徑）', 'HSV 補間（ショートパス）'),
'HSV Interpolation (Long Path)': ('HSV 插值（长路径）', 'HSV 內插（長路徑）', 'HSV 補間（ロングパス）'),
'Utility': ('实用工具', '工具', 'ユーティリティ'),
'Area Range': ('面积范围', '面積範圍', '面積範囲'),
'Map a value to a Width and Height that produce a proportional area.': ('将值映射到产生比例面积的宽度和高度。', '將值映射到產生比例面積的寬度和高度。', '値を比例面積を生成する幅と高さにマッピングします。'),
'Maximum Value': ('最大值', '最大值', '最大値'),
'Maximum Dimensions': ('最大尺寸', '最大尺寸', '最大寸法'),
'Clamp': ('钳制', '箝制', 'クランプ'),
'Constrain Shapes to the bounding box of another Shape.': ('将形状约束到另一个形状的边界框内。', '將形狀約束到另一個形狀的邊界框內。', 'シェイプを別のシェイプのバウンディングボックスに制約します。'),
'Area': ('面积', '面積', '面積'),
'Bias': ('偏置', '偏置', 'バイアス'),
'Width': ('宽度', '寬度', '幅'),
'Height': ('高度', '高度', '高さ'),
'Out Position': ('输出位置', '輸出位置', '出力位置'),
'Playback audio and drive deformation or values.': ('播放音频并驱动变形或值。', '播放音訊並驅動變形或值。', 'オーディオを再生し、変形や値を駆動します。'),
'Frequency Bands': ('频段', '頻段', '周波数帯域'),
'Equaliser': ('均衡器', '等化器', 'イコライザー'),
'Volume Clipping': ('音量裁剪', '音量裁剪', 'ボリュームクリッピング'),
'Sub Steps': ('子步骤', '子步驟', 'サブステップ'),
'Smoothing Frames': ('平滑帧数', '平滑幀數', 'スムージングフレーム'),
'Frame Offset': ('帧偏移', '幀偏移', 'フレームオフセット'),
'Maximum dB': ('最大 dB', '最大 dB', '最大 dB'),
'The maximum dB value found when converting the audio signal amplitudes to dB. This value will be approximate when Smoothing Frames or Sub-Steps are used.': ('将音频信号振幅转换为 dB 时找到的最大 dB 值。使用平滑帧数或子步骤时，此值为近似值。', '將音訊訊號振幅轉換為 dB 時找到的最大 dB 值。使用平滑幀數或子步驟時，此值為近似值。', 'オーディオ信号の振幅を dB に変換する際に検出された最大 dB 値。スムージングフレームまたはサブステップを使用している場合、この値は近似値になります。'),
'File Length': ('文件长度', '檔案長度', 'ファイル長'),
'The file length (in frames).': ('文件长度（以帧为单位）。', '檔案長度（以幀為單位）。', 'ファイルの長さ（フレーム単位）。'),
'Active Bands': ('活跃频段', '活躍頻段', 'アクティブバンド'),
'The number of active bands in the Equalizer.': ('均衡器中活跃频段的数量。', '等化器中活躍頻段的數量。', 'イコライザーのアクティブバンド数。'),
'Band Weighting Graph': ('频段权重曲线', '頻段權重曲線', 'バンドウェイトグラフ'),
'Use this to control the volume of individual frequency bands.': ('使用此项控制各频段的音量。', '使用此項控制各頻段的音量。', '個々の周波数帯域の音量を制御するために使用します。'),
'Frequency Range Hz': ('频率范围 Hz', '頻率範圍 Hz', '周波数範囲 Hz'),
'The range of frequencies sampled. Human hearing can go up from around 20 Hz to 20,000 Hz.\nThe default is the frequency range of a piano.': ('采样的频率范围。人类听觉范围大约从 20 Hz 到 20,000 Hz。\n默认值是钢琴的频率范围。', '取樣的頻率範圍。人類聽覺範圍大約從 20 Hz 到 20,000 Hz。\n預設值是鋼琴的頻率範圍。', 'サンプリングされる周波数の範囲。人間の聴覚はおよそ 20 Hz から 20,000 Hz です。\nデフォルトはピアノの周波数範囲です。'),
'A-Weighting': ('A 加权', 'A 加權', 'A 特性'),
'Adjust the amplitude of the Frequency Bands to better reflect human hearing perception.': ('调整频段振幅以更好地反映人类听觉感知。', '調整頻段振幅以更好地反映人類聽覺感知。', '周波数帯域の振幅を調整して、人間の聴覚をより正確に反映します。'),
'Volume Adjustment dB': ('音量调整 dB', '音量調整 dB', '音量調整 dB'),
'Pan': ('声像', '聲像', 'パン'),
'Logarithmic': ('对数', '對數', '対数'),
'Mel': ('Mel', 'Mel', 'Mel'),
'Bark': ('Bark', 'Bark', 'Bark'),
'Taper a Shape along a vertical or horizontal axis.': ('沿垂直或水平轴锥化形状。', '沿垂直或水平軸錐化形狀。', '垂直または水平軸に沿ってシェイプをテーパーします。'),
'Start Stretch': ('起始拉伸', '起始拉伸', '開始ストレッチ'),
'End Stretch': ('结束拉伸', '結束拉伸', '終了ストレッチ'),
'Direction': ('方向', '方向', '方向'),
'Vertical': ('垂直', '垂直', '垂直'),
'Horizontal': ('水平', '水平', '水平'),
'Combine and control the effect of multiple Behaviours.': ('组合和控制多个行为的效果。', '組合和控制多個行為的效果。', '複数のビヘイビアの効果を組み合わせて制御します。'),
'Input Behaviour': ('输入行为', '輸入行為', '入力ビヘイビア'),
'Deform Shapes by bending them around the circumference of a circle.': ('通过沿圆周弯曲形状来变形。', '透過沿圓周彎曲形狀來變形。', '円の円周に沿って曲げることでシェイプを変形します。'),
'Vertical Pin': ('垂直钉固', '垂直釘固', '垂直ピン'),
'Horizontal Pin': ('水平钉固', '水平釘固', '水平ピン'),
'Level Mode': ('层级模式', '層級模式', 'レベルモード'),
'Custom Level': ('自定义层级', '自訂層級', 'カスタムレベル'),
'Use Levels': ('使用层级', '使用層級', 'レベルを使用'),
'High Quality': ('高品质', '高品質', '高品質'),
'Geometry will be sampled to a higher quality, at the expense of performance.': ('几何体将以更高的品质进行采样，但会降低性能。', '幾何體將以更高的品質進行取樣，但會降低效能。', 'ジオメトリはパフォーマンスを犠牲にして、より高品質でサンプリングされます。'),
'Text (Lines)/ Duplicator': ('文本（行）/ 复制器', '文字（行）/ 複製器', 'テキスト（行）/ デュプリケーター'),
'Text (Words)': ('文本（词）', '文字（詞）', 'テキスト（単語）'),
'Text (Characters)': ('文本（字符）', '文字（字元）', 'テキスト（文字）'),
'Squash and Stretch': ('挤压和拉伸', '擠壓和拉伸', 'スカッシュ＆ストレッチ'),
'Squash and Stretch Shapes, optionally adding Bulge.': ('挤压和拉伸形状，可选择添加膨胀。', '擠壓和拉伸形狀，可選擇新增膨脹。', 'シェイプのスカッシュ＆ストレッチ。オプションでバルジを追加できます。'),
'Automatic Bulge Adjustments': ('自动膨胀调整', '自動膨脹調整', '自動バルジ調整'),
'Bulge will fade on and off as the Shape squashes.': ('膨胀效果会随形状挤压而渐入渐出。', '膨脹效果會隨形狀擠壓而漸入漸出。', 'シェイプがスカッシュされるとバルジがフェードイン/アウトします。'),
'Subdivide Geometry': ('细分几何体', '細分幾何體', 'ジオメトリを細分化'),
'Extra geometry will be added when bulging.': ('膨胀时将添加额外的几何体。', '膨脹時將新增額外的幾何體。', 'バルジ時に追加のジオメトリが生成されます。'),
'Area Preservation': ('面积保持', '面積保持', '面積保持'),
'The Bulge will be scaled in order to maintain the overall Shape area.': ('膨胀将被缩放以保持形状的整体面积。', '膨脹將被縮放以保持形狀的整體面積。', '全体のシェイプ面積を維持するためにバルジがスケーリングされます。'),
'Use and manipulate time to drive other Attributes.': ('使用和操纵时间来驱动其他属性。', '使用和操控時間來驅動其他屬性。', '時間を使用・操作して他のアトリビュートを駆動します。'),
'Start Frame': ('起始帧', '起始幀', '開始フレーム'),
'Cycle Length': ('循环长度', '循環長度', 'サイクル長'),
'Interpolation Mode': ('插值模式', '內插模式', '補間モード'),
'Frame': ('帧', '幀', 'フレーム'),
'Color Material Override': ('颜色材质覆盖', '顏色材質覆寫', 'カラーマテリアルオーバーライド'),
'Override the colors within Sub-Meshes.': ('覆盖子网格中的颜色。', '覆寫子網格中的顏色。', 'サブメッシュ内のカラーをオーバーライドします。'),
'Alpha Material Override': ('Alpha 材质覆盖', 'Alpha 材質覆寫', 'Alpha マテリアルオーバーライド'),
'Override the alpha within Sub-Meshes.': ('覆盖子网格中的透明度。', '覆寫子網格中的透明度。', 'サブメッシュ内の Alpha をオーバーライドします。'),
'HSV Material Override': ('HSV 材质覆盖', 'HSV 材質覆寫', 'HSV マテリアルオーバーライド'),
'Override the Hue, Saturation and Value of Shapes within Sub-Meshes.': ('覆盖子网格中形状的色相、饱和度和明度。', '覆寫子網格中形狀的色相、飽和度和明度。', 'サブメッシュ内のシェイプの色相、彩度、明度をオーバーライドします。'),
'Apply Distribution': ('应用分布', '套用分佈', '分布を適用'),
'Apply a Distribution to the Sub-Meshes on a Shape.': ('将分布应用到形状上的子网格。', '將分佈套用到形狀上的子網格。', 'シェイプのサブメッシュに分布を適用します。'),
'Distribution': ('分布', '分佈', '分布'),
'Determine the layout of the sub-shapes.': ('确定子形状的布局。', '決定子形狀的佈局。', 'サブシェイプのレイアウトを決定します。'),
'Horizontal Centre': ('水平居中', '水平置中', '水平中央'),
'Vertical Centre': ('垂直居中', '垂直置中', '垂直中央'),
'Text (Lines)': ('文本（行）', '文字（行）', 'テキスト（行）'),
'Count Sub-Meshes': ('计算子网格', '計算子網格', 'サブメッシュをカウント'),
'Count the number of Sub-Meshes at a given level.': ('计算给定层级上的子网格数量。', '計算指定層級上的子網格數量。', '指定レベルのサブメッシュ数をカウントします。'),
'Apply Layout': ('应用布局', '套用佈局', 'レイアウトを適用'),
'Stack Shapes within a Sub-Mesh in a similar way to the Layout Group.': ('以类似布局编组的方式将子网格中的形状堆叠。', '以類似佈局群組的方式將子網格中的形狀堆疊。', 'レイアウトグループと同様の方法でサブメッシュ内のシェイプをスタックします。'),
'Layout': ('布局', '佈局', 'レイアウト'),
'Choose the layout used to position your shapes.': ('选择用于定位形状的布局。', '選擇用於定位形狀的佈局。', 'シェイプの配置に使用するレイアウトを選択します。'),
'Level': ('层级', '層級', 'レベル'),
'The Sub-Mesh depth to use with the layout.': ('与布局一起使用的子网格深度。', '與佈局一起使用的子網格深度。', 'レイアウトで使用するサブメッシュの深度。'),
'Horizontal Alignment': ('水平对齐', '水平對齊', '水平揃え'),
'Vertical Alignment': ('垂直对齐', '垂直對齊', '垂直揃え'),
'Chop Path': ('切割路径', '切割路徑', 'パスを切断'),
'Cuts a path into chunks using Rectangles.': ('使用矩形将路径切割成块。', '使用矩形將路徑切割成塊。', '矩形を使用してパスをチャンクに切断します。'),
'The number of rectangles to use when chopping the path.': ('切割路径时使用的矩形数量。', '切割路徑時使用的矩形數量。', 'パスを切断する際に使用する矩形の数。'),
'Angle': ('角度', '角度', '角度'),
'The angle of the cuts.': ('切割的角度。', '切割的角度。', '切断の角度。'),
"You can connect a Behaviour such as Random, Noise, or Stagger to 'Spread' and 'Offset' to create interesting effects.": ('您可以将随机、噪声或交错等行为连接到“展开”和“偏移”以创建有趣的效果。', '您可以將隨機、雜訊或交錯等行為連接到「展開」和「偏移」以建立有趣的效果。', 'Random、Noise、Stagger などのビヘイビアを「スプレッド」と「オフセット」に接続して、面白い効果を作成できます。'),
'Offset the cut parts of the path. You can, for example, connect a Stagger, Random or Noise here.': ('偏移路径的切割部分。例如，您可以在此连接交错、随机或噪声。', '偏移路徑的切割部分。例如，您可以在此連接交錯、隨機或雜訊。', 'パスの切断部分をオフセットします。例えば、ここに Stagger、Random、Noise を接続できます。'),
'The gap between the cuts.': ('切割之间的间隙。', '切割之間的間隙。', '切断間の隙間。'),
'Rectangle Deformers': ('矩形变形器', '矩形變形器', '矩形デフォーマ'),
'Deform the Rectangles used to cut the path.': ('变形用于切割路径的矩形。', '變形用於切割路徑的矩形。', 'パスの切断に使用する矩形を変形します。'),
'Flatten Shape': ('展平形状', '展平形狀', 'シェイプをフラット化'),
'With this on, the Chop will treat all Sub-Meshes as if they are one.': ('启用此选项后，切割会将所有子网格视为一个整体。', '啟用此選項後，切割會將所有子網格視為一個整體。', 'これをオンにすると、チョップはすべてのサブメッシュを 1 つとして扱います。'),
'With Flatten Shape on, you will lose any input materials, to apply a material to the output slices, use a Sub-Mesh Behaviour.': ('启用展平形状后，您将丢失所有输入材质。要将材质应用到输出切片，请使用子网格行为。', '啟用展平形狀後，您將遺失所有輸入材質。要將材質套用到輸出切片，請使用子網格行為。', '「シェイプをフラット化」をオンにすると、入力マテリアルが失われます。出力スライスにマテリアルを適用するには、サブメッシュビヘイビアを使用してください。'),
'Sub-Mesh': ('子网格', '子網格', 'サブメッシュ'),
'Access the Sub-Meshes within Shapes to apply transforms, materials and more.': ('访问形状中的子网格以应用变换、材质等。', '存取形狀中的子網格以套用變換、材質等。', 'シェイプ内のサブメッシュにアクセスして、トランスフォーム、マテリアルなどを適用します。'),
'Visibility': ('可见性', '可見性', '表示/非表示'),
'Recalculate Pivot': ('重新计算锚点', '重新計算錨點', 'ピボットを再計算'),
'Place the pivot for each child-mesh based on the Pivot Position.': ('根据锚点位置为每个子网格放置锚点。', '根據錨點位置為每個子網格放置錨點。', 'ピボット位置に基づいて各子メッシュのピボットを配置します。'),
'Pivot Position': ('锚点位置', '錨點位置', 'ピボット位置'),
"Position the pivots by aligning them to each child-mesh's bounding box.": ('通过将锚点对齐到每个子网格的边界框来定位锚点。', '透過將錨點對齊到每個子網格的邊界框來定位錨點。', '各子メッシュのバウンディングボックスに揃えてピボットを配置します。'),
'Custom Level Range': ('自定义层级范围', '自訂層級範圍', 'カスタムレベル範囲'),
'Geometry Mode': ('几何体模式', '幾何體模式', 'ジオメトリモード'),
'Replace Fill': ('替换填充', '取代填充', '塗りを置換'),
'Replace Stroke': ('替换描边', '取代描邊', 'ストロークを置換'),
'Fill Overrides': ('填充覆盖', '填充覆寫', '塗りオーバーライド'),
'Stroke Overrides': ('描边覆盖', '描邊覆寫', 'ストロークオーバーライド'),
'Flatten Mesh at Level': ('在层级展平网格', '在層級展平網格', 'レベルでメッシュをフラット化'),
"This will flatten meshes at a particular level.\nIt's useful for taking per character materials and making them per word/line.": ('这将在特定层级展平网格。\n对于将逐字符材质转换为逐词/行材质很有用。', '這將在特定層級展平網格。\n對於將逐字元材質轉換為逐詞/行材質很有用。', '特定レベルでメッシュをフラット化します。\n文字ごとのマテリアルを単語/行ごとに変換するのに便利です。'),
'Replacement Mode': ('替换模式', '取代模式', '置換モード'),
'Opacity Mode': ('不透明度模式', '不透明度模式', '不透明度モード'),
'This setting determines if any existing opacity should be overwritten or multiplied.': ('此设置确定是否应覆盖或乘以现有不透明度。', '此設定決定是否應覆寫或乘以現有不透明度。', 'この設定は、既存の不透明度を上書きするか乗算するかを決定します。'),
'Index Mode': ('索引模式', '索引模式', 'インデックスモード'),
'Determines if Behaviours such as Random give unique values for every sub-mesh, or if the index is unique per parent mesh.': ('确定随机等行为是否为每个子网格提供唯一值，或者索引是否按父网格唯一。', '決定隨機等行為是否為每個子網格提供唯一值，或者索引是否按父網格唯一。', 'Random などのビヘイビアがすべてのサブメッシュに固有の値を与えるか、またはインデックスが親メッシュごとに固有かを決定します。'),
'Sub-Meshes': ('子网格', '子網格', 'サブメッシュ'),
'Polygons': ('多边形', '多邊形', 'ポリゴン'),
'Multiply Existing': ('乘以现有', '乘以現有', '既存値を乗算'),
'Unique Index': ('唯一索引', '唯一索引', '固有インデックス'),
'Child Index': ('子级索引', '子級索引', '子インデックス'),
'All': ('全部', '全部', 'すべて'),
'Replace All': ('全部替换', '全部取代', 'すべて置換'),
'Replace Missing': ('替换缺失', '取代缺失', '未設定を置換'),
'Replace Existing': ('替换现有', '取代現有', '既存を置換'),
'A deformer to create round or mitred edges.': ('用于创建圆角或斜角边缘的变形器。', '用於建立圓角或斜角邊緣的變形器。', '角丸またはマイターエッジを作成するデフォーマ。'),
'Radius': ('半径', '半徑', '半径'),
'Radius Mode': ('半径模式', '半徑模式', '半径モード'),
'When Radius has an input, this dictates how the radius is then calculated.': ('当半径有输入时，此项决定半径的计算方式。', '當半徑有輸入時，此項決定半徑的計算方式。', '半径に入力がある場合、これにより半径の計算方法が決まります。'),
'Curve To End Points': ('曲线到端点', '曲線到端點', '端点へのカーブ'),
'Min Angle': ('最小角度', '最小角度', '最小角度'),
'Only bevel corners with an interior angle greater than this value (in degrees).': ('仅对内角大于此值（度）的角进行倒角。', '僅對內角大於此值（度）的角進行倒角。', 'この値（度）より大きい内角を持つコーナーのみにベベルを適用します。'),
'Max Angle': ('最大角度', '最大角度', '最大角度'),
'Only bevel corners with an interior angle less than this value (in degrees).': ('仅对内角小于此值（度）的角进行倒角。', '僅對內角小於此值（度）的角進行倒角。', 'この値（度）より小さい内角を持つコーナーのみにベベルを適用します。'),
'Fillet': ('圆角', '圓角', 'フィレット'),
'Chamfer': ('倒角', '倒角', '面取り'),
'Per Sub-Mesh': ('按子网格', '按子網格', 'サブメッシュごと'),
'Per Point': ('按点', '按點', 'ポイントごと'),
'Add, subtract, union and intersect Shapes.': ('对形状进行加、减、并集和交集运算。', '對形狀進行加、減、聯集和交集運算。', 'シェイプの加算、減算、合体、交差を行います。'),
'Clipping Shapes': ('裁剪形状', '裁剪形狀', 'クリッピングシェイプ'),
'Adds a Fill material that can be used on many shapes at once.': ('添加可同时用于多个形状的填充材质。', '新增可同時用於多個形狀的填充材質。', '多くのシェイプに一度に使用できる塗りマテリアルを追加します。'),
'Shaders': ('着色器', '著色器', 'シェーダー'),
'Adds a Stroke material that can be used on many shapes at once.': ('添加可同时用于多个形状的描边材质。', '新增可同時用於多個形狀的描邊材質。', '多くのシェイプに一度に使用できるストロークマテリアルを追加します。'),
'Cap Style': ('端点样式', '端點樣式', 'キャップスタイル'),
'Join Style': ('连接样式', '連接樣式', 'ジョインスタイル'),
'Mitre Limit': ('斜接限制', '斜接限制', 'マイターリミット'),
'Dash Pattern': ('虚线模式', '虛線模式', '破線パターン'),
'Dash Offset': ('虚线偏移', '虛線偏移', '破線オフセット'),
'Trim': ('修剪', '修剪', 'トリム'),
'Start': ('起始', '起始', '開始'),
'End': ('结束', '結束', '終了'),
'Reverse Path': ('反转路径', '反轉路徑', 'パスを反転'),
'Align': ('对齐', '對齊', '整列'),
'Tapered Width': ('锥化宽度', '錐化寬度', 'テーパー幅'),
'Double Taper': ('双向锥化', '雙向錐化', 'ダブルテーパー'),
'A good default for a double taper is to set the Start and End Widths to 0.': ('双向锥化的一个良好默认值是将起始宽度和结束宽度设置为 0。', '雙向錐化的一個良好預設值是將起始寬度和結束寬度設為 0。', 'ダブルテーパーの適切なデフォルトは、開始幅と終了幅を 0 に設定することです。'),
'Taper From': ('锥化起点', '錐化起點', 'テーパー起点'),
'Start Width': ('起始宽度', '起始寬度', '開始幅'),
'End Width': ('结束宽度', '結束寬度', '終了幅'),
'Middle Length': ('中间长度', '中間長度', '中間の長さ'),
'Cap Centres': ('端点中心', '端點中心', 'キャップ中心'),
'Cap Style must be set to Round.': ('端点样式必须设置为圆形。', '端點樣式必須設為圓形。', 'キャップスタイルを「ラウンド」に設定する必要があります。'),
'Dash Pattern Mode': ('虚线模式类型', '虛線模式類型', '破線パターンモード'),
'Flat': ('平面', '平面', 'フラット'),
'Projecting': ('投影', '投影', 'プロジェクティング'),
'Mitre': ('斜接', '斜接', 'マイター'),
'Bevel': ('倒角', '倒角', 'ベベル'),
'Inner': ('内部', '內部', '内側'),
'Outer': ('外部', '外部', '外側'),
'Single Color': ('单色', '單色', '単色'),
'Percentage': ('百分比', '百分比', 'パーセント'),
'Oklab Interpolation': ('Oklab 插值', 'Oklab 內插', 'Oklab 補間'),
'LCH Interpolation (Short Path)': ('LCH 插值（短路径）', 'LCH 內插（短路徑）', 'LCH 補間（ショートパス）'),
'LCH Interpolation (Long Path)': ('LCH 插值（长路径）', 'LCH 內插（長路徑）', 'LCH 補間（ロングパス）'),
'Convert Shapes into voxels with control over their size and scale to create gaps.': ('将形状转换为体素，并控制其大小和缩放以创建间隙。', '將形狀轉換為體素，並控制其大小和縮放以建立間隙。', 'シェイプをボクセルに変換し、サイズとスケールを制御して隙間を作成します。'),
'Voxel Scale': ('体素缩放', '體素縮放', 'ボクセルスケール'),
'Screen Space': ('屏幕空间', '螢幕空間', 'スクリーン空間'),
'Screen Size': ('屏幕大小', '螢幕大小', 'スクリーンサイズ'),
'Output repeating sequences of numbers using the modulus function.': ('使用取模函数输出重复的数字序列。', '使用取模函數輸出重複的數字序列。', '剰余関数を使用して繰り返しの数列を出力します。'),
'Divisor': ('除数', '除數', '除数'),
'Pass Value': ('通过值', '通過值', 'パス値'),
'Fail Value': ('失败值', '失敗值', 'フェイル値'),
'Custom Pattern': ('自定义模式', '自訂模式', 'カスタムパターン'),
'Remainder': ('余数', '餘數', '余り'),
'Pass / Fail': ('通过 / 失败', '通過 / 失敗', 'パス/フェイル'),
'Store and manipulate a value.': ('存储和操作一个值。', '儲存和操作一個值。', '値を保存して操作します。'),
'Store and manipulate two dimensional values (e.g. X,Y).': ('存储和操作二维值（例如 X,Y）。', '儲存和操作二維值（例如 X,Y）。', '2 次元の値（例: X,Y）を保存して操作します。'),
'Value3': ('三维值', '三維值', '3D 値'),
'Store and manipulate three dimensional values (e.g. X,Y,Z).': ('存储和操作三维值（例如 X,Y,Z）。', '儲存和操作三維值（例如 X,Y,Z）。', '3 次元の値（例: X,Y,Z）を保存して操作します。'),
"Dynamically position a Shape's pivot point along the edges of its bounding box.": ('动态地将形状的锚点放置在其边界框的边缘上。', '動態地將形狀的錨點放置在其邊界框的邊緣上。', 'シェイプのピボットポイントをバウンディングボックスの辺に沿って動的に配置します。'),
'X': ('X', 'X', 'X'),
'Y': ('Y', 'Y', 'Y'),
'Auto-Crop': ('自动裁剪', '自動裁剪', '自動クロップ'),
'Easily crop shapes based on their bounding box.': ('基于边界框轻松裁剪形状。', '基於邊界框輕鬆裁剪形狀。', 'バウンディングボックスに基づいてシェイプを簡単にクロップします。'),
'Align X': ('X 对齐', 'X 對齊', 'X 揃え'),
'Align Y': ('Y 对齐', 'Y 對齊', 'Y 揃え'),
'Mask Shape': ('蒙版形状', '遮罩形狀', 'マスクシェイプ'),
'Progress Mode': ('进度模式', '進度模式', '進行モード'),
'Ellipse': ('椭圆', '橢圓', '楕円'),
'Rotate shapes towards a target.': ('将形状旋转朝向目标。', '將形狀旋轉朝向目標。', 'シェイプをターゲットに向かって回転させます。'),
'Target': ('目标', '目標', 'ターゲット'),
'Round values up, down or to the nearest multiple of a value.': ('将值向上、向下或四舍五入到最接近的倍数。', '將值向上、向下或四捨五入到最接近的倍數。', '値を切り上げ、切り捨て、または最も近い倍数に丸めます。'),
'Rounding': ('取整', '取整', '丸め'),
'Deformer Mode': ('变形器模式', '變形器模式', 'デフォーマモード'),
'Both': ('两者', '兩者', '両方'),
'Round Up': ('向上取整', '向上取整', '切り上げ'),
'Round Down': ('向下取整', '向下取整', '切り捨て'),
'Add more points to Shapes to create smoother deformations.': ('为形状添加更多点以创建更平滑的变形。', '為形狀新增更多點以建立更平滑的變形。', 'シェイプにポイントを追加して、より滑らかな変形を作成します。'),
'Max. Length': ('最大长度', '最大長度', '最大長さ'),
'Edge Length': ('边长', '邊長', 'エッジの長さ'),
'Keep Original Points': ('保留原始点', '保留原始點', '元のポイントを保持'),
'Number of Divisions': ('分割数', '分割數', '分割数'),
'Drive an attribute of one layer using its distance from another.': ('使用一个图层与另一个图层的距离来驱动属性。', '使用一個圖層與另一個圖層的距離來驅動屬性。', 'あるレイヤーと別のレイヤーの距離を使用してアトリビュートを駆動します。'),
'Blend between two colors using a gradient to control the transition.': ('使用渐变控制过渡，在两种颜色之间混合。', '使用漸層控制過渡，在兩種顏色之間混合。', 'グラデーションを使用して遷移を制御しながら、2 つのカラー間をブレンドします。'),
'First Color': ('第一颜色', '第一顏色', '第 1 カラー'),
'Second Color': ('第二颜色', '第二顏色', '第 2 カラー'),
'Use Alpha': ('使用 Alpha', '使用 Alpha', 'Alpha を使用'),
'Morph between shapes with different point counts.': ('在具有不同点数的形状之间进行变形。', '在具有不同點數的形狀之間進行變形。', '異なるポイント数を持つシェイプ間でモーフします。'),
'Morph Target': ('变形目标', '變形目標', 'モーフターゲット'),
'Morph Divisions': ('变形分割', '變形分割', 'モーフ分割'),
'Sampling Offset': ('采样偏移', '取樣偏移', 'サンプリングオフセット'),
'Simple Morph': ('简单变形', '簡單變形', 'シンプルモーフ'),
'Wave Morph': ('波形变形', '波形變形', 'ウェーブモーフ'),
'Blend (lerp) between two values.': ('在两个值之间进行线性混合。', '在兩個值之間進行線性混合。', '2 つの値間を線形補間（lerp）します。'),
'Value2 Blend': ('二维值混合', '二維值混合', '2D 値ブレンド'),
'Blend (lerp) between two dimensional values (e.g. X,Y).': ('在二维值（例如 X,Y）之间进行线性混合。', '在二維值（例如 X,Y）之間進行線性混合。', '2 次元の値（例: X,Y）間を線形補間（lerp）します。'),
'Value3 Blend': ('三维值混合', '三維值混合', '3D 値ブレンド'),
'Blend (lerp) between three dimensional values (e.g. X,Y,Z).': ('在三维值（例如 X,Y,Z）之间进行线性混合。', '在三維值（例如 X,Y,Z）之間進行線性混合。', '3 次元の値（例: X,Y,Z）間を線形補間（lerp）します。'),
'Blend (lerp) between two positions.': ('在两个位置之间进行线性混合。', '在兩個位置之間進行線性混合。', '2 つの位置間を線形補間（lerp）します。'),
'First (origin)': ('第一（原点）', '第一（原點）', '第 1（原点）'),
'A simple 2 bone IK system for bendy or straight limbs.': ('用于弯曲或笔直肢体的简单 2 骨骼 IK 系统。', '用於彎曲或筆直肢體的簡單 2 骨頭 IK 系統。', '曲がったまたは真っ直ぐな四肢用のシンプルな 2 ボーン IK システム。'),
'Start Controller': ('起始控制器', '起始控制器', '開始コントローラー'),
'End Controller': ('结束控制器', '結束控制器', '終了コントローラー'),
'Stretch': ('拉伸', '拉伸', 'ストレッチ'),
'Joint Position': ('关节位置', '關節位置', 'ジョイント位置'),
'Curvature': ('曲率', '曲率', '曲率'),
'Length': ('长度', '長度', '長さ'),
'Sample the color of a Shape to drive other Attributes. Alternatively, use the Image Sampler.': ('采样形状的颜色以驱动其他属性。或者，使用图像采样器。', '取樣形狀的顏色以驅動其他屬性。或者，使用影像取樣器。', 'シェイプのカラーをサンプリングして他のアトリビュートを駆動します。代わりにイメージサンプラーも使用できます。'),
'Get the directional vector between two points. Useful when used with Push Along Vector.': ('获取两点之间的方向向量。与沿向量推动配合使用时很有用。', '取得兩點之間的方向向量。與沿向量推動配合使用時很有用。', '2 点間の方向ベクトルを取得します。「ベクトルに沿って押し出し」と組み合わせて使用すると便利です。'),
'Normalize': ('归一化', '正規化', '正規化'),
'Apply a skew transform to a Shape.': ('对形状应用倾斜变换。', '對形狀套用傾斜變換。', 'シェイプにスキュー変換を適用します。'),
'Pivot X': ('锚点 X', '錨點 X', 'ピボット X'),
'Pivot Y': ('锚点 Y', '錨點 Y', 'ピボット Y'),
"'Pinch and pull' Shapes within a Falloff by moving a Null.": ('通过移动 Null 在衰减范围内“捏拉”形状。', '透過移動 Null 在衰減範圍內「捏拉」形狀。', 'Null を移動してフォールオフ内のシェイプを「ピンチ＆プル」します。'),
'Pinch Point': ('捏取点', '捏取點', 'ピンチポイント'),
'Bind Area': ('绑定区域', '綁定區域', 'バインド領域'),
'Convert Bézier curves to polygonal lines.': ('将贝塞尔曲线转换为多边形线段。', '將貝茲曲線轉換為多邊形線段。', 'ベジェ曲線をポリゴンラインに変換します。'),
'Lines per Curve': ('每条曲线的线段数', '每條曲線的線段數', 'カーブあたりの線分数'),
'Deform a Shape along a vector. Useful when used with Get Vector.': ('沿向量变形形状。与获取向量配合使用时很有用。', '沿向量變形形狀。與取得向量配合使用時很有用。', 'ベクトルに沿ってシェイプを変形します。「ベクトルを取得」と組み合わせて使用すると便利です。'),
'Reverse Direction': ('反转方向', '反轉方向', '方向を反転'),
'Blend Sub-Mesh Positions': ('混合子网格位置', '混合子網格位置', 'サブメッシュ位置をブレンド'),
'Blend between the sub-mesh positions of two shapes.': ('在两个形状的子网格位置之间混合。', '在兩個形狀的子網格位置之間混合。', '2 つのシェイプのサブメッシュ位置間をブレンドします。'),
'Blend': ('混合', '混合', 'ブレンド'),
'Destination Shape': ('目标形状', '目標形狀', '目標シェイプ'),
'Use Global Positions': ('使用全局位置', '使用全域位置', 'グローバル位置を使用'),
"Legacy Layer - new 'Blend Sub-Mesh Positions' available.\nBlend between the sub-mesh positions of two shapes.": ('旧版图层 - 新的“混合子网格位置”可用。\n在两个形状的子网格位置之间混合。', '舊版圖層 - 新的「混合子網格位置」可用。\n在兩個形狀的子網格位置之間混合。', 'レガシーレイヤー - 新しい「サブメッシュ位置をブレンド」が利用可能です。\n2 つのシェイプのサブメッシュ位置間をブレンドします。'),
'Apply transformations to Shapes.': ('对形状应用变换。', '對形狀套用變換。', 'シェイプにトランスフォームを適用します。'),
'Apply 3D transformations to Shapes and Sub-Meshes.': ('对形状和子网格应用 3D 变换。', '對形狀和子網格套用 3D 變換。', 'シェイプとサブメッシュに 3D トランスフォームを適用します。'),
'Position Z': ('位置 Z', '位置 Z', '位置 Z'),
'Rotation Z': ('旋转 Z', '旋轉 Z', '回転 Z'),
'Swap Color': ('交换颜色', '交換顏色', 'カラーを入れ替え'),
'Searches for, and swaps specific colors on Sub-Meshes.': ('搜索并交换子网格上的特定颜色。', '搜尋並交換子網格上的特定顏色。', 'サブメッシュ上の特定のカラーを検索して入れ替えます。'),
'Old Color': ('旧颜色', '舊顏色', '元のカラー'),
'New Color': ('新颜色', '新顏色', '新しいカラー'),
'Spreadsheet Lookup': ('电子表格查找', '試算表查詢', 'スプレッドシートルックアップ'),
'Lookup values in spreadsheets based on keys.': ('根据键在电子表格中查找值。', '根據鍵在試算表中查詢值。', 'キーに基づいてスプレッドシートの値を検索します。'),
'Lookup Column': ('查找列', '查詢欄', 'ルックアップ列'),
'Value Column': ('值列', '值欄', '値列'),
'Lookup Key': ('查找键', '查詢鍵', 'ルックアップキー'),
'Visibility Sequence': ('可见性序列', '可見性序列', '表示シーケンス'),
'Affect the visibilty of Sub-Meshes.': ('影响子网格的可见性。', '影響子網格的可見性。', 'サブメッシュの表示/非表示に影響します。'),
'Always On': ('始终开启', '始終開啟', '常にオン'),
'Always Off': ('始终关闭', '始終關閉', '常にオフ'),
'Invert': ('反转', '反轉', '反転'),
'Shader': ('着色器', '著色器', 'シェーダー'),
'Color Filter': ('颜色滤镜', '顏色濾鏡', 'カラーフィルター'),
'Linear To sRGB': ('Linear 到 sRGB', 'Linear 到 sRGB', 'Linear から sRGB'),
'sRGB To Linear': ('sRGB 到 Linear', 'sRGB 到 Linear', 'sRGB から Linear'),
'Repeat': ('重复', '重複', 'リピート'),
'Mirror': ('镜像', '鏡像', 'ミラー'),
'Decal': ('贴花', '貼花', 'デカール'),
'Destination Over': ('目标上方', '目標上方', 'デスティネーションオーバー'),
'Source In': ('源内部', '來源內部', 'ソースイン'),
'Destination In': ('目标内部', '目標內部', 'デスティネーションイン'),
'Source Out': ('源外部', '來源外部', 'ソースアウト'),
'Destination Out': ('目标外部', '目標外部', 'デスティネーションアウト'),
'Source Atop': ('源在上', '來源在上', 'ソースアトップ'),
'Destination Atop': ('目标在上', '目標在上', 'デスティネーションアトップ'),
'Xor': ('异或', '互斥或', '排他的論理和'),
'Plus': ('加', '加', 'プラス'),
'Modulate': ('调制', '調制', 'モジュレート'),
'Gradient Map': ('渐变映射', '漸層映射', 'グラデーションマップ'),
'Generates a gradient based on the brightness of an input.': ('根据输入的亮度生成渐变。', '根據輸入的亮度產生漸層。', '入力の明るさに基づいてグラデーションを生成します。'),
'Premultiply': ('预乘', '預乘', 'プリマルチプライ'),
'Luma (Gamma Corrected)': ('亮度（伽马校正）', '亮度（Gamma 校正）', '輝度（ガンマ補正済み）'),
'Red Channel': ('红色通道', '紅色通道', '赤チャンネル'),
'Green Channel': ('绿色通道', '綠色通道', '緑チャンネル'),
'Blue Channel': ('蓝色通道', '藍色通道', '青チャンネル'),
'Custom RGB Multipliers': ('自定义 RGB 乘数', '自訂 RGB 乘數', 'カスタム RGB 乗数'),
'Checkerboard Shader': ('棋盘格着色器', '棋盤格著色器', 'チェッカーボードシェーダー'),
'A checkerboard shader with adjustable pattern size.': ('具有可调图案大小的棋盘格着色器。', '具有可調圖案大小的棋盤格著色器。', 'パターンサイズを調整可能なチェッカーボードシェーダー。'),
'Filter': ('滤镜', '濾鏡', 'フィルター'),
'None (Fastest)': ('无（最快）', '無（最快）', 'なし（最速）'),
'Bilinear': ('双线性', '雙線性', 'バイリニア'),
'Mipmaps (Use For Scaling Down)': ('Mipmaps（用于缩小）', 'Mipmaps（用於縮小）', 'Mipmaps（縮小用）'),
'Bicubic (Use For Scaling Up)': ('双三次（用于放大）', '雙三次（用於放大）', 'バイキュービック（拡大用）'),
'Gradient Shader': ('渐变着色器', '漸層著色器', 'グラデーションシェーダー'),
'A gradient shader with Linear, Radial, Sweep and Conical gradients.': ('具有线性、径向、扫描和锥形渐变的渐变着色器。', '具有線性、放射狀、掃描和錐形漸層的漸層著色器。', 'リニア、ラジアル、スウィープ、コニカルグラデーションを持つグラデーションシェーダー。'),
'Tiling': ('平铺', '平鋪', 'タイリング'),
'Linear Gradient': ('线性渐变', '線性漸層', 'リニアグラデーション'),
'Generate a linear gradient for the Gradient Shader.': ('为渐变着色器生成线性渐变。', '為漸層著色器產生線性漸層。', 'グラデーションシェーダー用のリニアグラデーションを生成します。'),
'Wrap UVs': ('包裹 UV', '包裹 UV', 'UV をラップ'),
'Gradient Scales With Rotation': ('渐变随旋转缩放', '漸層隨旋轉縮放', '回転に合わせてグラデーションをスケール'),
'Conical Gradient': ('锥形渐变', '錐形漸層', 'コニカルグラデーション'),
"Legacy Layer - new 'Conical Gradient Shader' available.\nGenerate a Conical gradient for the Gradient Shader.": ('旧版图层 - 新的“锥形渐变着色器”可用。\n为渐变着色器生成锥形渐变。', '舊版圖層 - 新的「錐形漸層著色器」可用。\n為漸層著色器產生錐形漸層。', 'レガシーレイヤー - 新しい「コニカルグラデーションシェーダー」が利用可能です。\nグラデーションシェーダー用のコニカルグラデーションを生成します。'),
'Start Radius': ('起始半径', '起始半徑', '開始半径'),
'Start Centre': ('起始中心', '起始中心', '開始中心'),
'End Radius': ('结束半径', '結束半徑', '終了半径'),
'End Centre': ('结束中心', '結束中心', '終了中心'),
'First Ratio': ('第一比率', '第一比率', '第 1 比率'),
'Second Ratio': ('第二比率', '第二比率', '第 2 比率'),
'First Centre Ratio': ('第一中心比率', '第一中心比率', '第 1 中心比率'),
'Second Centre Ratio': ('第二中心比率', '第二中心比率', '第 2 中心比率'),
'Fixed Radius': ('固定半径', '固定半徑', '固定半径'),
'Bounding Box': ('边界框', '邊界框', 'バウンディングボックス'),
'Generate a Conical gradient for the Gradient Shader.': ('为渐变着色器生成锥形渐变。', '為漸層著色器產生錐形漸層。', 'グラデーションシェーダー用のコニカルグラデーションを生成します。'),
'Shape Gradient': ('形状渐变', '形狀漸層', 'シェイプグラデーション'),
'Generate a Shape gradient for the Gradient Shader.': ('为渐变着色器生成形状渐变。', '為漸層著色器產生形狀漸層。', 'グラデーションシェーダー用のシェイプグラデーションを生成します。'),
'Size Ratio': ('大小比率', '大小比率', 'サイズ比率'),
'Shape Sides': ('形状边数', '形狀邊數', 'シェイプの辺数'),
'Radial Gradient': ('径向渐变', '放射狀漸層', 'ラジアルグラデーション'),
}
