T = {
"Inwards": ("向内", "向內", "内側"),
"Outward": ("向外", "向外", "外側"),
"Particle Modifier": ("粒子修改器", "粒子修改器", "パーティクルモディファイア"),
"info.": ("信息。", "資訊。", "情報。"),
"Enable Modifier": ("启用修改器", "啟用修改器", "モディファイアを有効化"),
"Falloff Shape": ("衰减形状", "衰減形狀", "フォールオフシェイプ"),
"Turbulence": ("湍流", "亂流", "乱流"),
"Drag Force": ("阻力", "阻力", "ドラッグフォース"),
"General": ("常规", "一般", "一般"),
"Falloff": ("衰减", "衰減", "フォールオフ"),
"Data Modifier": ("数据修改器", "資料修改器", "データモディファイア"),
"Affect a Particle's properties including Id, lifespan and velocity.": ("影响粒子的属性，包括 Id、生命周期和速度。", "影響粒子的屬性，包括 Id、生命週期和速度。", "パーティクルの Id、寿命、速度などのプロパティに影響を与えます。"),
"Kill Particles": ("消灭粒子", "消滅粒子", "パーティクルを消滅"),
"Change Emitter ID": ("更改发射器 ID", "變更發射器 ID", "エミッター ID を変更"),
"New Emitter ID": ("新发射器 ID", "新發射器 ID", "新しいエミッター ID"),
"Lifespan Mode": ("生命周期模式", "生命週期模式", "寿命モード"),
"Age": ("年龄", "年齡", "年齢"),
"Age on Arrival": ("到达时的年龄", "到達時的年齡", "到着時の年齢"),
"Reset Velocity on Arrival": ("到达时重置速度", "到達時重設速度", "到着時に速度をリセット"),
"Clamp Velocity": ("限制速度", "限制速度", "速度をクランプ"),
"Velocity Limit": ("速度限制", "速度限制", "速度制限"),
"Particle Shape": ("粒子形状", "粒子形狀", "パーティクルシェイプ"),
"Simulate complex physically-based effects like smoke, rain or dust.": ("模拟复杂的基于物理的效果，如烟雾、雨或灰尘。", "模擬複雜的基於物理的效果，如煙霧、雨或灰塵。", "煙、雨、ほこりなどの複雑な物理ベースのエフェクトをシミュレートします。"),
"Modifiers": ("修改器", "修改器", "モディファイア"),
"Input Image": ("输入图像", "輸入影像", "入力画像"),
"Number of Particles": ("粒子数量", "粒子數量", "パーティクル数"),
"When using a transparent Input Image, try setting the Image Blend Mode to Color Alpha.": ("使用透明输入图像时，请尝试将图像混合模式设置为 Color Alpha。", "使用透明輸入影像時，請嘗試將影像混合模式設定為 Color Alpha。", "透明な入力画像を使用する場合は、画像ブレンドモードを Color Alpha に設定してみてください。"),
"OkLab Interpolation": ("OkLab 插值", "OkLab 插值", "OkLab 補間"),
"Fit Vertically": ("垂直适配", "垂直適配", "垂直にフィット"),
"Fit Horizontally": ("水平适配", "水平適配", "水平にフィット"),
"Bicubic (Useful for Scaling up)": ("双三次（适合放大）", "雙三次（適合放大）", "バイキュービック（拡大に便利）"),
"Static": ("静态", "靜態", "静的"),
"Animating": ("动画中", "動畫中", "アニメーション中"),
"60 Hz": ("60 Hz", "60 Hz", "60 Hz"),
"120 Hz": ("120 Hz", "120 Hz", "120 Hz"),
"240 Hz": ("240 Hz", "240 Hz", "240 Hz"),
"Color Over Lifespan": ("生命周期颜色", "生命週期顏色", "寿命カラー"),
"Inverse": ("反转", "反轉", "反転"),
"Color Alpha": ("Color Alpha", "Color Alpha", "Color Alpha"),
"Image Alpha": ("Image Alpha", "Image Alpha", "Image Alpha"),
"Visual": ("视觉", "視覺", "ビジュアル"),
"Visual Modifier": ("视觉修改器", "視覺修改器", "ビジュアルモディファイア"),
"Change the visual appearance of Particles.": ("更改粒子的视觉外观。", "變更粒子的視覺外觀。", "パーティクルのビジュアル外観を変更します。"),
"Scale Over Lifespan": ("生命周期缩放", "生命週期縮放", "寿命スケール"),
"Rotation Over Lifespan": ("生命周期旋转", "生命週期旋轉", "寿命回転"),
"Image Modifier": ("图像修改器", "影像修改器", "画像モディファイア"),
"Add images or sequences of images to Particles.": ("向粒子添加图像或图像序列。", "向粒子新增影像或影像序列。", "パーティクルに画像または画像シーケンスを追加します。"),
"Loop Sequence": ("循环序列", "循環序列", "ループシーケンス"),
"Fit To Lifespan": ("适配生命周期", "適配生命週期", "寿命にフィット"),
"Fps": ("Fps", "Fps", "Fps"),
"Path Modifier": ("路径修改器", "路徑修改器", "パスモディファイア"),
"Flow Particles along a Path.": ("沿路径流动粒子。", "沿路徑流動粒子。", "パスに沿ってパーティクルを流動させます。"),
"Overwrite Physics": ("覆盖物理", "覆寫物理", "物理をオーバーライド"),
"Force Magnitude": ("力的大小", "力的大小", "力の大きさ"),
"Path To Follow": ("跟随路径", "跟隨路徑", "追従パス"),
"Follow Path Mode": ("跟随路径模式", "跟隨路徑模式", "パス追従モード"),
"Smooth": ("平滑", "平滑", "スムーズ"),
"Points Per Second": ("每秒点数", "每秒點數", "毎秒ポイント数"),
"Margin": ("边距", "邊距", "マージン"),
"Reset On Change": ("更改时重置", "變更時重設", "変更時にリセット"),
"Loop Path": ("循环路径", "循環路徑", "ループパス"),
"Look Ahead": ("前瞻", "前瞻", "先読み"),
"This determines how far 'in front' the particles look. Smaller values mean tighter curves can be observed.": ("这决定了粒子向前看的距离。值越小，能观察到的曲线越紧凑。", "這決定了粒子向前看的距離。值越小，能觀察到的曲線越緊密。", "パーティクルが前方をどの程度見渡すかを決定します。値が小さいほど、より急なカーブを追従できます。"),
"Time Interpolation": ("时间插值", "時間插值", "時間補間"),
"Fit to Lifespan": ("适配生命周期", "適配生命週期", "寿命にフィット"),
"Vortex Modifier": ("涡旋修改器", "渦旋修改器", "ボルテックスモディファイア"),
"Swirl Particles around a position to create a spiral or galaxy effect.": ("使粒子围绕某个位置旋转，以创建螺旋或星系效果。", "使粒子圍繞某個位置旋轉，以建立螺旋或星系效果。", "パーティクルをある位置を中心に渦巻かせ、螺旋や銀河のエフェクトを作成します。"),
"Magnetic Modifier": ("磁力修改器", "磁力修改器", "磁力モディファイア"),
"Attract or repel Particles towards or away from a position.": ("将粒子吸引到某个位置或从某个位置排斥。", "將粒子吸引到某個位置或從某個位置排斥。", "パーティクルをある位置に引きつけたり反発させたりします。"),
"Flow Field Modifier": ("流场修改器", "流場修改器", "フローフィールドモディファイア"),
"Move Particles through a grid of directional cells to create a natural, fluid motion.": ("使粒子通过方向单元格网格移动，以创建自然的流体运动。", "使粒子通過方向性單元格網格移動，以建立自然的流體運動。", "パーティクルを方向性セルのグリッドを通して移動させ、自然な流体の動きを作成します。"),
"Flow Field": ("流场", "流場", "フローフィールド"),
"Goal Modifier": ("目标修改器", "目標修改器", "ゴールモディファイア"),
"Move Particles towards a target Distribution.": ("将粒子移向目标分布。", "將粒子移向目標分佈。", "パーティクルをターゲットディストリビューションに向かって移動させます。"),
"Goal Force": ("目标力", "目標力", "ゴールフォース"),
"Maximum Distance": ("最大距离", "最大距離", "最大距離"),
"Arrival": ("到达", "到達", "到着"),
"You can tell the particles to break as they approach the goal. Using breaking you can stop particles when they are 'close enough' to a goal.": ("您可以让粒子在接近目标时减速。使用制动功能，可以在粒子"足够接近"目标时停止它们。", "您可以讓粒子在接近目標時減速。使用制動功能，可以在粒子「足夠接近」目標時停止它們。", "パーティクルがゴールに近づいた時にブレーキをかけることができます。ブレーキを使うと、パーティクルがゴールに「十分近づいた」時に停止させることができます。"),
"Braking Force": ("制动力", "制動力", "ブレーキ力"),
"Braking Distance": ("制动距离", "制動距離", "ブレーキ距離"),
"Speed Modifier": ("速度修改器", "速度修改器", "速度モディファイア"),
"Add drag or set limits for a Particle's speed.": ("为粒子的速度添加阻力或设置限制。", "為粒子的速度新增阻力或設定限制。", "パーティクルの速度にドラッグを追加したり制限を設定したりします。"),
"Limit Type": ("限制类型", "限制類型", "制限タイプ"),
"Top Speed": ("最高速度", "最高速度", "最高速度"),
"Drag": ("阻力", "阻力", "ドラッグ"),
"Force Modifier": ("力修改器", "力修改器", "フォースモディファイア"),
"Change the physical properties of Particles such as gravity and mass by applying a force.": ("通过施加力来更改粒子的物理属性（如重力和质量）。", "透過施加力來變更粒子的物理屬性（如重力和質量）。", "力を適用してパーティクルの重力や質量などの物理プロパティを変更します。"),
"Force Velocity": ("力速度", "力速度", "フォース速度"),
"Mass Over Lifespan": ("生命周期质量", "生命週期質量", "寿命質量"),
"Mass Multiplier": ("质量乘数", "質量乘數", "質量乗数"),
"Turbulence Modifier": ("湍流修改器", "亂流修改器", "乱流モディファイア"),
"Use noise to influence a Particle's position and velocity to add interest to a simulation.": ("使用噪波影响粒子的位置和速度，为模拟增添趣味。", "使用雜訊影響粒子的位置和速度，為模擬增添趣味。", "ノイズを使用してパーティクルの位置と速度に影響を与え、シミュレーションに変化を加えます。"),
"Physics Mode": ("物理模式", "物理模式", "物理モード"),
"Draw Color": ("绘制颜色", "繪製顏色", "描画カラー"),
"Multi-Point Gradient Shader": ("多点渐变着色器", "多點漸層著色器", "マルチポイントグラデーションシェーダー"),
"Position colors and then use influence to set how they falloff.": ("设置颜色位置，然后使用影响力设置其衰减方式。", "設定顏色位置，然後使用影響力設定其衰減方式。", "カラーの位置を設定し、影響力を使用してフォールオフの方法を設定します。"),
"Influence": ("影响力", "影響力", "影響力"),
"Gamma Correction": ("伽马校正", "Gamma 校正", "ガンマ補正"),
"Elevates colors to a power to increase or decrease perceived brightness and darkness.": ("对颜色应用幂运算以增加或减少感知的亮度和暗度。", "對顏色套用冪運算以增加或減少感知的亮度和暗度。", "カラーにべき乗を適用して、知覚される明るさと暗さを増減します。"),
"Gamma Value": ("伽马值", "Gamma 值", "ガンマ値"),
"Blend Shader": ("混合着色器", "混合著色器", "ブレンドシェーダー"),
"Combine several Shaders together and output a single Shader.": ("将多个着色器组合在一起并输出单个着色器。", "將多個著色器組合在一起並輸出單一著色器。", "複数のシェーダーを組み合わせて単一のシェーダーを出力します。"),
"Sample Mode": ("采样模式", "取樣模式", "サンプルモード"),
"SLA Shader": ("SLA 着色器", "SLA 著色器", "SLA シェーダー"),
"Novel Noise Shader.": ("新型噪波着色器。", "新型雜訊著色器。", "新しいノイズシェーダー。"),
"Select the noise type.": ("选择噪波类型。", "選擇雜訊類型。", "ノイズタイプを選択します。"),
"Set the blend mode for the Shader.": ("设置着色器的混合模式。", "設定著色器的混合模式。", "シェーダーのブレンドモードを設定します。"),
"The number of octaves over which the noise function is calculated. Use a higher value to increase the amount of detail in the noise pattern.": ("计算噪波函数的倍频程数。使用较高的值可以增加噪波图案的细节量。", "計算雜訊函數的八度音程數。使用較高的值可以增加雜訊圖案的細節量。", "ノイズ関数が計算されるオクターブの数。値を大きくすると、ノイズパターンのディテールが増加します。"),
"Color A": ("颜色 A", "顏色 A", "カラー A"),
"Set a color for the noise to interpolate with Color B.": ("设置噪波与颜色 B 进行插值的颜色。", "設定雜訊與顏色 B 進行插值的顏色。", "ノイズがカラー B と補間するためのカラーを設定します。"),
"Color B": ("颜色 B", "顏色 B", "カラー B"),
"Set a color for the noise to interpolate with Color A.": ("设置噪波与颜色 A 进行插值的颜色。", "設定雜訊與顏色 A 進行插值的顏色。", "ノイズがカラー A と補間するためのカラーを設定します。"),
"Increase/decrease the scale of the noise.": ("增加/减少噪波的缩放。", "增加/減少雜訊的縮放。", "ノイズのスケールを増減します。"),
"Set the gamma correction applied to the input values where values greater/less than 1 will darken/lighten a Layer.": ("设置应用于输入值的伽马校正，大于/小于 1 的值将使图层变暗/变亮。", "設定套用於輸入值的 Gamma 校正，大於/小於 1 的值將使圖層變暗/變亮。", "入力値に適用されるガンマ補正を設定します。1 より大きい/小さい値はレイヤーを暗く/明るくします。"),
"Increase/decrease the speed of the noise.": ("增加/减少噪波的速度。", "增加/減少雜訊的速度。", "ノイズの速度を増減します。"),
"Displacement": ("置换", "置換", "ディスプレースメント"),
"Increase this value to create more turbulent noise.": ("增加此值以创建更多湍流噪波。", "增加此值以建立更多亂流雜訊。", "この値を増やすとより乱流的なノイズが生成されます。"),
"Offset the noise position in x/y.": ("偏移噪波在 x/y 方向的位置。", "偏移雜訊在 x/y 方向的位置。", "ノイズの x/y 位置をオフセットします。"),
"This attribute is automatically connected to the Composition's frame number. Disconnect it for static Noise.": ("此属性会自动连接到合成的帧号。断开连接以获得静态噪波。", "此屬性會自動連接到合成的影格編號。斷開連接以取得靜態雜訊。", "この属性はコンポジションのフレーム番号に自動的に接続されます。静的なノイズにするには接続を解除してください。"),
"Invert RGB colors. Note that this is a post process so is not 'flipping' Color A and Color B \u2013 alpha is not affected.": ("反转 RGB 颜色。请注意，这是后处理操作，不是"翻转"颜色 A 和颜色 B\u2014\u2014Alpha 不受影响。", "反轉 RGB 顏色。請注意，這是後處理操作，不是「翻轉」顏色 A 和顏色 B\u2014\u2014Alpha 不受影響。", "RGB カラーを反転します。これはポストプロセスであり、カラー A とカラー B の「反転」ではありません。アルファには影響しません。"),
"Stapl": ("Stapl", "Stapl", "Stapl"),
"Luka": ("Luka", "Luka", "Luka"),
"Naki": ("Naki", "Naki", "Naki"),
"Nutous": ("Nutous", "Nutous", "Nutous"),
"Poxo": ("Poxo", "Poxo", "Poxo"),
"Stupl": ("Stupl", "Stupl", "Stupl"),
"Pezo": ("Pezo", "Pezo", "Pezo"),
"Blistered Turbulence": ("泡状湍流", "泡狀亂流", "ブリスター乱流"),
"Buya": ("Buya", "Buya", "Buya"),
"Cell": ("Cell", "Cell", "Cell"),
"Cranal": ("Cranal", "Cranal", "Cranal"),
"Dents": ("Dents", "Dents", "Dents"),
"Displaced Turbulence": ("置换湍流", "置換亂流", "ディスプレースメント乱流"),
"Hama": ("Hama", "Hama", "Hama"),
"Mod": ("Mod", "Mod", "Mod"),
"Sema": ("Sema", "Sema", "Sema"),
"Variable Length": ("可变长度", "可變長度", "可変長"),
"RGB Split": ("RGB 分离", "RGB 分離", "RGB 分離"),
"Offset the Red, Green and Blue color channels of a layer.": ("偏移图层的红色、绿色和蓝色通道。", "偏移圖層的紅色、綠色和藍色色彩通道。", "レイヤーの赤、緑、青のカラーチャンネルをオフセットします。"),
"Automatic Padding": ("自动填充", "自動填充", "自動パディング"),
"Lens Radius": ("透镜半径", "透鏡半徑", "レンズ半径"),
"Halftone": ("半色调", "半色調", "ハーフトーン"),
"Legacy Layer - new 'Halftone' available.\nRedraw the layer as a series of circles proportional in size to the brightness of the layer.": ("旧版图层 - 新版"半色调"可用。\n将图层重新绘制为一系列大小与图层亮度成比例的圆形。", "舊版圖層 - 新版「半色調」可用。\n將圖層重新繪製為一系列大小與圖層亮度成比例的圓形。", "レガシーレイヤー - 新しい「ハーフトーン」が利用可能です。\nレイヤーをレイヤーの明るさに比例したサイズの円のシリーズとして再描画します。"),
"Greyscale Mode": ("灰度模式", "灰階模式", "グレースケールモード"),
"Invert Brightness": ("反转亮度", "反轉亮度", "明るさを反転"),
"Softness": ("柔和度", "柔和度", "ソフトネス"),
"Red Multiplier": ("红色乘数", "紅色乘數", "赤の乗数"),
"Green Multiplier": ("绿色乘数", "綠色乘數", "緑の乗数"),
"Blue Multiplier": ("蓝色乘数", "藍色乘數", "青の乗数"),
"Background Color": ("背景颜色", "背景顏色", "背景カラー"),
"Circle Color": ("圆形颜色", "圓形顏色", "円カラー"),
"Redraw the Layer as a series of circles proportional in size to the brightness of the layer.": ("将图层重新绘制为一系列大小与图层亮度成比例的圆形。", "將圖層重新繪製為一系列大小與圖層亮度成比例的圓形。", "レイヤーをレイヤーの明るさに比例したサイズの円のシリーズとして再描画します。"),
"Foreground Color": ("前景颜色", "前景顏色", "前景カラー"),
"Classic": ("经典", "經典", "クラシック"),
"Strokes": ("描边", "描邊", "ストローク"),
"Ink": ("墨水", "墨水", "インク"),
"Quads": ("四边形", "四邊形", "クワッド"),
"Frosted Glass": ("磨砂玻璃", "磨砂玻璃", "すりガラス"),
"Tint": ("色调", "色調", "ティント"),
"Detail Level": ("细节级别", "細節層級", "ディテールレベル"),
"Dithering": ("抖动", "抖色", "ディザリング"),
"Redraw a layer using a reduced color bit depth applying noise to prevent banding.": ("使用降低的颜色位深度重新绘制图层，并应用噪波以防止色带。", "使用降低的顏色位元深度重新繪製圖層，並套用雜訊以防止色帶。", "色の深度を減らしてレイヤーを再描画し、バンディングを防ぐためにノイズを適用します。"),
"Contrast": ("对比度", "對比度", "コントラスト"),
"Use Color Palette": ("使用调色板", "使用調色盤", "カラーパレットを使用"),
"Greyscale": ("灰度", "灰階", "グレースケール"),
"White Noise": ("白噪声", "白雜訊", "ホワイトノイズ"),
"Bricks": ("砖块", "磚塊", "ブリック"),
"Stripes": ("条纹", "條紋", "ストライプ"),
"Bubbles": ("气泡", "氣泡", "バブル"),
"Virus": ("病毒", "病毒", "ウイルス"),
"Blue Noise": ("蓝噪声", "藍雜訊", "ブルーノイズ"),
"Bayer": ("Bayer", "Bayer", "Bayer"),
"Color Palette": ("调色板", "調色盤", "カラーパレット"),
"Pixel Sorting": ("像素排序", "像素排序", "ピクセルソーティング"),
"Reorder a Layer's pixels by sorting them according to various attributes such as brightness.": ("根据各种属性（如亮度）对图层的像素进行重新排序。", "根據各種屬性（如亮度）對圖層的像素進行重新排序。", "明るさなどのさまざまな属性に基づいてレイヤーのピクセルを並べ替えます。"),
"Sort Mode": ("排序模式", "排序模式", "ソートモード"),
"Detail": ("细节", "細節", "ディテール"),
"Reverse Sort": ("反向排序", "反向排序", "逆順ソート"),
"Pixel Masks": ("像素蒙版", "像素遮罩", "ピクセルマスク"),
"Input Shapes used as masks on Pixel Sorting will be set to Wireframe mode.": ("在像素排序中用作蒙版的输入形状将被设置为线框模式。", "在像素排序中用作遮罩的輸入形狀將被設定為線框模式。", "ピクセルソーティングでマスクとして使用される入力シェイプはワイヤーフレームモードに設定されます。"),
"Extra Contrast": ("额外对比度", "額外對比度", "追加コントラスト"),
"Sample a line of pixels and extend them to create a striped pattern.": ("采样一行像素并扩展它们以创建条纹图案。", "取樣一行像素並擴展它們以建立條紋圖案。", "ピクセルの一行をサンプリングして拡張し、ストライプパターンを作成します。"),
"Stripes Angle": ("条纹角度", "條紋角度", "ストライプ角度"),
"Angle Offset": ("角度偏移", "角度偏移", "角度オフセット"),
"Show Sampler": ("显示采样器", "顯示取樣器", "サンプラーを表示"),
"Clipping Range": ("裁剪范围", "裁剪範圍", "クリッピング範囲"),
"Pixelate": ("像素化", "像素化", "ピクセル化"),
"Redraw your layer using blocks of uniform color. The 'pixels' can have various different shapes.": ("使用均匀颜色的色块重新绘制图层。"像素"可以具有各种不同的形状。", "使用均勻顏色的色塊重新繪製圖層。「像素」可以具有各種不同的形狀。", "均一カラーのブロックを使用してレイヤーを再描画します。「ピクセル」にはさまざまな形状を使用できます。"),
"Invert Leading Diagonal": ("反转前导对角线", "反轉前導對角線", "前方対角線を反転"),
"Pixel Size": ("像素大小", "像素大小", "ピクセルサイズ"),
"Pixel Scale": ("像素缩放", "像素縮放", "ピクセルスケール"),
"Border Color": ("边框颜色", "邊框顏色", "ボーダーカラー"),
"Pixel Shape": ("像素形状", "像素形狀", "ピクセルシェイプ"),
"Squared Triangle": ("方形三角形", "方形三角形", "正方三角形"),
"Hexagon Triangle": ("六边形三角形", "六邊形三角形", "六角三角形"),
"Scan Lines": ("扫描线", "掃描線", "スキャンライン"),
"Mimic the effect of a CRT monitor.": ("模拟 CRT 显示器的效果。", "模擬 CRT 顯示器的效果。", "CRT モニターの効果を模倣します。"),
"Use Scan Lines Resolution": ("使用扫描线分辨率", "使用掃描線解析度", "スキャンライン解像度を使用"),
"Line Count": ("线条数量", "線條數量", "ライン数"),
"Line Feather": ("线条羽化", "線條羽化", "ラインのフェザー"),
"Line Width": ("线宽", "線寬", "ライン幅"),
"Line Opacity": ("线条不透明度", "線條不透明度", "ラインの不透明度"),
"Line Color": ("线条颜色", "線條顏色", "ラインカラー"),
"Line Rotation": ("线条旋转", "線條旋轉", "ラインの回転"),
"Interlace Frame Interval": ("隔行帧间隔", "交錯影格間隔", "インターレースフレーム間隔"),
"Use Shadow Mask": ("使用阴影遮罩", "使用陰影遮罩", "シャドウマスクを使用"),
"Brightness Boost": ("亮度增强", "亮度增強", "明るさブースト"),
"Shadow Mask Opacity": ("阴影遮罩不透明度", "陰影遮罩不透明度", "シャドウマスクの不透明度"),
"Shadow Mask": ("阴影遮罩", "陰影遮罩", "シャドウマスク"),
"Kitaoka Filter": ("Kitaoka 滤镜", "Kitaoka 濾鏡", "Kitaoka フィルター"),
"Makes nice looking waves.": ("创建美观的波形。", "建立美觀的波形。", "美しい波形を作成します。"),
"Line Mode": ("线条模式", "線條模式", "ラインモード"),
"Lines Count": ("线条数量", "線條數量", "ライン数"),
"Line Size": ("线条大小", "線條大小", "ラインサイズ"),
"Top Color": ("顶部颜色", "頂部顏色", "上部カラー"),
"Middle Color": ("中间颜色", "中間顏色", "中間カラー"),
"Bottom Color": ("底部颜色", "底部顏色", "下部カラー"),
"Threshold Floor": ("阈值下限", "閾值下限", "閾値フロア"),
"Threshold Contrast": ("阈值对比度", "閾值對比度", "閾値コントラスト"),
"Lowest Channel": ("最低通道", "最低色版", "最低チャンネル"),
"Middle Channel": ("中间通道", "中間色版", "中間チャンネル"),
"Top Channel": ("最高通道", "最高色版", "最高チャンネル"),
"Reverse a shape along a centre line to create a reflection.": ("沿中心线翻转形状以创建反射。", "沿中心線翻轉形狀以建立反射。", "中心線に沿ってシェイプを反転させ、反射を作成します。"),
"Persist Opacity": ("保持不透明度", "保持不透明度", "不透明度を維持"),
"Distortion": ("扭曲", "扭曲", "ディストーション"),
"Distort a layer based on a shader (such as Noise).": ("基于着色器（如噪波）扭曲图层。", "基於著色器（如雜訊）扭曲圖層。", "シェーダー（ノイズなど）に基づいてレイヤーを歪ませます。"),
"Use Single Direction": ("使用单一方向", "使用單一方向", "単一方向を使用"),
"Direction Angle": ("方向角度", "方向角度", "方向角度"),
"Input Shader": ("输入着色器", "輸入著色器", "入力シェーダー"),
"Preview Opacity": ("预览不透明度", "預覽不透明度", "プレビュー不透明度"),
"Distortion Offset": ("扭曲偏移", "扭曲偏移", "ディストーションオフセット"),
"Show Preview": ("显示预览", "顯示預覽", "プレビューを表示"),
"Curve Interpolation": ("曲线插值", "曲線插值", "カーブ補間"),
"Lens": ("透镜", "透鏡", "レンズ"),
"Directional": ("方向性", "方向性", "方向性"),
"Warp": ("弯曲", "彎曲", "ワープ"),
"Sine Wave": ("正弦波", "正弦波", "サイン波"),
"Distort Edges": ("扭曲边缘", "扭曲邊緣", "エッジの歪み"),
"Distort only the edges of a layer using a shader.": ("仅使用着色器扭曲图层的边缘。", "僅使用著色器扭曲圖層的邊緣。", "シェーダーを使用してレイヤーのエッジのみを歪ませます。"),
"Border": ("边框", "邊框", "ボーダー"),
"Edge Sharpness": ("边缘锐度", "邊緣銳度", "エッジのシャープネス"),
"Inward": ("向内", "向內", "内側"),
"Chromatic Displacement": ("色差置换", "色差置換", "クロマティックディスプレースメント"),
"Apply independent RGB channel displacement based on a height map shader for chromatic aberration and refraction effects.": ("基于高度图着色器应用独立的 RGB 通道置换，以产生色差和折射效果。", "基於高度圖著色器套用獨立的 RGB 色彩通道置換，以產生色差和折射效果。", "ハイトマップシェーダーに基づいて独立した RGB チャンネルディスプレースメントを適用し、色収差と屈折効果を生成します。"),
"Red Angle": ("红色角度", "紅色角度", "赤の角度"),
"Red Distance": ("红色距离", "紅色距離", "赤の距離"),
"Green Angle": ("绿色角度", "綠色角度", "緑の角度"),
"Green Distance": ("绿色距离", "綠色距離", "緑の距離"),
"Blue Angle": ("蓝色角度", "藍色角度", "青の角度"),
"Blue Distance": ("蓝色距离", "藍色距離", "青の距離"),
"Displacement Mode": ("置换模式", "置換模式", "ディスプレースメントモード"),
"Softening": ("柔化", "柔化", "ソフトニング"),
"Displacement Utility": ("置换工具", "置換工具", "ディスプレースメントユーティリティ"),
"Color Info": ("颜色信息", "顏色資訊", "カラー情報"),
"Get the Hue, Saturation or Value of a given color.": ("获取给定颜色的色相、饱和度或明度。", "取得給定顏色的色相、飽和度或明度。", "指定したカラーの色相、彩度、明度を取得します。"),
"HSV Color": ("HSV 颜色", "HSV 顏色", "HSV カラー"),
"Create a Color from Hue Saturation and Value.": ("从色相、饱和度和明度创建颜色。", "從色相、飽和度和明度建立顏色。", "色相、彩度、明度からカラーを作成します。"),
"Output Color": ("输出颜色", "輸出顏色", "出力カラー"),
"Input Color": ("输入颜色", "輸入顏色", "入力カラー"),
"Sub-Mesh Bounding Box": ("子网格边界框", "子網格邊界框", "サブメッシュバウンディングボックス"),
"Create rectangles using the bounding boxes of Sub-Meshes (Duplicator, Text, SVG etc.).": ("使用子网格的边界框创建矩形（复制器、文本、SVG 等）。", "使用子網格的邊界框建立矩形（複製器、文字、SVG 等）。", "サブメッシュ（デュプリケーター、テキスト、SVG など）のバウンディングボックスを使用して矩形を作成します。"),
"Limit the bounding boxes to specific indices. Comma separated values (e.g 1,2)\nand sequences (e.g 1:3) can be used.": ("将边界框限制为特定索引。可以使用逗号分隔的值（如 1,2）\n和序列（如 1:3）。", "將邊界框限制為特定索引。可以使用逗號分隔的值（如 1,2）\n和序列（如 1:3）。", "バウンディングボックスを特定のインデックスに制限します。カンマ区切りの値（例: 1,2）\nおよびシーケンス（例: 1:3）を使用できます。"),
"Sequences Keep Gaps": ("序列保留间隙", "序列保留間隙", "シーケンスのギャップを維持"),
"When using sequences in the Specific Indices attribute (e.g 0:2),\nuse this mode to keep the gaps between bounding boxes.": ("在"特定索引"属性中使用序列时（如 0:2），\n使用此模式保持边界框之间的间隙。", "在「特定索引」屬性中使用序列時（如 0:2），\n使用此模式保持邊界框之間的間隙。", "「特定インデックス」属性でシーケンスを使用する場合（例: 0:2）、\nバウンディングボックス間のギャップを維持するにはこのモードを使用します。"),
"Segment Path": ("分段路径", "分段路徑", "セグメントパス"),
"Segment Paths into smaller sections.": ("将路径分段为更小的部分。", "將路徑分段為更小的部分。", "パスを小さなセクションに分割します。"),
"Extension Mode": ("延伸模式", "延伸模式", "延長モード"),
"Relative Counts": ("相对计数", "相對計數", "相対カウント"),
"The longest contour will be split 'count' times with other contours\nbeing split by a relative count depending on their length.": ("最长的轮廓将被分割"计数"次，其他轮廓\n将根据其长度按相对计数进行分割。", "最長的輪廓將被分割「計數」次，其他輪廓\n將根據其長度按相對計數進行分割。", "最長の輪郭が「カウント」回分割され、他の輪郭は\nその長さに応じた相対カウントで分割されます。"),
"Extend": ("延伸", "延伸", "延長"),
"Extend the cut paths by this distance (you can also use this mode without cutting the paths).": ("按此距离延伸切割路径（您也可以在不切割路径的情况下使用此模式）。", "按此距離延伸切割路徑（您也可以在不切割路徑的情況下使用此模式）。", "この距離だけカットパスを延長します（パスをカットせずにこのモードを使用することもできます）。"),
"Number of cuts": ("切割次数", "切割次數", "カット数"),
"Automatic cuts": ("自动切割", "自動切割", "自動カット"),
"Do not cut": ("不切割", "不切割", "カットしない"),
"Forge Dynamics": ("Forge 动力学", "Forge 動力學", "Forge ダイナミクス"),
"A 2d physics engine for rigid body collisions.": ("用于刚体碰撞的 2D 物理引擎。", "用於剛體碰撞的 2D 物理引擎。", "剛体の衝突シミュレーション用 2D 物理エンジン。"),
"Ground Mode": ("地面模式", "地面模式", "地面モード"),
"World Scale": ("世界缩放", "世界縮放", "ワールドスケール"),
"Friction": ("摩擦力", "摩擦力", "摩擦"),
"Bounce": ("弹力", "彈力", "バウンス"),
"Density": ("密度", "密度", "密度"),
"Body Type": ("物体类型", "物體類型", "ボディタイプ"),
"Collision Shape Type": ("碰撞形状类型", "碰撞形狀類型", "コリジョンシェイプタイプ"),
"Box: A Box Collision Shape\nCircle: A Circular Collision Shape\nSimple Polygon: A 'best fit' convex polygon with up to 8 sides will be created to represent the shape.\nComplex Polygon: Accurate collision for concave polygons - automatically triangulated for precise collision detection.\nChain: A **still** one sided collision object that represents a chain of points. This is suitable for open paths.\nChain (reversed): As above but collisions happen on the other side of the shape.\nSoft Body: Deformable physics body made from spring-connected particles. Supports complex polygons with holes.": ("Box：盒形碰撞形状\nCircle：圆形碰撞形状\nSimple Polygon：将创建最多 8 条边的"最佳拟合"凸多边形来表示形状。\nComplex Polygon：凹多边形的精确碰撞 - 自动三角化以实现精确的碰撞检测。\nChain：表示点链的**静止**单面碰撞对象。适用于开放路径。\nChain (reversed)：与上述相同，但碰撞发生在形状的另一面。\nSoft Body：由弹簧连接的粒子构成的可变形物理体。支持带孔的复杂多边形。", "Box：盒形碰撞形狀\nCircle：圓形碰撞形狀\nSimple Polygon：將建立最多 8 條邊的「最佳擬合」凸多邊形來表示形狀。\nComplex Polygon：凹多邊形的精確碰撞 - 自動三角化以實現精確的碰撞偵測。\nChain：表示點鏈的**靜止**單面碰撞物件。適用於開放路徑。\nChain (reversed)：與上述相同，但碰撞發生在形狀的另一面。\nSoft Body：由彈簧連接的粒子構成的可變形物理體。支援帶孔的複雜多邊形。", "Box: ボックスコリジョンシェイプ\nCircle: 円形コリジョンシェイプ\nSimple Polygon: シェイプを表す最大 8 辺の「ベストフィット」凸多角形が作成されます。\nComplex Polygon: 凹多角形の正確なコリジョン - 精密なコリジョン検出のために自動三角形分割されます。\nChain: 点の連鎖を表す**静的**な片面コリジョンオブジェクトです。オープンパスに適しています。\nChain (reversed): 上記と同じですが、シェイプの反対側でコリジョンが発生します。\nSoft Body: スプリング接続されたパーティクルから構成される変形可能な物理ボディ。穴のある複雑な多角形をサポートします。"),
"Starts Asleep": ("初始休眠", "初始休眠", "初期スリープ状態"),
"Allows Sleep": ("允许休眠", "允許休眠", "スリープを許可"),
"Starting Velocity": ("初始速度", "初始速度", "初速度"),
"Starting Rotational Velocity": ("初始旋转速度", "初始旋轉速度", "初期回転速度"),
"Position Damping": ("位置阻尼", "位置阻尼", "位置ダンピング"),
"Rotation Damping": ("旋转阻尼", "旋轉阻尼", "回転ダンピング"),
"Gravity Scale": ("重力缩放", "重力縮放", "重力スケール"),
"Auxiliary": ("辅助", "輔助", "補助"),
"Constrain Hybrids": ("约束混合体", "約束混合體", "ハイブリッドを拘束"),
"Hybrid Frequency": ("混合频率", "混合頻率", "ハイブリッド周波数"),
"Hybrid Damping": ("混合阻尼", "混合阻尼", "ハイブリッドダンピング"),
"Sensor": ("传感器", "感應器", "センサー"),
"Collision Groups": ("碰撞组", "碰撞群組", "コリジョングループ"),
"Comma-separated group names this body belongs to (e.g., 'terrain,solid'). Leave empty to belong to all groups. Use 'none' to belong to no groups.": ("此物体所属的组名称，以逗号分隔（如 'terrain,solid'）。留空则属于所有组。使用 'none' 表示不属于任何组。", "此物體所屬的群組名稱，以逗號分隔（如 'terrain,solid'）。留空則屬於所有群組。使用 'none' 表示不屬於任何群組。", "このボディが属するグループ名をカンマ区切りで指定します（例: 'terrain,solid'）。空欄にするとすべてのグループに属します。'none' を使用するとどのグループにも属しません。"),
"Collides With": ("碰撞对象", "碰撞對象", "衝突対象"),
"Comma-separated group names this body collides with (e.g., 'terrain,solid'). Leave empty to collide with all groups. Use 'none' to collide with nothing.": ("此物体与之碰撞的组名称，以逗号分隔（如 'terrain,solid'）。留空则与所有组碰撞。使用 'none' 表示不与任何物体碰撞。", "此物體與之碰撞的群組名稱，以逗號分隔（如 'terrain,solid'）。留空則與所有群組碰撞。使用 'none' 表示不與任何物體碰撞。", "このボディが衝突するグループ名をカンマ区切りで指定します（例: 'terrain,solid'）。空欄にするとすべてのグループと衝突します。'none' を使用すると何とも衝突しません。"),
"Max Fixtures Per Body": ("每物体最大固定装置数", "每物體最大固定裝置數", "ボディあたりの最大フィクスチャ数"),
"Maximum number of triangular fixtures to create for Complex Polygon shapes. Higher values give more accurate collision for highly detailed shapes, at the cost of performance.": ("为复杂多边形形状创建的三角形固定装置的最大数量。较高的值为高细节形状提供更精确的碰撞，但会降低性能。", "為複雜多邊形形狀建立的三角形固定裝置的最大數量。較高的值為高細節形狀提供更精確的碰撞，但會降低效能。", "Complex Polygon シェイプに作成する三角形フィクスチャの最大数。値が大きいほど詳細なシェイプのコリジョンが正確になりますが、パフォーマンスが低下します。"),
"Spring frequency in Hz (vibrations per second). Higher values make the soft body stiffer.": ("弹簧频率（赫兹，每秒振动次数）。较高的值使软体更坚硬。", "彈簧頻率（赫茲，每秒振動次數）。較高的值使軟體更堅硬。", "スプリング周波数（Hz、毎秒の振動数）。値が大きいほどソフトボディが硬くなります。"),
"Damping ratio. Controls how quickly oscillations settle.": ("阻尼比。控制振荡平息的速度。", "阻尼比。控制振盪平息的速度。", "ダンピング比。振動が収まる速さを制御します。"),
"Pressure": ("压力", "壓力", "圧力"),
"Internal pressure for volume preservation. Higher values push particles outward to maintain the body's shape.": ("用于保持体积的内部压力。较高的值将粒子向外推以维持物体的形状。", "用於保持體積的內部壓力。較高的值將粒子向外推以維持物體的形狀。", "体積を保持するための内部圧力。値が大きいほどパーティクルを外側に押し出してボディの形状を維持します。"),
"Shape Matching": ("形状匹配", "形狀匹配", "シェイプマッチング"),
"Strength of shape preservation. Gently pulls particles toward their original relative positions to help restore the body's shape after deformation.": ("形状保持的强度。轻柔地将粒子拉向其原始相对位置，以帮助物体在变形后恢复形状。", "形狀保持的強度。輕柔地將粒子拉向其原始相對位置，以幫助物體在變形後恢復形狀。", "シェイプ保持の強度。パーティクルを元の相対位置に穏やかに引き戻し、変形後のボディの形状復元を助けます。"),
"Particle Radius": ("粒子半径", "粒子半徑", "パーティクル半径"),
"Size of the particles that are used to simulate the soft body. Smaller values give finer detail but more particles - smaller values are much harder to control.": ("用于模拟软体的粒子大小。较小的值提供更精细的细节但粒子更多——较小的值更难控制。", "用於模擬軟體的粒子大小。較小的值提供更精細的細節但粒子更多——較小的值更難控制。", "ソフトボディをシミュレートするパーティクルのサイズ。値が小さいほど細かいディテールが得られますが、パーティクル数が増え、制御が難しくなります。"),
"Max Stretch": ("最大拉伸", "最大拉伸", "最大ストレッチ"),
"Maximum allowed stretch of spring connections as a multiple of rest length. Lower values maintain shape better under impact but may be less flexible. 2.0 = springs can stretch to double their rest length.": ("弹簧连接允许的最大拉伸倍数（相对于静止长度）。较低的值在冲击下更好地保持形状，但可能不够灵活。2.0 = 弹簧可以拉伸到静止长度的两倍。", "彈簧連接允許的最大拉伸倍數（相對於靜止長度）。較低的值在衝擊下更好地保持形狀，但可能不夠靈活。2.0 = 彈簧可以拉伸到靜止長度的兩倍。", "スプリング接続の最大許容ストレッチ（静止長の倍数）。値が低いほど衝撃時の形状維持に優れますが、柔軟性が低下する可能性があります。2.0 = スプリングが静止長の 2 倍まで伸びることができます。"),
"Live Forever": ("永久存活", "永久存活", "永続"),
"Use Maximum Velocity": ("使用最大速度", "使用最大速度", "最大速度を使用"),
"Maximum Velocity": ("最大速度", "最大速度", "最大速度"),
"Use Maximum Rotational Velocity": ("使用最大旋转速度", "使用最大旋轉速度", "最大回転速度を使用"),
"Maximum Rotational Velocity": ("最大旋转速度", "最大旋轉速度", "最大回転速度"),
"Initial Position Strength": ("初始位置强度", "初始位置強度", "初期位置強度"),
"Initial Rotation Strength": ("初始旋转强度", "初始旋轉強度", "初期回転強度"),
"Collision Events": ("碰撞事件", "碰撞事件", "コリジョンイベント"),
"Bodies": ("物体", "物體", "ボディ"),
"Use File Cache": ("使用文件缓存", "使用檔案快取", "ファイルキャッシュを使用"),
"Cache File Path": ("缓存文件路径", "快取檔案路徑", "キャッシュファイルパス"),
"Cache Offset": ("缓存偏移", "快取偏移", "キャッシュオフセット"),
"Time Step": ("时间步长", "時間步長", "タイムステップ"),
"Composition Bottom": ("合成底部", "合成底部", "コンポジション下部"),
"Composition Edges": ("合成边缘", "合成邊緣", "コンポジションエッジ"),
"Text Lines/ Duplicator": ("文本行/复制器", "文字行/複製器", "テキスト行/デュプリケーター"),
"Text Words": ("文本单词", "文字單詞", "テキスト単語"),
"Text Characters": ("文本字符", "文字字元", "テキスト文字"),
"Kinematic": ("运动学", "運動學", "キネマティック"),
"Kinematic Hybrid": ("运动学混合", "運動學混合", "キネマティックハイブリッド"),
"Simple Polygon": ("简单多边形", "簡單多邊形", "単純ポリゴン"),
"Chain": ("链", "鏈", "チェーン"),
"Chain (Reversed)": ("链（反向）", "鏈（反向）", "チェーン（反転）"),
"Complex Polygon": ("复杂多边形", "複雜多邊形", "複合ポリゴン"),
"Soft Body": ("软体", "軟體", "ソフトボディ"),
"Initial State": ("初始状态", "初始狀態", "初期状態"),
"Color Collision Event": ("颜色碰撞事件", "顏色碰撞事件", "カラーコリジョンイベント"),
"Change the color of Forge Dynamics bodies when they collide.": ("当 Forge 动力学物体发生碰撞时更改其颜色。", "當 Forge 動力學物體發生碰撞時變更其顏色。", "Forge ダイナミクスのボディが衝突した時にカラーを変更します。"),
"Fade Changes": ("淡入淡出变化", "淡入淡出變化", "フェード変化"),
"Fade Time": ("淡入淡出时间", "淡入淡出時間", "フェード時間"),
"How long it takes the color to fade, in seconds.": ("颜色淡出所需的时间（秒）。", "顏色淡出所需的時間（秒）。", "カラーがフェードするのにかかる時間（秒）。"),
"Fade to Third Color": ("淡出至第三颜色", "淡出至第三顏色", "第三カラーにフェード"),
"Instead of fading back to the original color, the shape will fade to a third color.": ("形状不会淡出回到原始颜色，而是淡出至第三颜色。", "形狀不會淡出回到原始顏色，而是淡出至第三顏色。", "元のカラーに戻る代わりに、シェイプが第三のカラーにフェードします。"),
"Third Color": ("第三颜色", "第三顏色", "第三カラー"),
"Third Shaders": ("第三着色器", "第三著色器", "第三シェーダー"),
"Use Collision Index": ("使用碰撞索引", "使用碰撞索引", "コリジョンインデックスを使用"),
"The collision number will be used instead of the body index to get unique values for each collision.\nUse this mode when you want each collision to be different, rather than for each body to be different.": ("将使用碰撞编号代替物体索引来获取每次碰撞的唯一值。\n当您希望每次碰撞不同而非每个物体不同时，请使用此模式。", "將使用碰撞編號代替物體索引來取得每次碰撞的唯一值。\n當您希望每次碰撞不同而非每個物體不同時，請使用此模式。", "ボディインデックスの代わりにコリジョン番号を使用して、各コリジョンの一意の値を取得します。\n各ボディではなく各コリジョンを異なるものにしたい場合にこのモードを使用します。"),
"Specific Collisions": ("特定碰撞", "特定碰撞", "特定コリジョン"),
"When on, the event will only be triggered for specific collisions. These can be set in the Collision Numbers box.": ("开启时，事件仅在特定碰撞时触发。可在"碰撞编号"框中设置。", "開啟時，事件僅在特定碰撞時觸發。可在「碰撞編號」框中設定。", "オンにすると、イベントは特定のコリジョンでのみトリガーされます。コリジョン番号ボックスで設定できます。"),
"Collision Numbers": ("碰撞编号", "碰撞編號", "コリジョン番号"),
"The collisions you want the event to happen for. E.g '0,2' will mean the event is triggered for the first and third collision.": ("您希望事件发生的碰撞。例如 '0,2' 表示事件在第一次和第三次碰撞时触发。", "您希望事件發生的碰撞。例如 '0,2' 表示事件在第一次和第三次碰撞時觸發。", "イベントを発生させたいコリジョン。例えば '0,2' は最初と 3 番目のコリジョンでイベントがトリガーされることを意味します。"),
"Fill and Stroke": ("填充和描边", "填充和描邊", "塗りとストローク"),
"Measure Text": ("测量文本", "測量文字", "テキストを計測"),
"Measure the size of a text string, given a font and font size.": ("根据字体和字号测量文本字符串的大小。", "根據字型和字型大小測量文字字串的大小。", "フォントとフォントサイズに基づいてテキスト文字列のサイズを計測します。"),
"Font Axis": ("字体轴", "字型軸", "フォント軸"),
"Out Text Size": ("输出文本大小", "輸出文字大小", "出力テキストサイズ"),
"The size of the resulting text, this does not account for metrics such as line spacing.": ("结果文本的大小，不包括行间距等度量指标。", "結果文字的大小，不包括行距等度量指標。", "結果テキストのサイズ。行間などのメトリクスは含まれません。"),
"Out Font Scale": ("输出字体缩放", "輸出字型縮放", "出力フォントスケール"),
"This is the resulting scale factor of 'Shrink to Fit Text Box' being used on a Text Shape. The advantage is that you don't need a Text Shape to create this factor.": ("这是在文本形状上使用"缩小以适配文本框"的结果缩放因子。其优点是无需文本形状即可创建此因子。", "這是在文字形狀上使用「縮小以適配文字框」的結果縮放因子。其優點是無需文字形狀即可建立此因子。", "テキストシェイプで「テキストボックスに縮小して合わせる」を使用した場合のスケール係数です。テキストシェイプがなくてもこの係数を作成できる利点があります。"),
"Sticky Collision Event": ("粘附碰撞事件", "黏附碰撞事件", "スティッキーコリジョンイベント"),
"Stick Forge Dynamics bodies to each other when they collide.": ("当 Forge 动力学物体发生碰撞时使其粘附在一起。", "當 Forge 動力學物體發生碰撞時使其黏附在一起。", "Forge ダイナミクスのボディが衝突した時に互いに貼り付けます。"),
"Breakable": ("可断裂", "可斷裂", "破壊可能"),
"Directional Force": ("方向力", "方向力", "方向力"),
"Rotational Force": ("旋转力", "旋轉力", "回転力"),
"Impulse Collision Event": ("冲量碰撞事件", "衝量碰撞事件", "インパルスコリジョンイベント"),
"Add additional forces to Forge Dynamics bodies when they collide.": ("当 Forge 动力学物体发生碰撞时为其添加额外的力。", "當 Forge 動力學物體發生碰撞時為其新增額外的力。", "Forge ダイナミクスのボディが衝突した時に追加の力を加えます。"),
"Use Bounce Direction": ("使用反弹方向", "使用反彈方向", "バウンス方向を使用"),
"Bounce Factor": ("反弹系数", "反彈係數", "バウンス係数"),
"Rotational Power": ("旋转力度", "旋轉力度", "回転パワー"),
"Body Settings Collision Event": ("物体设置碰撞事件", "物體設定碰撞事件", "ボディ設定コリジョンイベント"),
"Update the settings of a Forge Dynamics body when it collides with another.": ("当 Forge 动力学物体与另一个物体碰撞时更新其设置。", "當 Forge 動力學物體與另一個物體碰撞時更新其設定。", "Forge ダイナミクスのボディが別のボディと衝突した時にその設定を更新します。"),
"Visibility Collision Event": ("可见性碰撞事件", "可見性碰撞事件", "ビジビリティコリジョンイベント"),
"Affect the Visibility or Opacity of Forge Dynamics bodies when they collide.": ("当 Forge 动力学物体发生碰撞时影响其可见性或不透明度。", "當 Forge 動力學物體發生碰撞時影響其可見性或不透明度。", "Forge ダイナミクスのボディが衝突した時にその表示/不透明度に影響を与えます。"),
"Visibility After Collision": ("碰撞后的可见性", "碰撞後的可見性", "コリジョン後のビジビリティ"),
"Bridge Constraint": ("桥接约束", "橋接約束", "ブリッジコンストレイント"),
"Connect Shapes together to form chains or bridge structures in a Forge Dynamics simulation.": ("在 Forge 动力学模拟中将形状连接在一起以形成链或桥结构。", "在 Forge 動力學模擬中將形狀連接在一起以形成鏈或橋結構。", "Forge ダイナミクスシミュレーションでシェイプを接続してチェーンやブリッジ構造を形成します。"),
"Frequency (Hz)": ("频率（Hz）", "頻率（Hz）", "周波数（Hz）"),
"Damping Ratio": ("阻尼比", "阻尼比", "ダンピング比"),
"Breaking Force": ("断裂力", "斷裂力", "破壊力"),
"Breaking Mode": ("断裂模式", "斷裂模式", "破壊モード"),
"Stretch Limit": ("拉伸限制", "拉伸限制", "ストレッチ限界"),
"Distance multiplier before breaking (for Distance mode). A value of 2.0 means the constraint breaks when stretched to twice the rest length.": ("断裂前的距离倍数（用于距离模式）。值为 2.0 表示拉伸到静止长度的两倍时约束断裂。", "斷裂前的距離倍數（用於距離模式）。值為 2.0 表示拉伸到靜止長度的兩倍時約束斷裂。", "破壊前の距離倍数（距離モード用）。値が 2.0 の場合、静止長の 2 倍に伸びるとコンストレイントが破壊されます。"),
"Breaking Duration": ("断裂持续时间", "斷裂持續時間", "破壊持続時間"),
"Number of consecutive frames under stress before breaking (for Time mode).": ("断裂前受力的连续帧数（用于时间模式）。", "斷裂前受力的連續影格數（用於時間模式）。", "破壊前にストレスを受ける連続フレーム数（時間モード用）。"),
"Stress Threshold": ("应力阈值", "應力閾值", "ストレス閾値"),
"Stress level required to count towards breaking duration (for Time mode) as a percentage of breaking force.": ("计入断裂持续时间所需的应力水平（用于时间模式），以断裂力的百分比表示。", "計入斷裂持續時間所需的應力水準（用於時間模式），以斷裂力的百分比表示。", "破壊持続時間にカウントするために必要なストレスレベル（時間モード用）。破壊力のパーセンテージで表します。"),
"Report Stress": ("报告应力", "報告應力", "ストレスを報告"),
"Enable stress level reporting for debugging and visual feedback.": ("启用应力级别报告，用于调试和视觉反馈。", "啟用應力級別報告，用於除錯和視覺回饋。", "デバッグとビジュアルフィードバック用にストレスレベルの報告を有効にします。"),
"Pinned Index": ("固定索引", "固定索引", "ピン留めインデックス"),
"Rotational Limits": ("旋转限制", "旋轉限制", "回転制限"),
"Force": ("力", "力", "フォース"),
"Impulse": ("冲量", "衝量", "インパルス"),
"Pin Constraint": ("固定约束", "固定約束", "ピンコンストレイント"),
"Pin Shapes to their original position in a Forge Dynamics simulation but allow them to rotate.": ("在 Forge 动力学模拟中将形状固定到其原始位置，但允许旋转。", "在 Forge 動力學模擬中將形狀固定到其原始位置，但允許旋轉。", "Forge ダイナミクスシミュレーションでシェイプを元の位置にピン留めしますが、回転は許可します。"),
"Motor": ("马达", "馬達", "モーター"),
"Motor Speed": ("马达速度", "馬達速度", "モーター速度"),
"Maximum Torque": ("最大扭矩", "最大扭矩", "最大トルク"),
"Tension": ("张力", "張力", "テンション"),
"Joint flexibility. When 0, the pin is rigid (default behavior - bodies can rotate freely around the pin point). When greater than 0, the joint becomes a flexible weld that resists rotation with spring-like behavior.": ("关节灵活性。当为 0 时，固定点是刚性的（默认行为 - 物体可以绕固定点自由旋转）。当大于 0 时，关节变为弹性焊接，以弹簧式行为抵抗旋转。", "關節靈活性。當為 0 時，固定點是剛性的（預設行為 - 物體可以繞固定點自由旋轉）。當大於 0 時，關節變為彈性焊接，以彈簧式行為抵抗旋轉。", "ジョイントの柔軟性。0 の場合、ピンは剛体です（デフォルト動作 - ボディはピンポイントを中心に自由に回転できます）。0 より大きい場合、ジョイントはスプリングのような動作で回転に抵抗する柔軟な溶接になります。"),
"Reduces oscillation in flexible joints. 0 = no damping (springy), 1 = critical damping (smooth, no bounce).": ("减少柔性关节的振荡。0 = 无阻尼（有弹性），1 = 临界阻尼（平滑，无弹跳）。", "減少柔性關節的振盪。0 = 無阻尼（有彈性），1 = 臨界阻尼（平滑，無彈跳）。", "柔軟なジョイントの振動を軽減します。0 = ダンピングなし（弾性あり）、1 = 臨界ダンピング（スムーズ、バウンスなし）。"),
"Multiplies the Rotational Limits to determine the extra allowance beyond each limit before breaking.": ("将旋转限制相乘以确定断裂前超过每个限制的额外余量。", "將旋轉限制相乘以確定斷裂前超過每個限制的額外餘量。", "回転制限に乗算して、破壊前の各制限を超える追加許容範囲を決定します。"),
"Distance Constraint": ("距离约束", "距離約束", "距離コンストレイント"),
"Constrain Shapes to their original positions in a Forge Dynamics simulation.": ("在 Forge 动力学模拟中将形状约束到其原始位置。", "在 Forge 動力學模擬中將形狀約束到其原始位置。", "Forge ダイナミクスシミュレーションでシェイプを元の位置に拘束します。"),
"Rest Length": ("静止长度", "靜止長度", "静止長"),
"Minimum Length": ("最小长度", "最小長度", "最小長"),
"Maximum Length": ("最大长度", "最大長度", "最大長"),
"Spring Position": ("弹簧位置", "彈簧位置", "スプリング位置"),
"If there's no connection the initial position will be used as the spring's position.": ("如果没有连接，则初始位置将用作弹簧的位置。", "如果沒有連接，則初始位置將用作彈簧的位置。", "接続がない場合、初期位置がスプリングの位置として使用されます。"),
"Connect or add Falloffs to determine a Field's strength based on position.": ("连接或添加衰减以根据位置确定场的强度。", "連接或新增衰減以根據位置確定場的強度。", "フォールオフを接続または追加して、位置に基づいてフィールドの強度を決定します。"),
"Affects Groups": ("影响组", "影響群組", "影響グループ"),
"Comma-separated collision groups this field affects. Use 'none' to affect no groups.": ("此场影响的碰撞组，以逗号分隔。使用 'none' 表示不影响任何组。", "此場影響的碰撞群組，以逗號分隔。使用 'none' 表示不影響任何群組。", "このフィールドが影響するコリジョングループをカンマ区切りで指定します。'none' を使用するとどのグループにも影響しません。"),
"Direction Field": ("方向场", "方向場", "方向フィールド"),
"Creates a directional force in a Forge Dynamics simulation to push Shapes along.": ("在 Forge 动力学模拟中创建方向力以推动形状。", "在 Forge 動力學模擬中建立方向力以推動形狀。", "Forge ダイナミクスシミュレーションで方向力を作成してシェイプを押し進めます。"),
"Attractor Field": ("吸引场", "吸引場", "アトラクターフィールド"),
"Use with a Forge Dynamics simulation to move Shapes towards or away from a target.": ("与 Forge 动力学模拟一起使用，使形状向目标靠近或远离。", "與 Forge 動力學模擬一起使用，使形狀向目標靠近或遠離。", "Forge ダイナミクスシミュレーションで使用して、シェイプをターゲットに向かって移動または遠ざけます。"),
"Vortex Field": ("涡旋场", "渦旋場", "ボルテックスフィールド"),
"Apply spiral/rotational forces to Shapes around a center point.": ("围绕中心点对形状施加螺旋/旋转力。", "圍繞中心點對形狀施加螺旋/旋轉力。", "中心点を中心にシェイプに螺旋/回転力を適用します。"),
"Size of the vortex influence area.": ("涡旋影响区域的大小。", "渦旋影響區域的大小。", "ボルテックスの影響範囲のサイズ。"),
"Spiral Strength": ("螺旋强度", "螺旋強度", "スパイラル強度"),
"Tangential force strength. Makes bodies orbit around the vortex center.": ("切向力强度。使物体围绕涡旋中心轨道运动。", "切向力強度。使物體圍繞渦旋中心軌道運動。", "接線力の強度。ボディをボルテックスの中心を周回させます。"),
"Centripetal Strength": ("向心力强度", "向心力強度", "向心力の強度"),
"Radial force strength. Positive pulls inward toward center, negative pushes outward.": ("径向力强度。正值向中心拉入，负值向外推出。", "徑向力強度。正值向中心拉入，負值向外推出。", "放射方向の力の強度。正の値は中心に引き寄せ、負の値は外側に押し出します。"),
"Angular Strength": ("角度强度", "角度強度", "角度強度"),
"Spin/rotation force applied to bodies on their own axis. Makes bodies rotate as they move through the vortex.": ("施加在物体自身轴上的旋转力。使物体在通过涡旋时旋转。", "施加在物體自身軸上的旋轉力。使物體在通過渦旋時旋轉。", "ボディ自身の軸に適用される回転力。ボディがボルテックスを通過する際に回転させます。"),
"Direction of vortex rotation.": ("涡旋旋转方向。", "渦旋旋轉方向。", "ボルテックスの回転方向。"),
"Noise Generator": ("噪波生成器", "雜訊產生器", "ノイズジェネレーター"),
"Modulate forces based on noise.": ("基于噪波调制力。", "基於雜訊調變力。", "ノイズに基づいて力を変調します。"),
"Noise Affects": ("噪波影响", "雜訊影響", "ノイズの影響"),
"Which force component the noise modulates.": ("噪波调制的力分量。", "雜訊調變的力分量。", "ノイズが変調する力の成分。"),
"Noise Strength": ("噪波强度", "雜訊強度", "ノイズ強度"),
"Strength of the noise modulation effect.": ("噪波调制效果的强度。", "雜訊調變效果的強度。", "ノイズ変調効果の強度。"),
"Both Forces": ("两种力", "兩種力", "両方の力"),
"Angular Force": ("角力", "角力", "角力"),
"Buoyancy Field": ("浮力场", "浮力場", "浮力フィールド"),
"Create fluid containers where dynamic bodies will float or sink based on their density.": ("创建流体容器，动态物体将根据其密度浮起或下沉。", "建立流體容器，動態物體將根據其密度浮起或下沉。", "動的ボディがその密度に基づいて浮いたり沈んだりする流体コンテナを作成します。"),
"Width and height of the fluid region.": ("流体区域的宽度和高度。", "流體區域的寬度和高度。", "流体領域の幅と高さ。"),
"Fluid Density": ("流体密度", "流體密度", "流体密度"),
"Density of the fluid. Bodies with lower density will float, higher density will sink. Compare this to the body's density (set in Forge Dynamics Shape) to control behavior.": ("流体的密度。密度较低的物体会浮起，密度较高的会下沉。将此值与物体的密度（在 Forge 动力学形状中设置）进行比较以控制行为。", "流體的密度。密度較低的物體會浮起，密度較高的會下沉。將此值與物體的密度（在 Forge 動力學形狀中設定）進行比較以控制行為。", "流体の密度。密度が低いボディは浮き、高いボディは沈みます。動作を制御するには、ボディの密度（Forge ダイナミクスシェイプで設定）と比較してください。"),
"Buoyancy Strength": ("浮力强度", "浮力強度", "浮力の強度"),
"Multiplier for buoyant force. 1.0 = physically accurate, higher values create stronger upward push.": ("浮力的乘数。1.0 = 物理精确，较高的值产生更强的向上推力。", "浮力的乘數。1.0 = 物理精確，較高的值產生更強的向上推力。", "浮力の乗数。1.0 = 物理的に正確、値が大きいほど上向きの力が強くなります。"),
"Drag Coefficient": ("阻力系数", "阻力係數", "抗力係数"),
"Resistance to movement through the fluid. Higher values slow bodies down more (opposes velocity).": ("在流体中移动的阻力。较高的值使物体减速更多（抵抗速度）。", "在流體中移動的阻力。較高的值使物體減速更多（抵抗速度）。", "流体中の移動に対する抵抗。値が大きいほどボディの減速が大きくなります（速度に対抗）。"),
"Lift Coefficient": ("升力系数", "升力係數", "揚力係数"),
"Force perpendicular to velocity direction. Creates swirling/spiraling motion in the fluid. 0 = no lift.": ("垂直于速度方向的力。在流体中产生旋转/螺旋运动。0 = 无升力。", "垂直於速度方向的力。在流體中產生旋轉/螺旋運動。0 = 無升力。", "速度方向に垂直な力。流体中で渦巻き/螺旋運動を生成します。0 = 揚力なし。"),
"Angular Drag": ("角阻力", "角阻力", "角度ドラッグ"),
"Resistance to rotation in the fluid. Higher values slow down spinning.": ("流体中的旋转阻力。较高的值减缓旋转。", "流體中的旋轉阻力。較高的值減緩旋轉。", "流体中の回転に対する抵抗。値が大きいほど回転が遅くなります。"),
"Uprighting": ("扶正", "扶正", "アップライティング"),
"Apply rotational force to make bodies orient themselves to a target angle (self-righting).": ("施加旋转力使物体朝向目标角度（自动扶正）。", "施加旋轉力使物體朝向目標角度（自動扶正）。", "回転力を適用してボディをターゲット角度に向かせます（セルフライティング）。"),
"Uprighting Strength": ("扶正强度", "扶正強度", "アップライティング強度"),
"Strength of the righting torque. Higher values make bodies rotate to upright angle faster.": ("扶正扭矩的强度。较高的值使物体更快地旋转到垂直角度。", "扶正扭矩的強度。較高的值使物體更快地旋轉到垂直角度。", "ライティングトルクの強度。値が大きいほどボディが直立角度に速く回転します。"),
"Upright Angle": ("垂直角度", "垂直角度", "直立角度"),
"Target angle in degrees that bodies try to rotate towards.": ("物体尝试旋转到的目标角度（度）。", "物體嘗試旋轉到的目標角度（度）。", "ボディが回転して向かおうとするターゲット角度（度）。"),
"Surface Tension": ("表面张力", "表面張力", "表面張力"),
"Enable special forces when bodies enter/exit the fluid region (surface pop effects).": ("启用物体进入/离开流体区域时的特殊力（表面弹出效果）。", "啟用物體進入/離開流體區域時的特殊力（表面彈出效果）。", "ボディが流体領域に出入りする際の特殊な力を有効にします（表面ポップ効果）。"),
"Surface Tension Force": ("表面张力", "表面張力", "表面張力"),
"Impulse strength when crossing the fluid boundary. Creates splash-like entry effects.": ("跨越流体边界时的冲量强度。创建类似飞溅的进入效果。", "跨越流體邊界時的衝量強度。建立類似飛濺的進入效果。", "流体境界を横切る際のインパルス強度。スプラッシュのような進入効果を作成します。"),
"Surface Thickness": ("表面厚度", "表面厚度", "表面の厚さ"),
"Depth of the surface tension detection zone (currently unused in full-submersion mode).": ("表面张力检测区域的深度（目前在完全浸没模式下未使用）。", "表面張力偵測區域的深度（目前在完全浸沒模式下未使用）。", "表面張力検出ゾーンの深さ（現在、完全浸水モードでは未使用）。"),
"Path Field": ("路径场", "路徑場", "パスフィールド"),
"Apply path-following forces to Shapes.": ("对形状施加路径跟随力。", "對形狀施加路徑跟隨力。", "シェイプにパス追従力を適用します。"),
"Path to Follow": ("跟随路径", "跟隨路徑", "追従パス"),
"Connect a Shape to define the path that bodies will follow.": ("连接形状以定义物体将跟随的路径。", "連接形狀以定義物體將跟隨的路徑。", "シェイプを接続してボディが追従するパスを定義します。"),
"Capture Force": ("捕获力", "捕獲力", "キャプチャフォース"),
"Strength of the force pulling bodies towards the path.": ("将物体拉向路径的力的强度。", "將物體拉向路徑的力的強度。", "ボディをパスに引き寄せる力の強度。"),
"Flow Force": ("流动力", "流動力", "フローフォース"),
"Strength of the force moving bodies along the path tangent.": ("沿路径切线方向移动物体的力的强度。", "沿路徑切線方向移動物體的力的強度。", "パスの接線方向にボディを移動させる力の強度。"),
"Capture Margin": ("捕获边距", "捕獲邊距", "キャプチャマージン"),
"Distance from the path where capture forces apply.": ("捕获力适用的离路径的距离。", "捕獲力適用的離路徑的距離。", "キャプチャフォースが適用されるパスからの距離。"),
"Flow Margin": ("流动边距", "流動邊距", "フローマージン"),
"Distance from the path where flow forces apply.": ("流动力适用的离路径的距离。", "流動力適用的離路徑的距離。", "フローフォースが適用されるパスからの距離。"),
"Flow Variance": ("流动方差", "流動變異量", "フロー分散"),
"Add randomness to flow direction for more natural motion.": ("为流动方向添加随机性以获得更自然的运动。", "為流動方向新增隨機性以取得更自然的運動。", "より自然な動きのために流れの方向にランダム性を追加します。"),
"Capture Curve": ("捕获曲线", "捕獲曲線", "キャプチャカーブ"),
"Control how capture force attenuates with distance from the path.": ("控制捕获力随离路径距离的衰减方式。", "控制捕獲力隨離路徑距離的衰減方式。", "キャプチャフォースがパスからの距離に応じてどのように減衰するかを制御します。"),
"Flow Curve": ("流动曲线", "流動曲線", "フローカーブ"),
"Control how flow force attenuates with distance from the path.": ("控制流动力随离路径距离的衰减方式。", "控制流動力隨離路徑距離的衰減方式。", "フローフォースがパスからの距離に応じてどのように減衰するかを制御します。"),
"Velocity Damping": ("速度阻尼", "速度阻尼", "速度ダンピング"),
"Opposes body velocity to prevent oscillation and instability. Higher values create more stable but slower motion.": ("抵抗物体速度以防止振荡和不稳定。较高的值产生更稳定但更慢的运动。", "抵抗物體速度以防止振盪和不穩定。較高的值產生更穩定但更慢的運動。", "ボディの速度に対抗して振動と不安定性を防ぎます。値が大きいほど安定しますが動きが遅くなります。"),
"Draw Capture Margin": ("绘制捕获边距", "繪製捕獲邊距", "キャプチャマージンを描画"),
"Draw Flow Margin": ("绘制流动边距", "繪製流動邊距", "フローマージンを描画"),
"Move the start points along all Contours within a Path (a Path can contain multiple Contours).": ("沿路径中所有轮廓移动起始点（一个路径可以包含多个轮廓）。", "沿路徑中所有輪廓移動起始點（一個路徑可以包含多個輪廓）。", "パス内のすべての輪郭に沿って始点を移動します（パスには複数の輪郭を含めることができます）。"),
"travel": ("行程", "行程", "トラベル"),
"Reverse the direction of Contours within a Path (a Path can contain multiple Contours).": ("反转路径中轮廓的方向（一个路径可以包含多个轮廓）。", "反轉路徑中輪廓的方向（一個路徑可以包含多個輪廓）。", "パス内の輪郭の方向を反転します（パスには複数の輪郭を含めることができます）。"),
"Reverse All": ("全部反转", "全部反轉", "すべて反転"),
"Reverse Clockwise": ("反转顺时针", "反轉順時針", "時計回りを反転"),
"Reverse Counter-Clockwise": ("反转逆时针", "反轉逆時針", "反時計回りを反転"),
"Normalize Path Direction": ("规范化路径方向", "正規化路徑方向", "パス方向を正規化"),
"Set the direction of a Path's outer Contours and reverse its inner contours if needed.": ("设置路径外轮廓的方向，并在需要时反转其内轮廓。", "設定路徑外輪廓的方向，並在需要時反轉其內輪廓。", "パスの外側輪郭の方向を設定し、必要に応じて内側輪郭を反転します。"),
"Outer Contours": ("外轮廓", "外輪廓", "外側輪郭"),
"Skip Open Contours": ("跳过开放轮廓", "跳過開放輪廓", "開いた輪郭をスキップ"),
"No Change": ("不变", "不變", "変更なし"),
"Remove Contours": ("移除轮廓", "移除輪廓", "輪郭を削除"),
"Removes contours from a path based on their direction.": ("根据方向从路径中移除轮廓。", "根據方向從路徑中移除輪廓。", "方向に基づいてパスから輪郭を削除します。"),
"Remove Clockwise": ("移除顺时针", "移除順時針", "時計回りを削除"),
"Remove Counter-Clockwise": ("移除逆时针", "移除逆時針", "反時計回りを削除"),
"Asset From Smart Folder": ("来自智能文件夹的资产", "來自智慧資料夾的資產", "スマートフォルダーからのアセット"),
"Reference assets (images, videos, audio etc) contained within a Smart Folder.": ("引用智能文件夹中包含的资产（图像、视频、音频等）。", "參考智慧資料夾中包含的資產（影像、影片、音訊等）。", "スマートフォルダー内に含まれるアセット（画像、動画、音声など）を参照します。"),
"Smart Folder Asset": ("智能文件夹资产", "智慧資料夾資產", "スマートフォルダーアセット"),
}
