T = {
'Element': ('元素', '元素', 'エレメント'),
'Hidden': ('隐藏', '隱藏', '非表示'),
'Freeze Calculations': ('冻结计算', '凍結計算', '計算をフリーズ'),
"Freeze the calculation of this layer. Keyframe this attribute on to 'pause' layer calculations.": ('冻结此图层的计算。将此属性设置关键帧以“暂停”图层计算。', '凍結此圖層的計算。將此屬性設置關鍵幀以「暫停」圖層計算。', 'このレイヤーの計算をフリーズします。この属性にキーフレームを設定して、レイヤーの計算を「一時停止」できます。'),
'Draw on Top of Parent': ('绘制在父级之上', '繪製在父級之上', '親の上に描画'),
"When 'Draw on Top of Parent' is checked, this layer will appear above its parent layer in the Viewport.": ('当“绘制在父级之上”被选中时，此图层将在视口中显示在其父级图层上方。', '當「繪製在父級之上」被勾選時，此圖層將在檢視區中顯示在其父級圖層上方。', '「親の上に描画」をチェックすると、このレイヤーはビューポートで親レイヤーの上に表示されます。'),
'Atomic': ('原子', '原子', 'アトミック'),
'Group': ('编组', '群組', 'グループ'),
'Collect layers in a folder to organise them and/or create a common transform.': ('将图层收集到文件夹中以进行组织和/或创建公共变换。', '將圖層收集到資料夾中以進行組織和/或建立共同變換。', 'レイヤーをフォルダーにまとめて整理し、共通のトランスフォームを作成します。'),
'Blending and Opacity Mode': ('混合和不透明度模式', '混合與不透明度模式', '描画モードと不透明度モード'),
"Determine how Shapes within the Group visually combine with each other:\n\n**Artboard**:\n\nThe Group's Blend Mode will only affect the Shapes within the Group. Opacity affects everything in the Group together.\n\n**Individual Layers**:\n\nThe Group's Blend Mode will also affect Shapes outside the Group. Opacity affects each Shape individually.": ('确定编组内的形状如何相互进行视觉合成：\n\n**画板**：\n\n编组的混合模式只影响编组内的形状。不透明度将统一影响编组中的所有内容。\n\n**独立图层**：\n\n编组的混合模式也会影响编组外的形状。不透明度将分别影响每个形状。', '決定群組內的形狀如何相互進行視覺合成：\n\n**畫板**：\n\n群組的混合模式只影響群組內的形狀。不透明度將統一影響群組中的所有內容。\n\n**獨立圖層**：\n\n群組的混合模式也會影響群組外的形狀。不透明度將分別影響每個形狀。', 'グループ内のシェイプが互いにどのように視覚的に合成されるかを決定します：\n\n**アートボード**：\n\nグループの描画モードはグループ内のシェイプにのみ影響します。不透明度はグループ内のすべてに一括で影響します。\n\n**個別レイヤー**：\n\nグループの描画モードはグループ外のシェイプにも影響します。不透明度は各シェイプに個別に影響します。'),
'Artboard': ('画板', '畫板', 'アートボード'),
'Individual Layers': ('独立图层', '獨立圖層', '個別レイヤー'),
'Behaviour Base': ('行为基础', '行為基礎', 'ビヘイビアベース'),
'Transform': ('变换', '變換', 'トランスフォーム'),
'Position': ('位置', '位置', '位置'),
"Set the Shape's position. 0,0 is in the centre of your comp.": ('设置形状的位置。0,0 位于合成的中心。', '設定形狀的位置。0,0 位於合成的中心。', 'シェイプの位置を設定します。0,0 はコンポジションの中心です。'),
'Rotation': ('旋转', '旋轉', '回転'),
"Set the Shape's rotation (in degrees).": ('设置形状的旋转（以度为单位）。', '設定形狀的旋轉（以度為單位）。', 'シェイプの回転を設定します（度単位）。'),
'Scale': ('缩放', '縮放', 'スケール'),
"Set the Shape's scale.": ('设置形状的缩放。', '設定形狀的縮放。', 'シェイプのスケールを設定します。'),
'Skew': ('倾斜', '傾斜', 'スキュー'),
"Set the Shape's skew.": ('设置形状的倾斜。', '設定形狀的傾斜。', 'シェイプのスキューを設定します。'),
'Pivot': ('锚点', '錨點', 'ピボット'),
'Define the pivot point for the shape. This is useful when animating rotation and scale.': ('定义形状的锚点。这在制作旋转和缩放动画时非常有用。', '定義形狀的錨點。這在製作旋轉和縮放動畫時非常有用。', 'シェイプのピボットポイントを定義します。回転やスケールのアニメーションに便利です。'),
'Lottie Export': ('Lottie 导出', 'Lottie 匯出', 'Lottie エクスポート'),
'Export if Visible': ('可见时导出', '可見時匯出', '表示時にエクスポート'),
'Always Export': ('始终导出', '始終匯出', '常にエクスポート'),
'Never Export': ('从不导出', '從不匯出', 'エクスポートしない'),
'Drawable': ('可绘制', '可繪製', 'ドローアブル'),
'Poly Mesh': ('多边形网格', '多邊形網格', 'ポリメッシュ'),
'On': ('开启', '開啟', 'オン'),
'Opacity': ('不透明度', '不透明度', '不透明度'),
"Set the Shape's opacity.": ('设置形状的不透明度。', '設定形狀的不透明度。', 'シェイプの不透明度を設定します。'),
'Children Draw on Top': ('子级绘制在上方', '子級繪製在上方', '子を上に描画'),
"When this is off, the parent will draw below everything in it's hierarchy.": ('当此项关闭时，父级将绘制在其层级结构中所有内容的下方。', '當此項關閉時，父級將繪製在其層級結構中所有內容的下方。', 'これがオフの場合、親はその階層内のすべての下に描画されます。'),
'Wireframe': ('线框', '線框', 'ワイヤーフレーム'),
'Auto Index': ('自动索引', '自動索引', '自動インデックス'),
'Automatically output all indices within the array.': ('自动输出数组中的所有索引。', '自動輸出陣列中的所有索引。', '配列内のすべてのインデックスを自動的に出力します。'),
'Reverse': ('反转', '反轉', '反転'),
'Reverse the order of the array.': ('反转数组的顺序。', '反轉陣列的順序。', '配列の順序を反転します。'),
'Count': ('计数', '計數', 'カウント'),
'Number of indices in the array.': ('数组中的索引数量。', '陣列中的索引數量。', '配列内のインデックス数。'),
'Index': ('索引', '索引', 'インデックス'),
'Manually output an index within the array (uncheck Auto Index to enable).': ('手动输出数组中的索引（取消选中自动索引以启用）。', '手動輸出陣列中的索引（取消勾選自動索引以啟用）。', '配列内のインデックスを手動で出力します（有効にするには自動インデックスのチェックを外してください）。'),
'Shape': ('形状', '形狀', 'シェイプ'),
'Polygonal objects that can be drawn in the viewport': ('可在视口中绘制的多边形对象', '可在檢視區中繪製的多邊形物件', 'ビューポートに描画できるポリゴンオブジェクト'),
'Deformers': ('变形器', '變形器', 'デフォーマ'),
'Connect Behaviours to deform your Shape.': ('连接行为以变形您的形状。', '連接行為以變形您的形狀。', 'ビヘイビアを接続してシェイプを変形します。'),
'Clipping Masks': ('裁剪蒙版', '裁剪遮罩', 'クリッピングマスク'),
'Connect Shapes to be used as clipping masks.': ('连接形状以用作裁剪蒙版。', '連接形狀以用作裁剪遮罩。', 'シェイプを接続してクリッピングマスクとして使用します。'),
'Clipping Mode': ('裁剪模式', '裁剪模式', 'クリッピングモード'),
'Full Shape': ('完整形状', '完整形狀', 'フルシェイプ'),
'Child Shapes': ('子级形状', '子級形狀', '子シェイプ'),
'Fill': ('填充', '填充', '塗り'),
'Stroke': ('描边', '描邊', 'ストローク'),
'Track Mattes': ('轨道蒙版', '軌跡遮罩', 'トラックマット'),
'Track Matte Mode': ('轨道蒙版模式', '軌跡遮罩模式', 'トラックマットモード'),
'Feather': ('羽化', '羽化', 'フェザー'),
'Feather the Geometry/ Edges of the Shape by applying a mask blur.': ('通过应用蒙版模糊来羽化形状的几何体/边缘。', '透過套用遮罩模糊來羽化形狀的幾何體/邊緣。', 'マスクブラーを適用してシェイプのジオメトリ/エッジをフェザーします。'),
'Feather Clipping Masks': ('羽化裁剪蒙版', '羽化裁剪遮罩', 'クリッピングマスクをフェザー'),
'Feather the clipping masks along with the Shape.': ('将裁剪蒙版与形状一起羽化。', '將裁剪遮罩與形狀一起羽化。', 'シェイプと一緒にクリッピングマスクをフェザーします。'),
'Blend Mode': ('混合模式', '混合模式', '描画モード'),
'Determine how this Shape blends with other layers in the Scene Window.': ('确定此形状如何与场景窗口中的其他图层混合。', '決定此形狀如何與場景視窗中的其他圖層混合。', 'このシェイプがシーンウィンドウ内の他のレイヤーとどのように混合されるかを決定します。'),
'Filters': ('滤镜', '濾鏡', 'フィルター'),
'Add post effects to Shapes.': ('为形状添加后期效果。', '為形狀添加後製效果。', 'シェイプにポストエフェクトを追加します。'),
'Motion Blur': ('运动模糊', '動態模糊', 'モーションブラー'),
"Enable Motion Blur (ensure Motion Blur is also enabled in the Scene Window for 'Full' motion blur).": ('启用运动模糊（确保场景窗口中也启用了运动模糊以获得“完整”运动模糊效果）。', '啟用動態模糊（確保場景視窗中也啟用了動態模糊以獲得「完整」動態模糊效果）。', 'モーションブラーを有効にします（「フル」モーションブラーを使用するには、シーンウィンドウでもモーションブラーを有効にしてください）。'),
'Lottie Baking': ('Lottie 烘焙', 'Lottie 烘焙', 'Lottie ベイク'),
'If you only need a still mesh export, you can set that here, this will result in smaller Lottie files.': ('如果您只需要静态网格导出，可以在此处设置，这将生成更小的 Lottie 文件。', '如果您只需要靜態網格匯出，可以在此處設定，這將產生較小的 Lottie 檔案。', '静止メッシュのエクスポートのみが必要な場合、ここで設定できます。これにより Lottie ファイルのサイズが小さくなります。'),
'Scale Lottie Strokes': ('缩放 Lottie 描边', '縮放 Lottie 描邊', 'Lottie ストロークをスケール'),
"Experimental. This will scale stroke widths by the shape scale. Try this when Lottie stroke widths don't match those in your Cavalry Scene.": ('实验性功能。这将按形状缩放比例缩放描边宽度。当 Lottie 描边宽度与 Cavalry 场景中的不匹配时，请尝试此功能。', '實驗性功能。這將按形狀縮放比例縮放描邊寬度。當 Lottie 描邊寬度與 Cavalry 場景中的不匹配時，請嘗試此功能。', '実験的機能。シェイプのスケールに応じてストローク幅をスケールします。Lottie のストローク幅が Cavalry シーンと一致しない場合にお試しください。'),
'Vertical Layout Alignment': ('垂直布局对齐', '垂直版面對齊', '垂直レイアウト配置'),
'Control the Y position of items in a Horizontal or Grid Layout.': ('控制水平或网格布局中项目的 Y 位置。', '控制水平或網格版面中項目的 Y 位置。', '水平またはグリッドレイアウト内のアイテムの Y 位置を制御します。'),
'Horizontal Layout Alignment': ('水平布局对齐', '水平版面對齊', '水平レイアウト配置'),
'Control the X position of items in a Vertical or Grid Layout.': ('控制垂直或网格布局中项目的 X 位置。', '控制垂直或網格版面中項目的 X 位置。', '垂直またはグリッドレイアウト内のアイテムの X 位置を制御します。'),
'Exclude From Layout': ('从布局中排除', '從版面中排除', 'レイアウトから除外'),
'Tell Layout Groups to ignore this layer.': ('告知布局编组忽略此图层。', '告知版面群組忽略此圖層。', 'レイアウトグループにこのレイヤーを無視するよう指示します。'),
'Layout Based on Size at Frame': ('基于帧尺寸进行布局', '基於幀尺寸進行版面配置', 'フレームのサイズに基づくレイアウト'),
'Use the size of this Shape at a specific frame when calculating Layouts.': ('在计算布局时使用此形状在特定帧的尺寸。', '在計算版面配置時使用此形狀在特定幀的尺寸。', 'レイアウト計算時に、特定のフレームでのこのシェイプのサイズを使用します。'),
'Layout Frame': ('布局帧', '版面幀', 'レイアウトフレーム'),
'The frame to use when calculating the size of this Shape for a Layout.': ('计算此形状在布局中的尺寸时使用的帧。', '計算此形狀在版面配置中的尺寸時使用的幀。', 'レイアウトでこのシェイプのサイズを計算する際に使用するフレーム。'),
'Scheduling Group Mode': ('调度组模式', '排程群組模式', 'スケジューリンググループモード'),
'Control how this layer is used by Scheduling Groups.': ('控制调度组如何使用此图层。', '控制排程群組如何使用此圖層。', 'スケジューリンググループによるこのレイヤーの使用方法を制御します。'),
'Guide Layer': ('参考图层', '參考圖層', 'ガイドレイヤー'),
'You can make a layer visible in the viewport, but not final renders by turning into a Guide Layer.': ('通过将图层转为参考图层，可以使其在视口中可见，但不会出现在最终渲染中。', '透過將圖層轉為參考圖層，可以使其在檢視區中可見，但不會出現在最終算繪中。', 'レイヤーをガイドレイヤーにすることで、ビューポートでは表示されますが、最終レンダリングには含まれません。'),
'2.5D': ('2.5D', '2.5D', '2.5D'),
'Turn on 2.5D for this layer.': ('为此图层开启 2.5D。', '為此圖層開啟 2.5D。', 'このレイヤーの 2.5D を有効にします。'),
'Replace': ('替换', '取代', '置換'),
'Normal': ('正常', '正常', '通常'),
'Plus Lighter': ('加亮', '加亮', '加算（明）'),
'Screen': ('滤色', '濾色', 'スクリーン'),
'Overlay': ('叠加', '覆蓋', 'オーバーレイ'),
'Darken': ('变暗', '變暗', '暗く'),
'Lighten': ('变亮', '變亮', '明るく'),
'Color Dodge': ('颜色减淡', '顏色減淡', '覆い焼きカラー'),
'Color Burn': ('颜色加深', '顏色加深', '焼き込みカラー'),
'Hard Light': ('强光', '強光', 'ハードライト'),
'Soft Light': ('柔光', '柔光', 'ソフトライト'),
'Difference': ('差值', '差異', '差の絶対値'),
'Exclusion': ('排除', '排除', '除外'),
'Multiply': ('正片叠底', '色彩增值', '乗算'),
'Hue': ('色相', '色相', '色相'),
'Saturation': ('饱和度', '飽和度', '彩度'),
'Color': ('颜色', '顏色', 'カラー'),
'Luminosity': ('亮度', '亮度', '輝度'),
'Alpha Add': ('Alpha 叠加', 'Alpha 疊加', 'Alpha 加算'),
'Alpha Add Under': ('Alpha 底层叠加', 'Alpha 底層疊加', 'Alpha 背面加算'),
'Plus Darker': ('加暗', '加暗', '加算（暗）'),
'Normal (Anti-Aliasing)': ('正常（抗锯齿）', '正常（抗鋸齒）', '通常（アンチエイリアス）'),
'Best (Offscreen Anti-Aliasing)': ('最佳（离屏抗锯齿）', '最佳（離屏抗鋸齒）', '最高品質（オフスクリーンアンチエイリアス）'),
'Fast (No Anti-Aliasing)': ('快速（无抗锯齿）', '快速（無抗鋸齒）', '高速（アンチエイリアスなし）'),
'None': ('无', '無', 'なし'),
'Full': ('完整', '完整', 'フル'),
'Transform Only (Fast)': ('仅变换（快速）', '僅變換（快速）', 'トランスフォームのみ（高速）'),
'Off': ('关闭', '關閉', 'オフ'),
'On (Visible in Pre-Compositions)': ('开启（在预合成中可见）', '開啟（在預合成中可見）', 'オン（プリコンプで表示）'),
'On (Invisible in Pre-Compositions)': ('开启（在预合成中不可见）', '開啟（在預合成中不可見）', 'オン（プリコンプで非表示）'),
'Automatic': ('自动', '自動', '自動'),
'Animated Mesh': ('动画网格', '動畫網格', 'アニメーションメッシュ'),
'Animated Mesh & Materials': ('动画网格和材质', '動畫網格與材質', 'アニメーションメッシュ＆マテリアル'),
'Nuclear': ('核心', '核心', 'ニュークリア'),
'Still': ('静止', '靜止', '静止'),
'Stencil Geometry': ('模板几何体', '模板幾何體', 'ステンシルジオメトリ'),
'Silhouette Geometry': ('轮廓几何体', '輪廓幾何體', 'シルエットジオメトリ'),
'Luma': ('亮度', '亮度', '輝度'),
'Luma Inverted': ('亮度反转', '亮度反轉', '輝度反転'),
'Alpha': ('Alpha', 'Alpha', 'Alpha'),
'Alpha Inverted': ('Alpha 反转', 'Alpha 反轉', 'Alpha 反転'),
'Ignore': ('忽略', '忽略', '無視'),
'Top': ('顶部', '頂部', '上'),
'Middle': ('中间', '中間', '中央'),
'Bottom': ('底部', '底部', '下'),
'Leading': ('前端', '前端', '先頭'),
'Centre': ('居中', '置中', '中央'),
'Trailing': ('末端', '末端', '末尾'),
'Use': ('使用', '使用', '使用'),
'Use Children': ('使用子级', '使用子級', '子を使用'),
'Masks': ('蒙版', '遮罩', 'マスク'),
'Advanced': ('高级', '進階', '詳細'),
'Behaviour': ('行为', '行為', 'ビヘイビア'),
'Falloffs': ('衰减', '衰減', 'フォールオフ'),
'Connect or add Falloffs to determine a Behaviours strength based on position.': ('连接或添加衰减以根据位置确定行为的强度。', '連接或新增衰減以根據位置決定行為的強度。', 'フォールオフを接続または追加して、位置に基づくビヘイビアの強度を決定します。'),
'Strength': ('强度', '強度', '強度'),
"Increase or decrease the Behaviour's effect as a percentage.": ('以百分比增加或减少行为的效果。', '以百分比增加或減少行為的效果。', 'ビヘイビアの効果をパーセンテージで増減します。'),
'Use Normals': ('使用法线', '使用法線', '法線を使用'),
'Deform shapes along their normals.': ('沿法线方向变形形状。', '沿法線方向變形形狀。', '法線方向にシェイプを変形します。'),
'Output': ('输出', '輸出', '出力'),
'Normal (Add)': ('正常（添加）', '正常（新增）', '通常（加算）'),
'Min.': ('最小', '最小', '最小'),
'Max.': ('最大', '最大', '最大'),
'Minus': ('减去', '減去', '減算'),
"Remap an attribute's animation curve (e.g. from the first to the last keyframe) to a percentage.": ('将属性的动画曲线（例如从第一个关键帧到最后一个关键帧）重映射为百分比。', '將屬性的動畫曲線（例如從第一個關鍵幀到最後一個關鍵幀）重新映射為百分比。', '属性のアニメーションカーブ（例：最初のキーフレームから最後のキーフレームまで）をパーセンテージにリマップします。'),
'Amount': ('数量', '數量', '量'),
'Active': ('启用', '啟用', 'アクティブ'),
'To control animation with a slider. Simply drag the output<img src = icons:ConnectionAnchor.png width=18 height=18 style=vertical-align:middle/>from this layer to any animated Attribute.': ('使用滑块控制动画。只需将此图层的输出<img src = icons:ConnectionAnchor.png width=18 height=18 style=vertical-align:middle/>拖动到任何有动画的属性上。', '使用滑桿控制動畫。只需將此圖層的輸出<img src = icons:ConnectionAnchor.png width=18 height=18 style=vertical-align:middle/>拖動到任何有動畫的屬性上。', 'スライダーでアニメーションを制御します。このレイヤーの出力<img src = icons:ConnectionAnchor.png width=18 height=18 style=vertical-align:middle/>を任意のアニメーション属性にドラッグするだけです。'),
'Composition': ('合成', '合成', 'コンポジション'),
'Resolution': ('分辨率', '解析度', '解像度'),
'Frame Range': ('帧范围', '幀範圍', 'フレーム範囲'),
'Playback Range': ('播放范围', '播放範圍', '再生範囲'),
'Playback End': ('播放结束', '播放結束', '再生終了'),
'Background': ('背景', '背景', '背景'),
'Time': ('时间', '時間', '時間'),
'Frame Rate': ('帧率', '幀率', 'フレームレート'),
'Playback Step': ('播放步长', '播放步長', '再生ステップ'),
'Keyframe Layer': ('关键帧图层', '關鍵幀圖層', 'キーフレームレイヤー'),
'Shutter Angle': ('快门角度', '快門角度', 'シャッター角度'),
'Motion Blur Centre': ('运动模糊中心', '動態模糊中心', 'モーションブラー中心'),
'Blur Align': ('模糊对齐', '模糊對齊', 'ブラー配置'),
'Motion Blur Samples': ('运动模糊采样', '動態模糊取樣', 'モーションブラーサンプル数'),
'Linear Gamma': ('线性伽马', '線性伽瑪', 'リニアガンマ'),
'Active Audio Layer': ('活动音频图层', '活動音訊圖層', 'アクティブオーディオレイヤー'),
'Drag a layer into this slot to have it play during playback.': ('将图层拖入此插槽以在播放时播放。', '將圖層拖入此插槽以在播放時播放。', 'レイヤーをこのスロットにドラッグすると、再生中に再生されます。'),
'Looping': ('循环', '循環', 'ループ'),
'When checked, this means this Composition will loop when placed inside a longer Composition.': ('勾选后，表示此合成在放置于更长的合成内部时将循环播放。', '勾選後，表示此合成在放置於較長的合成內部時將循環播放。', 'チェックすると、このコンポジションはより長いコンポジション内に配置された際にループします。'),
'Automatic Range': ('自动范围', '自動範圍', '自動範囲'),
'Make the Composition frame range adapt to the Constraint Layers.': ('使合成帧范围适应约束图层。', '使合成幀範圍適應約束圖層。', 'コンポジションのフレーム範囲を制約レイヤーに合わせて調整します。'),
'Constraint Layers': ('约束图层', '約束圖層', '制約レイヤー'),
'Adapted Frame Range': ('适应帧范围', '適應幀範圍', '適応フレーム範囲'),
'Beats per Minute': ('每分钟节拍数', '每分鐘節拍數', 'BPM（テンポ）'),
'Offset': ('偏移', '偏移', 'オフセット'),
'Beats per Bar': ('每小节拍数', '每小節拍數', '1 小節あたりの拍数'),
'Mode': ('模式', '模式', 'モード'),
'Divisions': ('分段', '分段', '分割'),
'Referenceable': ('可引用', '可參考', '参照可能'),
'Specifies if this Composition is available when this Scene is used as a Reference.': ('指定当此场景用作引用时，此合成是否可用。', '指定當此場景用作參考時，此合成是否可用。', 'このシーンが参照として使用される場合に、このコンポジションを利用可能にするかどうかを指定します。'),
'Seconds': ('秒', '秒', '秒'),
'Label Color': ('标签颜色', '標籤顏色', 'ラベルカラー'),
'Overwrite': ('覆盖', '覆寫', '上書き'),
'File': ('文件', '檔案', 'ファイル'),
'File Name': ('文件名', '檔案名稱', 'ファイル名'),
'Path': ('路径', '路徑', 'パス'),
'Padding': ('填充', '填充', 'パディング'),
'Frame Range Mode': ('帧范围模式', '幀範圍模式', 'フレーム範囲モード'),
'File Format': ('文件格式', '檔案格式', 'ファイル形式'),
'Dynamic Render': ('动态渲染', '動態算繪', 'ダイナミックレンダリング'),
'Dynamic Index': ('动态索引', '動態索引', 'ダイナミックインデックス'),
'Number of Renders': ('渲染数量', '算繪數量', 'レンダリング数'),
'Render Range': ('渲染范围', '算繪範圍', 'レンダリング範囲'),
'Index Offset': ('索引偏移', '索引偏移', 'インデックスオフセット'),
'Resolution Scale': ('分辨率缩放', '解析度縮放', '解像度スケール'),
'Render Engine': ('渲染引擎', '算繪引擎', 'レンダリングエンジン'),
'Use Composition Playback Step': ('使用合成播放步长', '使用合成播放步長', 'コンポジション再生ステップを使用'),
'Compositions': ('合成', '合成', 'コンポジション'),
'Write Metadata': ('写入元数据', '寫入中繼資料', 'メタデータを書き込む'),
'Metadata': ('元数据', '中繼資料', 'メタデータ'),
'Key': ('键', '鍵', 'キー'),
'Value': ('值', '值', '値'),
'Single File': ('单个文件', '單一檔案', '単一ファイル'),
'Format': ('格式', '格式', 'フォーマット'),
"Use the Cog on the Composition Row to retime the Composition or change the Composition's FPS at render time.": ('使用合成行上的齿轮按钮来重新定时合成或在渲染时更改合成的 FPS。', '使用合成列上的齒輪按鈕來重新定時合成或在算繪時更改合成的 FPS。', 'コンポジション行の歯車を使用して、レンダリング時にコンポジションのリタイムや FPS の変更を行います。'),
'Render Quality': ('渲染质量', '算繪品質', 'レンダリング品質'),
'This setting will have no effect on vector render formats e.g SVG and Lottie.': ('此设置对矢量渲染格式（如 SVG 和 Lottie）无效。', '此設定對向量算繪格式（如 SVG 和 Lottie）無效。', 'この設定はベクターレンダリング形式（SVG や Lottie など）には影響しません。'),
'Ensure Unique File Names': ('确保唯一文件名', '確保唯一檔案名稱', '一意のファイル名を確保'),
'When this is off, you will need to set a unique File Name/ Path for each Dynamic Render to prevent one overwriting another during the same render session.': ('当此项关闭时，您需要为每个动态渲染设置唯一的文件名/路径，以防止在同一渲染会话中相互覆盖。', '當此項關閉時，您需要為每個動態算繪設定唯一的檔案名稱/路徑，以防止在同一算繪工作階段中相互覆寫。', 'これがオフの場合、同じレンダリングセッション中に互いに上書きされないよう、各ダイナミックレンダリングに一意のファイル名/パスを設定する必要があります。'),
'Setup Script': ('设置脚本', '設置腳本', 'セットアップスクリプト'),
'This script will be run once before the render begins.': ('此脚本将在渲染开始前运行一次。', '此腳本將在算繪開始前執行一次。', 'このスクリプトはレンダリング開始前に一度実行されます。'),
'Pre-Render Script': ('渲染前脚本', '算繪前腳本', 'プリレンダースクリプト'),
'This script will be run before each render (including Dynamic Renders). Render Queue Item settings cannot be changed from this script.': ('此脚本将在每次渲染（包括动态渲染）前运行。无法从此脚本更改渲染队列项设置。', '此腳本將在每次算繪（包括動態算繪）前執行。無法從此腳本更改算繪佇列項目設定。', 'このスクリプトは各レンダリング（ダイナミックレンダリングを含む）の前に実行されます。このスクリプトからレンダーキューアイテムの設定は変更できません。'),
'Post-Render Script': ('渲染后脚本', '算繪後腳本', 'ポストレンダースクリプト'),
'This script will be run after each render (e.g a movie, or image sequence).': ('此脚本将在每次渲染后（例如影片或图像序列）运行。', '此腳本將在每次算繪後（例如影片或影像序列）執行。', 'このスクリプトは各レンダリング後（例：動画や画像シーケンス）に実行されます。'),
'Respect Viewport Filtering': ('遵循视口过滤', '遵循檢視區過濾', 'ビューポートフィルタリングを適用'),
'By default, all layers will render regardless of viewport filtering, however with this setting on, layers filtered out by tags or soloing will not be rendered.': ('默认情况下，所有图层都会渲染，不受视口过滤影响。但是开启此设置后，通过标签或独奏过滤掉的图层将不会被渲染。', '預設情況下，所有圖層都會算繪，不受檢視區過濾影響。但是開啟此設定後，透過標籤或獨奏過濾掉的圖層將不會被算繪。', 'デフォルトでは、ビューポートフィルタリングに関係なくすべてのレイヤーがレンダリングされますが、この設定をオンにすると、タグやソロによりフィルタリングされたレイヤーはレンダリングされません。'),
'Retime Render': ('重新定时渲染', '重新定時算繪', 'リタイムレンダリング'),
'Enables retiming of a Composition at render time.': ('启用在渲染时对合成进行重新定时。', '啟用在算繪時對合成進行重新定時。', 'レンダリング時にコンポジションのリタイムを有効にします。'),
'New Composition Length': ('新合成长度', '新合成長度', '新しいコンポジション長'),
'Enter a Timecode (MM:SS:FF) that represents the desired length of the Render. This remapping will be based on the full Composition length.': ('输入一个时间码（MM:SS:FF），代表所需的渲染长度。此重映射将基于完整的合成长度。', '輸入一個時間碼（MM:SS:FF），代表所需的算繪長度。此重新映射將基於完整的合成長度。', 'レンダリングの希望する長さを表すタイムコード（MM:SS:FF）を入力します。このリマッピングは完全なコンポジション長に基づきます。'),
'Remap to FPS': ('重映射到 FPS', '重新映射至 FPS', 'FPS にリマップ'),
'Enable remapping the animation to a different FPS.': ('启用将动画重映射到不同的 FPS。', '啟用將動畫重新映射至不同的 FPS。', 'アニメーションを異なる FPS にリマップすることを有効にします。'),
'New FPS': ('新 FPS', '新 FPS', '新しい FPS'),
'The FPS that the animation should be remapped to. This will override the FPS set in the Composition settings.': ('动画应重映射到的 FPS。这将覆盖合成设置中设定的 FPS。', '動畫應重新映射至的 FPS。這將覆寫合成設定中設定的 FPS。', 'アニメーションをリマップする FPS。これはコンポジション設定で設定された FPS を上書きします。'),
'Control Centre Button Name': ('控制中心按钮名称', '控制中心按鈕名稱', 'コントロールセンターボタン名'),
'This is the name given to the button for this item in Cavalry Control.': ('这是 Cavalry Control 中此项目按钮的名称。', '這是 Cavalry Control 中此項目按鈕的名稱。', 'これは Cavalry Control でこのアイテムのボタンに付けられる名前です。'),
'Composition Start/End': ('合成起止', '合成起迄', 'コンポジション開始/終了'),
'Playback Start/End': ('播放起止', '播放起迄', '再生開始/終了'),
'Custom Range...': ('自定义范围...', '自訂範圍...', 'カスタム範囲...'),
'Current Frame': ('当前帧', '目前幀', '現在のフレーム'),
'CPU': ('CPU', 'CPU', 'CPU'),
'GPU': ('GPU', 'GPU', 'GPU'),
'High': ('高', '高', '高'),
'Low': ('低', '低', '低'),
'Lowest': ('最低', '最低', '最低'),
'Balanced': ('平衡', '平衡', 'バランス'),
'JSON': ('JSON', 'JSON', 'JSON'),
'Simple Traits JSON': ('Simple Traits JSON', 'Simple Traits JSON', 'Simple Traits JSON'),
'NFT Traits JSON (ERC-1155)': ('NFT Traits JSON (ERC-1155)', 'NFT Traits JSON (ERC-1155)', 'NFT Traits JSON (ERC-1155)'),
'Canva': ('Canva', 'Canva', 'Canva'),
'Preset...': ('预设...', '預設...', 'プリセット...'),
'Dynamic': ('动态', '動態', 'ダイナミック'),
'Scripts': ('脚本', '腳本', 'スクリプト'),
'Upload': ('上传', '上傳', 'アップロード'),
'PNG Sequence': ('PNG 序列', 'PNG 序列', 'PNG シーケンス'),
'Generate a PNG image file.': ('生成 PNG 图像文件。', '產生 PNG 影像檔案。', 'PNG 画像ファイルを生成します。'),
'Compression': ('压缩', '壓縮', '圧縮'),
'PNG Filter': ('PNG 滤镜', 'PNG 濾鏡', 'PNG フィルター'),
'Bit Depth': ('位深度', '位元深度', 'ビット深度'),
'Fast': ('快速', '快速', '高速'),
'Best': ('最佳', '最佳', '最高品質'),
'8-Bit': ('8 位', '8 位元', '8 ビット'),
'16-Bit': ('16 位', '16 位元', '16 ビット'),
'Sprite Sheet': ('精灵图', '精靈圖', 'スプライトシート'),
'Generate a Sprite Sheet image.': ('生成精灵图图像。', '產生精靈圖影像。', 'スプライトシート画像を生成します。'),
'Sheet Margin': ('图表边距', '圖表邊距', 'シート余白'),
'Cell Gap': ('单元格间距', '儲存格間距', 'セル間隔'),
'JSON Metadata': ('JSON 元数据', 'JSON 中繼資料', 'JSON メタデータ'),
'JPEG Sequence': ('JPEG 序列', 'JPEG 序列', 'JPEG シーケンス'),
'Generate a JPEG image file.': ('生成 JPEG 图像文件。', '產生 JPEG 影像檔案。', 'JPEG 画像ファイルを生成します。'),
'Quality': ('质量', '品質', '品質'),
'WebP Sequence': ('WebP 序列', 'WebP 序列', 'WebP シーケンス'),
'Generate a WebP image file.': ('生成 WebP 图像文件。', '產生 WebP 影像檔案。', 'WebP 画像ファイルを生成します。'),
'Lottie': ('Lottie', 'Lottie', 'Lottie'),
'Generate a Lottie JSON file.': ('生成 Lottie JSON 文件。', '產生 Lottie JSON 檔案。', 'Lottie JSON ファイルを生成します。'),
'GIF': ('GIF', 'GIF', 'GIF'),
'Generate a GIF file.': ('生成 GIF 文件。', '產生 GIF 檔案。', 'GIF ファイルを生成します。'),
"Sets the maximum number of colours in the output file.\n'256 Colours HQ' mode will try to better preserve gradients, at the expense of performance while exporting.": ('设置输出文件中的最大颜色数。\n“256 色高质量”模式将尝试更好地保留渐变，但会牺牲导出时的性能。', '設定輸出檔案中的最大顏色數。\n「256 色高品質」模式將嘗試更好地保留漸層，但會犧牲匯出時的效能。', '出力ファイルの最大カラー数を設定します。\n「256 色 HQ」モードはグラデーションをより良く保持しようとしますが、エクスポート時のパフォーマンスが低下します。'),
'Black and White (1-bit)': ('黑白（1 位）', '黑白（1 位元）', '白黒（1 ビット）'),
'4 Colours (2-bit)': ('4 色（2 位）', '4 色（2 位元）', '4 色（2 ビット）'),
'16 Colours (4-bit)': ('16 色（4 位）', '16 色（4 位元）', '16 色（4 ビット）'),
'256 Colours (8-bit)': ('256 色（8 位）', '256 色（8 位元）', '256 色（8 ビット）'),
'256 Colours HQ (pseudo 16-bit)': ('256 色高质量（伪 16 位）', '256 色高品質（偽 16 位元）', '256 色 HQ（擬似 16 ビット）'),
'APNG': ('APNG', 'APNG', 'APNG'),
'Generate an APNG file.': ('生成 APNG 文件。', '產生 APNG 檔案。', 'APNG ファイルを生成します。'),
'QuickTime': ('QuickTime', 'QuickTime', 'QuickTime'),
'Generate a QuickTime movie file.': ('生成 QuickTime 影片文件。', '產生 QuickTime 影片檔案。', 'QuickTime ムービーファイルを生成します。'),
'ProRes Codec': ('ProRes 编解码器', 'ProRes 編解碼器', 'ProRes コーデック'),
'ProRes 422 HQ (~220 Mbps at 1920x1080x29.97)\n\nProRes 422 (~145 Mbps at 1920x1080x29.97)\n\nProRes 422 LT (~100 Mbps at 1920x1080x29.97)\n\nProRes 422 Proxy (~ 45 Mbps at 1920x1080x29.97)\n\nProRes 4444 (~330 Mbps at 1920x1080x29.97 excluding alpha)\n\nProRes 4444 XQ (~495 Mbps at 1920x1080x29.97 excluding alpha)': ('ProRes 422 HQ（在 1920x1080x29.97 下约 220 Mbps）\n\nProRes 422（在 1920x1080x29.97 下约 145 Mbps）\n\nProRes 422 LT（在 1920x1080x29.97 下约 100 Mbps）\n\nProRes 422 Proxy（在 1920x1080x29.97 下约 45 Mbps）\n\nProRes 4444（在 1920x1080x29.97 下约 330 Mbps，不含 Alpha）\n\nProRes 4444 XQ（在 1920x1080x29.97 下约 495 Mbps，不含 Alpha）', 'ProRes 422 HQ（在 1920x1080x29.97 下約 220 Mbps）\n\nProRes 422（在 1920x1080x29.97 下約 145 Mbps）\n\nProRes 422 LT（在 1920x1080x29.97 下約 100 Mbps）\n\nProRes 422 Proxy（在 1920x1080x29.97 下約 45 Mbps）\n\nProRes 4444（在 1920x1080x29.97 下約 330 Mbps，不含 Alpha）\n\nProRes 4444 XQ（在 1920x1080x29.97 下約 495 Mbps，不含 Alpha）', 'ProRes 422 HQ（1920x1080x29.97 で約 220 Mbps）\n\nProRes 422（1920x1080x29.97 で約 145 Mbps）\n\nProRes 422 LT（1920x1080x29.97 で約 100 Mbps）\n\nProRes 422 Proxy（1920x1080x29.97 で約 45 Mbps）\n\nProRes 4444（1920x1080x29.97 で約 330 Mbps、Alpha を除く）\n\nProRes 4444 XQ（1920x1080x29.97 で約 495 Mbps、Alpha を除く）'),
'Pro-Res 422 can support 10-Bit rendering, Pro-Res 4444 can support 12-Bit rendering.': ('Pro-Res 422 支持 10 位渲染，Pro-Res 4444 支持 12 位渲染。', 'Pro-Res 422 支援 10 位元算繪，Pro-Res 4444 支援 12 位元算繪。', 'Pro-Res 422 は 10 ビットレンダリングに対応、Pro-Res 4444 は 12 ビットレンダリングに対応しています。'),
'Motion JPEG': ('Motion JPEG', 'Motion JPEG', 'Motion JPEG'),
'Uncompressed 422': ('非压缩 422', '非壓縮 422', '非圧縮 422'),
'ProRes': ('ProRes', 'ProRes', 'ProRes'),
'422 HQ': ('422 HQ', '422 HQ', '422 HQ'),
'422': ('422', '422', '422'),
'422 LT': ('422 LT', '422 LT', '422 LT'),
'422 Proxy': ('422 Proxy', '422 Proxy', '422 Proxy'),
'4444': ('4444', '4444', '4444'),
'4444 XQ': ('4444 XQ', '4444 XQ', '4444 XQ'),
'AAC': ('AAC', 'AAC', 'AAC'),
'Linear PCM': ('Linear PCM', 'Linear PCM', 'Linear PCM'),
'Up to 12-Bit': ('最高 12 位', '最高 12 位元', '最大 12 ビット'),
'Generate a ProRes video file.': ('生成 ProRes 视频文件。', '產生 ProRes 視訊檔案。', 'ProRes ビデオファイルを生成します。'),
'Codec': ('编解码器', '編解碼器', 'コーデック'),
'ProRes 422 HQ': ('ProRes 422 HQ', 'ProRes 422 HQ', 'ProRes 422 HQ'),
'ProRes 422': ('ProRes 422', 'ProRes 422', 'ProRes 422'),
'ProRes 422 LT': ('ProRes 422 LT', 'ProRes 422 LT', 'ProRes 422 LT'),
'ProRes 422 Proxy': ('ProRes 422 Proxy', 'ProRes 422 Proxy', 'ProRes 422 Proxy'),
'ProRes 4444': ('ProRes 4444', 'ProRes 4444', 'ProRes 4444'),
'ProRes 4444 XQ': ('ProRes 4444 XQ', 'ProRes 4444 XQ', 'ProRes 4444 XQ'),
'WebM': ('WebM', 'WebM', 'WebM'),
'Generate a WebM video file.': ('生成 WebM 视频文件。', '產生 WebM 視訊檔案。', 'WebM ビデオファイルを生成します。'),
'Bitrate Presets': ('比特率预设', '位元率預設', 'ビットレートプリセット'),
'Custom Bitrate': ('自定义比特率', '自訂位元率', 'カスタムビットレート'),
'Quality Mode': ('质量模式', '品質模式', '品質モード'),
'VP9': ('VP9', 'VP9', 'VP9'),
'VP8': ('VP8', 'VP8', 'VP8'),
'AV1': ('AV1', 'AV1', 'AV1'),
'Medium': ('中等', '中等', '中'),
'Very High': ('非常高', '非常高', '非常に高い'),
'Custom...': ('自定义...', '自訂...', 'カスタム...'),
'Bitrate': ('比特率', '位元率', 'ビットレート'),
'Generate a video file that includes audio.': ('生成包含音频的视频文件。', '產生包含音訊的視訊檔案。', 'オーディオを含むビデオファイルを生成します。'),
'Audio Quality': ('音频质量', '音訊品質', 'オーディオ品質'),
'Export Audio': ('导出音频', '匯出音訊', 'オーディオをエクスポート'),
'Audio Export is only available with a Professional Licence.': ('音频导出仅在专业许可证下可用。', '音訊匯出僅在專業授權下可用。', 'オーディオエクスポートはプロフェッショナルライセンスでのみ利用可能です。'),
'16 kbps': ('16 kbps', '16 kbps', '16 kbps'),
'64 kbps': ('64 kbps', '64 kbps', '64 kbps'),
'96 kbps': ('96 kbps', '96 kbps', '96 kbps'),
'128 kbps': ('128 kbps', '128 kbps', '128 kbps'),
'192 kbps': ('192 kbps', '192 kbps', '192 kbps'),
'256 kbps': ('256 kbps', '256 kbps', '256 kbps'),
'320 kbps': ('320 kbps', '320 kbps', '320 kbps'),
'512 kbps': ('512 kbps', '512 kbps', '512 kbps'),
'16000 Hz': ('16000 Hz', '16000 Hz', '16000 Hz'),
'22050 Hz': ('22050 Hz', '22050 Hz', '22050 Hz'),
'32000 Hz': ('32000 Hz', '32000 Hz', '32000 Hz'),
'44100 Hz': ('44100 Hz', '44100 Hz', '44100 Hz'),
'48000 Hz': ('48000 Hz', '48000 Hz', '48000 Hz'),
'88200 Hz': ('88200 Hz', '88200 Hz', '88200 Hz'),
'96000 Hz': ('96000 Hz', '96000 Hz', '96000 Hz'),
'192000 Hz': ('192000 Hz', '192000 Hz', '192000 Hz'),
'Color Profile': ('颜色配置文件', '顏色描述檔', 'カラープロファイル'),
'Use Working Space': ('使用工作空间', '使用工作空間', '作業スペースを使用'),
'sRGB': ('sRGB', 'sRGB', 'sRGB'),
'Adobe RGB': ('Adobe RGB', 'Adobe RGB', 'Adobe RGB'),
'Display P3': ('Display P3', 'Display P3', 'Display P3'),
'Rec.2020': ('Rec.2020', 'Rec.2020', 'Rec.2020'),
'Linear sRGB': ('Linear sRGB', 'Linear sRGB', 'Linear sRGB'),
'Audio Only': ('仅音频', '僅音訊', 'オーディオのみ'),
'Generate an audio file.': ('生成音频文件。', '產生音訊檔案。', 'オーディオファイルを生成します。'),
'Container': ('容器', '容器', 'コンテナ'),
'AIFF': ('AIFF', 'AIFF', 'AIFF'),
'Wav': ('Wav', 'Wav', 'Wav'),
'16bit': ('16bit', '16bit', '16bit'),
'32bit': ('32bit', '32bit', '32bit'),
'MP4': ('MP4', 'MP4', 'MP4'),
'Generate an MP4 video file.': ('生成 MP4 视频文件。', '產生 MP4 視訊檔案。', 'MP4 ビデオファイルを生成します。'),
'Encoding Speed': ('编码速度', '編碼速度', 'エンコード速度'),
'Ultra Fast': ('超快', '超快', '超高速'),
'Slow': ('慢速', '慢速', '低速'),
'Very Slow': ('非常慢', '非常慢', '非常に低速'),
'HVEC / H.265': ('HVEC / H.265', 'HVEC / H.265', 'HVEC / H.265'),
'Generate an HVEC (H.265) video file.': ('生成 HVEC (H.265) 视频文件。', '產生 HVEC (H.265) 視訊檔案。', 'HVEC (H.265) ビデオファイルを生成します。'),
'SVG Sequence': ('SVG 序列', 'SVG 序列', 'SVG シーケンス'),
'Generate an SVG file.': ('生成 SVG 文件。', '產生 SVG 檔案。', 'SVG ファイルを生成します。'),
'Include Background': ('包含背景', '包含背景', '背景を含む'),
'Camera': ('摄影机', '攝影機', 'カメラ'),
'Compose and view Shapes within a 2.5D viewport.': ('在 2.5D 视口中合成和查看形状。', '在 2.5D 檢視區中合成和檢視形狀。', '2.5D ビューポート内でシェイプを合成・表示します。'),
'Type': ('类型', '類型', 'タイプ'),
'Position Offset': ('位置偏移', '位置偏移', '位置オフセット'),
'Look At Offset': ('注视偏移', '注視偏移', 'ルックアットオフセット'),
'Look At': ('注视', '注視', 'ルックアット'),
'Zoom': ('缩放', '縮放', 'ズーム'),
'Freeform': ('自由形式', '自由形式', 'フリーフォーム'),
'Guide': ('参考线', '參考線', 'ガイド'),
'A 2d controller (or joystick by any other name).': ('2D 控制器（或称为摇杆）。', '2D 控制器（或稱為搖桿）。', '2D コントローラー（ジョイスティックとも呼ばれます）。'),
"The Rig Control (Joystick) can be connected to attributes such as 'Position' or an Editable Shape's 'Path'.": ('绑定控制器（摇杆）可以连接到“位置”等属性或可编辑形状的“路径”。', '綁定控制器（搖桿）可以連接到「位置」等屬性或可編輯形狀的「路徑」。', 'リグコントロール（ジョイスティック）は「位置」やエディタブルシェイプの「パス」などの属性に接続できます。'),
'Control': ('控制', '控制', 'コントロール'),
'Pre-Comp': ('预合成', '預合成', 'プリコンプ'),
'A Pre-Comp is a referenced Composition.': ('预合成是一个被引用的合成。', '預合成是一個被參考的合成。', 'プリコンプは参照されたコンポジションです。'),
'Time Offset': ('时间偏移', '時間偏移', '時間オフセット'),
'Composition Length': ('合成长度', '合成長度', 'コンポジション長'),
"To add a Pre-Comp Override, right click an Attribute on a Layer within its Composition and choose 'Add Pre-Comp Override'. That Attribute will then appear in this list.": ('要添加预合成覆盖，请右键单击其合成内图层上的属性，然后选择“添加预合成覆盖”。该属性随后将出现在此列表中。', '要新增預合成覆寫，請右鍵點擊其合成內圖層上的屬性，然後選擇「新增預合成覆寫」。該屬性隨後將出現在此列表中。', 'プリコンプオーバーライドを追加するには、コンポジション内のレイヤーの属性を右クリックし、「プリコンプオーバーライドを追加」を選択します。その属性がこのリストに表示されます。'),
'Attribute': ('属性', '屬性', '属性'),
'Use Override': ('使用覆盖', '使用覆寫', 'オーバーライドを使用'),
'Value2': ('Value2', 'Value2', 'Value2'),
'String': ('字符串', '字串', '文字列'),
'Font': ('字体', '字型', 'フォント'),
'Rich Text': ('富文本', '富文字', 'リッチテキスト'),
'Name': ('名称', '名稱', '名前'),
'Notes': ('备注', '備註', 'ノート'),
'When this is checked, layers inside the Composition will not be masked by the Composition boundary.': ('勾选后，合成内的图层将不会被合成边界蒙版。', '勾選後，合成內的圖層將不會被合成邊界遮罩。', 'チェックすると、コンポジション内のレイヤーはコンポジション境界でマスクされなくなります。'),
'Preserve Frame Rate': ('保留帧率', '保留幀率', 'フレームレートを保持'),
'When set, the pre-composition will retain its own frame rate.': ('设置后，预合成将保留其自身的帧率。', '設定後，預合成將保留其自身的幀率。', '設定すると、プリコンポジションは独自のフレームレートを保持します。'),
'Viewport Zoom Aware': ('视口缩放感知', '檢視區縮放感知', 'ビューポートズーム対応'),
'Re-render at higher resolution when the viewport is zoomed in. May impact performance.': ('当视口放大时以更高分辨率重新渲染。可能会影响性能。', '當檢視區放大時以更高解析度重新算繪。可能會影響效能。', 'ビューポートがズームインされた場合、より高い解像度で再レンダリングします。パフォーマンスに影響する可能性があります。'),
'Overrides': ('覆盖', '覆寫', 'オーバーライド'),
'Create a list of colors which can be assigned to other layers via their indices.': ('创建颜色列表，可通过索引分配给其他图层。', '建立顏色列表，可透過索引分配給其他圖層。', 'インデックスを通じて他のレイヤーに割り当てることができるカラーリストを作成します。'),
'Dynamic Index Offset': ('动态索引偏移', '動態索引偏移', 'ダイナミックインデックスオフセット'),
'A Shape with points that can be manipulated using the Edit Shape tool or the drawing tools.': ('一个可以使用编辑形状工具或绘图工具操纵其点的形状。', '一個可以使用編輯形狀工具或繪圖工具操縱其點的形狀。', '編集シェイプツールや描画ツールを使用してポイントを操作できるシェイプ。'),
'Animate Path': ('动画路径', '動畫路徑', 'パスをアニメーション'),
'Fill Rule': ('填充规则', '填充規則', '塗りルール'),
'Onion Skinning': ('洋葱皮', '洋蔥皮', 'オニオンスキン'),
'Even Odd': ('奇偶', '奇偶', '奇偶'),
'Winding': ('环绕', '環繞', 'ワインディング'),
'Extend the ends of open Paths along their tangent or a specified angle.': ('沿切线或指定角度延伸开放路径的端点。', '沿切線或指定角度延伸開放路徑的端點。', '開いたパスの端点を接線方向または指定した角度に沿って延長します。'),
'Extend Start': ('延伸起点', '延伸起點', '開始点を延長'),
'Extend End': ('延伸终点', '延伸終點', '終了点を延長'),
'Length Mode': ('长度模式', '長度模式', '長さモード'),
'Angle Mode': ('角度模式', '角度模式', '角度モード'),
'Start Angle': ('起始角度', '起始角度', '開始角度'),
'End Angle': ('终止角度', '終止角度', '終了角度'),
'Arc Radius': ('弧半径', '弧半徑', '円弧半径'),
'Arc Sweep Angle': ('弧扫描角度', '弧掃描角度', '円弧スイープ角度'),
'Arc Direction': ('弧方向', '弧方向', '円弧方向'),
'Opposite Direction for End': ('终点反向', '終點反向', '終点を逆方向に'),
'Flip the arc direction for the end extension (relative to start).': ('翻转终点延伸的弧方向（相对于起点）。', '翻轉終點延伸的弧方向（相對於起點）。', '終了延長の円弧方向を反転します（開始点を基準）。'),
'Pixels': ('像素', '像素', 'ピクセル'),
'Percentage of Length': ('长度百分比', '長度百分比', '長さの割合'),
'Path Tangent': ('路径切线', '路徑切線', 'パス接線'),
'Path Curvature': ('路径曲率', '路徑曲率', 'パス曲率'),
'Arc': ('弧', '弧', '円弧'),
'Inverted': ('反转', '反轉', '反転'),
'Auto (from Curvature)': ('自动（基于曲率）', '自動（基於曲率）', '自動（曲率から）'),
'Deform Shapes using a flexible grid of control points.': ('使用灵活的控制点网格变形形状。', '使用靈活的控制點網格變形形狀。', '柔軟な制御点グリッドを使用してシェイプを変形します。'),
'Grid Count': ('网格数量', '網格數量', 'グリッド数'),
'Number of control points in X and Y dimensions.': ('X 和 Y 维度中的控制点数量。', 'X 和 Y 維度中的控制點數量。', 'X および Y 方向の制御点の数。'),
'Bounds': ('边界', '邊界', '境界'),
'The rectangular area covered by the lattice deformer.': ('晶格变形器覆盖的矩形区域。', '晶格變形器覆蓋的矩形區域。', 'ラティスデフォーマがカバーする矩形領域。'),
'Control Point Offsets': ('控制点偏移', '控制點偏移', '制御点オフセット'),
'Offsets for each control point in the lattice grid.': ('晶格网格中每个控制点的偏移量。', '晶格網格中每個控制點的偏移量。', 'ラティスグリッド内の各制御点のオフセット。'),
'Connect Behaviours to procedurally modify the lattice control points.': ('连接行为以程序化修改晶格控制点。', '連接行為以程序化修改晶格控制點。', 'ビヘイビアを接続してラティス制御点をプロシージャルに変更します。'),
'Constraints': ('约束', '約束', '制約'),
'Connect Lattice Constraints to control groups of lattice points with transforms.': ('连接晶格约束以使用变换控制晶格点组。', '連接晶格約束以使用變換控制晶格點群組。', 'ラティス制約を接続して、トランスフォームでラティスポイントのグループを制御します。'),
'Controls the intensity of the deformation effect.': ('控制变形效果的强度。', '控制變形效果的強度。', '変形効果の強度を制御します。'),
'Triangulate': ('三角化', '三角化', '三角化'),
'Triangulate the Shape to enable texture deformation support.': ('对形状进行三角化以支持纹理变形。', '對形狀進行三角化以支援紋理變形。', 'シェイプを三角化してテクスチャ変形のサポートを有効にします。'),
'Lattice Controller': ('晶格控制器', '晶格控制器', 'ラティスコントローラー'),
'Manipulate multiple lattice points using position, rotation, and scale.': ('使用位置、旋转和缩放来操纵多个晶格点。', '使用位置、旋轉和縮放來操縱多個晶格點。', '位置、回転、スケールを使用して複数のラティスポイントを操作します。'),
'Bind': ('绑定', '綁定', 'バインド'),
'Enable to calculate and store the bind position and offsets for the controlled points.': ('启用以计算并存储受控点的绑定位置和偏移量。', '啟用以計算並儲存受控點的綁定位置和偏移量。', '制御ポイントのバインド位置とオフセットを計算して保存することを有効にします。'),
'Pivot Offset': ('锚点偏移', '錨點偏移', 'ピボットオフセット'),
'Offset the centre point of controlled points.': ('偏移受控点的中心点。', '偏移受控點的中心點。', '制御ポイントの中心点をオフセットします。'),
'Position offset for the controller transform.': ('控制器变换的位置偏移。', '控制器變換的位置偏移。', 'コントローラートランスフォームの位置オフセット。'),
'Rotation for the controller transform (in degrees).': ('控制器变换的旋转（以度为单位）。', '控制器變換的旋轉（以度為單位）。', 'コントローラートランスフォームの回転（度単位）。'),
'Scale for the controller transform.': ('控制器变换的缩放。', '控制器變換的縮放。', 'コントローラートランスフォームのスケール。'),
'Blend amount between bind state and transformed state.': ('绑定状态和变换状态之间的混合量。', '綁定狀態和變換狀態之間的混合量。', 'バインド状態とトランスフォーム状態間のブレンド量。'),
'Deform Shapes using a 4-corner warp with bézier handles.': ('使用带贝塞尔手柄的四角变形来变形形状。', '使用帶貝茲控制柄的四角變形來變形形狀。', 'ベジェハンドル付きの 4 コーナーワープを使用してシェイプを変形します。'),
'Center point of the warp.': ('变形的中心点。', '變形的中心點。', 'ワープの中心点。'),
'Size': ('尺寸', '尺寸', 'サイズ'),
'Width and height of the warp.': ('变形的宽度和高度。', '變形的寬度和高度。', 'ワープの幅と高さ。'),
'Top-Left': ('左上', '左上', '左上'),
'Position and tangent handles for the top-left corner.': ('左上角的位置和切线手柄。', '左上角的位置和切線控制柄。', '左上コーナーの位置とタンジェントハンドル。'),
'Top-Left In Handle': ('左上入控制柄', '左上入控制柄', '左上イン・ハンドル'),
'Top-Left Out Handle': ('左上出控制柄', '左上出控制柄', '左上アウト・ハンドル'),
'Top-Right': ('右上', '右上', '右上'),
'Position and tangent handles for the top-right corner.': ('右上角的位置和切线手柄。', '右上角的位置和切線控制柄。', '右上コーナーの位置とタンジェントハンドル。'),
'Top-Right In Handle': ('右上入控制柄', '右上入控制柄', '右上イン・ハンドル'),
'Top-Right Out Handle': ('右上出控制柄', '右上出控制柄', '右上アウト・ハンドル'),
'Bottom-Right': ('右下', '右下', '右下'),
'Position and tangent handles for the bottom-right corner.': ('右下角的位置和切线手柄。', '右下角的位置和切線控制柄。', '右下コーナーの位置とタンジェントハンドル。'),
'Bottom-Right In Handle': ('右下入控制柄', '右下入控制柄', '右下イン・ハンドル'),
'Bottom-Right Out Handle': ('右下出控制柄', '右下出控制柄', '右下アウト・ハンドル'),
'Bottom-Left': ('左下', '左下', '左下'),
'Position and tangent handles for the bottom-left corner.': ('左下角的位置和切线手柄。', '左下角的位置和切線控制柄。', '左下コーナーの位置とタンジェントハンドル。'),
'Bottom-Left In Handle': ('左下入控制柄', '左下入控制柄', '左下イン・ハンドル'),
'Bottom-Left Out Handle': ('左下出控制柄', '左下出控制柄', '左下アウト・ハンドル'),
'Choose the tessellation density for mesh deformation.': ('选择网格变形的细分密度。', '選擇網格變形的細分密度。', 'メッシュ変形のテッセレーション密度を選択します。'),
'Mesh Spacing': ('网格间距', '網格間距', 'メッシュ間隔'),
'Pixel spacing between mesh samples when Mesh Quality is set to Custom.': ('当网格质量设置为自定义时，网格样本之间的像素间距。', '當網格品質設定為自訂時，網格樣本之間的像素間距。', 'メッシュ品質がカスタムに設定されている場合のメッシュサンプル間のピクセル間隔。'),
'Controls the intensity of the warp effect.': ('控制变形效果的强度。', '控制變形效果的強度。', 'ワープ効果の強度を制御します。'),
'Custom': ('自定义', '自訂', 'カスタム'),
'Generate noise patterns to deform Shapes or affect other Attributes.': ('生成噪波图案以变形形状或影响其他属性。', '產生雜訊圖案以變形形狀或影響其他屬性。', 'ノイズパターンを生成してシェイプを変形したり、他の属性に影響を与えます。'),
'Noise Type': ('噪波类型', '雜訊類型', 'ノイズタイプ'),
'Strength Fades to Zero': ('强度渐变至零', '強度漸變至零', '強度がゼロにフェード'),
'Fractal Type': ('分形类型', '碎形類型', 'フラクタルタイプ'),
'Interpolation': ('插值', '插值', '補間'),
'Minimum': ('最小值', '最小值', '最小値'),
'Maximum': ('最大值', '最大值', '最大値'),
'Frequency': ('频率', '頻率', '周波数'),
'Separate Channels': ('分离通道', '分離通道', 'チャンネル分離'),
'Stagger': ('错开', '錯開', 'スタガー'),
'Time Scale': ('时间缩放', '時間縮放', 'タイムスケール'),
'Noise Position': ('噪波位置', '雜訊位置', 'ノイズ位置'),
'Noise Rotation': ('噪波旋转', '雜訊旋轉', 'ノイズ回転'),
'Noise Scale': ('噪波缩放', '雜訊縮放', 'ノイズスケール'),
'Seed': ('随机种子', '隨機種子', 'シード'),
'Loop Length': ('循环长度', '循環長度', 'ループ長'),
'Use Index Context': ('使用索引上下文', '使用索引上下文', 'インデックスコンテキストを使用'),
'Use Position Context': ('使用位置上下文', '使用位置上下文', '位置コンテキストを使用'),
'Uses the Position Context when sampling the noise field.': ('在采样噪波场时使用位置上下文。', '在取樣雜訊場時使用位置上下文。', 'ノイズフィールドのサンプリング時に位置コンテキストを使用します。'),
'Use Layer as Seed': ('使用图层作为种子', '使用圖層作為種子', 'レイヤーをシードとして使用'),
'Each layer will automatically be given a different seed value, this can be used in combination with Seed.': ('每个图层将自动获得不同的种子值，这可以与随机种子结合使用。', '每個圖層將自動獲得不同的種子值，這可以與隨機種子結合使用。', '各レイヤーには自動的に異なるシード値が割り当てられます。これはシードと組み合わせて使用できます。'),
'FBM': ('FBM', 'FBM', 'FBM'),
'Billow': ('膨胀', '膨脹', 'ビロウ'),
'Ridgid': ('山脊', '山脊', 'リッジ'),
'Linear': ('线性', '線性', 'リニア'),
'Hermite': ('Hermite', 'Hermite', 'エルミート'),
'Quintic': ('Quintic', 'Quintic', 'クインティック'),
'Settings': ('设置', '設定', '設定'),
'Simplex Noise': ('单纯形噪波', '單純形雜訊', 'シンプレックスノイズ'),
'Generate a Simplex Noise pattern.': ('生成单纯形噪波图案。', '產生單純形雜訊圖案。', 'シンプレックスノイズパターンを生成します。'),
}
