T = {
"Math": ("数学", "數學", "数学"),
"Distribute points using mathematical expressions.": ("使用数学表达式分布点。", "使用數學表達式分佈點。", "数式を使用してポイントを分布します。"),
"Mask": ("蒙版", "遮罩", "マスク"),
"Distribute points and remove any that fall outside another Shape.": ("分布点并移除落在另一个形状外部的点。", "分佈點並移除落在另一個形狀外部的點。", "ポイントを分布し、別のシェイプの外側にあるポイントを削除します。"),
"Shuffle": ("随机排列", "隨機排列", "シャッフル"),
"Distribute points by rearranging the Ids of a sub-mesh.": ("通过重新排列子网格的 ID 来分布点。", "透過重新排列子網格的 ID 來分佈點。", "サブメッシュの ID を並べ替えてポイントを分布します。"),
"Distribution Masks": ("分布蒙版", "分佈遮罩", "分布マスク"),
"Sort": ("排序", "排序", "ソート"),
"Distribute points by reordering the Ids of another Distribution.": ("通过重新排列另一个分布的 ID 来分布点。", "透過重新排列另一個分佈的 ID 來分佈點。", "別の分布の ID を並べ替えてポイントを分布します。"),
"Distance From Centroid": ("到质心的距离", "到質心的距離", "重心からの距離"),
"Distance From Target": ("到目标的距离", "到目標的距離", "ターゲットからの距離"),
"Fibonacci": ("斐波那契", "費氏", "フィボナッチ"),
"Distribute points in a Fibonacci spiral pattern.": ("以斐波那契螺旋图案分布点。", "以費氏螺旋圖案分佈點。", "フィボナッチ螺旋パターンでポイントを分布します。"),
"Corner Divisions": ("角分段", "角分段", "コーナー分割"),
"Edge Divisions": ("边分段", "邊分段", "エッジ分割"),
"Vectorize": ("矢量化", "向量化", "ベクター化"),
"Polygon": ("多边形", "多邊形", "ポリゴン"),
"Generate a Polygon primitive.": ("生成多边形基本体。", "產生多邊形基本體。", "ポリゴンプリミティブを生成します。"),
"Super Ellipse": ("超椭圆", "超橢圓", "スーパー楕円"),
"Generate a Super Ellipse primitive.": ("生成超椭圆基本体。", "產生超橢圓基本體。", "スーパー楕円プリミティブを生成します。"),
"Push": ("推送", "推送", "プッシュ"),
"Béziers": ("贝塞尔", "貝茲", "ベジェ"),
"Super Shape": ("超级形状", "超級形狀", "スーパーシェイプ"),
"Generate a Super Shape primitive.": ("生成超级形状基本体。", "產生超級形狀基本體。", "スーパーシェイプのプリミティブを生成します。"),
"Complexity": ("复杂度", "複雜度", "複雑度"),
"n1": ("n1", "n1", "n1"),
"n2": ("n2", "n2", "n2"),
"n3": ("n3", "n3", "n3"),
"a": ("a", "a", "a"),
"b": ("b", "b", "b"),
"Squircle": ("方圆形", "方圓形", "スクワークル"),
"Generate a Squircle primitive.": ("生成方圆形基本体。", "產生方圓形基本體。", "スクワークルプリミティブを生成します。"),
"Corner Smoothing": ("圆角平滑", "圓角平滑", "コーナースムージング"),
"Star": ("星形", "星形", "スター"),
"Generate a Star primitive.": ("生成星形基本体。", "產生星形基本體。", "スタープリミティブを生成します。"),
"Use Inner Radius": ("使用内半径", "使用內半徑", "内側半径を使用"),
"Use Individual Radii": ("使用独立半径", "使用獨立半徑", "個別の半径を使用"),
"Apply behaviours to the radius of each side individually.": ("将行为分别应用于每条边的半径。", "將行為分別套用於每條邊的半徑。", "各辺の半径に個別にビヘイビアを適用します。"),
"Generate an Arc primitive.": ("生成圆弧基本体。", "產生圓弧基本體。", "円弧プリミティブを生成します。"),
"Set the number of divisions between points. This is particularly useful for creating smoother deformations.": ("设置点之间的分段数。这对于创建更平滑的变形特别有用。", "設定點之間的分段數。這對於建立更平滑的變形特別有用。", "ポイント間の分割数を設定します。より滑らかなデフォーメーションを作成するのに特に便利です。"),
"Set the inner radius of the circle the arc is drawn around.": ("设置圆弧所绘制的圆的内半径。", "設定圓弧所繪製的圓的內半徑。", "円弧が描かれる円の内側半径を設定します。"),
"Set the angle the curve starts at.": ("设置曲线的起始角度。", "設定曲線的起始角度。", "カーブの開始角度を設定します。"),
"Set the angle the curve ends at.": ("设置曲线的结束角度。", "設定曲線的結束角度。", "カーブの終了角度を設定します。"),
"When checked the Arc is created with bézier points.": ("勾选后，圆弧将使用贝塞尔点创建。", "勾選後，圓弧將使用貝茲點建立。", "チェックすると、円弧がベジェポイントで作成されます。"),
"Ring": ("环形", "環形", "リング"),
"Generate a Ring primitive.": ("生成环形基本体。", "產生環形基本體。", "リングプリミティブを生成します。"),
"Generate an Ellipse primitive.": ("生成椭圆基本体。", "產生橢圓基本體。", "楕円プリミティブを生成します。"),
"Semicircle": ("半圆", "半圓", "半円"),
"Capsule": ("胶囊形", "膠囊形", "カプセル"),
"Generate a Capsule primitive.": ("生成胶囊形基本体。", "產生膠囊形基本體。", "カプセルプリミティブを生成します。"),
"Trim Ends": ("修剪端点", "修剪端點", "トリムエンド"),
"Start/End": ("起点/终点", "起點/終點", "開始/終了"),
"Random Date": ("随机日期", "隨機日期", "ランダム日付"),
"Generate a Random Date for the String Generator.": ("为字符串生成器生成随机日期。", "為字串產生器產生隨機日期。", "文字列ジェネレーター用のランダム日付を生成します。"),
"Start Date": ("开始日期", "開始日期", "開始日"),
"End Date": ("结束日期", "結束日期", "終了日"),
"Formatting": ("格式化", "格式化", "フォーマット"),
"DD MM YYYY": ("DD MM YYYY", "DD MM YYYY", "DD MM YYYY"),
"MM DD YYYY": ("MM DD YYYY", "MM DD YYYY", "MM DD YYYY"),
"YYYY MM DD": ("YYYY MM DD", "YYYY MM DD", "YYYY MM DD"),
"Block": ("块", "區塊", "ブロック"),
"Generates hierarchically structured text with configurable paragraph, line, word, and character counts.": ("生成具有可配置段落、行、词和字符数的分层结构文本。", "產生具有可配置段落、行、詞和字元數的階層結構文字。", "段落、行、単語、文字数を設定可能な階層構造テキストを生成します。"),
"Paragraphs": ("段落", "段落", "段落"),
"Number of paragraphs to generate.": ("要生成的段落数。", "要產生的段落數。", "生成する段落数。"),
"Lines": ("行", "行", "行"),
"Number of lines per paragraph. Connect a behaviour for variation.": ("每段的行数。连接行为以产生变化。", "每段的行數。連接行為以產生變化。", "段落ごとの行数。バリエーションのためにビヘイビアを接続してください。"),
"Words": ("词", "詞", "単語"),
"Number of words per line. Connect a behaviour for variation.": ("每行的词数。连接行为以产生变化。", "每行的詞數。連接行為以產生變化。", "行ごとの単語数。バリエーションのためにビヘイビアを接続してください。"),
"Characters": ("字符", "字元", "文字"),
"Number of characters per word. Connect a behaviour for variation.": ("每词的字符数。连接行为以产生变化。", "每詞的字元數。連接行為以產生變化。", "単語ごとの文字数。バリエーションのためにビヘイビアを接続してください。"),
"Choose between Unicode code points or string characters.": ("在 Unicode 码位或字符串字符之间选择。", "在 Unicode 碼位或字串字元之間選擇。", "Unicode コードポイントまたは文字列の文字から選択します。"),
"Code Point": ("码位", "碼位", "コードポイント"),
"Unicode code point for the character. Connect a behaviour for variation based on position.": ("字符的 Unicode 码位。连接行为以基于位置产生变化。", "字元的 Unicode 碼位。連接行為以基於位置產生變化。", "文字の Unicode コードポイント。位置に基づくバリエーションのためにビヘイビアを接続してください。"),
"The character or string to use. Connect a generator for variation based on position.": ("要使用的字符或字符串。连接生成器以基于位置产生变化。", "要使用的字元或字串。連接產生器以基於位置產生變化。", "使用する文字または文字列。位置に基づくバリエーションのためにジェネレーターを接続してください。"),
"Word Delimiter": ("词分隔符", "詞分隔符", "単語区切り"),
"Separator between words.": ("词之间的分隔符。", "詞之間的分隔符。", "単語間のセパレーター。"),
"Line Delimiter": ("行分隔符", "行分隔符", "行区切り"),
"Separator between lines.": ("行之间的分隔符。", "行之間的分隔符。", "行間のセパレーター。"),
"Paragraph Delimiter": ("段落分隔符", "段落分隔符", "段落区切り"),
"Separator between paragraphs.": ("段落之间的分隔符。", "段落之間的分隔符。", "段落間のセパレーター。"),
"Unicode Code Point": ("Unicode 码位", "Unicode 碼位", "Unicode コードポイント"),
"Formatted Date and Time": ("格式化日期和时间", "格式化日期和時間", "書式付き日付と時刻"),
"Generate a string using Date and Time tokens with the String Generator.": ("使用字符串生成器通过日期和时间标记生成字符串。", "使用字串產生器透過日期和時間標記產生字串。", "文字列ジェネレーターで日付と時刻のトークンを使用して文字列を生成します。"),
"Formatted String": ("格式化字符串", "格式化字串", "書式付き文字列"),
"Generate concatenated strings with the String Generator.": ("使用字符串生成器生成连接的字符串。", "使用字串產生器產生連接的字串。", "文字列ジェネレーターで連結文字列を生成します。"),
"Chart": ("图表", "圖表", "チャート"),
"Chart Type": ("图表类型", "圖表類型", "チャートタイプ"),
"Line Chart": ("折线图", "折線圖", "折れ線グラフ"),
"X Axis": ("X 轴", "X 軸", "X 軸"),
"Y Axis": ("Y 轴", "Y 軸", "Y 軸"),
"A Shape which resizes to the resolution of its Composition.": ("一个会调整大小以匹配其合成分辨率的形状。", "一個會調整大小以符合其合成解析度的形狀。", "コンポジションの解像度に合わせてリサイズするシェイプ。"),
"Shrink": ("收缩", "收縮", "縮小"),
"Use the Mesh Tool in combination with this Shape to warp images and shaders.": ("将网格工具与此形状结合使用来变形图像和着色器。", "將網格工具與此形狀結合使用來變形影像和著色器。", "メッシュツールとこのシェイプを組み合わせて、画像やシェーダーをワープさせます。"),
"Mesh": ("网格", "網格", "メッシュ"),
"When checked, the Shape is converted to a mesh and so can be deformed by adding vertices with the Mesh tool.": ("勾选后，形状将转换为网格，因此可以通过使用网格工具添加顶点来进行变形。", "勾選後，形狀將轉換為網格，因此可以透過使用網格工具新增頂點來進行變形。", "チェックすると、シェイプがメッシュに変換され、メッシュツールで頂点を追加してデフォームできるようになります。"),
"Set the size of the Shape.": ("设置形状的大小。", "設定形狀的大小。", "シェイプのサイズを設定します。"),
"Vertices": ("顶点", "頂點", "頂点"),
"Open a popover window containing a list of the mesh vertices.": ("打开一个包含网格顶点列表的弹出窗口。", "開啟一個包含網格頂點列表的彈出視窗。", "メッシュ頂点のリストを含むポップオーバーウィンドウを開きます。"),
"Top Left Offset": ("左上偏移", "左上偏移", "左上オフセット"),
"Set a position offset for the Shape's top left corner.": ("设置形状左上角的位置偏移。", "設定形狀左上角的位置偏移。", "シェイプの左上隅の位置オフセットを設定します。"),
"Top Right Offset": ("右上偏移", "右上偏移", "右上オフセット"),
"Set a position offset for the Shape's top right corner.": ("设置形状右上角的位置偏移。", "設定形狀右上角的位置偏移。", "シェイプの右上隅の位置オフセットを設定します。"),
"Bottom Left Offset": ("左下偏移", "左下偏移", "左下オフセット"),
"Set a position offset for the Shape's bottom left corner.": ("设置形状左下角的位置偏移。", "設定形狀左下角的位置偏移。", "シェイプの左下隅の位置オフセットを設定します。"),
"Bottom Right Offset": ("右下偏移", "右下偏移", "右下オフセット"),
"Set a position offset for the Shape's bottom right corner.": ("设置形状右下角的位置偏移。", "設定形狀右下角的位置偏移。", "シェイプの右下隅の位置オフセットを設定します。"),
"Bind Position": ("绑定位置", "綁定位置", "バインド位置"),
"Set the starting position for the vertex.": ("设置顶点的起始位置。", "設定頂點的起始位置。", "頂点の開始位置を設定します。"),
"Set values to offset the vertex's position from its Bind Position.": ("设置值以将顶点的位置从其绑定位置偏移。", "設定值以將頂點的位置從其綁定位置偏移。", "頂点の位置をバインド位置からオフセットする値を設定します。"),
"Bind Path": ("绑定路径", "綁定路徑", "バインドパス"),
"Offset Path": ("偏移路径", "偏移路徑", "オフセットパス"),
"Controllers": ("控制器", "控制器", "コントローラー"),
"Add Falloffs which can be used to affect groups of vertices.": ("添加衰减以用于影响顶点组。", "新增衰減以用於影響頂點群組。", "頂点グループに影響を与えるフォールオフを追加します。"),
"Generate trails (lines) from Shape movement.": ("从形状运动生成轨迹（线条）。", "從形狀運動產生軌跡（線條）。", "シェイプの動きからトレイル（線）を生成します。"),
"Limit Length": ("限制长度", "限制長度", "長さを制限"),
"Path Type": ("路径类型", "路徑類型", "パスタイプ"),
"Create frame-by-frame animation.": ("创建逐帧动画。", "建立逐幀動畫。", "フレームごとのアニメーションを作成します。"),
"Post Steps": ("后续步骤", "後續步驟", "ポストステップ"),
"Pre Steps": ("前置步骤", "前置步驟", "プリステップ"),
"Pre Tint": ("前置着色", "前置著色", "プリティント"),
"Post Tint": ("后置着色", "後置著色", "ポストティント"),
"Create a Shape that encompasses other Shapes.": ("创建一个包含其他形状的形状。", "建立一個包含其他形狀的形狀。", "他のシェイプを包含するシェイプを作成します。"),
"Points to Path": ("点到路径", "點到路徑", "ポイントからパス"),
"Create a path using the points within a Distribution.": ("使用分布中的点创建路径。", "使用分佈中的點建立路徑。", "分布内のポイントを使用してパスを作成します。"),
"Point Source": ("点源", "點來源", "ポイントソース"),
"Close": ("闭合", "閉合", "閉じる"),
"Use a Distribution to subdivide a square into smaller squares depending on the density of points.": ("使用分布根据点的密度将正方形细分为更小的正方形。", "使用分佈根據點的密度將正方形細分為更小的正方形。", "分布を使用して、ポイントの密度に応じて正方形をより小さな正方形に分割します。"),
"Max. Iterations": ("最大迭代次数", "最大迭代次數", "最大反復回数"),
"Distribute points onto the position of a Layer.": ("将点分布到图层的位置上。", "將點分佈到圖層的位置上。", "レイヤーの位置にポイントを分布します。"),
"Cogwheel": ("齿轮", "齒輪", "コグホイール"),
"Generate a Cogwheel (cog/gear) primitive.": ("生成齿轮基本体。", "產生齒輪基本體。", "コグホイール（歯車）プリミティブを生成します。"),
"Teeth": ("齿数", "齒數", "歯数"),
"Pitch Radius": ("节圆半径", "節圓半徑", "ピッチ半径"),
"Tooth Depth": ("齿深", "齒深", "歯の深さ"),
"Tooth Width": ("齿宽", "齒寬", "歯の幅"),
"Taper": ("锥度", "錐度", "テーパー"),
"Hole Radius": ("孔半径", "孔半徑", "穴の半径"),
"Midpoint Position": ("中点位置", "中點位置", "中間点位置"),
"Cogwheel (Gear)": ("齿轮", "齒輪", "コグホイール（歯車）"),
"Tooth Taper": ("齿锥度", "齒錐度", "歯のテーパー"),
"Arrow": ("箭头", "箭頭", "矢印"),
"Generate an Arrow primitive.": ("生成箭头基本体。", "產生箭頭基本體。", "矢印プリミティブを生成します。"),
"Body Length": ("主体长度", "主體長度", "ボディの長さ"),
"Body Width": ("主体宽度", "主體寬度", "ボディの幅"),
"First End": ("第一端", "第一端", "最初の端"),
"Second End": ("第二端", "第二端", "2番目の端"),
"Generate an Arrow end for the Arrow Primitive.": ("为箭头基本体生成箭头端。", "為箭頭基本體產生箭頭端。", "矢印プリミティブ用の矢印端を生成します。"),
"End Length": ("端部长度", "端部長度", "端の長さ"),
"Arrow Width": ("箭头宽度", "箭頭寬度", "矢印の幅"),
"Arrow Length": ("箭头长度", "箭頭長度", "矢印の長さ"),
"Chevron": ("折线", "折線", "シェブロン"),
"Generate a Chevron end for the Arrow Primitive.": ("为箭头基本体生成折线端。", "為箭頭基本體產生折線端。", "矢印プリミティブ用のシェブロン端を生成します。"),
"Chevron Width": ("折线宽度", "折線寬度", "シェブロンの幅"),
"Chevron Length": ("折线长度", "折線長度", "シェブロンの長さ"),
"Chevron Position": ("折线位置", "折線位置", "シェブロン位置"),
"Barbed": ("倒刺", "倒刺", "バーブ"),
"Generate a Barbed end for the Arrow Primitive.": ("为箭头基本体生成倒刺端。", "為箭頭基本體產生倒刺端。", "矢印プリミティブ用のバーブ端を生成します。"),
"Barb Width": ("倒刺宽度", "倒刺寬度", "バーブの幅"),
"Barb Position": ("倒刺位置", "倒刺位置", "バーブ位置"),
"Generate a Circular end for the Arrow Primitive.": ("为箭头基本体生成圆形端。", "為箭頭基本體產生圓形端。", "矢印プリミティブ用の円形端を生成します。"),
"Hole": ("孔", "孔", "穴"),
"Hole Size": ("孔大小", "孔大小", "穴のサイズ"),
"Box": ("方形", "方形", "ボックス"),
"Generate a Box end for the Arrow Primitive.": ("为箭头基本体生成方形端。", "為箭頭基本體產生方形端。", "矢印プリミティブ用のボックス端を生成します。"),
"Timecode": ("时间码", "時間碼", "タイムコード"),
"Generate a Timecode for the String Generator.": ("为字符串生成器生成时间码。", "為字串產生器產生時間碼。", "文字列ジェネレーター用のタイムコードを生成します。"),
"Frames per Second": ("每秒帧数", "每秒幀數", "フレーム/秒"),
"Delimeter": ("分隔符", "分隔符", "区切り文字"),
"Remap input values within one range to another range.": ("将输入值从一个范围重映射到另一个范围。", "將輸入值從一個範圍重新對應到另一個範圍。", "入力値を1つの範囲から別の範囲にリマップします。"),
"Source Minimum": ("源最小值", "來源最小值", "ソース最小値"),
"Source Maximum": ("源最大值", "來源最大值", "ソース最大値"),
"Remap input values within a range to a gradient.": ("将范围内的输入值重映射到渐变。", "將範圍內的輸入值重新對應到漸層。", "範囲内の入力値をグラデーションにリマップします。"),
"Number Range": ("数值范围", "數值範圍", "数値範囲"),
"Number Range To Color": ("数值范围到颜色", "數值範圍到顏色", "数値範囲からカラーへ"),
"Remove unwanted points to optimise path topology.": ("移除不需要的点以优化路径拓扑。", "移除不需要的點以最佳化路徑拓撲。", "不要なポイントを削除してパストポロジーを最適化します。"),
"Use Distance": ("使用距离", "使用距離", "距離を使用"),
"Use Angle": ("使用角度", "使用角度", "角度を使用"),
"Remove overlapping contours and/or simplify a path. Open paths will be closed.": ("移除重叠轮廓和/或简化路径。开放路径将被闭合。", "移除重疊輪廓和/或簡化路徑。開放路徑將被閉合。", "重なり合う輪郭を削除したりパスを簡略化します。オープンパスは閉じられます。"),
"Merge Overlaps": ("合并重叠", "合併重疊", "オーバーラップを結合"),
"Resample as Béziers": ("重采样为贝塞尔", "重新取樣為貝茲", "ベジェとして再サンプリング"),
"Simplify": ("简化", "簡化", "簡略化"),
"Simplify Threshold": ("简化阈值", "簡化閾值", "簡略化しきい値"),
"Corner Angle": ("角度", "角度", "コーナー角度"),
"Union": ("联合", "聯合", "結合"),
"Measure the distance between two Shapes.": ("测量两个形状之间的距离。", "測量兩個形狀之間的距離。", "2つのシェイプ間の距離を測定します。"),
"First Target": ("第一目标", "第一目標", "最初のターゲット"),
"Second Target": ("第二目标", "第二目標", "2番目のターゲット"),
"Extract and send the index of this Layer to the inputs of Layers such as the Duplicator and Connect Shape.": ("提取此图层的索引并发送到复制器和连接形状等图层的输入。", "擷取此圖層的索引並傳送到複製器和連接形狀等圖層的輸入。", "このレイヤーのインデックスを抽出し、デュプリケーターやシェイプ接続などのレイヤーの入力に送信します。"),
"Upstream Depth": ("上游深度", "上游深度", "上流の深さ"),
"Generate unique random values for individual Layer connections.": ("为各图层连接生成唯一的随机值。", "為各圖層連接產生唯一的隨機值。", "個々のレイヤー接続に対して一意のランダム値を生成します。"),
"Output the length of a path.": ("输出路径的长度。", "輸出路徑的長度。", "パスの長さを出力します。"),
"String Manipulator": ("字符串操作器", "字串操作器", "文字列マニピュレーター"),
"Alter existing strings (text) in some way. Includes options to shuffle, resize, replace and more.": ("以某种方式修改现有字符串（文本）。包括随机排列、调整大小、替换等选项。", "以某種方式修改現有字串（文字）。包括隨機排列、調整大小、替換等選項。", "既存の文字列（テキスト）を何らかの方法で変更します。シャッフル、リサイズ、置換などのオプションがあります。"),
"Manipulator": ("操作器", "操作器", "マニピュレーター"),
"Array Manipulator": ("数组操作器", "陣列操作器", "配列マニピュレーター"),
"Shuffle String": ("随机排列字符串", "隨機排列字串", "文字列のシャッフル"),
"Rearrange the characters of a string.": ("重新排列字符串的字符。", "重新排列字串的字元。", "文字列の文字を並べ替えます。"),
"Shuffle from the End": ("从末尾开始随机排列", "從末尾開始隨機排列", "末尾からシャッフル"),
"Custom String": ("自定义字符串", "自訂字串", "カスタム文字列"),
"Unicode Offset": ("Unicode 偏移", "Unicode 偏移", "Unicode オフセット"),
"Grouping": ("分组", "分組", "グループ化"),
"Direction Mode": ("方向模式", "方向模式", "方向モード"),
"Random Alphanumeric": ("随机字母数字", "隨機字母數字", "ランダム英数字"),
"Resize String": ("调整字符串大小", "調整字串大小", "文字列のリサイズ"),
"Reduce the length of a string.": ("减少字符串的长度。", "減少字串的長度。", "文字列の長さを縮小します。"),
"Erase from Start": ("从开头删除", "從開頭刪除", "先頭から消去"),
"Empty String is Space": ("空字符串为空格", "空字串為空格", "空文字列をスペースに"),
"Match Mode": ("匹配模式", "比對模式", "マッチモード"),
"Fixed Length": ("固定长度", "固定長度", "固定長"),
"Erase from End": ("从末尾删除", "從末尾刪除", "末尾から消去"),
"Erase Randomly": ("随机删除", "隨機刪除", "ランダムに消去"),
"Replace String": ("替换字符串", "替換字串", "文字列の置換"),
"Replace part of a string with another string.": ("将字符串的一部分替换为另一个字符串。", "將字串的一部分替換為另一個字串。", "文字列の一部を別の文字列に置き換えます。"),
"With": ("替换为", "替換為", "置換先"),
"Change String Case": ("更改字符串大小写", "變更字串大小寫", "文字列の大文字小文字を変更"),
"Word Exclusion List": ("词排除列表", "詞排除列表", "除外単語リスト"),
"New Line as Sentence Delimeter": ("新行作为句子分隔符", "新行作為句子分隔符", "改行を文の区切りとする"),
"Lower Case": ("小写", "小寫", "小文字"),
"Upper Case": ("大写", "大寫", "大文字"),
"Proper Case": ("首字母大写", "首字母大寫", "各単語の先頭を大文字"),
"Sentence Case": ("句首大写", "句首大寫", "文の先頭を大文字"),
"Transition String": ("过渡字符串", "轉換字串", "トランジション文字列"),
"Transition one string to another.": ("将一个字符串过渡到另一个。", "將一個字串轉換到另一個。", "1つの文字列から別の文字列へトランジションします。"),
"Transition From End": ("从末尾过渡", "從末尾轉換", "末尾からトランジション"),
"Final String": ("最终字符串", "最終字串", "最終文字列"),
"Stores a piece of text.": ("存储一段文本。", "儲存一段文字。", "テキストを保存します。"),
"Press Shift+Return to convert a string into a multi-line string.": ("按 Shift+Return 将字符串转换为多行字符串。", "按 Shift+Return 將字串轉換為多行字串。", "Shift+Return を押して文字列を複数行文字列に変換します。"),
"Output the current time or date.": ("输出当前时间或日期。", "輸出目前時間或日期。", "現在の時刻または日付を出力します。"),
"Seconds through Minute": ("分钟内的秒数", "分鐘內的秒數", "分内の秒数"),
"Seconds through Hour": ("小时内的秒数", "小時內的秒數", "時間内の秒数"),
"Seconds through Day": ("一天内的秒数", "一天內的秒數", "日内の秒数"),
"Seconds through Week": ("一周内的秒数", "一週內的秒數", "週内の秒数"),
"Seconds through Month": ("一月内的秒数", "一月內的秒數", "月内の秒数"),
"Seconds through Year": ("一年内的秒数", "一年內的秒數", "年内の秒数"),
"Minutes through Hour": ("小时内的分钟数", "小時內的分鐘數", "時間内の分数"),
"Minutes through Day": ("一天内的分钟数", "一天內的分鐘數", "日内の分数"),
"Minutes through Week": ("一周内的分钟数", "一週內的分鐘數", "週内の分数"),
"Minutes through Month": ("一月内的分钟数", "一月內的分鐘數", "月内の分数"),
"Minutes through Year": ("一年内的分钟数", "一年內的分鐘數", "年内の分数"),
"Day of the Week": ("星期几", "星期幾", "曜日"),
"Day of the Month": ("月中的日期", "月中的日期", "月の日"),
"Day of the Year": ("年中的日期", "年中的日期", "年の日"),
"Month of the Year": ("年中的月份", "年中的月份", "年の月"),
"Milliseconds through Second": ("秒内的毫秒数", "秒內的毫秒數", "秒内のミリ秒数"),
"Hours through Day": ("一天内的小时数", "一天內的小時數", "日内の時間数"),
"Unit": ("单位", "單位", "単位"),
"Ratio": ("比率", "比率", "比率"),
"Extract the bounding box of a Shape and its children.": ("提取形状及其子级的边界框。", "擷取形狀及其子層級的邊界框。", "シェイプとその子要素のバウンディングボックスを抽出します。"),
"Expand": ("展开", "展開", "展開"),
"Sample at Frame": ("在帧处采样", "在幀處取樣", "フレームでサンプル"),
"Sample Frame": ("采样帧", "取樣幀", "サンプルフレーム"),
"Convert a given number of seconds into the equivalent number of frames.": ("将给定的秒数转换为等效的帧数。", "將給定的秒數轉換為等效的幀數。", "指定された秒数を同等のフレーム数に変換します。"),
"Enter the number of seconds.": ("输入秒数。", "輸入秒數。", "秒数を入力してください。"),
"Enter the frame rate. By default, this is connected to the Composition's Frame Rate.": ("输入帧率。默认情况下，这连接到合成的帧率。", "輸入幀率。預設情況下，這連接到合成的幀率。", "フレームレートを入力してください。デフォルトでは、コンポジションのフレームレートに接続されています。"),
"Frames": ("帧", "幀", "フレーム"),
"An output for the equivalent number of frames. The calculation is simply 'FPS * Seconds'": ("等效帧数的输出。计算方式为 'FPS * 秒数'。", "等效幀數的輸出。計算方式為 'FPS * 秒數'。", "同等のフレーム数の出力。計算は単純に 'FPS × 秒数' です。"),
"Find the radius of a shape.": ("查找形状的半径。", "找出形狀的半徑。", "シェイプの半径を求めます。"),
"Centre Mode": ("中心模式", "中心模式", "中心モード"),
"Centre Position": ("中心位置", "中心位置", "中心位置"),
"Custom Centre": ("自定义中心", "自訂中心", "カスタム中心"),
"Shapes' Centre": ("形状中心", "形狀中心", "シェイプの中心"),
"Smallest Circle": ("最小圆", "最小圓", "最小円"),
"Attributes": ("属性", "屬性", "属性"),
"Edit Mode": ("编辑模式", "編輯模式", "編集モード"),
"Controls": ("控件", "控制項", "コントロール"),
"Filter strings using a regular expression.": ("使用正则表达式过滤字符串。", "使用正規表達式過濾字串。", "正規表現を使用して文字列をフィルタリングします。"),
"Sub-String": ("子字符串", "子字串", "部分文字列"),
"Crop a string.": ("裁剪字符串。", "裁剪字串。", "文字列をトリミングします。"),
"Offset characters by Unicode code point. Useful for picture fonts and glyph manipulation.": ("按 Unicode 码位偏移字符。适用于图片字体和字形操作。", "按 Unicode 碼位偏移字元。適用於圖片字型和字形操作。", "Unicode コードポイントで文字をオフセットします。ピクチャーフォントやグリフ操作に便利です。"),
"Clamp to Range": ("限制到范围", "限制到範圍", "範囲にクランプ"),
"Code Point Range": ("码位范围", "碼位範圍", "コードポイント範囲"),
"Selection Mode": ("选择模式", "選擇模式", "選択モード"),
"Keep Punctuation": ("保留标点", "保留標點", "句読点を保持"),
"Keep Whitespace": ("保留空白", "保留空白", "空白を保持"),
"Create a list of typefaces which can be assigned to other layers via their indices.": ("创建一个可通过索引分配给其他图层的字体列表。", "建立一個可透過索引指定給其他圖層的字型列表。", "インデックスを介して他のレイヤーに割り当てることができるフォントのリストを作成します。"),
"Typeface": ("字体", "字型", "書体"),
"Create an list of Assets which can be assigned to other layers via their indices.": ("创建一个可通过索引分配给其他图层的资产列表。", "建立一個可透過索引指定給其他圖層的資產列表。", "インデックスを介して他のレイヤーに割り当てることができるアセットのリストを作成します。"),
"Asset": ("资产", "資產", "アセット"),
"Create a list of Shaders which can be assigned to other layers via their indices.": ("创建一个可通过索引分配给其他图层的着色器列表。", "建立一個可透過索引指定給其他圖層的著色器列表。", "インデックスを介して他のレイヤーに割り当てることができるシェーダーのリストを作成します。"),
"Create a list of strings which can be assigned to other layers via their indices.": ("创建一个可通过索引分配给其他图层的字符串列表。", "建立一個可透過索引指定給其他圖層的字串列表。", "インデックスを介して他のレイヤーに割り当てることができる文字列のリストを作成します。"),
"Longest": ("最长", "最長", "最長"),
"Shortest": ("最短", "最短", "最短"),
"Shape Array": ("形状数组", "形狀陣列", "シェイプ配列"),
"Create a list of connected Shapes which can be assigned to other layers via their indices.": ("创建一个可通过索引分配给其他图层的已连接形状列表。", "建立一個可透過索引指定給其他圖層的已連接形狀列表。", "インデックスを介して他のレイヤーに割り当てることができる接続済みシェイプのリストを作成します。"),
"Resize Array": ("调整数组大小", "調整陣列大小", "配列のリサイズ"),
"Sort Array": ("排序数组", "排序陣列", "配列のソート"),
"Shuffle Array": ("随机排列数组", "隨機排列陣列", "配列のシャッフル"),
"Manipulate Array": ("操作数组", "操作陣列", "配列の操作"),
"Moving Average": ("移动平均", "移動平均", "移動平均"),
"Exponential Moving Average": ("指数移动平均", "指數移動平均", "指数移動平均"),
"Define how holes and self-intersections affect a Shape's fill.": ("定义孔洞和自相交如何影响形状的填充。", "定義孔洞和自相交如何影響形狀的填充。", "穴と自己交差がシェイプの塗りにどのように影響するかを定義します。"),
"Subdivide": ("细分", "細分", "サブディバイド"),
"Subdivisions": ("细分级别", "細分級別", "サブディビジョン"),
"Smooth Angle": ("平滑角度", "平滑角度", "スムーズ角度"),
"Any edges with an angle greater than this amount will be smoothed. Adjust this to keep sharp corners when smoothing.": ("角度大于此值的边将被平滑处理。调整此值可在平滑时保留尖角。", "角度大於此值的邊將被平滑處理。調整此值可在平滑時保留尖角。", "この値より大きい角度のエッジはスムーズ処理されます。スムーズ時にシャープなコーナーを維持するにはこの値を調整してください。"),
"Segments shorter than this distance (in pixels) will not be subdivided.": ("短于此距离（以像素为单位）的线段将不会被细分。", "短於此距離（以像素為單位）的線段將不會被細分。", "この距離（ピクセル単位）より短いセグメントはサブディバイドされません。"),
"Composition Constraint": ("合成约束", "合成約束", "コンポジション制約"),
"Constrain Shapes to the edges of your Composition.": ("将形状约束到合成的边缘。", "將形狀約束到合成的邊緣。", "シェイプをコンポジションのエッジに制約します。"),
"Constrain one Shape to another with options to 'pick up' and 'put down'.": ("将一个形状约束到另一个，提供\"拾起\"和\"放下\"选项。", "將一個形狀約束到另一個，提供「拾起」和「放下」選項。", "「拾い上げ」と「置く」オプションで1つのシェイプを別のシェイプに制約します。"),
"Rest Position": ("静止位置", "靜止位置", "レスト位置"),
"Rest Offset": ("静止偏移", "靜止偏移", "レストオフセット"),
"Rotated Offset": ("旋转偏移", "旋轉偏移", "回転オフセット"),
"Position Strength": ("位置强度", "位置強度", "位置の強度"),
"Rotation Strength": ("旋转强度", "旋轉強度", "回転の強度"),
"Out Rotation": ("输出旋转", "輸出旋轉", "出力回転"),
"Rest Rotation": ("静止旋转", "靜止旋轉", "レスト回転"),
"Component Constraint": ("组件约束", "元件約束", "コンポーネント制約"),
"Constrain Shapes to the points or edges of another.": ("将形状约束到另一个形状的点或边。", "將形狀約束到另一個形狀的點或邊。", "シェイプを別のシェイプのポイントまたはエッジに制約します。"),
"Constraint Type": ("约束类型", "約束類型", "制約タイプ"),
"Join String": ("连接字符串", "連接字串", "文字列の結合"),
"Concatenate several strings together.": ("将多个字符串连接在一起。", "將多個字串連接在一起。", "複数の文字列を連結します。"),
"Start Delimiter": ("起始分隔符", "起始分隔符", "開始区切り"),
"End Delimiter": ("结束分隔符", "結束分隔符", "終了区切り"),
"Determine if one Shape's position falls within another.": ("确定一个形状的位置是否在另一个形状内。", "判斷一個形狀的位置是否在另一個形狀內。", "1つのシェイプの位置が別のシェイプ内にあるかどうかを判定します。"),
"Within Shape": ("在形状内", "在形狀內", "シェイプ内"),
"Edge Constraint": ("边约束", "邊約束", "エッジ制約"),
"Generate an Edge Constraint for the Component Constraint.": ("为组件约束生成边约束。", "為元件約束產生邊約束。", "コンポーネント制約用のエッジ制約を生成します。"),
"Normal Bias": ("法线偏差", "法線偏差", "法線バイアス"),
"Transform Constraint": ("变换约束", "變換約束", "トランスフォーム制約"),
"Point Constraint": ("点约束", "點約束", "ポイント制約"),
"Generate a Point Constraint for the Component Constraint.": ("为组件约束生成点约束。", "為元件約束產生點約束。", "コンポーネント制約用のポイント制約を生成します。"),
"Shrink or grow paths.": ("收缩或扩展路径。", "收縮或擴展路徑。", "パスを縮小または拡大します。"),
"Rounded": ("圆角", "圓角", "丸角"),
"Open Paths Cap Style": ("开放路径端点样式", "開放路徑端點樣式", "オープンパスのキャップスタイル"),
"Closed Paths Mode": ("闭合路径模式", "閉合路徑模式", "クローズパスモード"),
"Joined": ("连接", "連接", "結合"),
"Single Sided": ("单面", "單面", "片面"),
"Double Sided": ("双面", "雙面", "両面"),
"A non-rendering layer that can be used to control other layers.": ("一个不渲染的图层，可用于控制其他图层。", "一個不算繪的圖層，可用於控制其他圖層。", "他のレイヤーを制御するための非レンダリングレイヤー。"),
"Limit Position": ("限制位置", "限制位置", "位置を制限"),
"Minimum Position": ("最小位置", "最小位置", "最小位置"),
"Maximum Position": ("最大位置", "最大位置", "最大位置"),
"Draw Position Limits": ("绘制位置限制", "繪製位置限制", "位置制限を描画"),
"Limit Rotation": ("限制旋转", "限制旋轉", "回転を制限"),
"Minimum Rotation": ("最小旋转", "最小旋轉", "最小回転"),
"Maximum Rotation": ("最大旋转", "最大旋轉", "最大回転"),
"Limit Scale": ("限制缩放", "限制縮放", "スケールを制限"),
"Minimum Scale": ("最小缩放", "最小縮放", "最小スケール"),
"Maximum Scale": ("最大缩放", "最大縮放", "最大スケール"),
"Cross": ("十字", "十字", "クロス"),
"A way to control a Camera by animating the view box.": ("通过动画化视图框来控制摄像机的方式。", "透過動畫化檢視框來控制攝影機的方式。", "ビューボックスをアニメーションすることでカメラを制御する方法。"),
"By default a Camera Guide will inherit its label color but when checked, the Camera Guide's color can be specified by the Color attribute.": ("默认情况下，摄像机引导将继承其标签颜色，但勾选后，可以通过颜色属性指定摄像机引导的颜色。", "預設情況下，攝影機引導將繼承其標籤顏色，但勾選後，可以透過顏色屬性指定攝影機引導的顏色。", "デフォルトではカメラガイドはラベルカラーを継承しますが、チェックするとカラー属性でカメラガイドの色を指定できます。"),
"Null Color": ("空对象颜色", "空物件顏色", "ヌルカラー"),
"Set a custom color for the Camera Guide.": ("为摄像机引导设置自定义颜色。", "為攝影機引導設定自訂顏色。", "カメラガイドにカスタムカラーを設定します。"),
"Stops": ("色标", "色標", "ストップ"),
"Positions": ("位置", "位置", "位置"),
"Colours": ("颜色", "顏色", "カラー"),
"Position Modifier": ("位置修改器", "位置修改器", "位置モディファイアー"),
"Blend one Shape into another. This is not a morph; all shapes must have the same point count.": ("将一个形状混合到另一个形状。这不是变形；所有形状必须具有相同的点数。", "將一個形狀混合到另一個形狀。這不是變形；所有形狀必須具有相同的點數。", "1つのシェイプを別のシェイプにブレンドします。これはモーフではありません。すべてのシェイプは同じポイント数である必要があります。"),
"Blend Shape": ("混合形状", "混合形狀", "ブレンドシェイプ"),
"Deltas": ("增量", "增量", "デルタ"),
"Creates procedural strings such as dates and time, hashes, numbers and timecodes.": ("创建程序化字符串，如日期和时间、哈希值、数字和时间码。", "建立程序化字串，如日期和時間、雜湊值、數字和時間碼。", "日付と時刻、ハッシュ、数値、タイムコードなどのプロシージャル文字列を作成します。"),
"Generator": ("生成器", "產生器", "ジェネレーター"),
"Manipulators": ("操作器", "操作器", "マニピュレーター"),
"All Caps": ("全大写", "全大寫", "すべて大文字"),
"Prefix": ("前缀", "前綴", "プレフィックス"),
"Suffix": ("后缀", "後綴", "サフィックス"),
"Save Limit": ("保存限制", "儲存限制", "保存制限"),
"End Frame": ("结束帧", "結束幀", "終了フレーム"),
"Value2 Solver": ("二维值求解器", "二維值求解器", "Value2 ソルバー"),
"Store the two dimensional values from previous frames in order to accumulate and/ or fade them.": ("存储前几帧的二维值，以便累积和/或淡化它们。", "儲存前幾幀的二維值，以便累積和/或淡化它們。", "前のフレームの2次元値を保存して、累積やフェードを行います。"),
"Fade Mode": ("淡化模式", "淡化模式", "フェードモード"),
"Fade Value": ("淡化值", "淡化值", "フェード値"),
"Highest": ("最高", "最高", "最高"),
"Velocity": ("速度", "速度", "速度"),
"Fade by Value": ("按值淡化", "按值淡化", "値でフェード"),
"Multiply by Value": ("按值乘", "按值乘", "値で乗算"),
"Use Time (graph)": ("使用时间（图表）", "使用時間（圖表）", "時間を使用（グラフ）"),
"Solver": ("求解器", "求解器", "ソルバー"),
"Value Solver": ("值求解器", "值求解器", "値ソルバー"),
"Store the values from previous frames in order to accumulate and/ or fade them.": ("存储前几帧的值，以便累积和/或淡化它们。", "儲存前幾幀的值，以便累積和/或淡化它們。", "前のフレームの値を保存して、累積やフェードを行います。"),
"Colors": ("颜色", "顏色", "カラー"),
"Preview": ("预览", "預覽", "プレビュー"),
"Gradient Stop": ("渐变色标", "漸層色標", "グラデーションストップ"),
"Stepped": ("阶梯式", "階梯式", "ステップ"),
"In Points": ("输入点", "輸入點", "入力ポイント"),
"Add this to a Shape within a Duplicator to extract the Shape's direction.": ("将此添加到复制器中的形状以提取形状的方向。", "將此新增到複製器中的形狀以擷取形狀的方向。", "デュプリケーター内のシェイプに追加して、シェイプの方向を抽出します。"),
"Normalise": ("归一化", "正規化", "正規化"),
"Add this to a Shape within a Duplicator to extract the Shape's speed.": ("将此添加到复制器中的形状以提取形状的速度。", "將此新增到複製器中的形狀以擷取形狀的速度。", "デュプリケーター内のシェイプに追加して、シェイプの速度を抽出します。"),
"Generates non-repeating number sequences which can also be randomised.": ("生成不重复的数字序列，也可以随机化。", "產生不重複的數字序列，也可以隨機化。", "重複しない数値シーケンスを生成し、ランダム化することもできます。"),
"Sequence": ("序列", "序列", "シーケンス"),
"Skip Indices": ("跳过索引", "略過索引", "インデックスをスキップ"),
"Flatten the internal hierarchy of a Shape into one single path or layer.": ("将形状的内部层级结构展平为单一路径或图层。", "將形狀的內部階層結構展平為單一路徑或圖層。", "シェイプの内部階層を1つのパスまたはレイヤーにフラット化します。"),
"Single Path": ("单一路径", "單一路徑", "単一パス"),
"Single Layer (keeps materials)": ("单一图层（保留材质）", "單一圖層（保留材質）", "単一レイヤー（マテリアルを保持）"),
"Layout Shape": ("布局形状", "佈局形狀", "レイアウトシェイプ"),
"This Layer has been deprecated - see Layouts for the replacement feature.": ("此图层已弃用 - 请参阅布局功能作为替代。", "此圖層已棄用 - 請參閱佈局功能作為替代。", "このレイヤーは廃止されました - 代替機能についてはレイアウトをご覧ください。"),
"Layout Items": ("布局项目", "佈局項目", "レイアウト項目"),
"Column Span": ("列跨度", "欄跨度", "列スパン"),
"Row Span": ("行跨度", "列跨度", "行スパン"),
"Fixed Position": ("固定位置", "固定位置", "固定位置"),
"Spacer": ("间距器", "間距器", "スペーサー"),
"Horizontal Layout": ("水平布局", "水平佈局", "水平レイアウト"),
"Generate a Horizontal Layout for the Apply Layout Behaviour.": ("为应用布局行为生成水平布局。", "為套用佈局行為產生水平佈局。", "レイアウト適用ビヘイビア用の水平レイアウトを生成します。"),
"Auto Spacing": ("自动间距", "自動間距", "自動スペーシング"),
"Horizontal Padding": ("水平内边距", "水平內邊距", "水平パディング"),
"Vertical Padding": ("垂直内边距", "垂直內邊距", "垂直パディング"),
"Reverse Layout Order": ("反转布局顺序", "反轉佈局順序", "レイアウト順序を反転"),
"Invert Layout Direction": ("反转布局方向", "反轉佈局方向", "レイアウト方向を反転"),
"Vertical Layout": ("垂直布局", "垂直佈局", "垂直レイアウト"),
"Generate a Vertical Layout for the Apply Layout Behaviour.": ("为应用布局行为生成垂直布局。", "為套用佈局行為產生垂直佈局。", "レイアウト適用ビヘイビア用の垂直レイアウトを生成します。"),
"Grid Layout": ("网格布局", "網格佈局", "グリッドレイアウト"),
"Generate a Grid Layout for the Apply Layout Behaviour.": ("为应用布局行为生成网格布局。", "為套用佈局行為產生網格佈局。", "レイアウト適用ビヘイビア用のグリッドレイアウトを生成します。"),
"Rows": ("行", "列", "行"),
"Columns": ("列", "欄", "列"),
"Used in combination with Layout Shape to create gaps or blank cells.": ("与布局形状结合使用以创建间隙或空白单元格。", "與佈局形狀結合使用以建立間隙或空白儲存格。", "レイアウトシェイプと組み合わせて隙間や空白セルを作成します。"),
"Minimum Size": ("最小尺寸", "最小尺寸", "最小サイズ"),
"Get Name": ("获取名称", "取得名稱", "名前を取得"),
"Get the 'nice name' for a layer and output it as a string.": ("获取图层的\"友好名称\"并将其输出为字符串。", "取得圖層的「友善名稱」並將其輸出為字串。", "レイヤーの「表示名」を取得し文字列として出力します。"),
"Input": ("输入", "輸入", "入力"),
"String Length": ("字符串长度", "字串長度", "文字列の長さ"),
"Count how many lines/ words/ characters there are within a string.": ("计算字符串中有多少行/词/字符。", "計算字串中有多少行/詞/字元。", "文字列内の行数/単語数/文字数をカウントします。"),
"Maximum Size": ("最大尺寸", "最大尺寸", "最大サイズ"),
"The maximum size this layout is allowed to take.": ("此布局允许的最大尺寸。", "此佈局允許的最大尺寸。", "このレイアウトが取ることのできる最大サイズ。"),
"The minimum size this layout is allowed to take.": ("此布局允许的最小尺寸。", "此佈局允許的最小尺寸。", "このレイアウトが取ることのできる最小サイズ。"),
"Margins": ("外边距", "外邊距", "マージン"),
"The margins around the edge of the layout.": ("布局边缘周围的外边距。", "佈局邊緣周圍的外邊距。", "レイアウトのエッジ周りのマージン。"),
"Create Horizontal or Vertical layouts.": ("创建水平或垂直布局。", "建立水平或垂直佈局。", "水平または垂直レイアウトを作成します。"),
"The space between each item in the layout.": ("布局中每个项目之间的间距。", "佈局中每個項目之間的間距。", "レイアウト内の各項目間のスペース。"),
"Spacing Mode": ("间距模式", "間距模式", "スペーシングモード"),
"How items are distributed in the available space. By default you can add 'Spacer' layers to push Shapes around.": ("项目如何在可用空间中分布。默认情况下，您可以添加\"间距器\"图层来推动形状。", "項目如何在可用空間中分佈。預設情況下，您可以新增「間距器」圖層來推動形狀。", "利用可能なスペースにアイテムがどのように分布されるか。デフォルトでは「スペーサー」レイヤーを追加してシェイプを配置できます。"),
"Dictates the direction of the layout.": ("决定布局的方向。", "決定佈局的方向。", "レイアウトの方向を指定します。"),
"Ordering Policy": ("排列策略", "排列策略", "順序ポリシー"),
"Flip Order": ("翻转顺序", "翻轉順序", "順序を反転"),
"Shuffle Seed": ("随机种子", "隨機種子", "シャッフルシード"),
"Wrap Mode": ("换行模式", "換行模式", "ラップモード"),
"Control how items wrap when they exceed the available space.": ("控制项目超出可用空间时如何换行。", "控制項目超出可用空間時如何換行。", "利用可能なスペースを超えた場合のアイテムの折り返し方法を制御します。"),
"Align Content": ("对齐内容", "對齊內容", "コンテンツの配置"),
"How wrapped lines are distributed in the available space.": ("换行后的行如何在可用空间中分布。", "換行後的行如何在可用空間中分佈。", "折り返された行が利用可能なスペースにどのように分布されるか。"),
"The space between wrapped lines.": ("换行后的行之间的间距。", "換行後的行之間的間距。", "折り返された行間のスペース。"),
"Layer Order": ("图层顺序", "圖層順序", "レイヤー順序"),
"Alphabetical": ("按字母顺序", "按字母順序", "アルファベット順"),
"Manual Spacers": ("手动间距器", "手動間距器", "手動スペーサー"),
"Flex Start": ("弹性起始", "彈性起始", "フレックス開始"),
"Flex End": ("弹性结束", "彈性結束", "フレックス終了"),
"Space Between": ("两端对齐", "兩端對齊", "均等配置（両端）"),
"Space Around": ("环绕间距", "環繞間距", "均等配置（周囲）"),
"Space Evenly": ("均匀间距", "均勻間距", "均等配置"),
"No Wrap": ("不换行", "不換行", "折り返しなし"),
"Wrap": ("换行", "換行", "折り返し"),
"Wrap Reverse": ("反向换行", "反向換行", "逆折り返し"),
"Create a Grid Layout, Grid Layouts are made up of Grid Layout Rows.": ("创建网格布局，网格布局由网格布局行组成。", "建立網格佈局，網格佈局由網格佈局列組成。", "グリッドレイアウトを作成します。グリッドレイアウトはグリッドレイアウト行で構成されます。"),
"Create a grid row for use with the Grid Layout Group.": ("创建网格行以与网格布局组一起使用。", "建立網格列以與網格佈局群組一起使用。", "グリッドレイアウトグループで使用するグリッド行を作成します。"),
"Minimum Column Width": ("最小列宽", "最小欄寬", "最小列幅"),
"The minimum width for each column in the layout.": ("布局中每列的最小宽度。", "佈局中每欄的最小寬度。", "レイアウト内の各列の最小幅。"),
"Rectangle Pattern": ("矩形图案", "矩形圖案", "矩形パターン"),
"Create stacked bar/ pie/ ring charts and barcodes.": ("创建堆叠条形图/饼图/环形图和条形码。", "建立堆疊長條圖/圓餅圖/環形圖和條碼。", "積み重ね棒グラフ/円グラフ/リングチャートとバーコードを作成します。"),
"Pattern Mode": ("图案模式", "圖案模式", "パターンモード"),
"Dynamic Bar Size": ("动态条形大小", "動態長條大小", "ダイナミックバーサイズ"),
"Use Fixed Size": ("使用固定大小", "使用固定大小", "固定サイズを使用"),
"Orientation": ("方向", "方向", "向き"),
"Fixed Gap Width": ("固定间隙宽度", "固定間隙寬度", "固定ギャップ幅"),
"Alternating": ("交替", "交替", "交互"),
"Fixed Width": ("固定宽度", "固定寬度", "固定幅"),
"Fixed Gap Angle": ("固定间隙角度", "固定間隙角度", "固定ギャップ角度"),
"Fixed Angle": ("固定角度", "固定角度", "固定角度"),
"Bento": ("Bento", "Bento", "Bento"),
"Grid Columns": ("网格列", "網格欄", "グリッド列"),
"Grid Rows": ("网格行", "網格列", "グリッド行"),
"Gap": ("间隙", "間隙", "ギャップ"),
"Hero Mode": ("主元素模式", "主元素模式", "ヒーローモード"),
"Hero Count": ("主元素数量", "主元素數量", "ヒーロー数"),
"Hero Size": ("主元素大小", "主元素大小", "ヒーローサイズ"),
"Hero Position X": ("主元素位置 X", "主元素位置 X", "ヒーロー位置 X"),
"Hero Position Y": ("主元素位置 Y", "主元素位置 Y", "ヒーロー位置 Y"),
"Single": ("单一", "單一", "単一"),
"Chromatic Aberration": ("色差", "色差", "色収差"),
"Separate the Red, Green and Blue channels while distorting the edges of the layer.": ("分离红色、绿色和蓝色通道，同时扭曲图层边缘。", "分離紅色、綠色和藍色通道，同時扭曲圖層邊緣。", "レイヤーのエッジを歪ませながら赤、緑、青のチャンネルを分離します。"),
"Alignment X": ("对齐 X", "對齊 X", "配置 X"),
"Alignment Y": ("对齐 Y", "對齊 Y", "配置 Y"),
"Lens Type": ("镜头类型", "鏡頭類型", "レンズタイプ"),
"Red Channel Offset": ("红色通道偏移", "紅色通道偏移", "赤チャンネルオフセット"),
"Green Channel Offset": ("绿色通道偏移", "綠色通道偏移", "緑チャンネルオフセット"),
"Blue Channel Offset": ("蓝色通道偏移", "藍色通道偏移", "青チャンネルオフセット"),
"Distortion Radius": ("扭曲半径", "扭曲半徑", "ディストーション半径"),
"Repetition Distance": ("重复距离", "重複距離", "繰り返し距離"),
"Concave": ("凹面", "凹面", "凹面"),
"Fisheye/ Barrel Distortion": ("鱼眼/桶形扭曲", "魚眼/桶形扭曲", "魚眼/樽型ディストーション"),
"Maximum Particles": ("最大粒子数", "最大粒子數", "最大パーティクル数"),
"Lifespan": ("生命周期", "生命週期", "寿命"),
"Emitter": ("发射器", "發射器", "エミッター"),
"Distribution Emitter": ("分布发射器", "分佈發射器", "分布エミッター"),
"Emit Particles from a Distribution.": ("从分布发射粒子。", "從分佈發射粒子。", "分布からパーティクルを発射します。"),
"Emission Mode": ("发射模式", "發射模式", "エミッションモード"),
"Rate Mode": ("速率模式", "速率模式", "レートモード"),
"Rate": ("速率", "速率", "レート"),
"Once": ("一次", "一次", "1回"),
"Every Frame": ("每帧", "每幀", "毎フレーム"),
"Rate per Second": ("每秒速率", "每秒速率", "秒あたりのレート"),
"Ordered": ("有序", "有序", "順序付き"),
"Particle Emitter": ("粒子发射器", "粒子發射器", "パーティクルエミッター"),
"Emit Particles from a Point, Shape or Path.": ("从点、形状或路径发射粒子。", "從點、形狀或路徑發射粒子。", "ポイント、シェイプまたはパスからパーティクルを発射します。"),
"Duration": ("持续时间", "持續時間", "デュレーション"),
"Interval": ("间隔", "間隔", "インターバル"),
"Emitter Shape": ("发射器形状", "發射器形狀", "エミッターシェイプ"),
"Emission Shape": ("发射形状", "發射形狀", "エミッションシェイプ"),
"Use Single Position": ("使用单一位置", "使用單一位置", "単一位置を使用"),
"Initial Velocity": ("初始速度", "初始速度", "初期速度"),
"Connect a Behaviour (e.g. Random) to Initial Direction and/or Initial Speed to give each Particle a different direction/speed.": ("将行为（例如随机）连接到初始方向和/或初始速度，以为每个粒子提供不同的方向/速度。", "將行為（例如隨機）連接到初始方向和/或初始速度，以為每個粒子提供不同的方向/速度。", "ビヘイビア（例：ランダム）を初期方向や初期速度に接続して、各パーティクルに異なる方向/速度を与えます。"),
"Input Shape Perimeter": ("输入形状周长", "輸入形狀周長", "入力シェイプの周長"),
}
