T = {
"Generate a Radial gradient for the Gradient Shader.": ("为渐变着色器生成径向渐变。", "為漸層著色器產生放射狀漸層。", "グラデーションシェーダー用のラジアルグラデーションを生成します。"),
"Sweep Gradient": ("扫描渐变", "掃描漸層", "スイープグラデーション"),
"Generate a Sweep gradient for the Gradient Shader.": ("为渐变着色器生成扫描渐变。", "為漸層著色器產生掃描漸層。", "グラデーションシェーダー用のスイープグラデーションを生成します。"),
"Color Shader": ("颜色着色器", "顏色著色器", "カラーシェーダー"),
"A simple shader that outputs a color.": ("一个输出颜色的简单着色器。", "一個輸出顏色的簡單著色器。", "カラーを出力するシンプルなシェーダーです。"),
"SkSL Shader": ("SkSL 着色器", "SkSL 著色器", "SkSL シェーダー"),
"Write your own shader in SkSL (based on GLSL).": ("使用 SkSL（基于 GLSL）编写自定义着色器。", "使用 SkSL（基於 GLSL）撰寫自訂著色器。", "SkSL（GLSL ベース）で独自のシェーダーを記述します。"),
"Inputs": ("输入", "輸入", "入力"),
"Shader Code": ("着色器代码", "著色器程式碼", "シェーダーコード"),
"Contours to Sub-Meshes": ("轮廓转子网格", "輪廓轉子網格", "輪郭をサブメッシュに変換"),
"Convert Path Contours into different Sub-Meshes, optionally keeping holes.": ("将路径轮廓转换为不同的子网格，可选择保留孔洞。", "將路徑輪廓轉換為不同的子網格，可選擇保留孔洞。", "パスの輪郭を異なるサブメッシュに変換します。オプションで穴を保持できます。"),
"Keep Holes": ("保留孔洞", "保留孔洞", "穴を保持"),
"SkSL Filter": ("SkSL 滤镜", "SkSL 濾鏡", "SkSL フィルター"),
"Write your own filter in SkSL (based on GLSL).": ("使用 SkSL（基于 GLSL）编写自定义滤镜。", "使用 SkSL（基於 GLSL）撰寫自訂濾鏡。", "SkSL（GLSL ベース）で独自のフィルターを記述します。"),
"Filter Code": ("滤镜代码", "濾鏡程式碼", "フィルターコード"),
"Write/paste/edit SkSL code here.": ("在此编写/粘贴/编辑 SkSL 代码。", "在此撰寫/貼上/編輯 SkSL 程式碼。", "ここに SkSL コードを記述/貼り付け/編集します。"),
"Set the blend mode for the Filter.": ("设置滤镜的混合模式。", "設定濾鏡的混合模式。", "フィルターの描画モードを設定します。"),
"Where a Filter produces pixels that fall outside of the original Shape's boundary this can be used to expand it.": ("当滤镜产生超出原始形状边界的像素时，可使用此选项扩展边界。", "當濾鏡產生超出原始形狀邊界的像素時，可使用此選項擴展邊界。", "フィルターが元のシェイプの境界外にピクセルを生成する場合、これを使用して境界を拡張できます。"),
"Render Passes Offscreen": ("离屏渲染通道", "離屏算繪通道", "オフスクリーンレンダリングパス"),
"Sampling Quality": ("采样质量", "取樣品質", "サンプリング品質"),
"Controls how the image is sampled/interpolated.": ("控制图像的采样/插值方式。", "控制影像的取樣/內插方式。", "画像のサンプリング/補間方法を制御します。"),
"Nearest Neighbour": ("最近邻", "最近鄰", "ニアレストネイバー"),
"Catmull-Rom": ("Catmull-Rom", "Catmull-Rom", "Catmull-Rom"),
"Mitchell": ("Mitchell", "Mitchell", "Mitchell"),
"Image Shader": ("图像着色器", "影像著色器", "画像シェーダー"),
"A Shader for images, image sequences and video.": ("用于图像、图像序列和视频的着色器。", "用於影像、影像序列和影片的著色器。", "画像、画像シーケンス、動画用のシェーダーです。"),
"Scale Mode": ("缩放模式", "縮放模式", "スケールモード"),
"Tiling X": ("平铺 X", "平鋪 X", "タイリング X"),
"Tiling Y": ("平铺 Y", "平鋪 Y", "タイリング Y"),
"FPS": ("FPS", "FPS", "FPS"),
"Sequence Length": ("序列长度", "序列長度", "シーケンス長"),
"Missing Frames": ("缺失帧", "缺失幀", "欠落フレーム"),
"Fit Contain": ("适应包含", "適應包含", "フィット（収める）"),
"Fit Height": ("适应高度", "適應高度", "高さにフィット"),
"Fit Width": ("适应宽度", "適應寬度", "幅にフィット"),
"Fit Cover": ("适应覆盖", "適應覆蓋", "フィット（カバー）"),
"Noise": ("噪声", "雜訊", "ノイズ"),
"Nearest Frame": ("最近帧", "最近幀", "最近フレーム"),
"Black": ("黑色", "黑色", "ブラック"),
"Mix Shader": ("混合着色器", "混合著色器", "ミックスシェーダー"),
"First Shader": ("第一着色器", "第一著色器", "第 1 シェーダー"),
"Second Shader": ("第二着色器", "第二著色器", "第 2 シェーダー"),
"Mattes": ("蒙片", "蒙片", "マット"),
"Matte Shape": ("蒙片形状", "蒙片形狀", "マットシェイプ"),
"Tile Mode": ("平铺模式", "平鋪模式", "タイルモード"),
"Apply Mode": ("应用模式", "套用模式", "適用モード"),
"How the matte affects the filtered output": ("蒙片如何影响滤镜输出", "蒙片如何影響濾鏡輸出", "マットがフィルター出力にどのように影響するか"),
"Luminance": ("亮度", "亮度", "輝度"),
"Luminance Inverted": ("亮度反转", "亮度反轉", "輝度反転"),
"Filter Input": ("滤镜输入", "濾鏡輸入", "フィルター入力"),
"Clip Output": ("裁剪输出", "裁剪輸出", "出力をクリップ"),
"Mask Blur": ("蒙版模糊", "遮罩模糊", "マスクブラー"),
"Style": ("样式", "樣式", "スタイル"),
"Blur Outside": ("外部模糊", "外部模糊", "外側をぼかす"),
"Blur Outside (Mask Inside)": ("外部模糊（内部蒙版）", "外部模糊（內部遮罩）", "外側をぼかす（内側マスク）"),
"Blur Inside": ("内部模糊", "內部模糊", "内側をぼかす"),
"Drop Shadow": ("投影", "陰影", "ドロップシャドウ"),
"Add a drop shadow to Shapes.": ("为形状添加投影。", "為形狀新增陰影。", "シェイプにドロップシャドウを追加します。"),
"Blur Amount": ("模糊量", "模糊量", "ぼかし量"),
"Shadow Mode": ("阴影模式", "陰影模式", "シャドウモード"),
"Shadow Only": ("仅阴影", "僅陰影", "シャドウのみ"),
"Gaussian Drop Shadow": ("高斯投影", "高斯陰影", "ガウスドロップシャドウ"),
"Background Blur": ("背景模糊", "背景模糊", "背景ぼかし"),
"Blur only a certain portion of a Layer, based on an Input Shape.": ("基于输入形状，仅模糊图层的特定部分。", "基於輸入形狀，僅模糊圖層的特定部分。", "入力シェイプに基づいて、レイヤーの特定部分のみをぼかします。"),
"Blur Shape": ("模糊形状", "模糊形狀", "ぼかしシェイプ"),
"Inner Shadow": ("内阴影", "內陰影", "インナーシャドウ"),
"Add an inner shadow to Shapes to simulate depth.": ("为形状添加内阴影以模拟深度。", "為形狀新增內陰影以模擬深度。", "シェイプにインナーシャドウを追加して奥行きをシミュレートします。"),
"Colour": ("颜色", "顏色", "カラー"),
"Expand or contract the shadow.": ("扩展或收缩阴影。", "擴展或收縮陰影。", "シャドウを拡張または収縮します。"),
"Fast Blur": ("快速模糊", "快速模糊", "高速ぼかし"),
"Add blur to Shapes with independent controls for vertical and horizontal blur.": ("为形状添加模糊，可独立控制垂直和水平模糊。", "為形狀新增模糊，可獨立控制垂直和水平模糊。", "シェイプにぼかしを追加します。垂直方向と水平方向を個別に制御できます。"),
"Tile": ("平铺", "平鋪", "タイル"),
"Transparent": ("透明", "透明", "透明"),
"Gaussian Blur": ("高斯模糊", "高斯模糊", "ガウスぼかし"),
"Add Gaussian blur to Shapes with independent controls for vertical and horizontal blur.": ("为形状添加高斯模糊，可独立控制垂直和水平模糊。", "為形狀新增高斯模糊，可獨立控制垂直和水平模糊。", "シェイプにガウスぼかしを追加します。垂直方向と水平方向を個別に制御できます。"),
"Shape to Shader": ("形状转着色器", "形狀轉著色器", "シェイプからシェーダー"),
"Use a Shape to create a Shader for another Shape.": ("使用一个形状为另一个形状创建着色器。", "使用一個形狀為另一個形狀建立著色器。", "シェイプを使用して別のシェイプ用のシェーダーを作成します。"),
"Very Low": ("非常低", "非常低", "非常に低い"),
"Levels": ("色阶", "色階", "レベル"),
"Remap the black and white levels of a Layer to adjust its tonal range and color balance.": ("重新映射图层的黑白色阶，以调整色调范围和颜色平衡。", "重新對映圖層的黑白色階，以調整色調範圍和顏色平衡。", "レイヤーの黒と白のレベルを再マッピングして、トーン範囲とカラーバランスを調整します。"),
"Channel": ("通道", "通道", "チャンネル"),
"Clip Black": ("裁剪黑", "裁剪黑", "クリップ黒"),
"Clip White": ("裁剪白", "裁剪白", "クリップ白"),
"In Black": ("输入黑", "輸入黑", "入力黒"),
"In White": ("输入白", "輸入白", "入力白"),
"Out Black": ("输出黑", "輸出黑", "出力黒"),
"Out White": ("输出白", "輸出白", "出力白"),
"Gamma": ("伽马", "伽瑪", "ガンマ"),
"RGB": ("RGB", "RGB", "RGB"),
"Red": ("红色", "紅色", "レッド"),
"Green": ("绿色", "綠色", "グリーン"),
"Blue": ("蓝色", "藍色", "ブルー"),
"TriTone": ("三色调", "三色調", "トライトーン"),
"Map dark, midtone and bright values to specified colors.": ("将暗部、中间调和亮部值映射到指定颜色。", "將暗部、中間調和亮部值對映到指定顏色。", "暗部、中間調、明部の値を指定したカラーにマッピングします。"),
"Shadows": ("阴影", "陰影", "シャドウ"),
"Mid-Tones": ("中间调", "中間調", "中間調"),
"Highlights": ("高光", "亮部", "ハイライト"),
"Venetian Blinds": ("百叶窗", "百葉窗", "ブラインド"),
"Reveal a layer using a striped wipe effect.": ("使用条纹擦除效果显示图层。", "使用條紋擦除效果顯示圖層。", "ストライプワイプ効果でレイヤーを表示します。"),
"Completion": ("完成度", "完成度", "完了"),
"Fill Color": ("填充颜色", "填充顏色", "塗りカラー"),
"Overwrite the color of a layer with a given fill color.": ("使用指定的填充颜色覆盖图层的颜色。", "使用指定的填充顏色覆蓋圖層的顏色。", "レイヤーのカラーを指定した塗りカラーで上書きします。"),
"Radial Wipe": ("径向擦除", "放射狀擦除", "ラジアルワイプ"),
"Reveal a layer based on a circular wipe.": ("基于圆形擦除显示图层。", "基於圓形擦除顯示圖層。", "円形ワイプでレイヤーを表示します。"),
"Counter-Clockwise": ("逆时针", "逆時針", "反時計回り"),
"Clockwise": ("顺时针", "順時針", "時計回り"),
"HSL": ("HSL", "HSL", "HSL"),
"Lightness": ("明度", "明度", "明度"),
"Invert the colors of a layer.": ("反转图层的颜色。", "反轉圖層的顏色。", "レイヤーのカラーを反転します。"),
"Skip Transparent": ("跳过透明", "跳過透明", "透明をスキップ"),
"Preserve Edges": ("保留边缘", "保留邊緣", "エッジを保持"),
"Linear Wipe": ("线性擦除", "線性擦除", "リニアワイプ"),
"Create a simple linear wipe on a layer.": ("在图层上创建简单的线性擦除。", "在圖層上建立簡單的線性擦除。", "レイヤー上にシンプルなリニアワイプを作成します。"),
"Noise Shader": ("噪声着色器", "雜訊著色器", "ノイズシェーダー"),
"Create a coherent noise effect from Perlin, Value or Cellular noise.": ("使用 Perlin、Value 或 Cellular 噪声创建连贯的噪声效果。", "使用 Perlin、Value 或 Cellular 雜訊建立連貫的雜訊效果。", "Perlin、Value、または Cellular ノイズからコヒーレントノイズ効果を作成します。"),
"Amplitude": ("振幅", "振幅", "振幅"),
"Fractal Mode": ("分形模式", "碎形模式", "フラクタルモード"),
"Ridge Offset": ("山脊偏移", "山脊偏移", "リッジオフセット"),
"Perlin Noise": ("Perlin 噪声", "Perlin 雜訊", "Perlin ノイズ"),
"Turbulent": ("湍流", "湍流", "乱流"),
"Ridged": ("山脊", "山脊", "リッジ"),
"A primitive shape such as a Rectangle, Ellipse or Polygon.": ("基本形状，如矩形、椭圆或多边形。", "基本形狀，如矩形、橢圓或多邊形。", "矩形、楕円、多角形などのプリミティブシェイプです。"),
"Primitive Type": ("基本类型", "基本類型", "プリミティブタイプ"),
"SVG": ("SVG", "SVG", "SVG"),
"Create shapes from .svg Assets.": ("从 .svg 素材创建形状。", "從 .svg 素材建立形狀。", ".svg アセットからシェイプを作成します。"),
"SVG Materials": ("SVG 材质", "SVG 材質", "SVG マテリアル"),
"SVG Strokes": ("SVG 描边", "SVG 描邊", "SVG ストローク"),
"Font Size": ("字体大小", "字型大小", "フォントサイズ"),
"Alignment": ("对齐", "對齊", "配置"),
"Spacing": ("间距", "間距", "間隔"),
"Word Spacing": ("词间距", "字詞間距", "単語間隔"),
"Line Spacing": ("行间距", "行間距", "行間隔"),
"String Manipulators": ("字符串操作器", "字串操作器", "文字列マニピュレーター"),
"Monospace Multiplier": ("等宽倍数", "等寬倍數", "等幅乗数"),
"Force Monospacing": ("强制等宽", "強制等寬", "等幅を強制"),
"Create and format rich text.": ("创建和格式化富文本。", "建立和格式化富文字。", "リッチテキストを作成してフォーマットします。"),
"Character Spacing": ("字符间距", "字元間距", "文字間隔"),
"Text Box Size": ("文本框大小", "文字方塊大小", "テキストボックスサイズ"),
"Auto Width": ("自动宽度", "自動寬度", "自動幅"),
"Auto Height": ("自动高度", "自動高度", "自動高さ"),
"Formatting Inputs": ("格式化输入", "格式化輸入", "フォーマット入力"),
"Background Shape": ("背景形状", "背景形狀", "背景シェイプ"),
"Ascender Adjustment": ("上伸部调整", "上伸部調整", "アセンダー調整"),
"Descender Adjustment": ("下伸部调整", "下伸部調整", "ディセンダー調整"),
"Paragraph Spacing": ("段落间距", "段落間距", "段落間隔"),
"Shrink to Fit Text Box": ("缩小以适应文本框", "縮小以適應文字方塊", "テキストボックスに合わせて縮小"),
"Shrink the Font Size so that the text fits the text box.\n*Requires **Auto Height** on **Text Box Size** to be unchecked.*": ("缩小字体大小使文本适应文本框。\n*需要取消勾选**文本框大小**中的**自动高度**。*", "縮小字型大小使文字適應文字方塊。\n*需要取消勾選**文字方塊大小**中的**自動高度**。*", "テキストがテキストボックスに収まるようにフォントサイズを縮小します。\n***テキストボックスサイズ**の**自動高さ**のチェックを外す必要があります。*"),
"Allow Word Breaks": ("允许断词", "允許斷詞", "ワードブレークを許可"),
"Allow long words to be split over two or more lines.\n*Can only be disabled when **Scale to Fit Text Box** is enabled.*": ("允许长词跨两行或多行拆分。\n*仅在启用**缩放以适应文本框**时才可禁用。*", "允許長詞跨兩行或多行拆分。\n*僅在啟用**縮放以適應文字方塊**時才可停用。*", "長い単語を 2 行以上に分割できるようにします。\n***テキストボックスに合わせてスケール**が有効な場合のみ無効にできます。*"),
"Specific Indices": ("特定索引", "特定索引", "特定インデックス"),
"Limit the backgound to specific indices. Comma separated values (e.g 1,2)\nand sequences (e.g 1:3) can be used.": ("将背景限制为特定索引。可使用逗号分隔值（如 1,2）\n和序列（如 1:3）。", "將背景限制為特定索引。可使用逗號分隔值（如 1,2）\n和序列（如 1:3）。", "背景を特定のインデックスに制限します。カンマ区切りの値（例: 1,2）\nやシーケンス（例: 1:3）が使用できます。"),
"Path Push": ("路径推移", "路徑推移", "パスプッシュ"),
"Path Travel": ("路径行进", "路徑行進", "パストラベル"),
"Text Path": ("文本路径", "文字路徑", "テキストパス"),
"Path Loop": ("路径循环", "路徑循環", "パスループ"),
"Font Scale": ("字体缩放", "字型縮放", "フォントスケール"),
"When `Shrink to Fit Text Box` is on, this is the resulting scale applied to the font size.": ("当「缩小以适应文本框」开启时，此为应用于字体大小的缩放结果。", "當「縮小以適應文字方塊」開啟時，此為套用於字型大小的縮放結果。", "「テキストボックスに合わせて縮小」がオンの場合、フォントサイズに適用されるスケールの結果です。"),
"Automatic Naming": ("自动命名", "自動命名", "自動命名"),
"When on, this layer will rename itself to match it's text.": ("开启时，此图层将自动重命名以匹配其文本内容。", "開啟時，此圖層將自動重新命名以符合其文字內容。", "オンにすると、このレイヤーはテキストに合わせて自動的に名前を変更します。"),
"Avoid Orphans": ("避免孤行", "避免孤行", "孤立行を回避"),
"Avoid single word lines. Requires the Text Box to be on.": ("避免单词独占一行。需要开启文本框。", "避免單詞獨占一行。需要開啟文字方塊。", "1 単語だけの行を避けます。テキストボックスが有効である必要があります。"),
"Corner Radius": ("圆角半径", "圓角半徑", "角の半径"),
"Corner Radius Mode": ("圆角半径模式", "圓角半徑模式", "角の半径モード"),
"Top Radii": ("顶部半径", "頂部半徑", "上部半径"),
"Bottom Radii": ("底部半径", "底部半徑", "下部半径"),
"Line Style": ("线条样式", "線條樣式", "ラインスタイル"),
"Baseline": ("基线", "基線", "ベースライン"),
"Line": ("行", "行", "行"),
"Word": ("词", "字詞", "単語"),
"Character": ("字符", "字元", "文字"),
"Paragraph": ("段落", "段落", "段落"),
"Document": ("文档", "文件", "ドキュメント"),
"Individual": ("单独", "個別", "個別"),
"Through": ("穿过", "穿過", "貫通"),
"Gaps": ("间隙", "間隙", "ギャップ"),
"Apply Font Size": ("应用字体大小", "套用字型大小", "フォントサイズを適用"),
"Procedurally set a Text Shape's Font Size based on a search (regex) via a Text Shape's Style Behaviours.": ("通过文本形状的样式行为，基于搜索（正则表达式）程序化设置文本形状的字体大小。", "透過文字形狀的樣式行為，基於搜尋（正規表達式）程序化設定文字形狀的字型大小。", "テキストシェイプのスタイルビヘイビアを通じて、検索（正規表現）に基づいてテキストシェイプのフォントサイズをプロシージャルに設定します。"),
"Indices": ("索引", "索引", "インデックス"),
"Regex": ("正则表达式", "正規表達式", "正規表現"),
"Apply Typeface": ("应用字体", "套用字體", "書体を適用"),
"Procedurally set a Text Shape's Typeface based on a search (regex) via a Text Shape's Style Behaviours.": ("通过文本形状的样式行为，基于搜索（正则表达式）程序化设置文本形状的字体。", "透過文字形狀的樣式行為，基於搜尋（正規表達式）程序化設定文字形狀的字體。", "テキストシェイプのスタイルビヘイビアを通じて、検索（正規表現）に基づいてテキストシェイプの書体をプロシージャルに設定します。"),
"Range": ("范围", "範圍", "範囲"),
"Apply Text Fill": ("应用文本填充", "套用文字填充", "テキスト塗りを適用"),
"Legacy Layer - new 'Apply Text Material' available.\nProcedurally set the Fill Color of a Text Shape's lines/ words/ characters or based on a search (regex).": ("旧版图层 - 新版「应用文本材质」已可用。\n程序化设置文本形状的行/词/字符的填充颜色，或基于搜索（正则表达式）设置。", "舊版圖層 - 新版「套用文字材質」已可用。\n程序化設定文字形狀的行/字詞/字元的填充顏色，或基於搜尋（正規表達式）設定。", "レガシーレイヤー - 新しい「テキストマテリアルを適用」が利用可能です。\nテキストシェイプの行/単語/文字の塗りカラーを検索（正規表現）に基づいてプロシージャルに設定します。"),
"Apply Text Material": ("应用文本材质", "套用文字材質", "テキストマテリアルを適用"),
"Procedurally set the Fill/Stroke of a Text Shape by lines/words/characters or search (regex).": ("按行/词/字符或搜索（正则表达式）程序化设置文本形状的填充/描边。", "按行/字詞/字元或搜尋（正規表達式）程序化設定文字形狀的填充/描邊。", "行/単語/文字または検索（正規表現）でテキストシェイプの塗り/ストロークをプロシージャルに設定します。"),
"Overwrite Blend Mode": ("覆盖混合模式", "覆寫混合模式", "描画モードを上書き"),
"Filters only work when either Fill or Stroke is enabled.": ("滤镜仅在启用填充或描边时有效。", "濾鏡僅在啟用填充或描邊時有效。", "フィルターは塗りまたはストロークが有効な場合のみ機能します。"),
"Apply Character Spacing": ("应用字符间距", "套用字元間距", "文字間隔を適用"),
"Create procedural kerning pairs via the Text Shape's Style Behaviours.": ("通过文本形状的样式行为创建程序化字距对。", "透過文字形狀的樣式行為建立程序化字距對。", "テキストシェイプのスタイルビヘイビアを通じてプロシージャルなカーニングペアを作成します。"),
"Matches": ("匹配", "符合", "マッチ"),
"Match String": ("匹配字符串", "符合字串", "マッチ文字列"),
"Apply OpenType": ("应用 OpenType", "套用 OpenType", "OpenType を適用"),
"Apply OpenType features to specific ranges of text.": ("将 OpenType 特性应用到特定范围的文本。", "將 OpenType 特性套用到特定範圍的文字。", "テキストの特定範囲に OpenType 機能を適用します。"),
"Features": ("特性", "特性", "機能"),
"Font Feature": ("字体特性", "字型特性", "フォント機能"),
"Access All Alternates": ("访问所有替代字形", "存取所有替代字形", "すべての代替字形にアクセス"),
"Above-base Forms": ("基线上方字形", "基線上方字形", "上部字形"),
"Above-base Mark Positioning": ("基线上方标记定位", "基線上方標記定位", "上部マーク位置決め"),
"Above-base Substitutions": ("基线上方替换", "基線上方替換", "上部代替"),
"Alternative Fractions": ("替代分数", "替代分數", "代替分数"),
"Akhand": ("Akhand", "Akhand", "Akhand"),
"Kerning for Alternate Proportional Widths": ("替代比例宽度字距", "替代比例寬度字距", "代替プロポーショナル幅カーニング"),
"Below-base Forms": ("基线下方字形", "基線下方字形", "下部字形"),
"Below-base Mark Positioning": ("基线下方标记定位", "基線下方標記定位", "下部マーク位置決め"),
"Below-base Substitutions": ("基线下方替换", "基線下方替換", "下部代替"),
"Contextual Alternates": ("上下文替代", "上下文替代", "コンテキスト代替"),
"Case-Sensitive Forms": ("大小写敏感字形", "大小寫敏感字形", "大文字小文字対応字形"),
"Glyph Composition/Decomposition": ("字形合成/分解", "字形合成/分解", "字形合成/分解"),
"Conjunct Form After Ro": ("Ro 后连接形式", "Ro 後連接形式", "Ro 後の結合形"),
"Contextual Half-width Spacing": ("上下文半角间距", "上下文半形間距", "コンテキスト半角スペーシング"),
"Conjunct Forms": ("连接形式", "連接形式", "結合形"),
"Contextual Ligatures": ("上下文连字", "上下文連字", "コンテキスト合字"),
"Centered CJK Punctuation": ("居中 CJK 标点", "置中 CJK 標點", "中央揃え CJK 句読点"),
"Capital Spacing": ("大写字母间距", "大寫字母間距", "大文字スペーシング"),
"Contextual Swash": ("上下文花饰", "上下文花飾", "コンテキストスワッシュ"),
"Cursive Positioning": ("草书定位", "草書定位", "筆記体位置決め"),
"Petite Capitals From Capitals": ("从大写到小型大写", "從大寫到小型大寫", "大文字からプチキャピタル"),
"Small Capitals From Capitals": ("从大写到小型大写字母", "從大寫到小型大寫字母", "大文字からスモールキャピタル"),
"Distances": ("距离", "距離", "距離"),
"Discretionary Ligatures": ("自由连字", "自由連字", "任意合字"),
"Denominators": ("分母", "分母", "分母"),
"Dotless Forms": ("无点字形", "無點字形", "ドットなし字形"),
"Expert Forms": ("专家字形", "專家字形", "エキスパート字形"),
"Final Glyph on Line Alternates": ("行尾字形替代", "行尾字形替代", "行末字形代替"),
"Terminal Forms #2": ("终结形式 #2", "終結形式 #2", "終端形 #2"),
"Terminal Forms #3": ("终结形式 #3", "終結形式 #3", "終端形 #3"),
"Terminal Forms": ("终结形式", "終結形式", "終端形"),
"Flattened Accent Forms": ("扁平重音字形", "扁平重音字形", "平坦化アクセント形"),
"Fractions": ("分数", "分數", "分数"),
"Full Widths": ("全角", "全形", "全角"),
"Half Forms": ("半形", "半形", "半字形"),
"Halant Forms": ("Halant 形式", "Halant 形式", "Halant 形"),
"Alternate Half Widths": ("替代半角", "替代半形", "代替半角"),
"Historical Forms": ("历史字形", "歷史字形", "歴史的字形"),
"Horizontal Kana Alternates": ("水平假名替代", "水平假名替代", "横書き仮名代替"),
"Historical Ligatures": ("历史连字", "歷史連字", "歴史的合字"),
"Hangul": ("韩文", "韓文", "ハングル"),
"Hojo Kanji Forms (JIS X 0212-1990 Kanji Forms)": ("补助汉字字形（JIS X 0212-1990 汉字字形）", "補助漢字字形（JIS X 0212-1990 漢字字形）", "補助漢字字形（JIS X 0212-1990 漢字字形）"),
"Half Widths": ("半角", "半形", "半角"),
"Initial Forms": ("起始形式", "起始形式", "語頭形"),
"Isolated Forms": ("独立形式", "獨立形式", "独立形"),
"Italics": ("斜体", "斜體", "イタリック"),
"Justification Alternates": ("两端对齐替代", "兩端對齊替代", "均等割り付け代替"),
"JIS78 Forms": ("JIS78 字形", "JIS78 字形", "JIS78 字形"),
"JIS83 Forms": ("JIS83 字形", "JIS83 字形", "JIS83 字形"),
"JIS90 Forms": ("JIS90 字形", "JIS90 字形", "JIS90 字形"),
"JIS2004 Forms": ("JIS2004 字形", "JIS2004 字形", "JIS2004 字形"),
"Kerning": ("字距调整", "字距調整", "カーニング"),
"Left Bounds": ("左边界", "左邊界", "左境界"),
"Standard Ligatures": ("标准连字", "標準連字", "標準合字"),
"Leading Jamo Forms": ("前导字母字形", "前導字母字形", "先頭字母字形"),
"Lining Figures": ("等线数字", "等線數字", "ライニング数字"),
"Localized Forms": ("本地化字形", "本地化字形", "ローカライズ字形"),
"Left-to-right Alternates": ("从左到右替代", "從左到右替代", "左から右代替"),
"Left-to-right Mirrored Forms": ("从左到右镜像字形", "從左到右鏡像字形", "左から右ミラー字形"),
"Mark Positioning": ("标记定位", "標記定位", "マーク位置決め"),
"Medial Forms #2": ("中间形式 #2", "中間形式 #2", "語中形 #2"),
"Medial Forms": ("中间形式", "中間形式", "語中形"),
"Mathematical Greek": ("数学希腊文", "數學希臘文", "数学用ギリシャ文字"),
"Mark to Mark Positioning": ("标记到标记定位", "標記到標記定位", "マーク間位置決め"),
"Mark Positioning via Substitution": ("通过替换进行标记定位", "透過替換進行標記定位", "代替によるマーク位置決め"),
"Alternate Annotation Forms": ("替代注释字形", "替代註解字形", "代替注釈字形"),
"NLC Kanji Forms": ("NLC 汉字字形", "NLC 漢字字形", "NLC 漢字字形"),
"Nukta Forms": ("Nukta 形式", "Nukta 形式", "Nukta 形"),
"Numerators": ("分子", "分子", "分子"),
"Oldstyle Figures": ("旧体数字", "舊體數字", "オールドスタイル数字"),
"Optical Bounds": ("视觉边界", "視覺邊界", "光学境界"),
"Ordinals": ("序数", "序數", "序数"),
"Ornaments": ("装饰", "裝飾", "オーナメント"),
"Proportional Alternate Widths": ("比例替代宽度", "比例替代寬度", "プロポーショナル代替幅"),
"Petite Capitals": ("小型大写", "小型大寫", "プチキャピタル"),
"Proportional Kana": ("比例假名", "比例假名", "プロポーショナル仮名"),
"Proportional Figures": ("比例数字", "比例數字", "プロポーショナル数字"),
"Pre-base Forms": ("基线前方字形", "基線前方字形", "前部字形"),
"Pre-base Substitutions": ("基线前方替换", "基線前方替換", "前部代替"),
"Post-base Forms": ("基线后方字形", "基線後方字形", "後部字形"),
"Post-base Substitutions": ("基线后方替换", "基線後方替換", "後部代替"),
"Proportional Widths": ("比例宽度", "比例寬度", "プロポーショナル幅"),
"Quarter Widths": ("四分之一宽", "四分之一寬", "1/4 角"),
"Randomize": ("随机化", "隨機化", "ランダム化"),
"Required Contextual Alternates": ("必需上下文替代", "必需上下文替代", "必須コンテキスト代替"),
"Rakar Forms": ("Rakar 形式", "Rakar 形式", "Rakar 形"),
"Required Ligatures": ("必需连字", "必需連字", "必須合字"),
"Reph Form": ("Reph 形式", "Reph 形式", "Reph 形"),
"Right Bounds": ("右边界", "右邊界", "右境界"),
"Right-to-left Alternates": ("从右到左替代", "從右到左替代", "右から左代替"),
"Right-to-left Mirrored Forms": ("从右到左镜像字形", "從右到左鏡像字形", "右から左ミラー字形"),
"Ruby Notation Forms": ("注音字形", "注音字形", "ルビ用字形"),
"Required Variation Alternates": ("必需变体替代", "必需變體替代", "必須バリエーション代替"),
"Stylistic Alternates": ("风格替代", "風格替代", "スタイル代替"),
"Scientific Inferiors": ("科学下标", "科學下標", "科学下付き"),
"Optical Size": ("视觉大小", "視覺大小", "オプティカルサイズ"),
"Small Capitals": ("小型大写字母", "小型大寫字母", "スモールキャピタル"),
"Simplified Forms": ("简化字形", "簡化字形", "簡略字形"),
"Math Script-style Alternates": ("数学手写风格替代", "數學手寫風格替代", "数学スクリプトスタイル代替"),
"Stretching Glyph Decomposition": ("拉伸字形分解", "拉伸字形分解", "伸縮字形分解"),
"Subscript": ("下标", "下標", "下付き"),
"Superscript": ("上标", "上標", "上付き"),
"Swash": ("花饰", "花飾", "スワッシュ"),
"Titling": ("标题", "標題", "タイトル用"),
"Trailing Jamo Forms": ("尾随字母字形", "尾隨字母字形", "末尾字母字形"),
"Traditional Name Forms": ("传统名称字形", "傳統名稱字形", "伝統的名前字形"),
"Tabular Figures": ("等宽数字", "等寬數字", "タビュラー数字"),
"Traditional Forms": ("传统字形", "傳統字形", "伝統的字形"),
"Third Widths": ("三分之一宽", "三分之一寬", "1/3 角"),
"Unicase": ("单一大小写", "單一大小寫", "ユニケース"),
"Alternate Vertical Metrics": ("替代垂直度量", "替代垂直度量", "代替縦書きメトリクス"),
"Kerning for Alternate Proportional Vertical Metrics": ("替代比例垂直度量字距", "替代比例垂直度量字距", "代替プロポーショナル縦書きメトリクスカーニング"),
"Vattu Variants": ("Vattu 变体", "Vattu 變體", "Vattu バリアント"),
"Vertical Contextual Half-width Spacing": ("垂直上下文半角间距", "垂直上下文半形間距", "縦書きコンテキスト半角スペーシング"),
"Vertical Alternates": ("垂直替代", "垂直替代", "縦書き代替"),
"Alternate Vertical Half Metrics": ("替代垂直半角度量", "替代垂直半形度量", "代替縦書き半角メトリクス"),
"Vowel Jamo Forms": ("元音字母字形", "母音字母字形", "母音字母字形"),
"Vertical Kana Alternates": ("垂直假名替代", "垂直假名替代", "縦書き仮名代替"),
"Vertical Kerning": ("垂直字距", "垂直字距", "縦書きカーニング"),
"Proportional Alternate Vertical Metrics": ("比例替代垂直度量", "比例替代垂直度量", "プロポーショナル代替縦書きメトリクス"),
"Vertical Alternates and Rotation": ("垂直替代和旋转", "垂直替代和旋轉", "縦書き代替と回転"),
"Vertical Alternates for Rotation": ("用于旋转的垂直替代", "用於旋轉的垂直替代", "回転用縦書き代替"),
"Slashed Zero": ("斜线零", "斜線零", "スラッシュゼロ"),
"Apply Font Style": ("应用字体样式", "套用字型樣式", "フォントスタイルを適用"),
"Apply Font styles such as underline and superscript to specific ranges of text.": ("将下划线和上标等字体样式应用到特定范围的文本。", "將底線和上標等字型樣式套用到特定範圍的文字。", "下線や上付きなどのフォントスタイルをテキストの特定範囲に適用します。"),
"": ("", "", ""),
"Set the indices to select. Values should be comma separated for lists or colon separated for ranges.": ("设置要选择的索引。列表使用逗号分隔，范围使用冒号分隔。", "設定要選取的索引。列表使用逗號分隔，範圍使用冒號分隔。", "選択するインデックスを設定します。リストにはカンマ区切り、範囲にはコロン区切りを使用します。"),
"Choose a mode for the selection type.": ("选择选取类型的模式。", "選擇選取類型的模式。", "選択タイプのモードを選択します。"),
"Set a Regular Expression to determine which parts of the string will be selected.": ("设置正则表达式以确定字符串中哪些部分将被选取。", "設定正規表達式以決定字串中哪些部分將被選取。", "文字列のどの部分が選択されるかを決定する正規表現を設定します。"),
"Select which level (Line/Word) is affected.": ("选择受影响的级别（行/词）。", "選擇受影響的層級（行/字詞）。", "影響を受けるレベル（行/単語）を選択します。"),
"Underline": ("下划线", "底線", "下線"),
"When checked, an underline style will be applied.": ("勾选时，将应用下划线样式。", "勾選時，將套用底線樣式。", "チェックすると、下線スタイルが適用されます。"),
"Strikethrough": ("删除线", "刪除線", "取り消し線"),
"When checked, a strikethrough style will be applied.": ("勾选时，将应用删除线样式。", "勾選時，將套用刪除線樣式。", "チェックすると、取り消し線スタイルが適用されます。"),
"Supers Inferiors Mode": ("上标下标模式", "上標下標模式", "上付き下付きモード"),
"Select a Superscript or Subscript style.": ("选择上标或下标样式。", "選擇上標或下標樣式。", "上付きまたは下付きスタイルを選択します。"),
"Capture Group Indices": ("捕获组索引", "擷取群組索引", "キャプチャグループインデックス"),
"Where a Regular Expression includes capture groups, specify which groups are returned.": ("当正则表达式包含捕获组时，指定返回哪些组。", "當正規表達式包含擷取群組時，指定傳回哪些群組。", "正規表現にキャプチャグループが含まれる場合、返されるグループを指定します。"),
"A Shape that uses geometry from another Layer (e.g. a Shape or the JavaScript Utility).": ("使用来自另一个图层（如形状或 JavaScript 实用工具）几何体的形状。", "使用來自另一個圖層（如形狀或 JavaScript 工具）幾何體的形狀。", "別のレイヤー（シェイプや JavaScript ユーティリティなど）のジオメトリを使用するシェイプです。"),
"Bake Transform": ("烘焙变换", "烘焙變換", "トランスフォームをベイク"),
"Control which Layers are affected by Behaviours by using indices.": ("使用索引控制哪些图层受行为影响。", "使用索引控制哪些圖層受行為影響。", "インデックスを使用してビヘイビアの影響を受けるレイヤーを制御します。"),
"Transition Size": ("过渡大小", "過渡大小", "トランジションサイズ"),
"The number of indices to include in the transition.": ("过渡中包含的索引数量。", "過渡中包含的索引數量。", "トランジションに含めるインデックスの数。"),
"Transition": ("过渡", "過渡", "トランジション"),
"Connect Distributions of points to create intricate patterns of lines.": ("连接点分布以创建复杂的线条图案。", "連接點分佈以建立複雜的線條圖案。", "ポイントの分布を接続して複雑なラインパターンを作成します。"),
"Source Distribution": ("源分布", "來源分佈", "ソース分布"),
"Target Distribution": ("目标分布", "目標分佈", "ターゲット分布"),
"Search Distance": ("搜索距离", "搜尋距離", "検索距離"),
"Line Type": ("线条类型", "線條類型", "ラインタイプ"),
"Connection Limit": ("连接限制", "連接限制", "接続制限"),
"Source Bézier Bias": ("源贝塞尔偏差", "來源貝茲偏差", "ソースベジェバイアス"),
"Target Bézier Bias": ("目标贝塞尔偏差", "目標貝茲偏差", "ターゲットベジェバイアス"),
"Skip Points": ("跳过点", "跳過點", "ポイントをスキップ"),
"Skip Offset": ("跳过偏移", "跳過偏移", "スキップオフセット"),
"Ignore Target Distribution": ("忽略目标分布", "忽略目標分佈", "ターゲット分布を無視"),
"Per Point Connection Limit": ("每点连接限制", "每點連接限制", "ポイントごとの接続制限"),
"Auto Bézier Mode": ("自动贝塞尔模式", "自動貝茲模式", "自動ベジェモード"),
"Control Point Bias": ("控制点偏差", "控制點偏差", "コントロールポイントバイアス"),
"Within Range": ("范围内", "範圍內", "範囲内"),
"Nearest": ("最近", "最近", "最近傍"),
"Point Index": ("点索引", "點索引", "ポイントインデックス"),
"Bézier": ("贝塞尔", "貝茲", "ベジェ"),
"Auto Bézier": ("自动贝塞尔", "自動貝茲", "自動ベジェ"),
"Shoulder Both": ("两侧弧肩", "兩側弧肩", "両側ショルダー"),
"Shoulder Target": ("目标弧肩", "目標弧肩", "ターゲットショルダー"),
"Shoulder Source": ("源弧肩", "來源弧肩", "ソースショルダー"),
"Projection Vectors": ("投影向量", "投影向量", "投影ベクトル"),
"Source": ("源", "來源", "ソース"),
"Offset Position": ("偏移位置", "偏移位置", "オフセット位置"),
"Offset Rotation": ("偏移旋转", "偏移旋轉", "オフセット回転"),
"Offset Scale": ("偏移缩放", "偏移縮放", "オフセットスケール"),
"Hash": ("哈希", "雜湊", "ハッシュ"),
"Generate a Hash string with the String Generator": ("使用字符串生成器生成哈希字符串", "使用字串產生器產生雜湊字串", "文字列ジェネレーターでハッシュ文字列を生成します"),
"Number of Lines": ("行数", "行數", "行数"),
"Line Offset": ("行偏移", "行偏移", "行オフセット"),
"Random Seed": ("随机种子", "隨機種子", "ランダムシード"),
"Generate a Value for the String Generator.": ("为字符串生成器生成一个值。", "為字串產生器產生一個值。", "文字列ジェネレーター用の値を生成します。"),
"Precision": ("精度", "精度", "精度"),
"Thousands Separator": ("千位分隔符", "千位分隔符", "桁区切り"),
"Multiplier": ("乘数", "乘數", "乗数"),
"Decimal Separator": ("小数分隔符", "小數分隔符", "小数点記号"),
"Hexadecimal": ("十六进制", "十六進位", "16 進数"),
"Generate a Hexidecimal (base-16) string for the String Generator.": ("为字符串生成器生成十六进制（base-16）字符串。", "為字串產生器產生十六進位（base-16）字串。", "文字列ジェネレーター用の 16 進数（base-16）文字列を生成します。"),
"Random Number": ("随机数", "隨機數", "乱数"),
"Generate a Random Number for the String Generator.": ("为字符串生成器生成随机数。", "為字串產生器產生隨機數。", "文字列ジェネレーター用の乱数を生成します。"),
"Whole Numbers": ("整数", "整數", "整数"),
"Delimiter": ("分隔符", "分隔符", "区切り文字"),
"Clamp Minimum": ("钳制最小值", "鉗制最小值", "クランプ最小値"),
"Clamp Maximum": ("钳制最大值", "鉗制最大值", "クランプ最大値"),
"Create shapes by sampling an Image Asset.": ("通过采样图像素材创建形状。", "透過取樣影像素材建立形狀。", "画像アセットをサンプリングしてシェイプを作成します。"),
"Iterations": ("迭代次数", "迭代次數", "反復回数"),
"Image": ("图像", "影像", "画像"),
"Rectangles": ("矩形", "矩形", "矩形"),
"Circles": ("圆形", "圓形", "円"),
"Create a primitive line such as bézier, spiral or straight.": ("创建基本线条，如贝塞尔、螺旋或直线。", "建立基本線條，如貝茲、螺旋或直線。", "ベジェ、スパイラル、直線などのプリミティブラインを作成します。"),
"Generate a line primitive.": ("生成线条基本体。", "產生線條基本體。", "ラインプリミティブを生成します。"),
"Spiral": ("螺旋", "螺旋", "スパイラル"),
"Generate a spiral line primitive.": ("生成螺旋线条基本体。", "產生螺旋線條基本體。", "スパイラルラインプリミティブを生成します。"),
"Outer Radius": ("外半径", "外半徑", "外径"),
"Inner Radius": ("内半径", "內半徑", "内径"),
"Sides": ("边数", "邊數", "辺数"),
"Generate a bézier line primitive.": ("生成贝塞尔线条基本体。", "產生貝茲線條基本體。", "ベジェラインプリミティブを生成します。"),
"Start Position": ("起始位置", "起始位置", "開始位置"),
"End Position": ("结束位置", "結束位置", "終了位置"),
"Start Offset": ("起始偏移", "起始偏移", "開始オフセット"),
"End Offset": ("结束偏移", "結束偏移", "終了オフセット"),
"Ray": ("射线", "射線", "レイ"),
"Cast a ray from a point to create a line of infinite length unless it collides with other Shapes.": ("从一个点投射射线创建无限长的线条，除非与其他形状碰撞。", "從一個點投射射線建立無限長的線條，除非與其他形狀碰撞。", "ポイントからレイをキャストして、他のシェイプと衝突しない限り無限長のラインを作成します。"),
"Collision Shapes": ("碰撞形状", "碰撞形狀", "衝突シェイプ"),
"Collision Margin": ("碰撞边距", "碰撞邊距", "衝突マージン"),
"Bidirectional": ("双向", "雙向", "双方向"),
"Create a geometry stroke around a Shape.": ("在形状周围创建几何描边。", "在形狀周圍建立幾何描邊。", "シェイプの周囲にジオメトリストロークを作成します。"),
"Input Shapes": ("输入形状", "輸入形狀", "入力シェイプ"),
"Clean Up": ("清理", "清理", "クリーンアップ"),
"Preserve Materials": ("保留材质", "保留材質", "マテリアルを保持"),
"Preserve Materials will copy Stroke (or Fill) settings from the Input Shapes to the Outline.": ("保留材质将从输入形状复制描边（或填充）设置到轮廓。", "保留材質將從輸入形狀複製描邊（或填充）設定到輪廓。", "マテリアルを保持すると、入力シェイプのストローク（または塗り）設定がアウトラインにコピーされます。"),
"Create paths between start and end points.": ("在起点和终点之间创建路径。", "在起點和終點之間建立路徑。", "開始点と終了点の間にパスを作成します。"),
"Points Distribution": ("点分布", "點分佈", "ポイント分布"),
"Start Travel": ("起始行进", "起始行進", "開始トラベル"),
"End Travel": ("结束行进", "結束行進", "終了トラベル"),
"Search Radius": ("搜索半径", "搜尋半徑", "検索半径"),
"Allows fine tuning of the Shortest Path algorithm by adjusting how far it can look for useful points in the Distribution.": ("通过调整算法在分布中寻找有用点的距离来微调最短路径算法。", "透過調整演算法在分佈中尋找有用點的距離來微調最短路徑演算法。", "分布内で有用なポイントを探索できる距離を調整して、最短パスアルゴリズムを微調整できます。"),
"Use Search Radius": ("使用搜索半径", "使用搜尋半徑", "検索半径を使用"),
"When Count is higher than 1, connect a Behaviour (e.g. Random) to the Start or End Travel Attributes so that each path is different.": ("当数量大于 1 时，将行为（如随机）连接到起始或结束行进属性，使每条路径不同。", "當數量大於 1 時，將行為（如隨機）連接到起始或結束行進屬性，使每條路徑不同。", "カウントが 1 より大きい場合、ビヘイビア（例: ランダム）を開始または終了トラベル属性に接続して、各パスを異なるものにします。"),
"Location": ("位置", "位置", "位置"),
"Duplicate and distribute shapes.": ("复制和分布形状。", "複製和分佈形狀。", "シェイプを複製して分布します。"),
"Connect or add Shapes to be duplicated.": ("连接或添加要复制的形状。", "連接或新增要複製的形狀。", "複製するシェイプを接続または追加します。"),
"Determine the layout of the duplicates.": ("确定复制体的布局。", "決定複製體的佈局。", "複製のレイアウトを決定します。"),
"Shape Position": ("形状位置", "形狀位置", "シェイプ位置"),
"Set positions on a per duplicate basis.": ("按复制体逐个设置位置。", "按複製體逐個設定位置。", "複製ごとに位置を設定します。"),
"Shape Rotation": ("形状旋转", "形狀旋轉", "シェイプ回転"),
"Set rotations on a per duplicate basis.": ("按复制体逐个设置旋转。", "按複製體逐個設定旋轉。", "複製ごとに回転を設定します。"),
"Shape Scale": ("形状缩放", "形狀縮放", "シェイプスケール"),
"Set scales on a per duplicate basis.": ("按复制体逐个设置缩放。", "按複製體逐個設定縮放。", "複製ごとにスケールを設定します。"),
"Shape Visibility": ("形状可见性", "形狀可見性", "シェイプの表示/非表示"),
"Set visibility on a per duplicate basis.": ("按复制体逐个设置可见性。", "按複製體逐個設定可見性。", "複製ごとに表示/非表示を設定します。"),
"Shape Opacity": ("形状不透明度", "形狀不透明度", "シェイプの不透明度"),
"Set opacity on a per duplicate basis.": ("按复制体逐个设置不透明度。", "按複製體逐個設定不透明度。", "複製ごとに不透明度を設定します。"),
"Auto Id": ("自动 ID", "自動 ID", "自動 ID"),
"Automatically assign shape ids.": ("自动分配形状 ID。", "自動分配形狀 ID。", "シェイプ ID を自動的に割り当てます。"),
"Shape Id": ("形状 ID", "形狀 ID", "シェイプ ID"),
"Set the Id of the Input Shape(s) to be duplicated.": ("设置要复制的输入形状的 ID。", "設定要複製的輸入形狀的 ID。", "複製する入力シェイプの ID を設定します。"),
"Shape Time Offset": ("形状时间偏移", "形狀時間偏移", "シェイプ時間オフセット"),
"Offset the animation curve for duplicates on a per shape basis.": ("按形状逐个偏移复制体的动画曲线。", "按形狀逐個偏移複製體的動畫曲線。", "シェイプごとに複製のアニメーションカーブをオフセットします。"),
"Index Context": ("索引上下文", "索引上下文", "インデックスコンテキスト"),
"Dynamically outputs the index for each duplicate.": ("动态输出每个复制体的索引。", "動態輸出每個複製體的索引。", "各複製のインデックスを動的に出力します。"),
"Skip Invisible Duplicates": ("跳过不可见复制体", "跳過不可見複製體", "非表示の複製をスキップ"),
"When Shape Visibility is set to false, the shape will be skipped (not calculated).": ("当形状可见性设为 false 时，该形状将被跳过（不计算）。", "當形狀可見性設為 false 時，該形狀將被跳過（不計算）。", "シェイプの表示/非表示が false に設定されている場合、そのシェイプはスキップされます（計算されません）。"),
"Grid": ("网格", "網格", "グリッド"),
"Distribute points in a radial pattern.": ("以径向图案分布点。", "以放射狀圖案分佈點。", "放射状パターンでポイントを分布します。"),
"Include End": ("包含结尾", "包含結尾", "終端を含む"),
"Use Rotation": ("使用旋转", "使用旋轉", "回転を使用"),
"Random": ("随机", "隨機", "ランダム"),
"Distribute points to random positions.": ("将点分布到随机位置。", "將點分佈到隨機位置。", "ランダムな位置にポイントを分布します。"),
"Relax": ("松弛", "鬆弛", "リラックス"),
"Relax Distance": ("松弛距离", "鬆弛距離", "リラックス距離"),
"Max Iterations": ("最大迭代次数", "最大迭代次數", "最大反復回数"),
"Keep Shape": ("保持形状", "保持形狀", "シェイプを保持"),
"Threshold": ("阈值", "閾值", "しきい値"),
"Use Probability": ("使用概率", "使用機率", "確率を使用"),
"Point": ("点", "點", "ポイント"),
"Distribute points at 0,0.": ("在 0,0 处分布点。", "在 0,0 處分佈點。", "0,0 にポイントを分布します。"),
"Array": ("数组", "陣列", "配列"),
"Distribute points by specifying positions for each index.": ("通过为每个索引指定位置来分布点。", "透過為每個索引指定位置來分佈點。", "各インデックスの位置を指定してポイントを分布します。"),
"Particle": ("粒子", "粒子", "パーティクル"),
"Distribute points onto a Particle Shape.": ("将点分布到粒子形状上。", "將點分佈到粒子形狀上。", "パーティクルシェイプ上にポイントを分布します。"),
"Distribute points along a path.": ("沿路径分布点。", "沿路徑分佈點。", "パスに沿ってポイントを分布します。"),
"Exclude End": ("排除结尾", "排除結尾", "終端を除外"),
"Count Mode": ("计数模式", "計數模式", "カウントモード"),
"Per Shape": ("按形状", "按形狀", "シェイプごと"),
"Per Contour": ("按轮廓", "按輪廓", "輪郭ごと"),
"Shape Points": ("形状点", "形狀點", "シェイプポイント"),
"Distribute points onto another Shape's points/vertices.": ("将点分布到另一个形状的点/顶点上。", "將點分佈到另一個形狀的點/頂點上。", "別のシェイプのポイント/頂点上にポイントを分布します。"),
"Distribution Shape": ("分布形状", "分佈形狀", "分布シェイプ"),
"Fill All": ("全部填充", "全部填充", "すべて塗り"),
"Shape Edges": ("形状边", "形狀邊", "シェイプエッジ"),
"Distribute points onto another Shape's edges.": ("将点分布到另一个形状的边上。", "將點分佈到另一個形狀的邊上。", "別のシェイプのエッジ上にポイントを分布します。"),
"Edge Bias": ("边偏差", "邊偏差", "エッジバイアス"),
"Voxelize": ("体素化", "體素化", "ボクセル化"),
"Distribute points by voxelizing another Shape.": ("通过体素化另一个形状来分布点。", "透過體素化另一個形狀來分佈點。", "別のシェイプをボクセル化してポイントを分布します。"),
"Pattern": ("图案", "圖案", "パターン"),
"Hypo": ("内旋轮线", "內旋輪線", "ハイポ"),
"Rose": ("玫瑰线", "玫瑰線", "ローズ"),
"Distribute points in a rose pattern.": ("以玫瑰线图案分布点。", "以玫瑰線圖案分佈點。", "ローズパターンでポイントを分布します。"),
"Close Path": ("闭合路径", "閉合路徑", "パスを閉じる"),
"Distribute points in a grid.": ("以网格分布点。", "以網格分佈點。", "グリッドでポイントを分布します。"),
"Set the number of duplicates. [x,y]": ("设置复制数量。[x,y]", "設定複製數量。[x,y]", "複製の数を設定します。[x,y]"),
"Set the size of the grid. [x,y]": ("设置网格大小。[x,y]", "設定網格大小。[x,y]", "グリッドのサイズを設定します。[x,y]"),
"Pattern Offset": ("图案偏移", "圖案偏移", "パターンオフセット"),
"Set a value to offset every other row/column. [x,y]": ("设置交替行/列的偏移值。[x,y]", "設定交替行/列的偏移值。[x,y]", "1 行/列おきにオフセットする値を設定します。[x,y]"),
"Size Mode": ("大小模式", "大小模式", "サイズモード"),
"Determine how the Size attribute affects the grid.": ("确定大小属性如何影响网格。", "決定大小屬性如何影響網格。", "サイズ属性がグリッドにどのように影響するかを決定します。"),
"Determine whether points are ordered in columns or rows.": ("确定点按列还是按行排列。", "決定點按列還是按行排列。", "ポイントを列順または行順のどちらで並べるかを決定します。"),
"Fit": ("适应", "適應", "フィット"),
"Step": ("步进", "步進", "ステップ"),
"Distribute points in a horizontal or vertical line.": ("以水平或垂直线分布点。", "以水平或垂直線分佈點。", "水平または垂直のラインにポイントを分布します。"),
"Distribute points using JavaScript.": ("使用 JavaScript 分布点。", "使用 JavaScript 分佈點。", "JavaScript を使用してポイントを分布します。"),
"Input Distribution": ("输入分布", "輸入分佈", "入力分布"),
"Distribute points onto the positions of child-meshes.": ("将点分布到子网格的位置上。", "將點分佈到子網格的位置上。", "子メッシュの位置上にポイントを分布します。"),
"Scale To Fit": ("缩放以适应", "縮放以適應", "フィットするようにスケール"),
"Scale Multiplier": ("缩放乘数", "縮放乘數", "スケール乗数"),
"Keep Aspect Ratio": ("保持纵横比", "保持長寬比", "アスペクト比を維持"),
"Ignore Empty Sub-Meshes": ("忽略空子网格", "忽略空子網格", "空のサブメッシュを無視"),
}
