<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh-Hans">
  <context>
    <name>QMenuBar</name>
    <message>
      <source>File</source>
      <translation>文件</translation>
    </message>
    <message>
      <source>Edit</source>
      <translation>编辑</translation>
    </message>
    <message>
      <source>View</source>
      <translation>视图</translation>
    </message>
    <message>
      <source>Window</source>
      <translation>窗口</translation>
    </message>
    <message>
      <source>Help</source>
      <translation>帮助</translation>
    </message>
  </context>
  <context>
    <name>MenuBarManager</name>
    <message>
      <source>File</source>
      <translation>文件</translation>
    </message>
    <message>
      <source>Edit</source>
      <translation>编辑</translation>
    </message>
    <message>
      <source>View</source>
      <translation>视图</translation>
    </message>
    <message>
      <source>Window</source>
      <translation>窗口</translation>
    </message>
    <message>
      <source>&amp;Help</source>
      <translation>&amp;帮助</translation>
    </message>
    <message>
      <source>New Scene</source>
      <translation>新建场景</translation>
    </message>
    <message>
      <source>Import Assets...</source>
      <translation>导入资源...</translation>
    </message>
    <message>
      <source>Import Assets</source>
      <translation>导入资源</translation>
    </message>
    <message>
      <source>Save Scene</source>
      <translation>保存场景</translation>
    </message>
    <message>
      <source>Project Settings</source>
      <translation>项目设置</translation>
    </message>
    <message>
      <source>Open Project Settings</source>
      <translation>打开项目设置</translation>
    </message>
    <message>
      <source>Preferences</source>
      <translation>偏好设置</translation>
    </message>
    <message>
      <source>Show Preferences Folder</source>
      <translation>显示偏好设置文件夹</translation>
    </message>
    <message>
      <source>Override Preferences</source>
      <translation>覆盖偏好设置</translation>
    </message>
    <message>
      <source>About Cavalry</source>
      <translation>关于 Cavalry</translation>
    </message>
  </context>
  <context>
    <name>QFileDialog</name>
    <message>
      <source>Open</source>
      <translation>打开</translation>
    </message>
    <message>
      <source>Save</source>
      <translation>保存</translation>
    </message>
    <message>
      <source>Save As</source>
      <translation>另存为</translation>
    </message>
    <message>
      <source>Close</source>
      <translation>关闭</translation>
    </message>
    <message>
      <source>File</source>
      <translation>文件</translation>
    </message>
    <message>
      <source>Folder</source>
      <translation>文件夹</translation>
    </message>
    <message>
      <source>Files of type:</source>
      <translation>文件类型:</translation>
    </message>
    <message>
      <source>Look in:</source>
      <translation>查找位置:</translation>
    </message>
    <message>
      <source>File name:</source>
      <translation>文件名:</translation>
    </message>
    <message>
      <source>Back</source>
      <translation>后退</translation>
    </message>
    <message>
      <source>Forward</source>
      <translation>前进</translation>
    </message>
    <message>
      <source>Parent Directory</source>
      <translation>上级目录</translation>
    </message>
    <message>
      <source>Create New Folder</source>
      <translation>新建文件夹</translation>
    </message>
    <message>
      <source>List View</source>
      <translation>列表视图</translation>
    </message>
    <message>
      <source>Detail View</source>
      <translation>详细视图</translation>
    </message>
  </context>
  <context>
    <name>QDialog</name>
    <message>
      <source>OK</source>
      <translation>确定</translation>
    </message>
    <message>
      <source>Cancel</source>
      <translation>取消</translation>
    </message>
    <message>
      <source>Apply</source>
      <translation>应用</translation>
    </message>
    <message>
      <source>Yes</source>
      <translation>是</translation>
    </message>
    <message>
      <source>No</source>
      <translation>否</translation>
    </message>
    <message>
      <source>Close</source>
      <translation>关闭</translation>
    </message>
    <message>
      <source>Help</source>
      <translation>帮助</translation>
    </message>
    <message>
      <source>Reset</source>
      <translation>重置</translation>
    </message>
    <message>
      <source>Retry</source>
      <translation>重试</translation>
    </message>
    <message>
      <source>Ignore</source>
      <translation>忽略</translation>
    </message>
    <message>
      <source>Abort</source>
      <translation>中止</translation>
    </message>
  </context>
  <context>
    <name>QMessageBox</name>
    <message>
      <source>OK</source>
      <translation>确定</translation>
    </message>
    <message>
      <source>Cancel</source>
      <translation>取消</translation>
    </message>
    <message>
      <source>Yes</source>
      <translation>是</translation>
    </message>
    <message>
      <source>No</source>
      <translation>否</translation>
    </message>
    <message>
      <source>Yes to All</source>
      <translation>全部是</translation>
    </message>
    <message>
      <source>No to All</source>
      <translation>全部否</translation>
    </message>
    <message>
      <source>Save</source>
      <translation>保存</translation>
    </message>
    <message>
      <source>Discard</source>
      <translation>放弃</translation>
    </message>
    <message>
      <source>Don&apos;t Save</source>
      <translation>不保存</translation>
    </message>
    <message>
      <source>Close</source>
      <translation>关闭</translation>
    </message>
    <message>
      <source>Help</source>
      <translation>帮助</translation>
    </message>
  </context>
  <context>
    <name>QUndoStack</name>
    <message>
      <source>Undo</source>
      <translation>撤销</translation>
    </message>
    <message>
      <source>Redo</source>
      <translation>重做</translation>
    </message>
    <message>
      <source>Undo %1</source>
      <translation>撤销 %1</translation>
    </message>
    <message>
      <source>Redo %1</source>
      <translation>重做 %1</translation>
    </message>
  </context>
  <context>
    <name>QShortcut</name>
    <message>
      <source>Ctrl</source>
      <translation>Ctrl</translation>
    </message>
    <message>
      <source>Shift</source>
      <translation>Shift</translation>
    </message>
    <message>
      <source>Alt</source>
      <translation>Alt</translation>
    </message>
  </context>
  <context>
    <name>QTabBar</name>
    <message>
      <source>Close</source>
      <translation>关闭</translation>
    </message>
    <message>
      <source>Close Tab</source>
      <translation>关闭标签页</translation>
    </message>
    <message>
      <source>Close Other Tabs</source>
      <translation>关闭其他标签页</translation>
    </message>
  </context>
  <context>
    <name>QLineEdit</name>
    <message>
      <source>Cut</source>
      <translation>剪切</translation>
    </message>
    <message>
      <source>Copy</source>
      <translation>复制</translation>
    </message>
    <message>
      <source>Paste</source>
      <translation>粘贴</translation>
    </message>
    <message>
      <source>Select All</source>
      <translation>全选</translation>
    </message>
    <message>
      <source>Undo</source>
      <translation>撤销</translation>
    </message>
    <message>
      <source>Redo</source>
      <translation>重做</translation>
    </message>
    <message>
      <source>Delete</source>
      <translation>删除</translation>
    </message>
  </context>
  <context>
    <name>QPrintDialog</name>
    <message>
      <source>Print</source>
      <translation>打印</translation>
    </message>
    <message>
      <source>Printer</source>
      <translation>打印机</translation>
    </message>
    <message>
      <source>Print to File</source>
      <translation>打印到文件</translation>
    </message>
  </context>
</TS>
