<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh_TW">
  <context>
    <name>QMenuBar</name>
    <message>
      <source>File</source>
      <translation>檔案</translation>
    </message>
    <message>
      <source>Edit</source>
      <translation>編輯</translation>
    </message>
    <message>
      <source>View</source>
      <translation>檢視</translation>
    </message>
    <message>
      <source>Window</source>
      <translation>視窗</translation>
    </message>
    <message>
      <source>Help</source>
      <translation>說明</translation>
    </message>
  </context>
  <context>
    <name>QFileDialog</name>
    <message>
      <source>Open</source>
      <translation>開啟</translation>
    </message>
    <message>
      <source>Save</source>
      <translation>儲存</translation>
    </message>
    <message>
      <source>Save As</source>
      <translation>另存新檔</translation>
    </message>
    <message>
      <source>Close</source>
      <translation>關閉</translation>
    </message>
    <message>
      <source>File</source>
      <translation>檔案</translation>
    </message>
    <message>
      <source>Folder</source>
      <translation>資料夾</translation>
    </message>
    <message>
      <source>Files of type:</source>
      <translation>檔案類型:</translation>
    </message>
    <message>
      <source>Look in:</source>
      <translation>查詢位置:</translation>
    </message>
    <message>
      <source>File name:</source>
      <translation>檔案名稱:</translation>
    </message>
    <message>
      <source>Back</source>
      <translation>上一步</translation>
    </message>
    <message>
      <source>Forward</source>
      <translation>下一步</translation>
    </message>
    <message>
      <source>Parent Directory</source>
      <translation>上層目錄</translation>
    </message>
    <message>
      <source>Create New Folder</source>
      <translation>建立新資料夾</translation>
    </message>
    <message>
      <source>List View</source>
      <translation>清單檢視</translation>
    </message>
    <message>
      <source>Detail View</source>
      <translation>詳細檢視</translation>
    </message>
  </context>
  <context>
    <name>QDialog</name>
    <message>
      <source>OK</source>
      <translation>確定</translation>
    </message>
    <message>
      <source>Cancel</source>
      <translation>取消</translation>
    </message>
    <message>
      <source>Apply</source>
      <translation>套用</translation>
    </message>
    <message>
      <source>Yes</source>
      <translation>是</translation>
    </message>
    <message>
      <source>No</source>
      <translation>否</translation>
    </message>
    <message>
      <source>Close</source>
      <translation>關閉</translation>
    </message>
    <message>
      <source>Help</source>
      <translation>說明</translation>
    </message>
    <message>
      <source>Reset</source>
      <translation>重設</translation>
    </message>
    <message>
      <source>Retry</source>
      <translation>重試</translation>
    </message>
    <message>
      <source>Ignore</source>
      <translation>略過</translation>
    </message>
    <message>
      <source>Abort</source>
      <translation>中止</translation>
    </message>
  </context>
  <context>
    <name>QMessageBox</name>
    <message>
      <source>OK</source>
      <translation>確定</translation>
    </message>
    <message>
      <source>Cancel</source>
      <translation>取消</translation>
    </message>
    <message>
      <source>Yes</source>
      <translation>是</translation>
    </message>
    <message>
      <source>No</source>
      <translation>否</translation>
    </message>
    <message>
      <source>Yes to All</source>
      <translation>全部皆是</translation>
    </message>
    <message>
      <source>No to All</source>
      <translation>全部皆否</translation>
    </message>
    <message>
      <source>Save</source>
      <translation>儲存</translation>
    </message>
    <message>
      <source>Discard</source>
      <translation>捨棄</translation>
    </message>
    <message>
      <source>Don&apos;t Save</source>
      <translation>不要儲存</translation>
    </message>
    <message>
      <source>Close</source>
      <translation>關閉</translation>
    </message>
    <message>
      <source>Help</source>
      <translation>說明</translation>
    </message>
  </context>
  <context>
    <name>QUndoStack</name>
    <message>
      <source>Undo</source>
      <translation>復原</translation>
    </message>
    <message>
      <source>Redo</source>
      <translation>重做</translation>
    </message>
    <message>
      <source>Undo %1</source>
      <translation>復原 %1</translation>
    </message>
    <message>
      <source>Redo %1</source>
      <translation>重做 %1</translation>
    </message>
  </context>
  <context>
    <name>QShortcut</name>
    <message>
      <source>Ctrl</source>
      <translation>Ctrl</translation>
    </message>
    <message>
      <source>Shift</source>
      <translation>Shift</translation>
    </message>
    <message>
      <source>Alt</source>
      <translation>Alt</translation>
    </message>
  </context>
  <context>
    <name>QTabBar</name>
    <message>
      <source>Close</source>
      <translation>關閉</translation>
    </message>
    <message>
      <source>Close Tab</source>
      <translation>關閉索引標籤</translation>
    </message>
    <message>
      <source>Close Other Tabs</source>
      <translation>關閉其他索引標籤</translation>
    </message>
  </context>
  <context>
    <name>QLineEdit</name>
    <message>
      <source>Cut</source>
      <translation>剪下</translation>
    </message>
    <message>
      <source>Copy</source>
      <translation>複製</translation>
    </message>
    <message>
      <source>Paste</source>
      <translation>貼上</translation>
    </message>
    <message>
      <source>Select All</source>
      <translation>全選</translation>
    </message>
    <message>
      <source>Undo</source>
      <translation>復原</translation>
    </message>
    <message>
      <source>Redo</source>
      <translation>重做</translation>
    </message>
    <message>
      <source>Delete</source>
      <translation>刪除</translation>
    </message>
  </context>
  <context>
    <name>QPrintDialog</name>
    <message>
      <source>Print</source>
      <translation>列印</translation>
    </message>
    <message>
      <source>Printer</source>
      <translation>印表機</translation>
    </message>
    <message>
      <source>Print to File</source>
      <translation>列印至檔案</translation>
    </message>
  </context>
</TS>
